//@version=6
indicator(title="Combined SMA/EMA, VWAP, and Real Price", shorttitle="3SMAScalp", overlay=true)

// Inputs for SMA/EMA
len1 = input.int(50, minval=1, title="SMA #1 length")
src1 = input(close, title="SMA Source #1")
out1 = ta.sma(src1, len1)
plot(out1, title="SMA #1", color=color.red, linewidth=1, style=plot.style_line)

len2 = input.int(100, minval=1, title="SMA #2 length")
src2 = input(close, title="SMA Source #2")
out2 = ta.sma(src2, len2)
plot(out2, title="SMA #2", color=color.teal, linewidth=1, style=plot.style_line)

len3 = input.int(200, minval=1, title="SMA #3 length")
src3 = input(close, title="SMA Source #3")
out3 = ta.sma(src3, len3)
plot(out3, title="SMA #3", color=color.blue, linewidth=1, style=plot.style_line)

len4 = input.int(50, minval=1, title="EMA #1 length")
src4 = input(close, title="EMA Source #1")
out4 = ta.ema(src4, len4)
plot(out4, title="EMA #1", color=color.black, linewidth=2, style=plot.style_line)

len5 = input.int(100, minval=1, title="EMA #2 length")
src5 = input(close, title="EMA Source #2")
out5 = ta.ema(src5, len5)
plot(out5, title="EMA #2", color=color.orange, linewidth=2, style=plot.style_line)

len6 = input.int(200, minval=1, title="EMA #3 length")
src6 = input(close, title="EMA Source #3")
out6 = ta.ema(src6, len6)
plot(out6, title="EMA #3", color=color.green, linewidth=2, style=plot.style_line)

// VWAP Settings
hideonDWM = input(false, title="Hide VWAP on 1D or Above", group="VWAP Settings")
var anchor = input.string(defval="Session", title="Anchor Period", options=["Session", "Week", "Month", "Quarter", "Year", "Decade", "Century", "Earnings", "Dividends", "Splits"], group="VWAP Settings")
srcVWAP = input.source(title="Source", defval=hlc3, group="VWAP Settings")
offsetVWAP = input.int(0, title="Offset", group="VWAP Settings")

// Bands Settings for VWAP
showBand_1 = input(true, title="Show Upper Band #1", group="Bands Settings")
bandMult_1 = input.float(1.0, title="Bands Multiplier #1", group="Bands Settings")
showBand_2 = input(false, title="Show Upper Band #2", group="Bands Settings")
bandMult_2 = input.float(2.0, title="Bands Multiplier #2", group="Bands Settings")
showBand_3 = input(false, title="Show Upper Band #3", group="Bands Settings")
bandMult_3 = input.float(3.0, title="Bands Multiplier #3", group="Bands Settings")

cumVolume = ta.cum(volume)
isNewPeriod = timeframe.change("D")
float vwapValue = na
float upperBandValue1 = na
float lowerBandValue1 = na
float upperBandValue2 = na
float lowerBandValue2 = na
float upperBandValue3 = na
float lowerBandValue3 = na

if not (hideonDWM and timeframe.isdwm)
    [_vwap, _stdevUpper, _] = ta.vwap(srcVWAP, isNewPeriod, 1)
    vwapValue := _vwap
    upperBandValue1 := _vwap + (_stdevUpper - _vwap) * bandMult_1
    lowerBandValue1 := _vwap - (_stdevUpper - _vwap) * bandMult_1
    upperBandValue2 := _vwap + (_stdevUpper - _vwap) * bandMult_2
    lowerBandValue2 := _vwap - (_stdevUpper - _vwap) * bandMult_2
    upperBandValue3 := _vwap + (_stdevUpper - _vwap) * bandMult_3
    lowerBandValue3 := _vwap - (_stdevUpper - _vwap) * bandMult_3

plot(vwapValue, title="VWAP", color=color.blue, offset=offsetVWAP)

var float band1Upper = na
var float band1Lower = na
var float band2Upper = na
var float band2Lower = na
var float band3Upper = na
var float band3Lower = na

if showBand_1
    band1Upper := upperBandValue1
    band1Lower := lowerBandValue1
if showBand_2
    band2Upper := upperBandValue2
    band2Lower := lowerBandValue2
if showBand_3
    band3Upper := upperBandValue3
    band3Lower := lowerBandValue3

plot(showBand_1 ? band1Upper : na, title="Upper Band #1", color=color.green, offset=offsetVWAP)
plot(showBand_1 ? band1Lower : na, title="Lower Band #1", color=color.green, offset=offsetVWAP)
plot(showBand_2 ? band2Upper : na, title="Upper Band #2", color=color.olive, offset=offsetVWAP)
plot(showBand_2 ? band2Lower : na, title="Lower Band #2", color=color.olive, offset=offsetVWAP)
plot(showBand_3 ? band3Upper : na, title="Upper Band #3", color=color.teal, offset=offsetVWAP)
plot(showBand_3 ? band3Lower : na, title="Lower Band #3", color=color.teal, offset=offsetVWAP)

// Real Price Line and Dots
showrealprice = input(true, title="show real price line", group="Real price line")
extendLine = input(true, title="Extend line", group="Real price line")
showrealpricelinecolor = input(#41ffb0, title="Real price line color", group="Real price line")
realpricewidth = input.string("Thin", options=["Thin", "Thicc"], title="Real price line width", group="Real price line")
realpricestyle = input.string("Dotted", options=["Dotted", "Solid", "Dashed"], title="Real price line style", group="Real price line")

plotrealclosedots = input(false, title="Show real close dots", group="Real price dots")
realclosecolour = input(color.new(#41ffb0, 50), title="Real close dot color", group="Real price dots")
size = input.string("Auto", options=["Auto", "Tiny", "Small"], title="Real close dot size", group="Real price dots")

real_price = ticker.new(prefix=syminfo.prefix, ticker=syminfo.ticker)
real_close = request.security(symbol=real_price, timeframe='', expression=close, gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_off)

showrealpricemicrodotstiny = (plotrealclosedots and size=="Tiny" ? display.all : display.none)
showrealpricemicrodotsauto = (plotrealclosedots and size=="Auto" ? display.all : display.none)
showrealpricedotslarge = (plotrealclosedots and size=="Small" ? display.all : display.none)

_width = switch realpricewidth
    "Thin" => 1
    "Thicc" => 2

// Real Price Line
if(showrealprice and (realpricestyle == "Solid"))
    real_price_line = line.new(bar_index[1], real_close, bar_index, real_close, xloc.bar_index, (extendLine ? extend.both : extend.right), showrealpricelinecolor, line.style_solid, _width)
    line.delete(real_price_line[1])
    
if(showrealprice and (realpricestyle == "Dotted"))
    real_price_line = line.new(bar_index[1], real_close, bar_index, real_close, xloc.bar_index, (extendLine ? extend.both : extend.right), showrealpricelinecolor, line.style_dotted, _width)
    line.delete(real_price_line[1])
    
if(showrealprice and (realpricestyle == "Dashed"))
    real_price_line = line.new(bar_index[1], real_close, bar_index, real_close, xloc.bar_index, (extendLine ? extend.both : extend.right), showrealpricelinecolor, line.style_dashed, _width)
    line.delete(real_price_line[1])

// Real Price Close Dots
plotchar(series=real_close, title="Real close dots", location=location.absolute, color=realclosecolour, editable=false, char="•", size=size.tiny, display=showrealpricemicrodotstiny)
plotchar(series=real_close, title="Real close dots", location=location.absolute, color=realclosecolour, editable=false, char="•", size=size.auto, display=showrealpricemicrodotsauto)
plotshape(series=real_close, title="Real close dots", location=location.absolute, color=realclosecolour, editable=false, style=shape.circle, size=size.auto, display=showrealpricedotslarge)
