//@version=5
indicator("Kripto Fema EMA Kırılım", overlay=true)

// Ayarlar
emaLen = input.int(9, "EMA Length")

// Hesaplama
ema9 = ta.ema(close, emaLen)

// Çizim
plot(ema9, color=color.orange)

// Kırılım şartı
longSignal = ta.crossover(close, ema9)
shortSignal = ta.crossunder(close, ema9)

// Oklar
plotshape(longSignal, title="LONG", location=location.belowbar,
     color=color.green, style=shape.triangleup)

plotshape(shortSignal, title="SHORT", location=location.abovebar,
     color=color.red, style=shape.triangledown)
