//@version=6

indicator(title = 'Range Entry Point', shorttitle = 'REP', overlay = true)
src = input(title = 'Source MA/EMA 1', defval = high, group = 'SMA Settings', display = display.data_window)
src1 = input(title = 'Source MA/EMA 2', defval = low, group = 'SMA Settings', display = display.data_window)
hideonDWM = input(true, title = 'Hide on h4 or Above', group = 'Line Settings', display = display.data_window)
linesalrt = input(false, title = 'RBO alert?')
linesalrt2 = input(false, title = 'Trend RBO alert?')

cciAlrt = input(false, title = 'CCI alert?')
bigres = input.string(title = 'Custom TF', defval = 'D', options = ['5','15','30','60','120','240', 'D','W'])
//SMA
fastLen = input(title='MA/EMA 1', defval=200)
fastLen1 = input(title='MA/EMA 2', defval=200)
fastLen2 = fastLen
maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA"])
ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)

fastEMA = ma(src, fastLen,maType)
fastEMA1 = ma(src1, fastLen1,maType)
fastEMA2 = ma(close, fastLen2,maType)
fema = plot(fastEMA, title='FastSMA', linewidth=1, style=plot.style_line,color = color.green)
fema1 = plot(fastEMA1, title='SlowSMA', linewidth=1, style=plot.style_line,color = color.red)
//SMA

//cci logic

cci_length = input.int(20, minval=1)
cci_src = input(hlc3, title="Source")
cci_ma = ta.sma(cci_src, cci_length)
cci = (cci_src - cci_ma) / (0.015 * ta.dev(cci_src, cci_length))
band1 = 100
band0 = -100


cci_band1up = ta.crossover(cci,band1)
cci_band1dwn = ta.crossunder(cci,band1)

cci_bandodwn = ta.crossunder(cci,band0)
cci_band0up = ta.crossover(cci,band0)

//cci end logic




// for opening day logic
// current day opening
cdo = request.security(syminfo.tickerid, bigres, open, lookahead = barmerge.lookahead_on)
// prev day high
pdh = request.security(syminfo.tickerid, bigres, high[1], lookahead = barmerge.lookahead_on)
// prev day low
pdl = request.security(syminfo.tickerid, bigres, low[1], lookahead = barmerge.lookahead_on)
//prev day opening
pdo = request.security(syminfo.tickerid, bigres, open[1], lookahead = barmerge.lookahead_on)
// prev day close
pdc = request.security(syminfo.tickerid, bigres, close[1], lookahead = barmerge.lookahead_on)


f_line_new() =>
    line.new(na, na, na, na, xloc.bar_time, extend.right, color =color.gray, style = line.style_solid,width = 1)


var line line_h_h = f_line_new()
var line line_h_l = f_line_new()
var line line_h_o = f_line_new()
var line line_h_c = f_line_new()

//var line line_h_o = f_line_new()

//                                           1      2     3    4      5     6        7        8       9         10       11       12       13      14        15
f_data_get(_res) =>
    request.security(syminfo.tickerid, _res, [open, high, low, close, time, open[1], high[1], low[1], close[1], time[1], open[2], high[2], low[2], close[2], time[2]], gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on)

f_line_move(_line, _x, _y) =>
    line.set_xy1(_line, _x, _y)
    line.set_xy2(_line,_x + 2, _y)

// 1     2     3     4     5     6     7     8     9    10    11    12    13    14    15
[o0_h, h0_h, l0_h, c0_h, t0_h, o1_h, h1_h, l1_h, c1_h, t1_h, o2_h, h2_h, l2_h, c2_h, t2_h] = f_data_get(bigres)


// --- NEW LOGIC: only plot if bigres >= current chart timeframe ---
bigres_sec     = timeframe.in_seconds(bigres)
current_tf_sec = timeframe.in_seconds(timeframe.period)


if not(hideonDWM and timeframe.isdwm) and (bigres_sec >= current_tf_sec)
    // high
    f_line_move(line_h_h, t1_h, h1_h)
    // low
    f_line_move(line_h_l, t1_h, l1_h)
   // prev open
    f_line_move(line_h_o, t1_h, o1_h)
    // prev close
    f_line_move(line_h_c, t1_h,c1_h)
     //f_line_move(line_h_o, t0_h, o0_h)


prev_high_bo = ta.crossover(close, pdh)
prev_low_bo = ta.crossover(close, pdl)
prev_open_bo = ta.crossover(close,pdo)
preve_close_bo = ta.crossover(close,pdc)

prev_high_bd = ta.crossunder(close, pdh)
prev_low_bd = ta.crossunder(close, pdl)
prev_open_bd = ta.crossunder(close,pdo)
preve_close_bd = ta.crossunder(close,pdc)


prev_high = ta.cross(close, pdh)
prev_low = ta.cross(close, pdl)
prev_open = ta.cross(close,pdo)
preve_close = ta.cross(close,pdc)


bullzone = src > fastEMA2
bearzone = src < fastEMA2

if prev_high_bo and linesalrt2 and bullzone
    alert('Prev. candle high BO', alert.freq_once_per_bar)
if prev_low_bo and linesalrt2 and bullzone
    alert('Prev. candle low BO', alert.freq_once_per_bar)
if prev_open_bo and linesalrt2 and bullzone
    alert('Prev. candle open BO', alert.freq_once_per_bar)
if preve_close_bo and linesalrt2 and bullzone
    alert('Prev. candle close BO', alert.freq_once_per_bar)

if prev_high_bd and linesalrt2 and bearzone
    alert('Prev. candle high BD', alert.freq_once_per_bar)
if prev_low_bd and linesalrt2 and bearzone
    alert('Prev. candle low BD', alert.freq_once_per_bar)
if prev_open_bd and linesalrt2 and bearzone
    alert('Prev. candle open BD', alert.freq_once_per_bar)
if preve_close_bd and linesalrt2 and bearzone
    alert('Prev. candle close BD', alert.freq_once_per_bar)


if prev_high and linesalrt
    alert('Prev. candle high alert', alert.freq_once_per_bar)
if prev_low and linesalrt
    alert('Prev. candle low alert', alert.freq_once_per_bar)
if prev_open and linesalrt
    alert('Prev. candle open alert', alert.freq_once_per_bar)
if preve_close and linesalrt
    alert('Prev. candle close alert', alert.freq_once_per_bar)
