//@version=5
indicator('BTC_bar_volume_color', overlay=true, max_labels_count=500)
bkbg = input.bool(false, title='Black Background')

// Z-оценка объёма
length = 100

// ───── СБОР ЦЕНЫ BTC (для BitMEX/Deribit пересчёта) ──────────────────────
btc_price = request.security("BINANCE:BTCUSDT", timeframe.period, close, barmerge.gaps_on)

// ───── АГРЕГАЦИЯ СПОТОВЫХ ОБЪЁМОВ ────────────────────────────────────────

binance_spot_usdt    = request.security("BINANCE:BTCUSDT" , timeframe.period, volume, barmerge.gaps_on)
binance_spot_fdusd   = request.security("BINANCE:BTCFDUSD", timeframe.period, volume, barmerge.gaps_on)
bybit_spot_usdt      = request.security("BYBIT:BTCUSDT"   , timeframe.period, volume, barmerge.gaps_on)
bybit_spot_usdc      = request.security("BYBIT:BTCUSDC"   , timeframe.period, volume, barmerge.gaps_on)
okx_spot_usdt        = request.security("OKX:BTCUSDT"     , timeframe.period, volume, barmerge.gaps_on)
coinbase_spot_usd    = request.security("COINBASE:BTCUSD" , timeframe.period, volume, barmerge.gaps_on)
coinbase_spot_usdc   = request.security("COINBASE:BTCUSDC", timeframe.period, volume, barmerge.gaps_on)
bitget_spot_usdt     = request.security("BITGET:BTCUSDT"  , timeframe.period, volume, barmerge.gaps_on)
htx_spot_usdt        = request.security("HTX:BTCUSDT"     , timeframe.period, volume, barmerge.gaps_on)
kraken_spot_usd      = request.security("KRAKEN:BTCUSD"   , timeframe.period, volume, barmerge.gaps_on)
kucoin_spot_usdt     = request.security("KUCOIN:BTCUSDT"  , timeframe.period, volume, barmerge.gaps_on)
gateio_spot_usdt     = request.security("GATEIO:BTCUSDT"  , timeframe.period, volume, barmerge.gaps_on)
whitebit_spot_usdt   = request.security("WHITEBIT:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)
cryptocom_spot_usd   = request.security("CRYPTOCOM:BTCUSD", timeframe.period, volume, barmerge.gaps_on)
cryptocom_spot_usdt  = request.security("CRYPTOCOM:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)
woonetwork_spot_usdt = request.security("WOONETWORK:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)
bitrue_spot_usdt     = request.security("BITRUE:BTCUSDT"  , timeframe.period, volume, barmerge.gaps_on)
mexc_spot_usdt = request.security("MEXC:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)
poloniex_spot_usdt = request.security("POLONIEX:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)
coinw_spot_usdt = request.security("COINW:BTCUSDT", timeframe.period, volume, barmerge.gaps_on)


spot = nz(binance_spot_usdt) + nz(binance_spot_fdusd) + nz(bybit_spot_usdt) + nz(bybit_spot_usdc) +
       nz(okx_spot_usdt)     + nz(coinbase_spot_usd)  + nz(coinbase_spot_usdc) +
       nz(bitget_spot_usdt)  + nz(htx_spot_usdt)      + nz(kraken_spot_usd)   +
       nz(kucoin_spot_usdt)  + nz(gateio_spot_usdt)   + nz(whitebit_spot_usdt)+
       nz(cryptocom_spot_usd)+ nz(cryptocom_spot_usdt)+ nz(woonetwork_spot_usdt)+
       nz(bitrue_spot_usdt)  + nz(mexc_spot_usdt)     + nz(poloniex_spot_usdt)+
       nz(coinw_spot_usdt)

 
// ==================== 3. ФЬЮЧ ====================

whitebit_perp_usdt = request.security("WHITEBIT:BTCUSDT.P", timeframe.period, volume, barmerge.gaps_on) 
gateio_perp_usdt = request.security("GATEIO:BTCUSDT.P", timeframe.period, volume, barmerge.gaps_on) * 0.001
blofin_perp_usdt = request.security("BLOFIN:BTCUSDT.P", timeframe.period, volume, barmerge.gaps_on) * 0.001
binance_perp_usdt  = request.security("BINANCE:BTCUSDT.P", timeframe.period, volume, barmerge.gaps_on)
binance_perp_usd   = request.security("BINANCE:BTCUSD.P" , timeframe.period, volume, barmerge.gaps_on) * 0.01
bybit_perp_usdt    = request.security("BYBIT:BTCUSDT.P"  , timeframe.period, volume, barmerge.gaps_on) 
bybit_perp_usdc    = request.security("BYBIT:BTCUSDC.P"  , timeframe.period, volume, barmerge.gaps_on)
okx_perp_usdt      = request.security("OKX:BTCUSDT.P"    , timeframe.period, volume, barmerge.gaps_on) * 0.0001
//okx_perp_usdc      = request.security("OKX:BTCUSDC.P"    , timeframe.period, volume, barmerge.gaps_on) * 0.001
bitget_perp_usdt   = request.security("BITGET:BTCUSDT.P" , timeframe.period, volume, barmerge.gaps_on) 
coinbase_perp_usdc = request.security("COINBASE:BTCUSDC.P", timeframe.period, volume, barmerge.gaps_on) 
htx_perp_usdt      = request.security("HTX:BTCUSDT.P"    , timeframe.period, volume, barmerge.gaps_on) * 0.01
htx_perp_usd       = request.security("HTX:BTCUSD.P"     , timeframe.period, volume, barmerge.gaps_on) * 0.001
bingx_perp_usdt    = request.security("BINGX:BTCUSDT.P"  , timeframe.period, volume, barmerge.gaps_on) * 0.001
bingx_perp_usdc    = request.security("BINGX:BTCUSDC.P"  , timeframe.period, volume, barmerge.gaps_on) * 0.01
mexc_perp_usdt     = request.security("MEXC:BTCUSDT.P"   , timeframe.period, volume, barmerge.gaps_on) * 0.001
mexc_perp_usdc     = request.security("MEXC:BTCUSDC.P"   , timeframe.period, volume, barmerge.gaps_on) * 0.01
bitmex_perp_usd    = request.security("BITMEX:BTCUSD.P"  , timeframe.period, volume, barmerge.gaps_on) * 0.001
deribit_perp_usd   = request.security("DERIBIT:BTCUSD.P" , timeframe.period, volume, barmerge.gaps_on) * 0.0001
bitmart_perp_usdt  = request.security("BITMART:BTCUSDT.P", timeframe.period, volume, barmerge.gaps_on) * 0.001

perp = nz(binance_perp_usdt)  + nz(binance_perp_usd) +
       nz(bybit_perp_usdt)    + nz(bybit_perp_usdc)  +
       nz(okx_perp_usdt)      + 
       nz(bitget_perp_usdt)   + nz(coinbase_perp_usdc) +
       nz(htx_perp_usdt)      + nz(htx_perp_usd)    +
       nz(bingx_perp_usdt)    + nz(bingx_perp_usdc) +
       nz(mexc_perp_usdt)     + nz(mexc_perp_usdc)  +
       nz(bitmex_perp_usd)    + nz(deribit_perp_usd)+
       nz(bitmart_perp_usdt)  +
       nz(whitebit_perp_usdt) + nz(gateio_perp_usdt)+
       nz(blofin_perp_usdt)
 

f_z(src,len)=>(src-ta.sma(src,len))/ta.stdev(src,len) 
z_spot  = f_z(spot ,length)
z_perp  = f_z(perp ,length)

z_vol   = (z_spot + z_perp) / 2


// Диапазон z от 1.3 до 1.95
z_min = -1.65
z_max = 3
z_raw = (z_vol - z_min) / (z_max - z_min)
z_scaled = math.max(0.0, math.min(z_raw, 1.0))  // clamp в диапазон [0, 1]

// Плавная прозрачность: от 70 до 10
transp = 80 - int(z_scaled * 150)

// Цвета с динамичной прозрачностью
green = color.new(color.lime, transp)
red   = color.new(color.red, transp)

// Цвет бара в зависимости от направления
barColor = close > close[1] ? green : red

// Цвет фона
bgcolor(bkbg ? color.black : na)

// Отрисовка
barcolor(barColor)
