//@version=6
indicator("Bull/Bear Volume Diagram", overlay=false)

method sumArray(array<float> arr) =>
    float sum = 0.0
    if array.size(arr) > 0
        for i = 0 to array.size(arr) - 1
            sum += array.get(arr, i)
    sum


var array<float> bullishVolumeArray = array.new<float>()
var array<float> bearishVolumeArray = array.new<float>()

int numOfCandles = input.int(defval = 20, title = "MA number of candles")

isUp = close > open
float plotValue = (isUp ? 1 : -1) * volume

if isUp
    if array.size(bullishVolumeArray) >= numOfCandles
        array.shift(bullishVolumeArray)
    array.push(bullishVolumeArray, volume)
else
    if array.size(bearishVolumeArray) >= numOfCandles
        array.shift(bearishVolumeArray)
    array.push(bearishVolumeArray, volume)


float bullishMA = sumArray(bullishVolumeArray) / array.size(bullishVolumeArray)
float bearishMA = sumArray(bearishVolumeArray) / array.size(bearishVolumeArray)

plot(isUp ? plotValue : na, style = plot.style_columns, color = #26a69a, title = "Bullish volume candles")
plot(not isUp ? plotValue : na, style = plot.style_columns, color = color.red, title = "Bearish volume candles")
plot(bullishMA, style = plot.style_line, title = "Bullish Volume MA", color = #ff9800, linewidth = 2)
plot(-bearishMA, style = plot.style_line, title = "Bearish Volume MA", color = #ff9800, linewidth = 2)
