"""
OpenClaw Backtest Results: assistant
============================================================

--- SPY ---
  Return                    -9.53%
  Buy & Hold Return         41.94%
  Max Drawdown              -19.50%
  Sharpe Ratio              -0.36
  Sortino Ratio             -0.48
  Calmar Ratio              -0.25
  Profit Factor             0.84
  Expectancy                -0.09%
  SQN                       -0.60
  # Trades                  96
  Win Rate                  55.21%
  Best Trade                4.05%
  Worst Trade               -11.22%
  Avg Trade                 -0.10%
  Exposure Time             62.60%
  Equity Final              90473.18$
  Equity Peak               102411.10$
  Avg Drawdown              -4.64%
  Max Drawdown Duration     669 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -4.92%
  Ann. Volatility           13.74%

--- BTC ---
  Return                    -16.90%
  Buy & Hold Return         46.22%
  Max Drawdown              -41.91%
  Sharpe Ratio              -0.35
  Sortino Ratio             -0.46
  Calmar Ratio              -0.21
  Profit Factor             1.04
  Expectancy                0.06%
  SQN                       -0.27
  # Trades                  134
  Win Rate                  51.49%
  Best Trade                12.27%
  Worst Trade               -10.81%
  Avg Trade                 -0.01%
  Exposure Time             66.21%
  Equity Final              83099.24$
  Equity Peak               130750.69$
  Avg Drawdown              -5.66%
  Max Drawdown Duration     417 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -8.83%
  Ann. Volatility           25.45%

--- QQQ ---
  Return                    -3.46%
  Buy & Hold Return         42.67%
  Max Drawdown              -19.61%
  Sharpe Ratio              -0.10
  Sortino Ratio             -0.15
  Calmar Ratio              -0.09
  Profit Factor             0.98
  Expectancy                -0.02%
  SQN                       -0.18
  # Trades                  96
  Win Rate                  52.08%
  Best Trade                4.51%
  Worst Trade               -11.72%
  Avg Trade                 -0.04%
  Exposure Time             63.20%
  Equity Final              96536.75$
  Equity Peak               104964.38$
  Avg Drawdown              -13.52%
  Max Drawdown Duration     350 days 00:00:00
  Max Trade Duration        10 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -1.76%
  Ann. Volatility           16.88%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — assistant
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    wick_threshold = 0.0
    
    def init(self):
        pass
    
    def next(self):
        # Calculate current candle values
        if len(self.data) < 5:
            return
        
        close = self.data.Close
        open_ = self.data.Open
        high = self.data.High
        low = self.data.Low
        
        # ===== LOGIC FOR WICKS =====
        body = abs(close[-1] - open_[-1])
        upper_wick = high[-1] - max(open_[-1], close[-1])
        lower_wick = min(open_[-1], close[-1]) - low[-1]
        
        valid_body = body > 0
        upper_signal = (upper_wick <= body * self.wick_threshold / 100 and valid_body) or upper_wick == 0
        lower_signal = (lower_wick <= body * self.wick_threshold / 100 and valid_body) or lower_wick == 0
        
        # ===== LOGIC FOR 3-CANDLE FRACTALS =====
        fractal_up_3 = high[-3] > high[-2] and high[-3] > high[-4]
        fractal_down_3 = low[-3] < low[-2] and low[-3] < low[-4]
        
        # ===== LOGIC FOR 5-CANDLE FRACTALS =====
        fractal_up_5 = (high[-3] > high[-1] and high[-3] > high[-2] and 
                        high[-3] > high[-4] and high[-3] > high[-5])
        fractal_down_5 = (low[-3] < low[-1] and low[-3] < low[-2] and 
                          low[-3] < low[-4] and low[-3] < low[-5])
        
        # ===== LOGIC FOR FVG =====
        bullish_fvg = low[-3] > high[-1]
        bearish_fvg = high[-3] < low[-1]
        
        # ===== TRADING RULES =====
        # Buy on bullish FVG or lower 3-candle fractal
        if bullish_fvg or fractal_down_3:
            if not self.position:
                self.buy()
        
        # Sell on bearish FVG or upper 3-candle fractal
        if bearish_fvg or fractal_up_3:
            if self.position:
                self.position.close()
        
        # Buy on lower 5-candle fractal
        if fractal_down_5:
            if not self.position:
                self.buy()
        
        # Sell on upper 5-candle fractal
        if fractal_up_5:
            if self.position:
                self.position.close()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)