"""
OpenClaw Backtest Results: bosstvs-tikole-sir-all-in-one-ultimate-new-strong-buy-sell
============================================================

--- SPY ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- BTC ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- QQQ ---
  ERROR: '_Indicator' object has no attribute 'iloc'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bosstvs-tikole-sir-all-in-one-ultimate-new-strong-buy-sell
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    sensitivity = 4
    pivot_len = 21

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # SuperTrend
        st_result = self.I(pta.supertrend, high, low, close, length=11, multiplier=self.sensitivity)
        self.st = st_result.iloc[:, 0]
        
        # Moving averages for signal confirmation
        self.sma_fast = self.I(pta.sma, close, length=8)
        self.sma_mid = self.I(pta.sma, close, length=9)
        self.sma_slow = self.I(pta.sma, close, length=13)
        
        # ATR for targets
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        # Trend cloud
        self.ma1 = self.I(pta.sma, close, length=21)
        self.ma2 = self.I(pta.sma, close, length=34)
        
        # Pivot points
        self.ph = self.I(pta.pivothigh, high, length=self.pivot_len, scalar=self.pivot_len)
        self.pl = self.I(pta.pivotlow, low, length=self.pivot_len, scalar=self.pivot_len)
        
        # EMA/SMA/VWAP for reference
        self.ema21 = self.I(pta.ema, close, length=21)
        self.sma50 = self.I(pta.sma, close, length=50)
        self.vwap = self.I(pta.vwap, high, low, close, volume)
        
        # Day tracking for first candle levels
        self.day_high = None
        self.day_low = None
        self.day_range = None
        self.buy_target = None
        self.sell_target = None
        self.last_day = None

    def next(self):
        if len(self) < 50:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        # Track day change for daily levels
        current_date = pd.Timestamp(self.data.index[-1]).date()
        if self.last_day is None or current_date != self.last_day:
            if self.last_day is not None:
                self.day_high = self.data.High[-2]
                self.day_low = self.data.Low[-2]
                self.day_range = self.day_high - self.day_low
                self.buy_target = self.day_high + self.day_range
                self.sell_target = self.day_low - self.day_range
            self.last_day = current_date
        
        # SuperTrend crossover signals
        bull = crossover(self.data.Close, self.st) and close > self.sma_slow[-1]
        bear = crossover(self.st, self.data.Close) and close < self.sma_slow[-1]
        
        # Daily target signals
        buy_hit = False
        sell_hit = False
        if self.buy_target is not None and self.sell_target is not None:
            if len(self) > 1:
                buy_hit = crossover(self.data.Close, pd.Series([self.buy_target] * len(self.data.Close)))
                sell_hit = crossover(pd.Series([self.sell_target] * len(self.data.Close)), self.data.Close)
        
        # Entry signals
        if bull or buy_hit:
            if not self.position:
                self.buy()
        
        # Exit signals
        if bear or sell_hit:
            if self.position:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()