"""
OpenClaw Backtest Results: colidation-breakout-structureha-cbs
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — colidation-breakout-structureha-cbs
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fvg_period_length = 4
    consolidation_length = 4
    swing_point_history = 500
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.consolidation_signal = 0
        self.fvg_signal = 0
        self.swing_signal = 0
        
        self.in_trade = False
        self.trade_direction = 0

    def next(self):
        if len(self.data) < self.fvg_period_length + self.consolidation_length:
            return
        
        current_idx = len(self.data) - 1
        
        consolidation_detected = self._detect_consolidation(current_idx)
        fvg_detected = self._detect_fvg(current_idx)
        
        if consolidation_detected == 1 and fvg_detected > 0:
            if not self.position:
                self.buy()
                self.in_trade = True
                self.trade_direction = 1
        
        elif consolidation_detected == -1 and fvg_detected < 0:
            if not self.position:
                self.sell()
                self.in_trade = True
                self.trade_direction = -1
        
        elif self.position:
            if self.trade_direction == 1 and self._check_bearish_reversal(current_idx):
                self.position.close()
                self.in_trade = False
            elif self.trade_direction == -1 and self._check_bullish_reversal(current_idx):
                self.position.close()
                self.in_trade = False

    def _detect_consolidation(self, idx):
        if idx < self.consolidation_length:
            return 0
        
        lookback = self.consolidation_length
        margin_rate = 0.015
        
        range_width = self.data.High[idx] - self.data.Low[idx]
        margin = range_width * margin_rate
        
        oc_max_current = max(self.data.Open[idx], self.data.Close[idx])
        oc_min_current = min(self.data.Open[idx], self.data.Close[idx])
        
        is_consolidated = True
        for i in range(idx - lookback + 1, idx):
            oc_max_prev = max(self.data.Open[i], self.data.Close[i])
            oc_min_prev = min(self.data.Open[i], self.data.Close[i])
            
            if (oc_max_prev + margin < oc_max_current or 
                oc_min_prev - margin > oc_min_current):
                is_consolidated = False
                break
        
        if is_consolidated:
            if self.data.Close[idx] > self.data.Close[idx - 1]:
                return 1
            else:
                return -1
        
        return 0

    def _detect_fvg(self, idx):
        if idx < self.fvg_period_length + 1:
            return 0
        
        period = self.fvg_period_length
        
        if (self.data.High[idx - period] < self.data.Low[idx] and 
            self.data.High[idx - 1] < self.data.Close[idx]):
            return 1
        
        elif (self.data.Low[idx - period] > self.data.High[idx] and 
              self.data.Low[idx - 1] > self.data.Close[idx]):
            return -1
        
        return 0

    def _check_bullish_reversal(self, idx):
        if idx < 2:
            return False
        
        return (self.data.Low[idx] < self.data.Low[idx - 1] and 
                self.data.Close[idx] > self.data.Close[idx - 1])

    def _check_bearish_reversal(self, idx):
        if idx < 2:
            return False
        
        return (self.data.High[idx] > self.data.High[idx - 1] and 
                self.data.Close[idx] < self.data.Close[idx - 1])


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()