"""
OpenClaw Backtest Results: ct-displacement-fvg-toolkit
============================================================

--- SPY ---
  ERROR: module 'pandas_ta' has no attribute 'highest'

--- BTC ---
  ERROR: module 'pandas_ta' has no attribute 'highest'

--- QQQ ---
  ERROR: module 'pandas_ta' has no attribute 'highest'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ct-displacement-fvg-toolkit
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Displacement parameters
    disp_lookback = 5
    disp_factor = 1.5
    use_body_size = True
    
    # Structure break filter
    sb_lookback = 5
    require_struct_br = True
    struct_break_type = "Close"
    
    # CISD parameters
    cisd_enable = True
    tolerance = 0.7
    len_swing = 12
    expiry_bars = 100
    liquidity_lookback = 10
    
    # Dealing range
    dr_len = 50

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Displacement calculation
        sz = np.where(self.use_body_size, np.abs(close - open_), high - low)
        self.avg_size = self.I(pta.sma, pd.Series(sz), length=self.disp_lookback)
        
        # Structure break levels
        self.sb_high = self.I(lambda x: pd.Series(x).rolling(self.sb_lookback).max(), high.shift(1).values)
        self.sb_low = self.I(lambda x: pd.Series(x).rolling(self.sb_lookback).min(), low.shift(1).values)
        
        # Dealing range
        self.dr_high = self.I(pta.highest, high, length=self.dr_len)
        self.dr_low = self.I(pta.lowest, low, length=self.dr_len)
        
        # Pivot points for CISD
        self.pivot_high = self.I(pta.pivothigh, high, length=self.len_swing)
        self.pivot_low = self.I(pta.pivotlow, low, length=self.len_swing)

    def next(self):
        if len(self.data) < max(self.disp_lookback, self.sb_lookback, self.dr_len, self.len_swing) + 2:
            return
        
        close_val = self.data.Close[-1]
        open_val = self.data.Open[-1]
        high_val = self.data.High[-1]
        low_val = self.data.Low[-1]
        
        # Calculate displacement
        sz_current = abs(close_val - open_val) if self.use_body_size else (high_val - low_val)
        avg_sz = self.avg_size[-1]
        
        is_disp = not np.isnan(avg_sz) and sz_current > avg_sz * self.disp_factor
        bull_disp = is_disp and close_val > open_val
        bear_disp = is_disp and close_val < open_val
        
        # Structure break check
        sb_high_val = self.sb_high[-1]
        sb_low_val = self.sb_low[-1]
        
        if self.struct_break_type == "Close":
            bull_sb = close_val > sb_high_val if not np.isnan(sb_high_val) else False
            bear_sb = close_val < sb_low_val if not np.isnan(sb_low_val) else False
        else:
            bull_sb = high_val > sb_high_val if not np.isnan(sb_high_val) else False
            bear_sb = low_val < sb_low_val if not np.isnan(sb_low_val) else False
        
        bull_disp_ok = (bull_disp and bull_sb) if self.require_struct_br else bull_disp
        bear_disp_ok = (bear_disp and bear_sb) if self.require_struct_br else bear_disp
        
        # Dealing range levels
        dr_high_val = self.dr_high[-1]
        dr_low_val = self.dr_low[-1]
        dr_mid = (dr_high_val + dr_low_val) * 0.5 if not np.isnan(dr_high_val) and not np.isnan(dr_low_val) else None
        
        # Pivot points
        pivot_high_val = self.pivot_high[-1]
        pivot_low_val = self.pivot_low[-1]
        
        # Trading logic based on displacement and structure
        if bull_disp_ok:
            if not self.position:
                self.buy()
        elif bear_disp_ok:
            if self.position:
                self.sell()
        
        # Exit on reversal at dealing range
        if self.position and dr_high_val is not None and not np.isnan(dr_high_val):
            if close_val > dr_high_val:
                self.sell()
        elif not self.position and dr_low_val is not None and not np.isnan(dr_low_val):
            if close_val < dr_low_val:
                self.buy()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()