"""
OpenClaw Backtest Results: dynamic-extreme-channels-reversals-luxalgo
============================================================

--- SPY ---
  Return                    29.80%
  Buy & Hold Return         41.94%
  Max Drawdown              -7.54%
  Sharpe Ratio              1.24
  Sortino Ratio             2.02
  Calmar Ratio              1.86
  Profit Factor             5.95
  Expectancy                3.12%
  SQN                       1.45
  # Trades                  9
  Win Rate                  55.56%
  Best Trade                17.89%
  Worst Trade               -3.56%
  Avg Trade                 2.95%
  Exposure Time             78.00%
  Equity Final              129797.41$
  Equity Peak               132592.58$
  Avg Drawdown              -1.42%
  Max Drawdown Duration     200 days 00:00:00
  Max Trade Duration        161 days 00:00:00
  Avg Trade Duration        62 days 00:00:00
  Ann. Return               14.05%
  Ann. Volatility           11.34%

--- BTC ---
  Return                    33.63%
  Buy & Hold Return         46.22%
  Max Drawdown              -23.83%
  Sharpe Ratio              0.55
  Sortino Ratio             1.02
  Calmar Ratio              0.65
  Profit Factor             1.66
  Expectancy                2.38%
  SQN                       0.71
  # Trades                  19
  Win Rate                  47.37%
  Best Trade                24.99%
  Worst Trade               -16.87%
  Avg Trade                 1.65%
  Exposure Time             56.09%
  Equity Final              133628.47$
  Equity Peak               159538.89$
  Avg Drawdown              -6.20%
  Max Drawdown Duration     260 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               15.57%
  Ann. Volatility           28.22%

--- QQQ ---
  Return                    34.21%
  Buy & Hold Return         42.67%
  Max Drawdown              -13.08%
  Sharpe Ratio              0.99
  Sortino Ratio             1.61
  Calmar Ratio              1.22
  Profit Factor             4.35
  Expectancy                4.08%
  SQN                       1.23
  # Trades                  8
  Win Rate                  62.50%
  Best Trade                23.31%
  Worst Trade               -4.38%
  Avg Trade                 3.76%
  Exposure Time             78.00%
  Equity Final              134211.46$
  Equity Peak               142672.00$
  Avg Drawdown              -2.08%
  Max Drawdown Duration     169 days 00:00:00
  Max Trade Duration        164 days 00:00:00
  Avg Trade Duration        70 days 00:00:00
  Ann. Return               15.99%
  Ann. Volatility           16.08%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — dynamic-extreme-channels-reversals-luxalgo
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lengthInput = 20
    alphaInput = 0.5
    trailingModeInput = False

    def init(self):
        self.upperLevel = self.data.High[0]
        self.lowerLevel = self.data.Low[0]
        self.upperCounter = 0
        self.lowerCounter = 0
        self.trend = 0
        
        self.upperLevels = []
        self.lowerLevels = []
        self.midlines = []
        self.trends = []
        self.bullishSignals = []
        self.bearishSignals = []

    def next(self):
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        
        isHH = current_high >= self.upperLevel
        isLL = current_low <= self.lowerLevel
        
        if current_high >= self.upperLevel:
            self.upperLevel = current_high
            self.upperCounter = 0
            self.trend = 1
        else:
            self.upperCounter += 1
            if self.upperCounter >= self.lengthInput:
                self.upperLevel = self.upperLevel * (1 - self.alphaInput) + current_high * self.alphaInput
                self.upperCounter = 0
        
        if current_low <= self.lowerLevel:
            self.lowerLevel = current_low
            self.lowerCounter = 0
            self.trend = -1
        else:
            self.lowerCounter += 1
            if self.lowerCounter >= self.lengthInput:
                self.lowerLevel = self.lowerLevel * (1 - self.alphaInput) + current_low * self.alphaInput
                self.lowerCounter = 0
        
        midline = (self.upperLevel + self.lowerLevel) / 2
        
        bearishSignal = isHH and current_low < midline
        bullishSignal = isLL and current_high > midline
        
        self.upperLevels.append(self.upperLevel)
        self.lowerLevels.append(self.lowerLevel)
        self.midlines.append(midline)
        self.trends.append(self.trend)
        self.bullishSignals.append(bullishSignal)
        self.bearishSignals.append(bearishSignal)
        
        if bullishSignal and not self.position:
            self.buy()
        elif bearishSignal and self.position:
            self.position.close()
        
        if self.position and self.trend == -1:
            self.position.close()
        elif not self.position and self.trend == 1:
            self.buy()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    results = bt.run()
    print(results)
    bt.plot()