"""
OpenClaw Backtest Results: gk-trend-ribbon-swing-prepare-hud
============================================================

--- SPY ---
  Return                    10.34%
  Buy & Hold Return         17.90%
  Max Drawdown              -5.06%
  Sharpe Ratio              0.80
  Sortino Ratio             1.18
  Calmar Ratio              1.00
  Profit Factor             nan
  Expectancy                12.53%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                12.53%
  Worst Trade               12.53%
  Avg Trade                 12.53%
  Exposure Time             31.40%
  Equity Final              110335.49$
  Equity Peak               114922.99$
  Avg Drawdown              -1.24%
  Max Drawdown Duration     42 days 00:00:00
  Max Trade Duration        226 days 00:00:00
  Avg Trade Duration        226 days 00:00:00
  Ann. Return               5.08%
  Ann. Volatility           6.37%

--- BTC ---
  Return                    54.85%
  Buy & Hold Return         17.39%
  Max Drawdown              -32.76%
  Sharpe Ratio              0.69
  Sortino Ratio             1.37
  Calmar Ratio              0.74
  Profit Factor             2.60
  Expectancy                13.75%
  SQN                       0.28
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                44.75%
  Worst Trade               -17.24%
  Avg Trade                 9.45%
  Exposure Time             45.55%
  Equity Final              154845.56$
  Equity Peak               161993.52$
  Avg Drawdown              -5.38%
  Max Drawdown Duration     301 days 00:00:00
  Max Trade Duration        189 days 00:00:00
  Avg Trade Duration        166 days 00:00:00
  Ann. Return               24.40%
  Ann. Volatility           35.39%

--- QQQ ---
  Return                    10.61%
  Buy & Hold Return         22.08%
  Max Drawdown              -7.88%
  Sharpe Ratio              0.57
  Sortino Ratio             0.83
  Calmar Ratio              0.66
  Profit Factor             nan
  Expectancy                13.40%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                13.40%
  Worst Trade               13.40%
  Avg Trade                 13.40%
  Exposure Time             33.80%
  Equity Final              110613.81$
  Equity Peak               120059.00$
  Avg Drawdown              -1.52%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        245 days 00:00:00
  Avg Trade Duration        245 days 00:00:00
  Ann. Return               5.22%
  Ann. Volatility           9.13%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gk-trend-ribbon-swing-prepare-hud
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 200
    mult = 2.0
    atr_len = 21
    conf = 2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate lag
        self.lag = max(int(np.floor((self.len - 1) / 2)), 0)
        
        # Calculate adjusted close with lag
        if self.lag > 0:
            adjusted_close = close + (close - close.shift(self.lag))
        else:
            adjusted_close = close
        
        # Calculate EMA on adjusted close
        self.zl = self.I(pta.ema, adjusted_close, length=self.len)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        
        # Calculate bands
        self.up = self.I(lambda x, y: x + y * self.mult, self.zl, self.atr)
        self.dn = self.I(lambda x, y: x - y * self.mult, self.zl, self.atr)
        
        # Store trend state
        self.tr = 0
        self.last_tr = 0

    def next(self):
        close = self.data.Close[-1]
        
        # Get current values
        zl_curr = self.zl[-1]
        zl_prev = self.zl[-2] if len(self.zl) > 1 else zl_curr
        
        up_curr = self.up[-1]
        up_prev = self.up[-2] if len(self.up) > 1 else up_curr
        
        dn_curr = self.dn[-1]
        dn_prev = self.dn[-2] if len(self.dn) > 1 else dn_curr
        
        close_prev = self.data.Close[-2] if len(self.data.Close) > 1 else close
        
        # Get confirmation bar values
        if len(self.data.Close) > self.conf - 1:
            close_conf = self.data.Close[-(self.conf)]
            up_conf = self.up[-(self.conf)]
            dn_conf = self.dn[-(self.conf)]
        else:
            close_conf = close
            up_conf = up_curr
            dn_conf = dn_curr
        
        # Swing confirmation logic
        bull = close > up_curr and close_prev > up_prev and close_conf > up_conf and zl_curr > zl_prev
        bear = close < dn_curr and close_prev < dn_prev and close_conf < dn_conf and zl_curr < zl_prev
        
        # Update trend
        self.last_tr = self.tr
        if bull:
            self.tr = 1
        elif bear:
            self.tr = -1
        
        # Flip signal (confirmed trend change)
        flip = self.tr != self.last_tr and self.tr != 0
        
        # Entry logic
        if flip and self.tr == 1:
            if not self.position:
                self.buy()
        elif flip and self.tr == -1:
            if self.position:
                self.sell()