"""
OpenClaw Backtest Results: gold-breakout-trader
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gold-breakout-trader
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    # Time Settings
    trigger_hour = 7
    trigger_minute = 0
    extension_minutes = 10
    enable_2hour_plot = True
    
    # Box Settings
    box_height = 10.0
    show_gray_box = True
    
    # Spacing Settings
    stop_line_buffer = 2.0
    stop_to_tp_gap = 2.0
    tp_zone_gap = 1.0
    
    # TP Zone Settings
    tp1_height = 4.0
    tp2_height = 4.0
    tp3_height = 4.0
    
    # Alert Settings
    enable_alerts = True

    def init(self):
        self.last_trigger_time = None
        self.latest_buy_stop = None
        self.latest_sell_stop = None
        self.zones = []
        
        close = pd.Series(self.data.Close)
        self.price = self.I(lambda x: x, close)

    def next(self):
        current_time = self.data.index[-1]
        current_hour = current_time.hour
        current_minute = current_time.minute
        current_day = current_time.day
        
        should_trigger = False
        
        if self.enable_2hour_plot:
            if (current_minute == 0 and current_hour % 2 == 0):
                if (self.last_trigger_time is None or 
                    (current_time - self.last_trigger_time) >= timedelta(hours=2)):
                    should_trigger = True
        else:
            if (current_hour == self.trigger_hour and 
                current_minute == self.trigger_minute):
                if (self.last_trigger_time is None or 
                    current_day != self.last_trigger_time.day):
                    should_trigger = True
        
        if should_trigger:
            self.last_trigger_time = current_time
            ref_price = self.data.Close[-1]
            
            half_box_height = self.box_height / 2
            gray_box_top = ref_price + half_box_height
            gray_box_bottom = ref_price - half_box_height
            
            buy_stop = gray_box_top + self.stop_line_buffer
            sell_stop = gray_box_bottom - self.stop_line_buffer
            
            self.latest_buy_stop = buy_stop
            self.latest_sell_stop = sell_stop
            
            tp1_up_bot = buy_stop + self.stop_to_tp_gap
            tp1_up_top = tp1_up_bot + self.tp1_height
            
            tp2_up_bot = tp1_up_top + self.tp_zone_gap
            tp2_up_top = tp2_up_bot + self.tp2_height
            
            tp3_up_bot = tp2_up_top + self.tp_zone_gap
            tp3_up_top = tp3_up_bot + self.tp3_height
            
            tp1_dn_top = sell_stop - self.stop_to_tp_gap
            tp1_dn_bot = tp1_dn_top - self.tp1_height
            
            tp2_dn_top = tp1_dn_bot - self.tp_zone_gap
            tp2_dn_bot = tp2_dn_top - self.tp2_height
            
            tp3_dn_top = tp2_dn_bot - self.tp_zone_gap
            tp3_dn_bot = tp3_dn_top - self.tp3_height
            
            self.zones.append({
                'time': current_time,
                'buy_stop': buy_stop,
                'sell_stop': sell_stop,
                'tp1_up': (tp1_up_bot, tp1_up_top),
                'tp2_up': (tp2_up_bot, tp2_up_top),
                'tp3_up': (tp3_up_bot, tp3_up_top),
                'tp1_dn': (tp1_dn_bot, tp1_dn_top),
                'tp2_dn': (tp2_dn_bot, tp2_dn_top),
                'tp3_dn': (tp3_dn_bot, tp3_dn_top),
            })
        
        if self.latest_buy_stop is not None and self.latest_sell_stop is not None:
            current_price = self.data.Close[-1]
            prev_price = self.data.Close[-2] if len(self.data.Close) > 1 else current_price
            
            if prev_price <= self.latest_buy_stop and current_price > self.latest_buy_stop:
                if not self.position:
                    self.buy()
            
            elif prev_price >= self.latest_sell_stop and current_price < self.latest_sell_stop:
                if self.position:
                    self.position.close()
            
            if self.position:
                tp3_up_mid = (self.zones[-1]['tp3_up'][0] + self.zones[-1]['tp3_up'][1]) / 2
                tp1_dn_mid = (self.zones[-1]['tp1_dn'][0] + self.zones[-1]['tp1_dn'][1]) / 2
                
                if current_price >= tp3_up_mid:
                    self.position.close()
                elif current_price <= tp1_dn_mid:
                    self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()