"""
OpenClaw Backtest Results: internal-vs-external-liquidity-zones-alpha-extract
============================================================

--- SPY ---
  Return                    6.73%
  Buy & Hold Return         39.08%
  Max Drawdown              -6.04%
  Sharpe Ratio              0.58
  Sortino Ratio             1.02
  Calmar Ratio              0.55
  Profit Factor             1.60
  Expectancy                0.27%
  SQN                       0.76
  # Trades                  26
  Win Rate                  53.85%
  Best Trade                5.25%
  Worst Trade               -2.28%
  Avg Trade                 0.25%
  Exposure Time             32.40%
  Equity Final              106731.52$
  Equity Peak               109564.21$
  Avg Drawdown              -2.33%
  Max Drawdown Duration     358 days 00:00:00
  Max Trade Duration        36 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               3.34%
  Ann. Volatility           5.80%

--- BTC ---
  Return                    3.64%
  Buy & Hold Return         14.14%
  Max Drawdown              -8.31%
  Sharpe Ratio              0.16
  Sortino Ratio             0.27
  Calmar Ratio              0.22
  Profit Factor             1.22
  Expectancy                0.38%
  SQN                       0.26
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                16.04%
  Worst Trade               -4.00%
  Avg Trade                 0.20%
  Exposure Time             6.84%
  Equity Final              103637.44$
  Equity Peak               109629.73$
  Avg Drawdown              -5.86%
  Max Drawdown Duration     445 days 00:00:00
  Max Trade Duration        16 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               1.80%
  Ann. Volatility           11.15%

--- QQQ ---
  Return                    9.16%
  Buy & Hold Return         42.00%
  Max Drawdown              -5.04%
  Sharpe Ratio              0.57
  Sortino Ratio             0.88
  Calmar Ratio              0.90
  Profit Factor             1.92
  Expectancy                0.46%
  SQN                       1.04
  # Trades                  20
  Win Rate                  55.00%
  Best Trade                4.96%
  Worst Trade               -2.22%
  Avg Trade                 0.44%
  Exposure Time             24.00%
  Equity Final              109159.70$
  Equity Peak               113082.54$
  Avg Drawdown              -2.17%
  Max Drawdown Duration     272 days 00:00:00
  Max Trade Duration        15 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               4.52%
  Ann. Volatility           7.87%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — internal-vs-external-liquidity-zones-alpha-extract
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Structure parameters
    intLen = 3
    extLen = 10
    eqTolAtr = 0.25
    
    # Zone parameters
    atrLen = 14
    zoneAtrExt = 0.40
    zoneAtrInt = 0.40
    
    # Structure lookback
    structureLookbackExternal = 36
    structureLookbackInternal = 2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR for zone sizing
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # Calculate SMAs for trend analysis
        self.sma10 = self.I(pta.sma, close, length=10)
        self.sma20 = self.I(pta.sma, close, length=20)
        
        # Track structure points
        self.ext_high_price = None
        self.ext_low_price = None
        self.last_bullish_structure = False
        self.last_bearish_structure = False
        self.in_long = False
        self.in_short = False

    def next(self):
        if len(self.data) < max(self.extLen, self.structureLookbackExternal) + 1:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        # Simple pivot detection using recent highs/lows
        if len(self.data) >= self.extLen + 1:
            ext_high = max(self.data.High[-(self.extLen+1):-1])
            ext_low = min(self.data.Low[-(self.extLen+1):-1])
            
            if ext_high > (self.ext_high_price if self.ext_high_price else 0):
                self.ext_high_price = ext_high
            if ext_low < (self.ext_low_price if self.ext_low_price else float('inf')):
                self.ext_low_price = ext_low
        
        # Trend direction based on SMA
        if self.sma10[-1] > self.sma20[-1]:
            trend_direction = 1  # Bullish
        elif self.sma10[-1] < self.sma20[-1]:
            trend_direction = -1  # Bearish
        else:
            trend_direction = 0  # Neutral
        
        # Entry logic: BOS/CHoCH detection
        if self.ext_high_price and self.ext_low_price:
            range_top = max(self.ext_high_price, self.ext_low_price)
            range_bottom = min(self.ext_high_price, self.ext_low_price)
            
            # Bullish break above external high with uptrend
            if high > self.ext_high_price and trend_direction == 1:
                if not self.in_long and not self.position:
                    self.buy()
                    self.in_long = True
                    self.in_short = False
            
            # Bearish break below external low with downtrend
            if low < self.ext_low_price and trend_direction == -1:
                if not self.in_short and not self.position:
                    self.sell()
                    self.in_short = True
                    self.in_long = False
        
        # Exit logic: trend reversal
        if self.in_long and crossover(self.sma20, self.sma10):
            if self.position:
                self.position.close()
            self.in_long = False
        
        if self.in_short and crossover(self.sma10, self.sma20):
            if self.position:
                self.position.close()
            self.in_short = False
        
        # Stop loss: price reversal beyond internal zones
        if self.in_long and self.position:
            zone_height = self.atr[-1] * self.zoneAtrInt
            if low < self.data.Close[-2] - (zone_height * 2):
                self.position.close()
                self.in_long = False
        
        if self.in_short and self.position:
            zone_height = self.atr[-1] * self.zoneAtrInt
            if high > self.data.Close[-2] + (zone_height * 2):
                self.position.close()
                self.in_short = False


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()