"""
OpenClaw Backtest Results: lfwd-watermark-checklist
============================================================

--- SPY ---
  Return                    4.63%
  Buy & Hold Return         39.08%
  Max Drawdown              -21.51%
  Sharpe Ratio              0.20
  Sortino Ratio             0.26
  Calmar Ratio              0.11
  Profit Factor             1.34
  Expectancy                0.76%
  SQN                       0.16
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                22.90%
  Worst Trade               -12.43%
  Avg Trade                 0.41%
  Exposure Time             67.80%
  Equity Final              104629.67$
  Equity Peak               109373.16$
  Avg Drawdown              -3.61%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        176 days 00:00:00
  Avg Trade Duration        48 days 00:00:00
  Ann. Return               2.31%
  Ann. Volatility           11.34%

--- BTC ---
  Return                    7.33%
  Buy & Hold Return         14.14%
  Max Drawdown              -29.94%
  Sharpe Ratio              0.15
  Sortino Ratio             0.24
  Calmar Ratio              0.12
  Profit Factor             1.44
  Expectancy                1.46%
  SQN                       0.16
  # Trades                  18
  Win Rate                  27.78%
  Best Trade                46.61%
  Worst Trade               -11.82%
  Avg Trade                 0.73%
  Exposure Time             51.30%
  Equity Final              107327.49$
  Equity Peak               152196.55$
  Avg Drawdown              -4.40%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               3.59%
  Ann. Volatility           23.20%

--- QQQ ---
  Return                    12.05%
  Buy & Hold Return         42.00%
  Max Drawdown              -17.08%
  Sharpe Ratio              0.42
  Sortino Ratio             0.60
  Calmar Ratio              0.35
  Profit Factor             1.78
  Expectancy                1.14%
  SQN                       0.54
  # Trades                  12
  Win Rate                  50.00%
  Best Trade                18.58%
  Worst Trade               -6.01%
  Avg Trade                 0.96%
  Exposure Time             67.60%
  Equity Final              112052.52$
  Equity Peak               121407.37$
  Avg Drawdown              -3.15%
  Max Drawdown Duration     394 days 00:00:00
  Max Trade Duration        127 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               5.90%
  Ann. Volatility           14.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — lfwd-watermark-checklist
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.sma_fast = self.I(pta.sma, close, length=10)
        self.sma_slow = self.I(pta.sma, close, length=20)
        self.rsi = self.I(pta.rsi, close, length=14)

    def next(self):
        if crossover(self.sma_fast, self.sma_slow):
            if not self.position:
                self.buy()
        elif crossover(self.sma_slow, self.sma_fast):
            if self.position:
                self.position.close()