"""
OpenClaw Backtest Results: malaysian-snr-kaidon
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         37.60%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         11.87%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         40.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — malaysian-snr-kaidon
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    depth = 3
    sma_len = 21

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.sma21 = self.I(pta.sma, close, length=self.sma_len)
        
        self.pivot_lows = self._calculate_pivots(low, self.depth, is_high=False)
        self.pivot_highs = self._calculate_pivots(high, self.depth, is_high=True)
        
        self.in_long = False
        self.in_short = False
        self.support_level = None
        self.resistance_level = None

    def _calculate_pivots(self, series, depth, is_high=False):
        pivots = np.full(len(series), np.nan)
        for i in range(depth, len(series) - depth):
            if is_high:
                if series.iloc[i] == series.iloc[i-depth:i+depth+1].max():
                    pivots[i] = series.iloc[i]
            else:
                if series.iloc[i] == series.iloc[i-depth:i+depth+1].min():
                    pivots[i] = series.iloc[i]
        return pivots

    def next(self):
        close_price = self.data.Close[-1]
        
        current_pivot_low = self.pivot_lows[-1]
        current_pivot_high = self.pivot_highs[-1]
        sma_value = self.sma21[-1]
        
        if not np.isnan(current_pivot_low) and current_pivot_low < sma_value:
            self.support_level = current_pivot_low
        
        if not np.isnan(current_pivot_high) and current_pivot_high > sma_value:
            self.resistance_level = current_pivot_high
        
        if self.support_level is not None and not self.in_long:
            if close_price < self.support_level and close_price > self.support_level * 0.99:
                self.buy()
                self.in_long = True
                self.in_short = False
        
        if self.in_long and self.resistance_level is not None:
            if close_price > self.resistance_level:
                self.sell()
                self.in_long = False
        
        if self.resistance_level is not None and not self.in_short:
            if close_price > self.resistance_level and close_price < self.resistance_level * 1.01:
                self.sell()
                self.in_short = True
                self.in_long = False
        
        if self.in_short and self.support_level is not None:
            if close_price < self.support_level:
                self.buy()
                self.in_short = False


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()