"""
OpenClaw Backtest Results: strategy-pack-by-cryptokazancev
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         0.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    -20.77%
  Buy & Hold Return         -33.84%
  Max Drawdown              -28.76%
  Sharpe Ratio              -0.78
  Sortino Ratio             -0.89
  Calmar Ratio              -0.38
  Profit Factor             0.19
  Expectancy                -2.63%
  SQN                       -1.33
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                3.48%
  Worst Trade               -16.85%
  Avg Trade                 -2.81%
  Exposure Time             8.62%
  Equity Final              79227.19$
  Equity Peak               100911.19$
  Avg Drawdown              -18.74%
  Max Drawdown Duration     57 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -10.98%
  Ann. Volatility           14.04%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         0.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — strategy-pack-by-cryptokazancev
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Parameters from Pine Script
    swing_len = 2
    deep = 100
    zi_lookback = 10
    zi_multiplier_atr = 1.0
    zi_min_swing_count = 5
    multiplier_atr = 0.8
    multiplier_engulfing = 0.8
    max_ob_blocks = 10
    
    def init(self):
        # Calculate ATR-based volatility metrics
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Percent range ATR
        percent_range = (high - low) / low * 100
        self.atr = self.I(pta.sma, percent_range, length=500)
        self.custom_atr = self.atr * self.zi_multiplier_atr / 100
        self.custom_atr_pinbar = self.atr * self.multiplier_atr / 100
        self.custom_atr_engulfing = self.atr * self.multiplier_engulfing / 100
        
        # Calculate body and wicks for pinbar detection
        self.body = np.abs(close - pd.Series(self.data.Open)) / low * 100
        self.upper_wick = (high - np.maximum(pd.Series(self.data.Open), close)) / low * 100
        self.lower_wick = (np.minimum(pd.Series(self.data.Open), close) - low) / low * 100
        
        # Pivot points for structure
        self.swing_high = self.I(self._calc_swing_high, high, length=self.swing_len)
        self.swing_low = self.I(self._calc_swing_low, low, length=self.swing_len)
        
        # Track swing points for structure
        self.key_swing_high = np.nan
        self.key_swing_low = np.nan
        self.trend = None
        
        # Engulfing detection
        self.is_bullish_engulfing = False
        self.is_bearish_engulfing = False
    
    def _calc_swing_high(self, high, length):
        result = pd.Series(np.nan, index=high.index)
        for i in range(length, len(high) - length):
            if high.iloc[i] == high.iloc[i-length:i+length+1].max():
                result.iloc[i] = high.iloc[i]
        return result
    
    def _calc_swing_low(self, low, length):
        result = pd.Series(np.nan, index=low.index)
        for i in range(length, len(low) - length):
            if low.iloc[i] == low.iloc[i-length:i+length+1].min():
                result.iloc[i] = low.iloc[i]
        return result
    
    def next(self):
        if len(self.data) < 5:
            return
        
        close = self.data.Close[-1]
        open_price = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        # Current bar body and wicks
        body = abs(close - open_price) / low * 100 if low > 0 else 0
        upper_wick = (high - max(open_price, close)) / low * 100 if low > 0 else 0
        lower_wick = (min(open_price, close) - low) / low * 100 if low > 0 else 0
        
        # Previous bar data
        prev_close = self.data.Close[-2]
        prev_open = self.data.Open[-2]
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        prev_body = abs(prev_close - prev_open) / prev_low * 100 if prev_low > 0 else 0
        
        # Pinbar detection
        bull_pin = (lower_wick > body * 1.1 and 
                   lower_wick > self.custom_atr_pinbar[-1] and 
                   lower_wick > 0.3 and 
                   low < prev_low)
        
        bear_pin = (upper_wick > body * 1.1 and 
                   upper_wick > self.custom_atr_pinbar[-1] and 
                   upper_wick > 0.3 and 
                   high > prev_high)
        
        # Engulfing detection
        body_curr = abs(close - open_price) / open_price if open_price > 0 else 0
        
        bull_engulfing = (close > open_price and 
                         prev_close < prev_open and 
                         open_price <= prev_close and 
                         close >= prev_open and 
                         body_curr * 100 > self.custom_atr_engulfing[-1] and 
                         prev_low < self.data.Low[-3] if len(self.data) > 2 else False)
        
        bear_engulfing = (close < open_price and 
                         prev_close > prev_open and 
                         open_price >= prev_close and 
                         close <= prev_open and 
                         body_curr * 100 > self.custom_atr_engulfing[-1] and 
                         prev_high > self.data.High[-3] if len(self.data) > 2 else False)
        
        # Trading logic based on detected patterns
        # Buy on bullish pinbar or bullish engulfing
        if (bull_pin or bull_engulfing) and not self.position:
            self.buy()
        
        # Sell on bearish pinbar or bearish engulfing
        elif (bear_pin or bear_engulfing) and self.position:
            self.position.close()
        
        # Alternative exit: use ATR-based stop loss
        elif self.position:
            # Close longs on opposite signal
            if bear_pin or bear_engulfing:
                self.position.close()
        
        # Structure-based trading (trend following)
        if not np.isnan(self.swing_high[-1]):
            self.key_swing_high = self.swing_high[-1]
            self.trend = "UP"
            
            # Buy on breakout of recent swing high
            if close > self.key_swing_high and not self.position:
                self.buy()
        
        if not np.isnan(self.swing_low[-1]):
            self.key_swing_low = self.swing_low[-1]
            self.trend = "DOWN"
            
            # Sell on breakout of recent swing low
            if close < self.key_swing_low and self.position:
                self.position.close()


if __name__ == '__main__':
    # Load data
    data = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()