"""
OpenClaw Backtest Results: swing-highlow-wick-zones-support-resistance-indicator
============================================================

--- SPY ---
  Return                    87.47%
  Buy & Hold Return         43.17%
  Max Drawdown              -6.32%
  Sharpe Ratio              2.13
  Sortino Ratio             5.22
  Calmar Ratio              5.90
  Profit Factor             25.23
  Expectancy                2.95%
  SQN                       4.67
  # Trades                  22
  Win Rate                  86.36%
  Best Trade                13.44%
  Worst Trade               -1.40%
  Avg Trade                 2.91%
  Exposure Time             59.80%
  Equity Final              187469.03$
  Equity Peak               187469.03$
  Avg Drawdown              -0.89%
  Max Drawdown Duration     50 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               37.26%
  Ann. Volatility           17.51%

--- BTC ---
  Return                    851.05%
  Buy & Hold Return         37.68%
  Max Drawdown              -6.63%
  Sharpe Ratio              2.37
  Sortino Ratio             17.52
  Calmar Ratio              31.35
  Profit Factor             44.32
  Expectancy                7.41%
  SQN                       5.69
  # Trades                  37
  Win Rate                  94.59%
  Best Trade                33.34%
  Worst Trade               -4.03%
  Avg Trade                 7.19%
  Exposure Time             51.03%
  Equity Final              951053.80$
  Equity Peak               951908.53$
  Avg Drawdown              -1.65%
  Max Drawdown Duration     31 days 00:00:00
  Max Trade Duration        24 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               207.92%
  Ann. Volatility           87.71%

--- QQQ ---
  Return                    191.91%
  Buy & Hold Return         41.48%
  Max Drawdown              -7.06%
  Sharpe Ratio              2.69
  Sortino Ratio             9.10
  Calmar Ratio              10.15
  Profit Factor             nan
  Expectancy                4.86%
  SQN                       5.10
  # Trades                  23
  Win Rate                  100.00%
  Best Trade                20.99%
  Worst Trade               0.70%
  Avg Trade                 4.78%
  Exposure Time             67.20%
  Equity Final              291905.31$
  Equity Peak               292459.71$
  Avg Drawdown              -0.96%
  Max Drawdown Duration     48 days 00:00:00
  Max Trade Duration        65 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               71.59%
  Ann. Volatility           26.58%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — swing-highlow-wick-zones-support-resistance-indicator
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swing_length = 5
    box_extension = 10
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.swing_highs = self.I(self._detect_swing_high, high, self.swing_length)
        self.swing_lows = self.I(self._detect_swing_low, low, self.swing_length)
        
        self.entry_price = None
        self.last_swing_high_idx = -999
        self.last_swing_low_idx = -999
    
    def _detect_swing_high(self, highs, length):
        result = np.full(len(highs), np.nan)
        for i in range(length, len(highs) - length):
            if highs[i] == np.max(highs[i-length:i+length+1]):
                result[i] = highs[i]
        return result
    
    def _detect_swing_low(self, lows, length):
        result = np.full(len(lows), np.nan)
        for i in range(length, len(lows) - length):
            if lows[i] == np.min(lows[i-length:i+length+1]):
                result[i] = lows[i]
        return result
    
    def next(self):
        current_idx = len(self.data) - 1
        
        if not np.isnan(self.swing_highs[-1]):
            if self.position:
                if self.position.is_long:
                    self.position.close()
            elif current_idx - self.last_swing_high_idx > self.box_extension:
                self.last_swing_high_idx = current_idx
        
        if not np.isnan(self.swing_lows[-1]):
            if self.position:
                if self.position.is_short:
                    self.position.close()
            elif current_idx - self.last_swing_low_idx > self.box_extension:
                self.buy()
                self.last_swing_low_idx = current_idx
        
        if len(self.data) > self.swing_length * 2:
            if not self.position and not np.isnan(self.swing_lows[-1]):
                self.buy()
            elif self.position and self.position.is_long:
                if not np.isnan(self.swing_highs[-1]):
                    self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()