"""
OpenClaw Backtest Results: xauusd-breakout-sl-points-15-minute-strategy-by-nitin-soni
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — xauusd-breakout-sl-points-15-minute-strategy-by-nitin-soni
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    target_hour = 4
    target_minute = 30

    def init(self):
        pass

    def next(self):
        if len(self.data) < 1:
            return
        
        current_time = self.data.index[-1]
        current_hour = current_time.hour
        current_minute = current_time.minute
        
        is_first_candle = (current_hour == self.target_hour and 
                          current_minute == self.target_minute)
        
        if is_first_candle:
            c_high = self.data.High[-1]
            c_low = self.data.Low[-1]
            body = c_high - c_low
            
            buy_tp1 = c_high + body
            buy_tp2 = c_high + (body * 2)
            buy_final = c_high + (body * 3)
            
            sell_tp1 = c_low - body
            sell_tp2 = c_low - (body * 2)
            sell_final = c_low - (body * 3)
            
            if not self.position:
                self.buy()
        
        if self.position:
            if self.position.is_long:
                if len(self.data) > 0:
                    if self.data.High[-1] >= buy_tp1 or self.data.Low[-1] <= c_low:
                        self.sell()
            elif self.position.is_short:
                if len(self.data) > 0:
                    if self.data.Low[-1] <= sell_tp1 or self.data.High[-1] >= c_high:
                        self.buy()


if __name__ == "__main__":
    df = pd.read_csv("XAUUSD.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(df, TvStrategy, cash=100000, commission=0.0002)
    stats = bt.run()
    print(stats)
    bt.plot()