"""
DS-TV Backtest Results: 4-in-1-ma-macd-stochastic-and-rsi
============================================================

--- SPY ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- BTC ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- QQQ ---
  ERROR: '_Indicator' object has no attribute 'iloc'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 4-in-1-ma-macd-stochastic-and-rsi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Moving Averages
    len_ema1 = 5
    len_ema2 = 15
    len_ema3 = 35
    len_ema4 = 89
    len_ema5 = 200
    
    # MACD
    fastLength = 12
    slowLength = 26
    signalLength = 9
    
    # Stochastic
    periodK = 14
    smoothK = 1
    periodD = 3
    
    # RSI
    rsiLen = 14
    maLen = 14
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Moving Averages
        self.ema1 = self.I(pta.ema, close, length=self.len_ema1)
        self.ema2 = self.I(pta.ema, close, length=self.len_ema2)
        self.ema3 = self.I(pta.ema, close, length=self.len_ema3)
        self.ema4 = self.I(pta.ema, close, length=self.len_ema4)
        self.ema5 = self.I(pta.ema, close, length=self.len_ema5)
        
        # MACD
        macd_result = self.I(pta.macd, close, fast=self.fastLength, slow=self.slowLength, signal=self.signalLength)
        self.macd_line = macd_result.iloc[:, 0] if macd_result is not None else self.I(lambda: pd.Series(0, index=close.index))
        self.macd_signal = macd_result.iloc[:, 1] if macd_result is not None else self.I(lambda: pd.Series(0, index=close.index))
        self.macd_hist = macd_result.iloc[:, 2] if macd_result is not None else self.I(lambda: pd.Series(0, index=close.index))
        
        # Stochastic
        stoch_result = self.I(pta.stoch, high, low, close, k=self.periodK, d=self.periodD, smooth_k=self.smoothK)
        self.stoch_k = stoch_result.iloc[:, 0] if stoch_result is not None else self.I(lambda: pd.Series(50, index=close.index))
        self.stoch_d = stoch_result.iloc[:, 1] if stoch_result is not None else self.I(lambda: pd.Series(50, index=close.index))
        
        # RSI
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        self.rsi_ma = self.I(pta.sma, self.rsi, length=self.maLen)
    
    def next(self):
        # Buy when EMA 1 crosses above EMA 2 and RSI is not overbought
        if len(self) > self.len_ema2:
            if crossover(self.ema1, self.ema2) and self.rsi[-1] < 70:
                if not self.position:
                    self.buy()
            
            # Sell when EMA 1 crosses below EMA 2 or RSI is overbought
            elif crossover(self.ema2, self.ema1) or self.rsi[-1] > 80:
                if self.position:
                    self.position.close()
            
            # Also consider MACD crossover as additional signal
            if len(self) > 1:
                if crossover(self.macd_line, self.macd_signal) and self.rsi[-1] < 70:
                    if not self.position:
                        self.buy()
                elif crossover(self.macd_signal, self.macd_line) and self.rsi[-1] > 50:
                    if self.position:
                        self.position.close()
            
            # Stochastic oversold/overbought signals
            if len(self) > 1:
                if self.stoch_k[-1] < 20 and self.stoch_k[-2] <= self.stoch_k[-1] and self.rsi[-1] < 50:
                    if not self.position:
                        self.buy()
                elif self.stoch_k[-1] > 80 and self.stoch_k[-2] >= self.stoch_k[-1]:
                    if self.position:
                        self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()