"""
DS-TV Backtest Results: average-sentiment-oscillator-aso-lead
============================================================

--- SPY ---
  Return                    -32.28%
  Buy & Hold Return         38.96%
  Max Drawdown              -37.62%
  Sharpe Ratio              -1.26
  Sortino Ratio             -1.38
  Calmar Ratio              -0.47
  Profit Factor             0.43
  Expectancy                -2.43%
  SQN                       -0.85
  # Trades                  13
  Win Rate                  38.46%
  Best Trade                16.02%
  Worst Trade               -30.93%
  Avg Trade                 -2.99%
  Exposure Time             85.80%
  Equity Final              67717.52$
  Equity Peak               108322.62$
  Avg Drawdown              -5.94%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        126 days 00:00:00
  Avg Trade Duration        49 days 00:00:00
  Ann. Return               -17.84%
  Ann. Volatility           14.17%

--- BTC ---
  Return                    -23.52%
  Buy & Hold Return         11.75%
  Max Drawdown              -38.13%
  Sharpe Ratio              -0.73
  Sortino Ratio             -0.82
  Calmar Ratio              -0.33
  Profit Factor             0.34
  Expectancy                -5.64%
  SQN                       -0.64
  # Trades                  7
  Win Rate                  71.43%
  Best Trade                9.37%
  Worst Trade               -54.69%
  Avg Trade                 -8.83%
  Exposure Time             33.52%
  Equity Final              76482.02$
  Equity Peak               118683.36$
  Avg Drawdown              -7.31%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        59 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               -12.53%
  Ann. Volatility           17.17%

--- QQQ ---
  Return                    -46.97%
  Buy & Hold Return         41.48%
  Max Drawdown              -50.27%
  Sharpe Ratio              -1.61
  Sortino Ratio             -1.59
  Calmar Ratio              -0.54
  Profit Factor             0.43
  Expectancy                -2.75%
  SQN                       -1.02
  # Trades                  17
  Win Rate                  35.29%
  Best Trade                17.99%
  Worst Trade               -40.27%
  Avg Trade                 -3.53%
  Exposure Time             93.00%
  Equity Final              53033.02$
  Equity Peak               103951.20$
  Avg Drawdown              -26.80%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        142 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               -27.36%
  Ann. Volatility           17.02%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — average-sentiment-oscillator-aso-lead
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 10
    mode = 0
    cycleLen = 120
    phaseShift = 0
    useASOFilter = False
    upperLevel = 70
    lowerLevel = 30
    useRotation = False
    rotationAngle = 0.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        opens = pd.Series(self.data.Open)
        
        # Calculate intrarange
        def calc_intrarange():
            return high - low
        
        # Calculate grouplow and grouphigh using rolling
        def calc_grouplow():
            return low.rolling(self.length).min()
        
        def calc_grouphigh():
            return high.rolling(self.length).max()
        
        # Get groupopen (open from length-1 bars ago)
        def calc_groupopen():
            return opens.shift(self.length - 1)
        
        def calc_grouprange():
            return calc_grouphigh() - calc_groupopen()
        
        # Calculate intrabar bulls and bears
        def calc_intrabarbulls():
            intrarange = calc_intrarange()
            K1 = intrarange.copy()
            K1[K1 == 0] = 1
            numerator = (((close - low) + (high - opens)) / 2) * 100
            return numerator / K1
        
        def calc_intrabarbears():
            intrarange = calc_intrarange()
            K1 = intrarange.copy()
            K1[K1 == 0] = 1
            numerator = (((high - close) + (opens - low)) / 2) * 100
            return numerator / K1
        
        # Calculate group bulls and bears
        def calc_groupbulls():
            grouprange = calc_grouprange()
            K2 = grouprange.copy()
            K2[K2 == 0] = 1
            grouplow = calc_grouplow()
            grouphigh = calc_grouphigh()
            groupopen = calc_groupopen()
            numerator = (((close - grouplow) + (grouphigh - groupopen)) / 2) * 100
            return numerator / K2
        
        def calc_groupbears():
            grouprange = calc_grouprange()
            K2 = grouprange.copy()
            K2[K2 == 0] = 1
            grouplow = calc_grouplow()
            grouphigh = calc_grouphigh()
            groupopen = calc_groupopen()
            numerator = (((grouphigh - close) + (groupopen - grouplow)) / 2) * 100
            return numerator / K2
        
        # Calculate TempBufferBulls and TempBufferBears based on mode
        def calc_tempbufferbulls():
            intrabarbulls = calc_intrabarbulls()
            groupbulls = calc_groupbulls()
            if self.mode == 0:
                return (intrabarbulls + groupbulls) / 2
            elif self.mode == 1:
                return intrabarbulls
            else:
                return groupbulls
        
        def calc_tempbufferbears():
            intrabarbears = calc_intrabarbears()
            groupbears = calc_groupbears()
            if self.mode == 0:
                return (intrabarbears + groupbears) / 2
            elif self.mode == 1:
                return intrabarbears
            else:
                return groupbears
        
        # Calculate ASO Bulls and Bears using SMA
        def calc_aso_bulls():
            tempbulls = calc_tempbufferbulls()
            result = pta.sma(tempbulls, length=self.length)
            return result if result is not None else pd.Series(50, index=close.index)
        
        def calc_aso_bears():
            tempbears = calc_tempbufferbears()
            result = pta.sma(tempbears, length=self.length)
            return result if result is not None else pd.Series(50, index=close.index)
        
        # Store ASO indicators
        self.aso_bulls = self.I(calc_aso_bulls)
        self.aso_bears = self.I(calc_aso_bears)
        
        # Calculate sine curve for cycle
        def calc_sine_curve():
            idx = np.arange(len(close))
            base_phase = 2 * np.pi * (idx + self.phaseShift) / self.cycleLen
            phase = base_phase + self.rotationAngle if self.useRotation else base_phase
            return np.sin(phase) * 50.0
        
        self.sine_curve = self.I(calc_sine_curve)
        
        # Calculate ASO gate (filter)
        def calc_aso_gate():
            aso_bulls = calc_aso_bulls()
            aso_bears = calc_aso_bears()
            if self.useASOFilter:
                return (aso_bulls > self.upperLevel) | (aso_bears < self.lowerLevel)
            else:
                return pd.Series(True, index=close.index)
        
        self.aso_gate = self.I(calc_aso_gate)

    def next(self):
        # Trading rules based on ASO indicator
        # Buy when ASO Bulls cross above ASO Bears and gate is open
        # Sell when ASO Bears cross above ASO Bulls
        
        if len(self.data) < 2:
            return
        
        aso_bulls_current = self.aso_bulls[-1]
        aso_bulls_prev = self.aso_bulls[-2]
        aso_bears_current = self.aso_bears[-1]
        aso_bears_prev = self.aso_bears[-2]
        gate_current = self.aso_gate[-1]
        
        # Check for crossover: Bulls crossing above Bears
        if aso_bulls_prev <= aso_bears_prev and aso_bulls_current > aso_bears_current and gate_current:
            if not self.position:
                self.buy()
        
        # Check for crossover: Bears crossing above Bulls
        elif aso_bears_prev <= aso_bulls_prev and aso_bears_current > aso_bulls_current:
            if self.position:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()