"""
DS-TV Backtest Results: capital-rotational-event-cre
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — capital-rotational-event-cre
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lenRS = 14
    lenMom = 9

    def init(self):
        close = pd.Series(self.data.Close)
        
        # For this strategy, we'll use the close price as both p1 and p2
        # since we can't access multiple symbols in backtesting.py
        # The indicator calculates RS as p2/p1, so we'll use a ratio approach
        # For demonstration, we'll calculate RS based on close price momentum
        
        # Calculate relative strength line (using close as proxy)
        rs_ratio = close / close.shift(1)
        self.rsLine = self.I(lambda: pta.sma(rs_ratio, length=self.lenRS) * 100 or pd.Series(100, index=close.index))
        
        # Calculate RS momentum
        rs_change = self.rsLine.diff()
        self.momRS = self.I(lambda: pta.sma(rs_change, length=self.lenMom) or pd.Series(0, index=close.index))
        
        # Calculate SMA of RS for comparison
        self.rsMA = self.I(lambda: pta.sma(self.rsLine, length=self.lenRS) or pd.Series(100, index=close.index))

    def next(self):
        if len(self.data) < self.lenRS + self.lenMom + 5:
            return
        
        # Define bullish rotation: RS > SMA(RS) and momentum > 0
        bull = self.rsLine[-1] > self.rsMA[-1] and self.momRS[-1] > 0
        
        # Define bearish rotation: RS < SMA(RS) and momentum < 0
        bear = self.rsLine[-1] < self.rsMA[-1] and self.momRS[-1] < 0
        
        # Entry logic
        if bull and not self.position:
            self.buy()
        elif bear and self.position:
            self.sell()