"""
DS-TV Backtest Results: double-relative-strength-index-drsi
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — double-relative-strength-index-drsi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length_RSI = 14
    LT_DRSI = 57
    ST_DRSI = 56

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate RSI
        self.rsi = self.I(pta.rsi, close, length=self.Length_RSI)
        
        # Calculate Double RSI (D_RSI = 2 * RSI - RSI(RSI))
        def calculate_drsi(close_series):
            rsi_vals = pta.rsi(close_series, length=self.Length_RSI)
            if rsi_vals is None or len(rsi_vals) == 0:
                return pd.Series(50, index=close_series.index)
            rsi_of_rsi = pta.rsi(rsi_vals, length=self.Length_RSI)
            if rsi_of_rsi is None or len(rsi_of_rsi) == 0:
                return pd.Series(50, index=close_series.index)
            drsi = 2 * rsi_vals - rsi_of_rsi
            return drsi
        
        self.d_rsi = self.I(calculate_drsi, close)
        
        # State tracker for T (similar to Pine Script)
        self.t_state = 0

    def next(self):
        # Update T state based on D_RSI thresholds
        if self.d_rsi[-1] > self.LT_DRSI:
            self.t_state = 1
        elif self.d_rsi[-1] < self.ST_DRSI:
            self.t_state = -1
        
        # Detect crossovers for Bull and Bear signals
        # Bull signal: T crosses above 0 (from previous state <= 0 to current state > 0)
        if len(self) >= 2:
            prev_t = 1 if self.d_rsi[-2] > self.LT_DRSI else (-1 if self.d_rsi[-2] < self.ST_DRSI else self.t_state)
            curr_t = self.t_state
            
            bull_signal = prev_t <= 0 and curr_t > 0
            bear_signal = prev_t >= 0 and curr_t < 0
            
            if bull_signal and not self.position:
                self.buy()
            elif bear_signal and self.position:
                self.sell()
        elif len(self) == 1:
            # First bar initialization
            if self.d_rsi[-1] > self.LT_DRSI and not self.position:
                self.buy()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()