"""
DS-TV Backtest Results: goldspread-algo
============================================================

--- SPY ---
  Return                    -14.04%
  Buy & Hold Return         43.93%
  Max Drawdown              -14.04%
  Sharpe Ratio              -2.76
  Sortino Ratio             -2.53
  Calmar Ratio              -0.52
  Profit Factor             0.00
  Expectancy                -0.32%
  SQN                       -4.32
  # Trades                  47
  Win Rate                  0.00%
  Best Trade                -0.20%
  Worst Trade               -3.55%
  Avg Trade                 -0.32%
  Exposure Time             9.40%
  Equity Final              85958.95$
  Equity Peak               100000.00$
  Avg Drawdown              -14.04%
  Max Drawdown Duration     710 days 00:00:00
  Max Trade Duration        0 days 00:00:00
  Avg Trade Duration        0 days 00:00:00
  Ann. Return               -7.34%
  Ann. Volatility           2.66%

--- BTC ---
  Return                    -8.53%
  Buy & Hold Return         44.64%
  Max Drawdown              -8.53%
  Sharpe Ratio              -5.53
  Sortino Ratio             -5.10
  Calmar Ratio              -0.51
  Profit Factor             0.00
  Expectancy                -0.21%
  SQN                       -46.87
  # Trades                  56
  Win Rate                  0.00%
  Best Trade                -0.20%
  Worst Trade               -0.28%
  Avg Trade                 -0.21%
  Exposure Time             7.66%
  Equity Final              91465.69$
  Equity Peak               100000.00$
  Avg Drawdown              -8.53%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        0 days 00:00:00
  Avg Trade Duration        0 days 00:00:00
  Ann. Return               -4.36%
  Ann. Volatility           0.79%

--- QQQ ---
  Return                    -15.87%
  Buy & Hold Return         44.93%
  Max Drawdown              -15.87%
  Sharpe Ratio              -2.98
  Sortino Ratio             -2.69
  Calmar Ratio              -0.53
  Profit Factor             0.00
  Expectancy                -0.34%
  SQN                       -4.62
  # Trades                  50
  Win Rate                  0.00%
  Best Trade                -0.20%
  Worst Trade               -3.50%
  Avg Trade                 -0.35%
  Exposure Time             10.00%
  Equity Final              84131.80$
  Equity Peak               100000.00$
  Avg Drawdown              -15.87%
  Max Drawdown Duration     706 days 00:00:00
  Max Trade Duration        0 days 00:00:00
  Avg Trade Duration        0 days 00:00:00
  Ann. Return               -8.34%
  Ann. Volatility           2.80%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — goldspread-algo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 14
    overbought = 70
    oversold = 30
    takeProfit = 10
    stopLoss = 5

    def init(self):
        close = pd.Series(self.data.Close)
        self.rsi = self.I(pta.rsi, close, length=self.length)

    def next(self):
        if len(self.data) < self.length:
            return

        current_rsi = self.rsi[-1]
        
        if current_rsi is None:
            return

        long_condition = current_rsi < self.oversold
        short_condition = current_rsi > self.overbought

        current_price = self.data.Close[-1]
        
        if long_condition and not self.position:
            tp_price = current_price + (self.takeProfit * 0.0001)
            sl_price = current_price - (self.stopLoss * 0.0001)
            self.buy(tp=tp_price, sl=sl_price)
        
        elif short_condition and not self.position:
            tp_price = current_price - (self.takeProfit * 0.0001)
            sl_price = current_price + (self.stopLoss * 0.0001)
            self.sell(tp=tp_price, sl=sl_price)


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("GC=F", start="2024-01-01", end="2024-12-31", interval="1m")
    data.columns = ['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']
    data = data[['Open', 'High', 'Low', 'Close', 'Volume']]
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.0002)
    results = bt.run()
    
    print(results)
    bt.plot()