"""
DS-TV Backtest Results: hybrid-volume-spread-analysis
============================================================

--- SPY ---
  Return                    9.81%
  Buy & Hold Return         39.08%
  Max Drawdown              -11.84%
  Sharpe Ratio              0.56
  Sortino Ratio             0.83
  Calmar Ratio              0.41
  Profit Factor             1.92
  Expectancy                1.00%
  SQN                       0.52
  # Trades                  11
  Win Rate                  45.45%
  Best Trade                17.70%
  Worst Trade               -3.81%
  Avg Trade                 0.86%
  Exposure Time             45.60%
  Equity Final              109810.87$
  Equity Peak               118052.29$
  Avg Drawdown              -1.74%
  Max Drawdown Duration     301 days 00:00:00
  Max Trade Duration        116 days 00:00:00
  Avg Trade Duration        30 days 00:00:00
  Ann. Return               4.83%
  Ann. Volatility           8.68%

--- BTC ---
  Return                    14.55%
  Buy & Hold Return         14.14%
  Max Drawdown              -23.20%
  Sharpe Ratio              0.30
  Sortino Ratio             0.52
  Calmar Ratio              0.30
  Profit Factor             1.55
  Expectancy                1.96%
  SQN                       0.37
  # Trades                  13
  Win Rate                  30.77%
  Best Trade                43.11%
  Worst Trade               -10.91%
  Avg Trade                 1.09%
  Exposure Time             44.46%
  Equity Final              114553.71$
  Equity Peak               130231.23$
  Avg Drawdown              -5.93%
  Max Drawdown Duration     208 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        24 days 00:00:00
  Ann. Return               7.02%
  Ann. Volatility           23.32%

--- QQQ ---
  Return                    39.56%
  Buy & Hold Return         42.00%
  Max Drawdown              -21.44%
  Sharpe Ratio              0.75
  Sortino Ratio             1.31
  Calmar Ratio              0.85
  Profit Factor             16.13
  Expectancy                3.44%
  SQN                       2.49
  # Trades                  10
  Win Rate                  80.00%
  Best Trade                11.82%
  Worst Trade               -1.80%
  Avg Trade                 3.36%
  Exposure Time             89.00%
  Equity Final              139558.24$
  Equity Peak               145032.64$
  Avg Drawdown              -2.67%
  Max Drawdown Duration     175 days 00:00:00
  Max Trade Duration        154 days 00:00:00
  Avg Trade Duration        63 days 00:00:00
  Ann. Return               18.29%
  Ann. Volatility           24.37%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hybrid-volume-spread-analysis
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lenth = 10
    malenth = 20

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # Calculate volume ratio
        v = volume / volume.shift(1)
        v = v.fillna(1)
        
        # Calculate EMA of close and open
        mac = self.I(pta.ema, close, length=self.lenth)
        mao = self.I(pta.ema, open_, length=self.lenth)
        
        # Volume-adjusted indicators
        vmac = mac * v
        vmao = mao * v
        
        # Volume spread difference
        vd = vmac - vmao
        
        # EMA of volume spread difference
        vdma = self.I(pta.ema, vd, length=self.malenth)
        
        self.vd = vd
        self.vdma = vdma

    def next(self):
        # Up signal: vd crosses above 0
        if len(self.vd) > 1 and crossover(self.vd, 0):
            if not self.position:
                self.buy()
        
        # Down signal: vd crosses below 0
        if len(self.vd) > 1 and crossover(0, self.vd):
            if self.position:
                self.position.close()
        
        # Trend confirmation: vdma crosses above 0 (uptrend)
        if len(self.vdma) > 1 and crossover(self.vdma, 0):
            if not self.position:
                self.buy()
        
        # Trend confirmation: vdma crosses below 0 (downtrend)
        if len(self.vdma) > 1 and crossover(0, self.vdma):
            if self.position:
                self.position.close()