"""
DS-TV Backtest Results: takashi-kotegawa-bnf-cis-ma-divergence
============================================================

--- SPY ---
  ERROR: No Strategy subclass found in /root/.openclaw/workspace/openclaw-tradingview/backtests/oscillators/takashi-kotegawa-bnf-cis-ma-divergence.py

--- BTC ---
  ERROR: No Strategy subclass found in /root/.openclaw/workspace/openclaw-tradingview/backtests/oscillators/takashi-kotegawa-bnf-cis-ma-divergence.py

--- QQQ ---
  ERROR: No Strategy subclass found in /root/.openclaw/workspace/openclaw-tradingview/backtests/oscillators/takashi-kotegawa-bnf-cis-ma-divergence.py

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — takashi-kotegawa-bnf-cis-ma-divergence
Generated by DeepStack TradingView Pipeline
"""

