"""
DS-TV Backtest Results: zion-momentum-flow-wjdtks255
============================================================

--- SPY ---
  ERROR: invalid syntax (zion-momentum-flow-wjdtks255.py, line 8)

--- BTC ---
  ERROR: invalid syntax (zion-momentum-flow-wjdtks255.py, line 8)

--- QQQ ---
  ERROR: invalid syntax (zion-momentum-flow-wjdtks255.py, line 8)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — zion-momentum-flow-wjdtks255
Generated by DeepStack TradingView Pipeline
"""

```python
import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters from Pine Script
    length = 14    # Momentum Strength Period
    smooth = 3     # Oscillator Smoothing
    level = 15     # Strength Threshold Level

    def __init__(self):
        close = pd.Series(self.data.Close)
        
        # Helper function to calculate the ZION Momentum Flow indicator
        def calc_zion_oscillator(c_series, l, s):
            # Calculate RSI
            rsi_val = pta.rsi(c_series, length=l)
            if rsi_val is None:
                return pd.Series(np.zeros(len(c_series)), index=c_series.index)
            
            # Calculate centered RSI (RSI - 50)
            centered_rsi = rsi_val - 50
            
            # Calculate EMA of centered RSI (The Oscillator)
            osc = pta.ema(centered_rsi, length=s)
            if osc is None:
                return pd.Series(np.zeros(len(c_series)), index=c_series.index)
            
            # Fill NaN values with 0 to ensure array is returned
            return osc.fillna(0)

        self.osc = self.I(calc_zion_oscillator, close, self.length, self.smooth)

    def next(self):
        # Entry/Exit Logic based on Alert Conditions:
        # Buy on Bullish Energy Surge (crossover above level)
        if crossover(self.osc, self.level):
            self.buy()
        
        # Sell (Short) on Bearish Energy Surge (crossunder below -level)
        # Note: backtesting.lib.crossover(a, b) is True when a crosses above b.
        # To detect crossunder, we swap arguments: crossover(level, osc)
        elif crossover(-self.level, self.osc):
            self.sell()
```