"""
DS-TV Backtest Results: 15m-bos-ote-fvg-ob-prop-firm
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 15m-bos-ote-fvg-ob-prop-firm
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        # Get HTF data (15m) - we'll use current bar as proxy for 15m data
        htf_high = self.data.High[-1]
        htf_low = self.data.Low[-1]
        htf_close = self.data.Close[-1]
        
        # Current bar data
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        
        # Previous bar data
        if len(self.data) < 2:
            return
            
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        prev_close = self.data.Close[-2]
        prev_open = self.data.Open[-2]
        
        # Get two bars back for FVG check
        if len(self.data) < 3:
            return
            
        high_2back = self.data.High[-3]
        low_2back = self.data.Low[-3]
        
        # Get four bars back for internal pivot check
        if len(self.data) < 5:
            return
        
        # Pivot High (2, 2) - highest of 5 bars centered at bar 2 back
        internal_high_val = max(self.data.High[-5:-1])
        internal_low_val = min(self.data.Low[-5:-1])
        
        # Initialize state variables if not exists
        if not hasattr(self, 'last_high'):
            self.last_high = htf_high
            self.last_low = htf_low
            self.range_high = np.nan
            self.range_low = np.nan
            self.traded = False
            self.internal_high = internal_high_val
            self.internal_low = internal_low_val
        
        # Detect pivot highs and lows (swing length 3)
        if len(self.data) >= 7:
            pivot_high = max(self.data.High[-7:-1]) == self.data.High[-4]
            pivot_low = min(self.data.Low[-7:-1]) == self.data.Low[-4]
            
            if pivot_high and self.data.High[-4] > self.last_high:
                self.last_high = self.data.High[-4]
            if pivot_low and self.data.Low[-4] < self.last_low:
                self.last_low = self.data.Low[-4]
        
        # BOS Detection
        bull_bos = current_close > self.last_high and prev_close <= self.last_high
        bear_bos = current_close < self.last_low and prev_close >= self.last_low
        
        # Dealing range + OTE
        if bull_bos:
            self.range_high = htf_high
            self.range_low = self.last_low
            self.traded = False
        
        if bear_bos:
            self.range_low = htf_low
            self.range_high = self.last_high
            self.traded = False
        
        # OTE levels
        if not np.isnan(self.range_high) and not np.isnan(self.range_low):
            ote_high = self.range_low + (self.range_high - self.range_low) * 0.79
            ote_low = self.range_low + (self.range_high - self.range_low) * 0.618
        else:
            return
        
        # Fair Value Gap (3-candle)
        bull_fvg = current_low > high_2back
        bear_fvg = current_high < low_2back
        
        if bull_fvg:
            fvg_low_bull = high_2back
            fvg_high_bull = current_low
        else:
            fvg_low_bull = np.nan
            fvg_high_bull = np.nan
        
        if bear_fvg:
            fvg_high_bear = low_2back
            fvg_low_bear = current_high
        else:
            fvg_high_bear = np.nan
            fvg_low_bear = np.nan
        
        # Order Block (last opposing candle)
        bull_ob = prev_close < prev_open and bull_bos
        bear_ob = prev_close > prev_open and bear_bos
        
        if bull_ob:
            ob_high = prev_high
            ob_low = prev_low
        elif bear_ob:
            ob_high = prev_high
            ob_low = prev_low
        else:
            ob_high = np.nan
            ob_low = np.nan
        
        # Internal BOS (Lower TF)
        if len(self.data) >= 5:
            if self.data.High[-5] > self.data.High[-4] and self.data.High[-4] > self.data.High[-3]:
                self.internal_high = self.data.High[-4]
            if self.data.Low[-5] < self.data.Low[-4] and self.data.Low[-4] < self.data.Low[-3]:
                self.internal_low = self.data.Low[-4]
        
        ltf_bull_bos = current_close > self.internal_high and prev_close <= self.internal_high
        ltf_bear_bos = current_close < self.internal_low and prev_close >= self.internal_low
        
        # Retracement conditions
        in_ote_bull = current_low <= ote_high and current_low >= ote_low
        in_ote_bear = current_high >= ote_low and current_high <= ote_high
        
        tap_bull_fvg = not np.isnan(fvg_low_bull) and current_low <= fvg_high_bull and current_low >= fvg_low_bull
        tap_bear_fvg = not np.isnan(fvg_high_bear) and current_high >= fvg_low_bear and current_high <= fvg_high_bear
        
        tap_bull_ob = not np.isnan(ob_high) and current_low <= ob_high and current_low >= ob_low
        tap_bear_ob = not np.isnan(ob_high) and current_high >= ob_low and current_high <= ob_high
        
        # Entry conditions
        long_entry = (bull_bos == False and not self.traded and in_ote_bull and 
                     tap_bull_fvg and tap_bull_ob and ltf_bull_bos)
        
        short_entry = (bear_bos == False and not self.traded and in_ote_bear and 
                      tap_bear_fvg and tap_bear_ob and ltf_bear_bos)
        
        if long_entry:
            self.traded = True
            if not self.position:
                self.buy()
        
        if short_entry:
            self.traded = True
            if self.position:
                self.position.close()
            else:
                self.sell()
        
        # Exit logic - close on stop loss or target
        if self.position:
            if self.position.is_long:
                if current_low <= self.internal_low:
                    self.position.close()
                if current_high >= self.range_high:
                    self.position.close()
            else:
                if current_high >= self.internal_high:
                    self.position.close()
                if current_low <= self.range_low:
                    self.position.close()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()