"""
DS-TV Backtest Results: chitranjan-shastri-fixed-ultra-clear-pilot
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(ema(10),10)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "ema(ema(10),10)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(ema(10),10)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — chitranjan-shastri-fixed-ultra-clear-pilot
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Support/Resistance levels
    rs2_h = 26013
    rs2_l = 25913
    rs1_h = 25831
    rs1_l = 25783
    b1_h = 25613
    b1_l = 25556

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate DEMA 10
        e1_10 = self.I(pta.ema, close, length=10)
        e2_10 = self.I(pta.ema, e1_10, length=10)
        self.d10 = self.I(lambda: 2 * e1_10 - e2_10)
        
        # Calculate DEMA 20
        e1_20 = self.I(pta.ema, close, length=20)
        e2_20 = self.I(pta.ema, e1_20, length=20)
        self.d20 = self.I(lambda: 2 * e1_20 - e2_20)
        
        # Calculate DEMA 50
        e1_50 = self.I(pta.ema, close, length=50)
        e2_50 = self.I(pta.ema, e1_50, length=50)
        self.d50 = self.I(lambda: 2 * e1_50 - e2_50)

    def next(self):
        # Buy when price crosses above B1 bottom (support) with DEMA confirmation
        if len(self.data) > 1:
            if self.data.Close[-2] <= self.b1_l and self.data.Close[-1] > self.b1_l:
                if self.d10[-1] > self.d20[-1] > self.d50[-1]:
                    self.buy()
            
            # Sell when price crosses below RS1 top (resistance) with DEMA confirmation
            if self.data.Close[-2] >= self.rs1_h and self.data.Close[-1] < self.rs1_h:
                if self.d10[-1] < self.d20[-1] < self.d50[-1]:
                    self.sell()
            
            # Sell when price crosses above RS2 top (strong resistance)
            if self.data.Close[-2] <= self.rs2_h and self.data.Close[-1] > self.rs2_h:
                if self.position:
                    self.sell()
            
            # Close position if price falls below B1 bottom
            if self.data.Close[-1] < self.b1_l and self.position:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()