"""
DS-TV Backtest Results: cpr-supertrend-sma-credit-spreadoptions-sellers-kedarc-quant
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         36.88%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         8.89%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         43.09%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — cpr-supertrend-sma-credit-spreadoptions-sellers-kedarc-quant
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    # Default parameters from Pine Script
    param1 = 14  # example
    param2 = 10  # example
    param3 = 3.0  # example
    param4 = 21  # example
    param5 = 1  # example
    param6 = 0  # example
    param7 = 10  # example
    param8 = 3.0  # example
    param9 = 21  # example
    param10 = 0  # example
    param11 = 50  # example

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.supertrend = self.I(lambda: pta.supertrend(high, low, close, length=self.param2, multiplier=self.param3))
        self.sma21 = self.I(pta.sma, close, length=self.param9)
        self.atr = self.I(pta.atr, high, low, close, length=self.param7)

    def next(self):
        # Trading logic
        if crossover(self.supertrend, self.sma21) and self.supertrend[-1] < self.sma21[-1]:
            self.buy()
        elif crossover(self.supertrend, self.sma21) and self.supertrend[-1] > self.sma21[-1]:
            self.sell()