"""
DS-TV Backtest Results: custom-ema-sma-ribbon
============================================================

--- SPY ---
  Return                    12.49%
  Buy & Hold Return         15.06%
  Max Drawdown              -18.67%
  Sharpe Ratio              0.41
  Sortino Ratio             0.66
  Calmar Ratio              0.33
  Profit Factor             nan
  Expectancy                3.38%
  SQN                       1.10
  # Trades                  4
  Win Rate                  100.00%
  Best Trade                12.73%
  Worst Trade               0.20%
  Avg Trade                 3.25%
  Exposure Time             51.59%
  Equity Final              112486.53$
  Equity Peak               114518.60$
  Avg Drawdown              -2.00%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        276 days 00:00:00
  Avg Trade Duration        94 days 00:00:00
  Ann. Return               6.08%
  Ann. Volatility           14.72%

--- BTC ---
  Return                    -32.38%
  Buy & Hold Return         24.97%
  Max Drawdown              -44.76%
  Sharpe Ratio              -0.96
  Sortino Ratio             -1.06
  Calmar Ratio              -0.40
  Profit Factor             0.00
  Expectancy                -51.55%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -51.55%
  Worst Trade               -51.55%
  Avg Trade                 -51.55%
  Exposure Time             12.98%
  Equity Final              67617.76$
  Equity Peak               102481.79$
  Avg Drawdown              -44.76%
  Max Drawdown Duration     498 days 00:00:00
  Max Trade Duration        94 days 00:00:00
  Avg Trade Duration        94 days 00:00:00
  Ann. Return               -17.73%
  Ann. Volatility           18.53%

--- QQQ ---
  Return                    16.60%
  Buy & Hold Return         17.54%
  Max Drawdown              -22.67%
  Sharpe Ratio              0.44
  Sortino Ratio             0.72
  Calmar Ratio              0.35
  Profit Factor             18.37
  Expectancy                4.80%
  SQN                       1.44
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                13.38%
  Worst Trade               -0.88%
  Avg Trade                 4.64%
  Exposure Time             47.01%
  Equity Final              116598.59$
  Equity Peak               123154.37$
  Avg Drawdown              -2.43%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        225 days 00:00:00
  Avg Trade Duration        86 days 00:00:00
  Ann. Return               8.01%
  Ann. Volatility           18.06%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — custom-ema-sma-ribbon
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param1 = 10  # Length 1
    param2 = 20  # Length 2
    param3 = 50  # Length 3
    param4 = 100  # Length 4
    param5 = 150  # Length 5
    param6 = 200  # Length 6

    def init(self):
        close = pd.Series(self.data.Close)
        self.ma1 = self.I(pta.sma, close, length=self.param1)
        self.ma2 = self.I(pta.sma, close, length=self.param2)
        self.ma3 = self.I(pta.sma, close, length=self.param3)
        self.ma4 = self.I(pta.sma, close, length=self.param4)
        self.ma5 = self.I(pta.sma, close, length=self.param5)
        self.ma6 = self.I(pta.sma, close, length=self.param6)

    def next(self):
        if crossover(self.ma1, self.ma2) and self.ma3 > self.ma4 and self.ma4 > self.ma5 and self.ma5 > self.ma6:
            self.buy()
        elif crossover(self.ma2, self.ma1) and self.ma3 < self.ma4 and self.ma4 < self.ma5 and self.ma5 < self.ma6:
            self.sell()