"""
DS-TV Backtest Results: draggable-vwap-pivot-pairs-simplified
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — draggable-vwap-pivot-pairs-simplified
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters from Pine Script
    param1 = 14  # example

    def init(self):
        close = pd.Series(self.data.Close)
        # Calculate indicators using self.I() wrapper
        self.vwapHiHigh = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='high'), self.data)
        self.vwapHiClose = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='close'), self.data)
        self.vwapLoLow = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='low'), self.data)
        self.vwapLoClose = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='close'), self.data)
        self.vwapHighFalling = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='high') < pta.vwap(close, length=self.param1, vwap_type='high')[1], self.data)
        self.vwapLowRising = self.I(lambda: pta.vwap(close, length=self.param1, vwap_type='low') > pta.vwap(close, length=self.param1, vwap_type='low')[1], self.data)
        self.afterAnchor = self.I(lambda: time >= self.input("Anchor Start (drag me)", timestamp("2025-12-01 00:00")) or barstate.isfirst, self.data)

    def next(self):
        # Trading logic
        if self.vwapHighFalling and self.afterAnchor:
            self.buy()
        elif self.vwapLowRising and self.afterAnchor:
            self.sell()