"""
DS-TV Backtest Results: ema-system
============================================================

--- SPY ---
  Return                    -52.43%
  Buy & Hold Return         17.90%
  Max Drawdown              -54.25%
  Sharpe Ratio              -3.14
  Sortino Ratio             -2.68
  Calmar Ratio              -0.58
  Profit Factor             0.51
  Expectancy                -0.26%
  SQN                       -2.74
  # Trades                  271
  Win Rate                  36.16%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.27%
  Exposure Time             54.80%
  Equity Final              47573.53$
  Equity Peak               103993.60$
  Avg Drawdown              -13.08%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        5 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -31.23%
  Ann. Volatility           9.94%

--- BTC ---
  Return                    -5.66%
  Buy & Hold Return         17.39%
  Max Drawdown              -6.15%
  Sharpe Ratio              -0.79
  Sortino Ratio             -0.84
  Calmar Ratio              -0.47
  Profit Factor             0.38
  Expectancy                -0.74%
  SQN                       -1.15
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                1.53%
  Worst Trade               -3.21%
  Avg Trade                 -0.75%
  Exposure Time             1.37%
  Equity Final              94338.65$
  Equity Peak               100524.61$
  Avg Drawdown              -6.15%
  Max Drawdown Duration     412 days 00:00:00
  Max Trade Duration        2 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -2.87%
  Ann. Volatility           3.65%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ema-system
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len9 = 9
    len21 = 21
    len50 = 50
    len200 = 200
    atrLen = 14
    atrMult = 0.30
    pctProximity = 0.25
    volLen = 20
    volDryFactor = 0.80
    useATRProximity = True
    bullishMode = "Close>Open"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        open_ = pd.Series(self.data.Open)

        self.ema9 = self.I(pta.ema, close, length=self.len9)
        self.ema21 = self.I(pta.ema, close, length=self.len21)
        self.ema50 = self.I(pta.ema, close, length=self.len50)
        self.ema200 = self.I(pta.ema, close, length=self.len200)

        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        self.volSma = self.I(pta.sma, volume, length=self.volLen)

        self.close_series = close
        self.open_series = open_
        self.high_series = high
        self.low_series = low
        self.volume_series = volume

    def next(self):
        if len(self.data) < self.len200 + 5:
            return

        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]

        ema9 = self.ema9[-1]
        ema21 = self.ema21[-1]
        ema50 = self.ema50[-1]
        ema200 = self.ema200[-1]
        atr = self.atr[-1]
        volSma = self.volSma[-1]

        if ema9 is None or ema21 is None or ema50 is None or ema200 is None or atr is None or volSma is None:
            return

        longOnly = close > ema200
        trendValid = ema21 > ema50
        noBuys = close < ema50
        near21_atr = abs(close - ema21) <= (atr * self.atrMult)
        near21_pct = abs(close - ema21) <= (close * (self.pctProximity / 100.0))
        near21 = near21_atr if self.useATRProximity else near21_pct
        volDriesUp = volume < (volSma * self.volDryFactor)

        if self.bullishMode == "Close>Open":
            bullishCandle = close > open_
        else:
            prev_high = self.data.High[-2] if len(self.data) > 1 else high
            bullishCandle = close > prev_high

        setupReady = longOnly and trendValid and not noBuys and near21 and volDriesUp
        buySignal = setupReady and bullishCandle

        if not self.position:
            if buySignal:
                self.buy()
        else:
            if not setupReady or close < ema50:
                self.sell()