"""
DS-TV Backtest Results: gk-trend-ribbon-swing-prepare-hud
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         37.60%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         11.87%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         40.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gk-trend-ribbon-swing-prepare-hud
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 200
    mult = 2.0
    atrLen = 21
    conf = 2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate lag
        lag = max(int(np.floor((self.len - 1) / 2)), 0)
        
        # Calculate lagged close adjustment
        def get_lagged_close():
            result = []
            for i in range(len(close)):
                if lag > 0 and i >= lag:
                    adjusted = close.iloc[i] + (close.iloc[i] - close.iloc[i - lag])
                else:
                    adjusted = close.iloc[i]
                result.append(adjusted)
            return pd.Series(result, index=close.index)
        
        lagged_close = self.I(get_lagged_close)
        
        # EMA of lagged close
        def get_zl():
            zl_series = pta.ema(lagged_close, length=self.len)
            return zl_series if zl_series is not None else pd.Series(0, index=close.index)
        
        self.zl = self.I(get_zl)
        
        # ATR
        def get_atr():
            atr_series = pta.atr(high, low, close, length=self.atrLen)
            return atr_series if atr_series is not None else pd.Series(0, index=close.index)
        
        self.atr = self.I(get_atr)
        
        # Upper and lower bands
        def get_up():
            return self.zl + self.atr * self.mult
        
        def get_dn():
            return self.zl - self.atr * self.mult
        
        self.up = self.I(get_up)
        self.dn = self.I(get_dn)
        
        # Trend state tracking
        self.tr = 0
        self.prev_tr = 0

    def next(self):
        close = self.data.Close[-1]
        close_1 = self.data.Close[-2] if len(self.data.Close) > 1 else close
        
        up_curr = self.up[-1]
        up_prev = self.up[-2] if len(self.up) > 1 else up_curr
        
        dn_curr = self.dn[-1]
        dn_prev = self.dn[-2] if len(self.dn) > 1 else dn_curr
        
        zl_curr = self.zl[-1]
        zl_prev = self.zl[-2] if len(self.zl) > 1 else zl_curr
        
        # Get historical close values for conf check
        conf_idx = self.conf - 1
        close_conf = self.data.Close[-(conf_idx + 1)] if len(self.data.Close) > conf_idx else close
        up_conf = self.up[-(conf_idx + 1)] if len(self.up) > conf_idx else up_curr
        dn_conf = self.dn[-(conf_idx + 1)] if len(self.dn) > conf_idx else dn_curr
        
        # Bullish condition
        bull = (close > up_curr and 
                close_1 > up_prev and 
                close_conf > up_conf and 
                zl_curr > zl_prev)
        
        # Bearish condition
        bear = (close < dn_curr and 
                close_1 < dn_prev and 
                close_conf < dn_conf and 
                zl_curr < zl_prev)
        
        # Update trend state
        self.prev_tr = self.tr
        if bull:
            self.tr = 1
        elif bear:
            self.tr = -1
        
        # Flip signal: trend changed and is confirmed
        flip = self.tr != self.prev_tr and self.tr != 0
        
        # Execute trades on confirmed flips
        if flip and self.tr == 1:
            if not self.position:
                self.buy()
        elif flip and self.tr == -1:
            if self.position:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()