"""
DS-TV Backtest Results: green-bull-strategy
============================================================

--- SPY ---
  Return                    -3.89%
  Buy & Hold Return         37.60%
  Max Drawdown              -21.77%
  Sharpe Ratio              -0.14
  Sortino Ratio             -0.18
  Calmar Ratio              -0.09
  Profit Factor             0.96
  Expectancy                -0.06%
  SQN                       -0.20
  # Trades                  30
  Win Rate                  23.33%
  Best Trade                15.90%
  Worst Trade               -5.44%
  Avg Trade                 -0.15%
  Exposure Time             95.60%
  Equity Final              96109.91$
  Equity Peak               112668.13$
  Avg Drawdown              -4.11%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        103 days 00:00:00
  Avg Trade Duration        24 days 00:00:00
  Ann. Return               -1.98%
  Ann. Volatility           14.58%

--- BTC ---
  Return                    -26.20%
  Buy & Hold Return         11.87%
  Max Drawdown              -37.83%
  Sharpe Ratio              -0.56
  Sortino Ratio             -0.70
  Calmar Ratio              -0.37
  Profit Factor             0.58
  Expectancy                -1.46%
  SQN                       -0.79
  # Trades                  24
  Win Rate                  16.67%
  Best Trade                43.74%
  Worst Trade               -9.24%
  Avg Trade                 -1.85%
  Exposure Time             47.61%
  Equity Final              73796.17$
  Equity Peak               110989.89$
  Avg Drawdown              -14.22%
  Max Drawdown Duration     699 days 00:00:00
  Max Trade Duration        69 days 00:00:00
  Avg Trade Duration        15 days 00:00:00
  Ann. Return               -14.08%
  Ann. Volatility           25.29%

--- QQQ ---
  Return                    6.76%
  Buy & Hold Return         40.00%
  Max Drawdown              -19.14%
  Sharpe Ratio              0.17
  Sortino Ratio             0.25
  Calmar Ratio              0.18
  Profit Factor             1.27
  Expectancy                0.44%
  SQN                       0.28
  # Trades                  31
  Win Rate                  25.81%
  Best Trade                19.63%
  Worst Trade               -6.62%
  Avg Trade                 0.29%
  Exposure Time             95.20%
  Equity Final              106760.11$
  Equity Peak               132026.06$
  Avg Drawdown              -4.89%
  Max Drawdown Duration     131 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               3.35%
  Ann. Volatility           19.48%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — green-bull-strategy
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy


class TvStrategy(Strategy):
    Length = 21
    Multiplier = 3.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR with length 1
        atr = self.I(pta.atr, high, low, close, length=1)
        
        # Calculate WMA of ATR
        atr_series = pd.Series(atr)
        avgTR = self.I(pta.wma, atr_series, length=self.Length)
        
        # Calculate highest high and lowest low over Length periods
        highest = self.I(lambda: high.rolling(window=self.Length).max())
        lowest = self.I(lambda: low.rolling(window=self.Length).min())
        
        self.atr = atr
        self.avgTR = avgTR
        self.highest = highest
        self.lowest = lowest
        self.ret = None
        self.pos = None
        self.prev_pos = 0

    def next(self):
        idx = len(self.data) - 1
        
        if idx < self.Length:
            return
        
        # Get previous values
        if idx == self.Length:
            prev_ret = self.data.Close[-self.Length]
            prev_pos = 0
        else:
            prev_ret = self.ret
            prev_pos = self.pos
        
        # Calculate limits using previous bar values
        hiLimit = self.highest[-2] - self.avgTR[-2] * self.Multiplier
        loLimit = self.lowest[-2] + self.avgTR[-2] * self.Multiplier
        
        current_close = self.data.Close[-1]
        
        # Update ret value
        if current_close > hiLimit and current_close > loLimit:
            ret = hiLimit
        elif current_close < loLimit and current_close < hiLimit:
            ret = loLimit
        else:
            ret = prev_ret
        
        # Update pos value
        if current_close > ret:
            pos = 1
        elif current_close < ret:
            pos = -1
        else:
            pos = prev_pos
        
        self.ret = ret
        self.pos = pos
        
        # Trading logic
        if pos != prev_pos:
            if pos == 1:
                if self.position.is_short:
                    self.position.close()
                self.buy()
            elif pos == -1:
                if self.position.is_long:
                    self.position.close()
                self.sell()
        
        self.prev_pos = pos