"""
DS-TV Backtest Results: ma-bb-levels-st
============================================================

--- SPY ---
  Return                    18.52%
  Buy & Hold Return         39.08%
  Max Drawdown              -4.14%
  Sharpe Ratio              1.39
  Sortino Ratio             2.53
  Calmar Ratio              2.16
  Profit Factor             7.27
  Expectancy                2.21%
  SQN                       1.71
  # Trades                  8
  Win Rate                  75.00%
  Best Trade                9.41%
  Worst Trade               -1.48%
  Avg Trade                 2.16%
  Exposure Time             26.60%
  Equity Final              118520.58$
  Equity Peak               118594.22$
  Avg Drawdown              -1.04%
  Max Drawdown Duration     175 days 00:00:00
  Max Trade Duration        41 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               8.94%
  Ann. Volatility           6.45%

--- BTC ---
  Return                    31.01%
  Buy & Hold Return         14.14%
  Max Drawdown              -13.17%
  Sharpe Ratio              0.71
  Sortino Ratio             1.33
  Calmar Ratio              1.10
  Profit Factor             2.38
  Expectancy                2.91%
  SQN                       1.17
  # Trades                  15
  Win Rate                  60.00%
  Best Trade                20.62%
  Worst Trade               -9.73%
  Avg Trade                 2.55%
  Exposure Time             26.13%
  Equity Final              131011.94$
  Equity Peak               134362.13$
  Avg Drawdown              -3.71%
  Max Drawdown Duration     145 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        12 days 00:00:00
  Ann. Return               14.44%
  Ann. Volatility           20.34%

--- QQQ ---
  Return                    22.82%
  Buy & Hold Return         42.00%
  Max Drawdown              -8.73%
  Sharpe Ratio              0.70
  Sortino Ratio             1.33
  Calmar Ratio              1.25
  Profit Factor             2.62
  Expectancy                2.59%
  SQN                       0.84
  # Trades                  9
  Win Rate                  44.44%
  Best Trade                21.01%
  Worst Trade               -4.36%
  Avg Trade                 2.31%
  Exposure Time             36.40%
  Equity Final              122820.22$
  Equity Peak               134572.62$
  Avg Drawdown              -2.08%
  Max Drawdown Duration     176 days 00:00:00
  Max Trade Duration        63 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               10.92%
  Ann. Volatility           15.57%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ma-bb-levels-st
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema9Len = 9
    ema20Len = 20
    bbLen = 20
    bbStdDev = 2.0

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.ema9 = self.I(pta.ema, close, length=self.ema9Len)
        self.ema20 = self.I(pta.ema, close, length=self.ema20Len)
        
        ema_basis = self.I(pta.ema, close, length=self.bbLen)
        
        dev_series = self.I(lambda x: self.bbStdDev * x.rolling(self.bbLen).std(), close)
        
        self.bbUpper = self.I(lambda: ema_basis + dev_series if len(ema_basis) > 0 and len(dev_series) > 0 else pd.Series(0, index=close.index))
        self.bbLower = self.I(lambda: ema_basis - dev_series if len(ema_basis) > 0 and len(dev_series) > 0 else pd.Series(0, index=close.index))

    def next(self):
        if len(self.data) < self.bbLen + 5:
            return
        
        if crossover(self.ema9, self.ema20):
            if not self.position:
                self.buy()
        
        elif crossover(self.ema20, self.ema9):
            if self.position:
                self.position.close()
        
        if self.position and self.data.Close[-1] >= self.bbUpper[-1]:
            self.position.close()
        
        if not self.position and self.data.Close[-1] <= self.bbLower[-1]:
            if len(self.data) > 1 and self.data.Close[-1] > self.data.Close[-2]:
                self.buy()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()