"""
DS-TV Backtest Results: mean-deviation-trend-backquant
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "atr(H,L,14)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (732,); indicator "atr(H,L,14)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "atr(H,L,14)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — mean-deviation-trend-backquant
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param1 = 21  # Mean Length
    param2 = 14  # Deviation Smoothing
    param3 = 8   # Deviation Accumulation
    param4 = 0.7 # Band Tight (High Deviation)
    param5 = 2.6 # Band Wide (Low Deviation)

    def init(self):
        close = pd.Series(self.data.Close)
        atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=14)
        mean = self.I(pta.ema, close=close, length=self.param1)
        rawDev = (close - mean) / atr
        devSmooth = self.I(pta.ema, close=rawDev, length=self.param2)
        cumDev = self.I(pta.sma, close=devSmooth, length=self.param3)
        devAbs = abs(cumDev)
        devHigh = devAbs.rolling(80).max()
        devNorm = devHigh / devAbs
        tDir = np.where(cumDev > 0, 1, -1)
        flip = tDir != tDir.shift(1)
        bandMult = self.param5 - devNorm * (self.param5 - self.param4)
        bandW = atr * bandMult
        activeBand = np.where(tDir == 1, mean - bandW, mean + bandW)
        activeBand = self.I(pta.ema, close=activeBand, length=3)
        outerBand = np.where(tDir == 1, mean + bandW * 0.5, mean - bandW * 0.5)
        outerBand = self.I(pta.ema, close=outerBand, length=3)
        self.mean = mean
        self.atr = atr
        self.rawDev = rawDev
        self.devSmooth = devSmooth
        self.cumDev = cumDev
        self.devAbs = devAbs
        self.devHigh = devHigh
        self.devNorm = devNorm
        self.tDir = tDir
        self.flip = flip
        self.bandMult = bandMult
        self.bandW = bandW
        self.activeBand = activeBand
        self.outerBand = outerBand

    def next(self):
        if self.flip and self.tDir == 1:
            self.buy()
        elif self.flip and self.tDir == -1:
            self.sell()