"""
DS-TV Backtest Results: mnq-gold-fib-ema-signal-tool
============================================================

--- SPY ---
  ERROR: TvStrategy.init.<locals>.<lambda>() got an unexpected keyword argument 'index'

--- BTC ---
  ERROR: TvStrategy.init.<locals>.<lambda>() got an unexpected keyword argument 'index'

--- QQQ ---
  ERROR: TvStrategy.init.<locals>.<lambda>() got an unexpected keyword argument 'index'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — mnq-gold-fib-ema-signal-tool
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    param1 = 20  # Fibonacci Lookback (Bars)
    param2 = 200  # Trend Filter (EMA 200)

    def init(self):
        close = pd.Series(self.data.Close)
        self.ema200 = self.I(pta.ema, close, length=self.param2)
        self.fib_786 = self.I(lambda: ta.highest(self.data.High, self.param1) - (ta.highest(self.data.High, self.param1) - ta.lowest(self.data.Low, self.param1)) * 0.786, index=close.index)
        self.fib_618 = self.I(lambda: ta.highest(self.data.High, self.param1) - (ta.highest(self.data.High, self.param1) - ta.lowest(self.data.Low, self.param1)) * 0.618, index=close.index)
        self.fib_500 = self.I(lambda: ta.highest(self.data.High, self.param1) - (ta.highest(self.data.High, self.param1) - ta.lowest(self.data.Low, self.param1)) * 0.500, index=close.index)

    def next(self):
        if self.data.Close[-1] > self.ema200[-1] and self.data.Close[-1] < self.fib_618[-1]:
            self.buy()
        elif self.data.Close[-1] < self.ema200[-1] and self.data.Close[-1] > self.fib_618[-1]:
            self.sell()

    def I(self, func, *args, **kwargs):
        result = func(*args, **kwargs)
        if result is None:
            return pd.Series([np.nan] * len(args[0]), index=args[0].index)
        return result