"""
DS-TV Backtest Results: nq-945-1015-ict-strategy-complete
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         1.96%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         46.09%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — nq-945-1015-ict-strategy-complete
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime


class TvStrategy(Strategy):
    daily_bias_type = "Price > EMA20"
    ema_length = 20
    risk_reward = 2.0
    show_levels = True
    ob_refine = "On"
    refine_type = "Defensive"

    def init(self):
        self.daily_ema = None
        self.prev_daily_close = None
        self.pd_high = None
        self.pd_low = None
        
        self.low_swept = False
        self.high_swept = False
        self.bullish_mss = False
        self.bearish_mss = False
        self.bull_mss_now = False
        self.bear_mss_now = False
        
        self.last_swing_high = np.nan
        self.last_swing_low = np.nan
        self.last_swing_high_bar = np.nan
        self.last_swing_low_bar = np.nan
        
        self.bull_ob_high = np.nan
        self.bull_ob_low = np.nan
        self.bull_ob_bar = np.nan
        self.bear_ob_high = np.nan
        self.bear_ob_low = np.nan
        self.bear_ob_bar = np.nan
        
        self.trade_taken_today = False
        self.last_day = None
        
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=55)

    def next(self):
        current_time = self.data.index[-1]
        current_day = current_time.date()
        
        if self.last_day is None:
            self.last_day = current_day
        
        is_new_day = current_day != self.last_day
        if is_new_day:
            self.low_swept = False
            self.high_swept = False
            self.bullish_mss = False
            self.bearish_mss = False
            self.bull_ob_high = np.nan
            self.bull_ob_low = np.nan
            self.bull_ob_bar = np.nan
            self.bear_ob_high = np.nan
            self.bear_ob_low = np.nan
            self.bear_ob_bar = np.nan
            self.trade_taken_today = False
            self.last_day = current_day
        
        in_time_window = (current_time.hour == 9 and current_time.minute >= 45) or \
                         (current_time.hour == 10 and current_time.minute <= 15)
        
        close_val = self.data.Close[-1]
        open_val = self.data.Open[-1]
        high_val = self.data.High[-1]
        low_val = self.data.Low[-1]
        
        if len(self.data.Close) >= self.ema_length:
            close_series = pd.Series(self.data.Close)
            ema_result = pta.ema(close_series, length=self.ema_length)
            if ema_result is not None and len(ema_result) > 0:
                self.daily_ema = ema_result.iloc[-1]
        
        if self.daily_ema is not None:
            if self.daily_bias_type == "Price > EMA20":
                bullish_bias = close_val > self.daily_ema
            else:
                if len(self.data.Close) >= 2:
                    prev_close = self.data.Close[-2]
                    bullish_bias = prev_close > self.daily_ema
                else:
                    bullish_bias = close_val > self.daily_ema
        else:
            bullish_bias = True
        
        bearish_bias = not bullish_bias
        
        if len(self.data.Close) >= 1:
            if self.pd_high is None:
                self.pd_high = high_val
                self.pd_low = low_val
        
        if low_val < self.pd_low and close_val > self.pd_low:
            self.low_swept = True
        
        if high_val > self.pd_high and close_val < self.pd_high:
            self.high_swept = True
        
        if len(self.data.Close) >= 5:
            is_fractal_high = (self.data.High[-3] > self.data.High[-5] and
                               self.data.High[-3] > self.data.High[-4] and
                               self.data.High[-3] > self.data.High[-2] and
                               self.data.High[-3] > self.data.High[-1])
            
            is_fractal_low = (self.data.Low[-3] < self.data.Low[-5] and
                              self.data.Low[-3] < self.data.Low[-4] and
                              self.data.Low[-3] < self.data.Low[-2] and
                              self.data.Low[-3] < self.data.Low[-1])
            
            if is_fractal_high:
                self.last_swing_high = self.data.High[-3]
                self.last_swing_high_bar = len(self.data) - 3
            
            if is_fractal_low:
                self.last_swing_low = self.data.Low[-3]
                self.last_swing_low_bar = len(self.data) - 3
        
        prev_bullish_mss = self.bullish_mss
        prev_bearish_mss = self.bearish_mss
        
        if not np.isnan(self.last_swing_high):
            if close_val > self.last_swing_high and len(self.data.Close) >= 2:
                if self.data.Close[-2] <= self.last_swing_high:
                    self.bullish_mss = True
                    self.bearish_mss = False
        
        if not np.isnan(self.last_swing_low):
            if close_val < self.last_swing_low and len(self.data.Close) >= 2:
                if self.data.Close[-2] >= self.last_swing_low:
                    self.bearish_mss = True
                    self.bullish_mss = False
        
        self.bull_mss_now = self.bullish_mss and not prev_bullish_mss
        self.bear_mss_now = self.bearish_mss and not prev_bearish_mss
        
        atr_val = self.atr[-1] if len(self.atr) > 0 and not np.isnan(self.atr[-1]) else 1.0
        
        if self.bull_mss_now and bullish_bias:
            for i in range(1, min(21, len(self.data.Close))):
                if self.data.Close[-i] < self.data.Open[-i]:
                    ob_high = self.data.High[-i]
                    ob_low = self.data.Low[-i]
                    
                    if self.ob_refine == "On":
                        candle_range = self.data.High[-i] - self.data.Low[-i]
                        
                        if self.refine_type == "Defensive":
                            if candle_range <= atr_val * 0.5:
                                ob_high = self.data.High[-i]
                                ob_low = self.data.Low[-i]
                            elif candle_range <= atr_val:
                                ob_high = self.data.Close[-i]
                                ob_low = self.data.Low[-i]
                            else:
                                ob_high = self.data.Close[-i]
                                ob_low = self.data.Low[-i]
                    
                    self.bull_ob_high = ob_high
                    self.bull_ob_low = ob_low
                    self.bull_ob_bar = len(self.data) - i
                    break
        
        if self.bear_mss_now and bearish_bias:
            for i in range(1, min(21, len(self.data.Close))):
                if self.data.Close[-i] > self.data.Open[-i]:
                    ob_high = self.data.High[-i]
                    ob_low = self.data.Low[-i]
                    
                    if self.ob_refine == "On":
                        candle_range = self.data.High[-i] - self.data.Low[-i]
                        
                        if self.refine_type == "Defensive":
                            if candle_range <= atr_val * 0.5:
                                ob_high = self.data.High[-i]
                                ob_low = self.data.Low[-i]
                            elif candle_range <= atr_val:
                                ob_high = self.data.High[-i]
                                ob_low = self.data.Close[-i]
                            else:
                                ob_high = self.data.High[-i]
                                ob_low = self.data.Close[-i]
                    
                    self.bear_ob_high = ob_high
                    self.bear_ob_low = ob_low
                    self.bear_ob_bar = len(self.data) - i
                    break
        
        if not np.isnan(self.bull_ob_low) and low_val <= self.bull_ob_low:
            self.bull_ob_high = np.nan
            self.bull_ob_low = np.nan
        
        if not np.isnan(self.bear_ob_high) and high_val >= self.bear_ob_high:
            self.bear_ob_high = np.nan
            self.bear_ob_low = np.nan
        
        long_condition = (bullish_bias and self.low_swept and self.bullish_mss and 
                         in_time_window and not np.isnan(self.bull_ob_low) and 
                         low_val <= self.bull_ob_high and close_val >= self.bull_ob_low)
        
        short_condition = (bearish_bias and self.high_swept and self.bearish_mss and 
                          in_time_window and not np.isnan(self.bear_ob_low) and 
                          high_val >= self.bear_ob_low and close_val <= self.bear_ob_high)
        
        if long_condition and not self.trade_taken_today and not self.position:
            stop_loss = self.bull_ob_low
            entry_price = close_val
            risk_amount = entry_price - stop_loss
            take_profit = entry_price + (risk_amount * self.risk_reward)
            
            self.buy()
            self.trade_taken_today = True
        
        if short_condition and not self.trade_taken_today and not self.position:
            stop_loss = self.bear_ob_high
            entry_price = close_val
            risk_amount = stop_loss - entry_price
            take_profit = entry_price - (risk_amount * self.risk_reward)
            
            self.sell()
            self.trade_taken_today = True
        
        if self.position and self.position.is_long:
            if low_val <= self.bull_ob_low or close_val > (self.position.open_price + 
                                                            (self.position.open_price - self.bull_ob_low) * self.risk_reward):
                self.position.close()
        
        if self.position and self.position.is_short:
            if high_val >= self.bear_ob_high or close_val < (self.position.open_price - 
                                                              (self.bear_ob_high - self.position.open_price) * self.risk_reward):
                self.position.close()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("NQ=F", start="2024-01-01", end="2024-12-31", interval="5m")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.0002)
    stats = bt.run()
    print(stats)