"""
DS-TV Backtest Results: oliver-velez-system-visual-helper-cocochoco
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(λ,10)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "sma(λ,10)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(λ,10)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — oliver-velez-system-visual-helper-cocochoco
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    threshold = 0.5
    slope_limit = 0.05
    slope_lookback = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        self.sma20 = self.I(pta.sma, close, length=20)
        self.sma200 = self.I(pta.sma, close, length=200)
        
        self.body_size = self.I(lambda: np.abs(open_ - close))
        self.total_range = self.I(lambda: high - low)
        self.avg_body = self.I(pta.sma, self.body_size, length=10)
        
        self.bull_confluence_bars = self.I(self._calc_bull_confluence)
        self.bear_confluence_bars = self.I(self._calc_bear_confluence)

    def _calc_bull_confluence(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        sma20 = pta.sma(close, length=20)
        sma200 = pta.sma(close, length=200)
        
        diff = np.abs(sma20 - sma200) / sma200 * 100
        is_narrow_dist = diff <= self.threshold
        
        sma20_slope = np.abs(sma20 - sma20.shift(self.slope_lookback)) / sma20.shift(self.slope_lookback) * 100
        sma200_slope = np.abs(sma200 - sma200.shift(self.slope_lookback)) / sma200.shift(self.slope_lookback) * 100
        is_horizontal = (sma20_slope <= self.slope_limit) & (sma200_slope <= self.slope_limit)
        
        is_narrow = is_narrow_dist & is_horizontal
        is_bull = sma20 > sma200
        
        bull_confluence = is_narrow & is_bull
        
        result = pd.Series(0, index=close.index)
        for i in range(len(result)):
            if bull_confluence.iloc[i]:
                result.iloc[i] = 0
            else:
                result.iloc[i] = result.iloc[i-1] + 1 if i > 0 else 1
        
        return result
    
    def _calc_bear_confluence(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        sma20 = pta.sma(close, length=20)
        sma200 = pta.sma(close, length=200)
        
        diff = np.abs(sma20 - sma200) / sma200 * 100
        is_narrow_dist = diff <= self.threshold
        
        sma20_slope = np.abs(sma20 - sma20.shift(self.slope_lookback)) / sma20.shift(self.slope_lookback) * 100
        sma200_slope = np.abs(sma200 - sma200.shift(self.slope_lookback)) / sma200.shift(self.slope_lookback) * 100
        is_horizontal = (sma20_slope <= self.slope_limit) & (sma200_slope <= self.slope_limit)
        
        is_narrow = is_narrow_dist & is_horizontal
        is_bear = sma20 < sma200
        
        bear_confluence = is_narrow & is_bear
        
        result = pd.Series(0, index=close.index)
        for i in range(len(result)):
            if bear_confluence.iloc[i]:
                result.iloc[i] = 0
            else:
                result.iloc[i] = result.iloc[i-1] + 1 if i > 0 else 1
        
        return result

    def next(self):
        if len(self.data) < self.slope_lookback + 1:
            return
        
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        sma20 = self.sma20[-1]
        sma200 = self.sma200[-1]
        
        close_prev = self.data.Close[-2]
        open_prev = self.data.Open[-2]
        high_prev = self.data.High[-2]
        low_prev = self.data.Low[-2]
        
        body_size = np.abs(open_ - close)
        total_range = high - low
        avg_body = self.avg_body[-1]
        
        is_solid = body_size >= total_range * 0.75
        is_eb = body_size > (avg_body * 1.5) and is_solid
        
        is_bt = low < min(open_, close) - (total_range * 0.60) and close > open_
        is_tt = high > max(open_, close) + (total_range * 0.60) and close < open_
        
        body_size_prev = np.abs(open_prev - close_prev)
        is_b180 = close_prev < open_prev and close > open_ and open_ <= close_prev and close >= open_prev
        is_bear180 = close_prev > open_prev and close < open_ and open_ >= close_prev and close <= open_prev
        
        was_bull_narrow = self.bull_confluence_bars[-1] <= 3
        was_bear_narrow = self.bear_confluence_bars[-1] <= 3
        
        bull_entry = was_bull_narrow and (is_eb or is_bt or is_b180) and close > sma20 and sma20 > sma200 and close > open_
        bear_entry = was_bear_narrow and (is_eb or is_tt or is_bear180) and close < sma20 and sma20 < sma200 and close < open_
        
        if bull_entry:
            self.buy()
        elif bear_entry:
            self.sell()
        elif self.position.is_long and close < sma20:
            self.position.close()
        elif self.position.is_short and close > sma20:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()