"""
DS-TV Backtest Results: range-entry-point
============================================================

--- SPY ---
  ERROR: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

--- BTC ---
  ERROR: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

--- QQQ ---
  ERROR: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — range-entry-point
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    param1 = 14  # example
    param2 = 20  # example
    param3 = 100  # example
    param4 = -100  # example
    param5 = 200  # example
    param6 = 200  # example
    param7 = 'D'  # example
    param8 = 'EMA'  # example

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # SMA
        self.fast_sma = self.I(pta.sma, close, length=self.param5)
        self.slow_sma = self.I(pta.sma, close, length=self.param6)
        self.fast_ema = self.I(pta.ema, close, length=self.param5)
        self.slow_ema = self.I(pta.ema, close, length=self.param6)

        # CCI
        self.cci = self.I(pta.cci, high, low, close, length=self.param2)

        # Bands
        self.bands = self.I(pta.bbands, close, length=self.param5, std=self.param3)

    def next(self):
        # SMA crossover logic
        if crossover(self.fast_sma, self.slow_sma):
            self.buy()
        elif crossover(self.slow_sma, self.fast_sma):
            self.sell()

        # CCI logic
        if self.cci[-1] > self.param4 and self.cci[-2] < self.param4:
            self.buy()
        elif self.cci[-1] < self.param3 and self.cci[-2] > self.param3:
            self.sell()

        # Bands logic
        if self.bands[-1]['low'][-1] < self.data.Close[-1] < self.bands[-1]['mid'][-1]:
            self.buy()
        elif self.bands[-1]['high'][-1] > self.data.Close[-1] < self.bands[-1]['mid'][-1]:
            self.sell()