"""
DS-TV Backtest Results: sj-stoch-mft-3
============================================================

--- SPY ---
  Return                    -11.45%
  Buy & Hold Return         40.21%
  Max Drawdown              -22.49%
  Sharpe Ratio              -0.47
  Sortino Ratio             -0.64
  Calmar Ratio              -0.26
  Profit Factor             0.81
  Expectancy                -0.11%
  SQN                       -0.82
  # Trades                  100
  Win Rate                  40.00%
  Best Trade                5.45%
  Worst Trade               -5.85%
  Avg Trade                 -0.13%
  Exposure Time             69.00%
  Equity Final              88551.59$
  Equity Peak               102213.75$
  Avg Drawdown              -7.93%
  Max Drawdown Duration     410 days 00:00:00
  Max Trade Duration        12 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -5.94%
  Ann. Volatility           12.72%

--- BTC ---
  Return                    -24.82%
  Buy & Hold Return         35.02%
  Max Drawdown              -37.72%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.81
  Calmar Ratio              -0.35
  Profit Factor             0.88
  Expectancy                -0.20%
  SQN                       -0.84
  # Trades                  88
  Win Rate                  34.09%
  Best Trade                15.81%
  Worst Trade               -9.61%
  Avg Trade                 -0.28%
  Exposure Time             42.41%
  Equity Final              75181.50$
  Equity Peak               119798.12$
  Avg Drawdown              -12.98%
  Max Drawdown Duration     389 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -13.28%
  Ann. Volatility           20.54%

--- QQQ ---
  Return                    4.05%
  Buy & Hold Return         42.44%
  Max Drawdown              -24.69%
  Sharpe Ratio              0.11
  Sortino Ratio             0.17
  Calmar Ratio              0.08
  Profit Factor             1.07
  Expectancy                0.06%
  SQN                       0.13
  # Trades                  98
  Win Rate                  45.92%
  Best Trade                7.47%
  Worst Trade               -6.20%
  Avg Trade                 0.03%
  Exposure Time             71.00%
  Equity Final              104046.38$
  Equity Peak               115029.43$
  Avg Drawdown              -3.42%
  Max Drawdown Duration     412 days 00:00:00
  Max Trade Duration        12 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               2.02%
  Ann. Volatility           17.74%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — sj-stoch-mft-3
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    periodK = 14
    smoothK = 1
    periodD = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate raw stochastic
        stoch_result = pta.stoch(high, low, close, k=self.periodK, d=self.periodD, smooth_k=self.smoothK)
        
        if stoch_result is not None:
            self.k = self.I(lambda: stoch_result['STOCHk_14_3_1'] if 'STOCHk_14_3_1' in stoch_result.columns else stoch_result.iloc[:, 0])
            self.d = self.I(lambda: stoch_result['STOCHd_14_3_1'] if 'STOCHd_14_3_1' in stoch_result.columns else stoch_result.iloc[:, 1])
        else:
            self.k = self.I(lambda: pd.Series(50, index=close.index))
            self.d = self.I(lambda: pd.Series(50, index=close.index))

    def next(self):
        if len(self.data) < self.periodK + self.periodD + self.smoothK:
            return
        
        # Get current K and D values
        k_val = self.k[-1]
        d_val = self.d[-1]
        
        # Determine direction: 1 if K > D, -1 if K < D, 0 if equal
        if k_val > d_val:
            direction = 1
        elif k_val < d_val:
            direction = -1
        else:
            direction = 0
        
        # Buy signal: direction == 1 (K > D)
        if direction == 1:
            if not self.position:
                self.buy()
            elif self.position.is_short:
                self.position.close()
                self.buy()
        # Sell signal: direction == -1 (K < D)
        elif direction == -1:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("EURUSD=X", start="2023-01-01", end="2024-01-01", interval="1h")
    data.columns = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.0002)
    stats = bt.run()
    print(stats)