"""
DS-TV Backtest Results: sma-rsi-strategy-entryexit-at-next-open
============================================================

--- SPY ---
  Return                    19.71%
  Buy & Hold Return         17.90%
  Max Drawdown              -16.14%
  Sharpe Ratio              0.64
  Sortino Ratio             1.07
  Calmar Ratio              0.59
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              119712.54$
  Equity Peak               119977.42$
  Avg Drawdown              -1.77%
  Max Drawdown Duration     77 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               9.49%
  Ann. Volatility           14.89%

--- BTC ---
  Return                    2.25%
  Buy & Hold Return         17.39%
  Max Drawdown              -30.10%
  Sharpe Ratio              0.04
  Sortino Ratio             0.06
  Calmar Ratio              0.04
  Profit Factor             nan
  Expectancy                2.47%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                2.47%
  Worst Trade               2.47%
  Avg Trade                 2.47%
  Exposure Time             43.23%
  Equity Final              102254.51$
  Equity Peak               133223.98$
  Avg Drawdown              -6.41%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        315 days 00:00:00
  Avg Trade Duration        315 days 00:00:00
  Ann. Return               1.12%
  Ann. Volatility           25.99%

--- QQQ ---
  Return                    23.24%
  Buy & Hold Return         22.08%
  Max Drawdown              -17.94%
  Sharpe Ratio              0.61
  Sortino Ratio             1.04
  Calmar Ratio              0.62
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              123243.22$
  Equity Peak               127369.61$
  Avg Drawdown              -2.36%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               11.11%
  Ann. Volatility           18.11%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — sma-rsi-strategy-entryexit-at-next-open
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    smaLength = 200
    rsiLength = 14
    rsiBuyLevel = 35
    rsiSellLevel = 65

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.sma = self.I(pta.sma, close, length=self.smaLength)
        self.rsi = self.I(pta.rsi, close, length=self.rsiLength)

    def next(self):
        if len(self.data) < max(self.smaLength, self.rsiLength):
            return
        
        close = self.data.Close[-1]
        sma_val = self.sma[-1]
        rsi_val = self.rsi[-1]
        
        if sma_val is None or rsi_val is None:
            return
        
        long_condition = (close > sma_val) and (rsi_val < self.rsiBuyLevel)
        exit_condition = (close < sma_val) and (rsi_val > self.rsiSellLevel)
        
        if long_condition and not self.position:
            self.buy()
        
        if exit_condition and self.position:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()