"""
DS-TV Backtest Results: smc-strategy-hub-alerts
============================================================

--- SPY ---
  Return                    19.06%
  Buy & Hold Return         39.08%
  Max Drawdown              -9.07%
  Sharpe Ratio              0.83
  Sortino Ratio             1.28
  Calmar Ratio              1.01
  Profit Factor             3.47
  Expectancy                3.59%
  SQN                       0.90
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                17.91%
  Worst Trade               -3.72%
  Avg Trade                 3.31%
  Exposure Time             67.00%
  Equity Final              119060.54$
  Equity Peak               122413.03$
  Avg Drawdown              -1.74%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        198 days 00:00:00
  Avg Trade Duration        97 days 00:00:00
  Ann. Return               9.19%
  Ann. Volatility           11.09%

--- BTC ---
  Return                    4.21%
  Buy & Hold Return         14.14%
  Max Drawdown              -26.94%
  Sharpe Ratio              0.08
  Sortino Ratio             0.12
  Calmar Ratio              0.08
  Profit Factor             1.26
  Expectancy                1.32%
  SQN                       0.11
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                48.07%
  Worst Trade               -16.03%
  Avg Trade                 0.01%
  Exposure Time             50.48%
  Equity Final              104211.54$
  Equity Peak               125696.65$
  Avg Drawdown              -7.29%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        159 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               2.08%
  Ann. Volatility           26.07%

--- QQQ ---
  Return                    23.64%
  Buy & Hold Return         42.00%
  Max Drawdown              -10.28%
  Sharpe Ratio              0.77
  Sortino Ratio             1.19
  Calmar Ratio              1.10
  Profit Factor             6.41
  Expectancy                5.92%
  SQN                       0.93
  # Trades                  4
  Win Rate                  75.00%
  Best Trade                22.77%
  Worst Trade               -4.38%
  Avg Trade                 5.46%
  Exposure Time             67.00%
  Equity Final              123644.04$
  Equity Peak               137808.97$
  Avg Drawdown              -2.25%
  Max Drawdown Duration     159 days 00:00:00
  Max Trade Duration        201 days 00:00:00
  Avg Trade Duration        122 days 00:00:00
  Ann. Return               11.29%
  Ann. Volatility           14.64%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — smc-strategy-hub-alerts
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookback = 20
    atr_mult = 2.0
    use_timer = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate highest high and lowest low using rolling windows
        self.high_h = self.I(lambda: high.rolling(self.lookback).max())
        self.low_l = self.I(lambda: low.rolling(self.lookback).min())
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=14)

    def next(self):
        # Time filter (only trade during NY session if enabled)
        if self.use_timer:
            bar_time = self.data.index[len(self.data) - 1]
            hour = bar_time.hour
            if not (hour >= 7 and hour <= 12):
                return
        
        # Ensure we have enough data
        if len(self.data) < self.lookback + 2:
            return
        
        # Get current and previous values
        current_close = self.data.Close[-1]
        prev_close = self.data.Close[-2]
        prev_high_h = self.high_h[-2] if len(self.high_h) > 1 else None
        prev_low_l = self.low_l[-2] if len(self.low_l) > 1 else None
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        if self.atr[-1] is None or np.isnan(self.atr[-1]):
            return
        
        atr_val = self.atr[-1]
        
        # Check for bullish market structure shift (close crosses above previous highest high)
        bull_mss = False
        if prev_high_h is not None and not np.isnan(prev_high_h):
            if prev_close <= prev_high_h and current_close > prev_high_h:
                bull_mss = True
        
        # Check for bearish market structure shift (close crosses below previous lowest low)
        bear_mss = False
        if prev_low_l is not None and not np.isnan(prev_low_l):
            if prev_close >= prev_low_l and current_close < prev_low_l:
                bear_mss = True
        
        # Trading logic
        if bull_mss and not self.position:
            self.buy()
        elif bear_mss and self.position:
            self.position.close()
        
        # Exit management based on risk/reward
        if self.position:
            if self.position.is_long:
                sl_price = current_low - (atr_val * 1.5)
                tp_price = current_close + (atr_val * self.atr_mult)
                
                if current_close <= sl_price or current_close >= tp_price:
                    self.position.close()
            else:
                sl_price = current_high + (atr_val * 1.5)
                tp_price = current_close - (atr_val * self.atr_mult)
                
                if current_close >= sl_price or current_close <= tp_price:
                    self.position.close()


if __name__ == "__main__":
    import yfinance as yf
    
    # Download sample data
    data = yf.download("EURUSD=X", start="2023-01-01", end="2024-01-01", interval="1h")
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.0002)
    stats = bt.run()
    print(stats)
    bt.plot()