"""
DS-TV Backtest Results: supply-and-demand-zone-indicator-5m
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — supply-and-demand-zone-indicator-5m
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    lookback = 20
    impulseMultiplier = 1.5

    def init(self):
        close = pd.Series(self.data.Close)
        body = np.abs(self.data.Close - self.data.Open)
        avgBody = pta.sma(body, self.lookback)
        self.bullImpulse = self.I(lambda: close > self.data.Open and body > avgBody * self.impulseMultiplier)
        self.bearImpulse = self.I(lambda: self.data.Open > close and body > avgBody * self.impulseMultiplier)
        self.baseCandle = self.I(lambda: body < avgBody)
        self.demandZone = self.I(lambda: self.baseCandle[1] and self.bullImpulse)
        self.supplyZone = self.I(lambda: self.baseCandle[1] and self.bearImpulse)
        self.demandLow = self.I(lambda: self.demandZone and self.data.Low[1])
        self.demandHigh = self.I(lambda: self.demandZone and self.data.High[1])
        self.supplyLow = self.I(lambda: self.supplyZone and self.data.Low[1])
        self.supplyHigh = self.I(lambda: self.supplyZone and self.data.High[1])

    def next(self):
        buySignal = not pd.isna(self.demandLow) and self.data.Low <= self.demandHigh and self.data.Low >= self.demandLow
        sellSignal = not pd.isna(self.supplyHigh) and self.data.High >= self.supplyLow and self.data.High <= self.supplyHigh
        if buySignal:
            self.buy()
        elif sellSignal:
            self.sell()