"""
DS-TV Backtest Results: temacd
============================================================

--- SPY ---
  ERROR: 'TvStrategy' object has no attribute 'position_size'

--- BTC ---
  ERROR: 'TvStrategy' object has no attribute 'position_size'

--- QQQ ---
  ERROR: 'TvStrategy' object has no attribute 'position_size'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — temacd
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    # Default parameters from Pine Script
    param1 = 9  # EMA 1 Length
    param2 = 21  # EMA 2 Length
    param3 = 50  # EMA 3 Length
    param4 = 200  # display ema
    param5 = 12  # MACD Fast Length
    param6 = 26  # MACD Slow Length
    param7 = 9  # MACD Signal Length

    def init(self):
        close = pd.Series(self.data.Close)
        self.ema1 = self.I(pta.ema, close, length=self.param1)
        self.ema2 = self.I(pta.ema, close, length=self.param2)
        self.ema3 = self.I(pta.ema, close, length=self.param3)
        self.ema200 = self.I(pta.ema, close, length=self.param4)
        self.macd_line, self.signal_line, self.hist_line = self.I(pta.macd, close, fast=self.param5, slow=self.param6, signal=self.param7)

    def next(self):
        cross_1_above_2 = crossover(self.ema1, self.ema2)
        cross_1_above_3 = crossover(self.ema1, self.ema3)
        cross_2_above_3 = crossover(self.ema2, self.ema3)
        cross_1_below_2 = crossover(self.ema2, self.ema1)
        cross_1_below_3 = crossover(self.ema3, self.ema1)
        cross_2_below_3 = crossover(self.ema3, self.ema2)
        macd_long = crossover(self.macd_line, self.signal_line)
        macd_short = crossover(self.signal_line, self.macd_line)

        long_entry = cross_1_above_2 or cross_1_above_3 or cross_2_above_3 or macd_long
        long_exit = cross_1_below_2 or cross_1_below_3 or cross_2_below_3 or macd_short
        short_entry = cross_1_below_2 or cross_1_below_3 or cross_2_below_3 or macd_short
        short_exit = cross_1_above_2 or cross_1_above_3 or cross_2_above_3 or macd_long

        if self.position_size > 0 and long_exit:
            self.sell()
        elif self.position_size < 0 and short_exit:
            self.sell()

        if self.position_size == 0 and (self.param7 == "Long Only" or self.param7 == "Long & Short") and long_entry:
            self.buy()
        elif self.position_size == 0 and (self.param7 == "Short Only" or self.param7 == "Long & Short") and short_entry:
            self.short()