"""
DS-TV Backtest Results: tl5-1-min-scalping-tool-mtf-sma8-mtf-alma30
============================================================

--- SPY ---
  Return                    -2.61%
  Buy & Hold Return         34.77%
  Max Drawdown              -28.65%
  Sharpe Ratio              -0.09
  Sortino Ratio             -0.11
  Calmar Ratio              -0.05
  Profit Factor             0.96
  Expectancy                -0.04%
  SQN                       -0.18
  # Trades                  38
  Win Rate                  34.21%
  Best Trade                10.15%
  Worst Trade               -9.15%
  Avg Trade                 -0.09%
  Exposure Time             91.63%
  Equity Final              97387.89$
  Equity Peak               109999.67$
  Avg Drawdown              -6.09%
  Max Drawdown Duration     583 days 00:00:00
  Max Trade Duration        64 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               -1.32%
  Ann. Volatility           15.22%

--- BTC ---
  Return                    18.10%
  Buy & Hold Return         -0.73%
  Max Drawdown              -33.16%
  Sharpe Ratio              0.24
  Sortino Ratio             0.40
  Calmar Ratio              0.26
  Profit Factor             1.02
  Expectancy                0.05%
  SQN                       -0.09
  # Trades                  34
  Win Rate                  26.47%
  Best Trade                52.26%
  Worst Trade               -7.73%
  Avg Trade                 -0.39%
  Exposure Time             59.43%
  Equity Final              118095.27$
  Equity Peak               122810.32$
  Avg Drawdown              -8.72%
  Max Drawdown Duration     259 days 00:00:00
  Max Trade Duration        50 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               8.65%
  Ann. Volatility           36.15%

--- QQQ ---
  Return                    3.89%
  Buy & Hold Return         38.14%
  Max Drawdown              -34.07%
  Sharpe Ratio              0.10
  Sortino Ratio             0.13
  Calmar Ratio              0.06
  Profit Factor             1.22
  Expectancy                0.36%
  SQN                       0.14
  # Trades                  28
  Win Rate                  35.71%
  Best Trade                29.77%
  Worst Trade               -11.19%
  Avg Trade                 0.16%
  Exposure Time             92.03%
  Equity Final              103891.80$
  Equity Peak               123100.57$
  Avg Drawdown              -5.56%
  Max Drawdown Duration     470 days 00:00:00
  Max Trade Duration        126 days 00:00:00
  Avg Trade Duration        24 days 00:00:00
  Ann. Return               1.94%
  Ann. Volatility           20.18%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — tl5-1-min-scalping-tool-mtf-sma8-mtf-alma30
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    param1 = 8
    param2 = 30

    def init(self):
        close = pd.Series(self.data.Close)
        self.sma8 = self.I(pta.sma, close, length=self.param1)
        self.alma30 = self.I(pta.alma, close, length=self.param2, multiplier=0.85, smooth=8)

    def next(self):
        if crossover(self.sma8, self.alma30):
            self.buy()
        elif crossover(self.alma30, self.sma8):
            self.sell()