"""
DS-TV Backtest Results: volatility-adjusted-cloud-lyro-rs
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.20%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         28.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.78%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volatility-adjusted-cloud-lyro-rs
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param1 = 25  # VIDYA Length
    param2 = 35  # SD History Length
    param3 = 1.5  # + Multiplier
    param4 = 0.7  # - Multiplier
    param5 = 80  # Cloud Transparency

    def init(self):
        close = pd.Series(self.data.Close)
        # Calculate VIDYA midline
        vidya_midline = self.I(lambda: pta.vidya(close, self.param1, self.param2))
        # Calculate VIDYA deviation
        vidya_deviation = self.I(lambda: pta.vidya(close - vidya_midline, self.param1, self.param2))
        # Calculate VAD Cloud bands
        self.upper_band = vidya_midline + (vidya_deviation * self.param3)
        self.lower_band = vidya_midline - (vidya_deviation * self.param4)

    def next(self):
        # Entry logic
        if crossover(self.data.Close, self.upper_band):
            self.buy()
        # Exit logic
        elif crossover(self.lower_band, self.data.Close):
            self.sell()