"""
DS-TV Backtest Results: welles-wilders-mas-mtf
============================================================

--- SPY ---
  Return                    -25.65%
  Buy & Hold Return         41.94%
  Max Drawdown              -36.37%
  Sharpe Ratio              -1.02
  Sortino Ratio             -1.17
  Calmar Ratio              -0.38
  Profit Factor             0.66
  Expectancy                -0.34%
  SQN                       -1.01
  # Trades                  73
  Win Rate                  50.68%
  Best Trade                7.63%
  Worst Trade               -12.27%
  Avg Trade                 -0.38%
  Exposure Time             70.80%
  Equity Final              74349.17$
  Equity Peak               116664.26$
  Avg Drawdown              -3.53%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        174 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -13.88%
  Ann. Volatility           13.55%

--- BTC ---
  Return                    -47.28%
  Buy & Hold Return         46.22%
  Max Drawdown              -58.24%
  Sharpe Ratio              -1.06
  Sortino Ratio             -1.07
  Calmar Ratio              -0.47
  Profit Factor             0.44
  Expectancy                -1.09%
  SQN                       -1.29
  # Trades                  72
  Win Rate                  45.83%
  Best Trade                7.08%
  Worst Trade               -53.97%
  Avg Trade                 -1.45%
  Exposure Time             28.18%
  Equity Final              52715.88$
  Equity Peak               103628.56$
  Avg Drawdown              -17.17%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        115 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -27.36%
  Ann. Volatility           25.90%

--- QQQ ---
  Return                    -27.58%
  Buy & Hold Return         42.67%
  Max Drawdown              -43.24%
  Sharpe Ratio              -0.89
  Sortino Ratio             -1.03
  Calmar Ratio              -0.35
  Profit Factor             0.68
  Expectancy                -0.37%
  SQN                       -0.93
  # Trades                  73
  Win Rate                  47.95%
  Best Trade                8.67%
  Worst Trade               -16.16%
  Avg Trade                 -0.43%
  Exposure Time             70.60%
  Equity Final              72419.04$
  Equity Peak               121878.60$
  Avg Drawdown              -5.29%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        176 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -15.01%
  Ann. Volatility           16.88%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — welles-wilders-mas-mtf
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    i_short_length = 34
    i_medium_length = 72
    i_medium_length_extension = 89
    i_long_length = 144

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.wilders_ma_short = self.I(pta.rma, close, length=self.i_short_length)
        self.wilders_ma_medium = self.I(pta.rma, close, length=self.i_medium_length)
        self.wilders_ma_medium_extension = self.I(pta.rma, close, length=self.i_medium_length_extension)
        self.wilders_ma_long = self.I(pta.rma, close, length=self.i_long_length)

    def next(self):
        if len(self.data) < self.i_long_length:
            return
        
        close = self.data.Close[-1]
        short = self.wilders_ma_short[-1]
        medium = self.wilders_ma_medium[-1]
        medium_ext = self.wilders_ma_medium_extension[-1]
        long_ma = self.wilders_ma_long[-1]
        
        if (short > medium and short > medium_ext and 
            close > short and close > medium and 
            short > long_ma):
            if not self.position:
                self.buy()
        
        elif (short < medium or short < medium_ext or 
              close < short or close < long_ma):
            if self.position:
                self.sell()