"""
DS-TV Backtest Results: xauusd-1-minute-scalping-strategy-advanced-strategy-for-exits
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — xauusd-1-minute-scalping-strategy-advanced-strategy-for-exits
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Parameters from Pine Script
    length = 14
    overbought = 70
    oversold = 30
    takeProfit = 10
    stopLoss = 5
    use_trend_filter = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate RSI
        self.rsi = self.I(lambda: pta.rsi(close, length=self.length) or pd.Series(50, index=close.index))
        
        # Calculate 200 EMA for trend filter
        self.ema200 = self.I(lambda: pta.ema(close, length=200) or pd.Series(close, index=close.index))
        
        # Track entry prices and TP/SL levels
        self.long_entry_price = None
        self.short_entry_price = None
        self.long_tp_price = None
        self.long_sl_price = None
        self.short_tp_price = None
        self.short_sl_price = None
        self.position_just_entered = False

    def next(self):
        # Get current values
        current_rsi = self.rsi[-1]
        current_close = self.data.Close[-1]
        current_ema200 = self.ema200[-1]
        
        # Check if we just exited a position
        if not self.position and self.position_just_entered:
            self.position_just_entered = False
            self.long_entry_price = None
            self.short_entry_price = None
            self.long_tp_price = None
            self.long_sl_price = None
            self.short_tp_price = None
            self.short_sl_price = None
        
        # Entry Conditions
        long_condition = (current_rsi < self.oversold and 
                         (not self.use_trend_filter or current_close > current_ema200))
        short_condition = (current_rsi > self.overbought and 
                          (not self.use_trend_filter or current_close < current_ema200))
        
        # LONG Entry
        if long_condition and not self.position:
            self.long_entry_price = current_close
            self.long_tp_price = current_close + self.takeProfit * 0.01
            self.long_sl_price = current_close - self.stopLoss * 0.01
            self.buy()
            self.position_just_entered = True
        
        # SHORT Entry
        if short_condition and not self.position:
            self.short_entry_price = current_close
            self.short_tp_price = current_close - self.takeProfit * 0.01
            self.short_sl_price = current_close + self.stopLoss * 0.01
            self.sell()
            self.position_just_entered = True
        
        # LONG TP/SL exits
        if self.position and self.position.is_long:
            if current_close >= self.long_tp_price or current_close <= self.long_sl_price:
                self.position.close()
        
        # SHORT TP/SL exits
        if self.position and not self.position.is_long:
            if current_close <= self.short_tp_price or current_close >= self.short_sl_price:
                self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=1000000, comm=.002)
    stats = bt.run()
    print(stats)
    bt.plot()