"""
OpenClaw Backtest Results: arbitrage-matrix-luxalgo
============================================================

--- SPY ---
  Return                    7.64%
  Buy & Hold Return         39.08%
  Max Drawdown              -19.22%
  Sharpe Ratio              0.34
  Sortino Ratio             0.44
  Calmar Ratio              0.20
  Profit Factor             1.48
  Expectancy                1.06%
  SQN                       0.26
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                22.90%
  Worst Trade               -12.43%
  Avg Trade                 0.70%
  Exposure Time             65.40%
  Equity Final              107636.00$
  Equity Peak               109251.03$
  Avg Drawdown              -2.95%
  Max Drawdown Duration     528 days 00:00:00
  Max Trade Duration        176 days 00:00:00
  Avg Trade Duration        47 days 00:00:00
  Ann. Return               3.78%
  Ann. Volatility           11.22%

--- BTC ---
  Return                    3.13%
  Buy & Hold Return         14.14%
  Max Drawdown              -27.68%
  Sharpe Ratio              0.07
  Sortino Ratio             0.11
  Calmar Ratio              0.06
  Profit Factor             1.30
  Expectancy                0.97%
  SQN                       0.08
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                30.96%
  Worst Trade               -11.82%
  Avg Trade                 0.46%
  Exposure Time             44.19%
  Equity Final              103125.44$
  Equity Peak               141615.01$
  Avg Drawdown              -4.88%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               1.55%
  Ann. Volatility           21.05%

--- QQQ ---
  Return                    17.01%
  Buy & Hold Return         42.00%
  Max Drawdown              -10.15%
  Sharpe Ratio              0.61
  Sortino Ratio             0.91
  Calmar Ratio              0.81
  Profit Factor             2.05
  Expectancy                1.53%
  SQN                       0.69
  # Trades                  12
  Win Rate                  50.00%
  Best Trade                18.58%
  Worst Trade               -6.01%
  Avg Trade                 1.32%
  Exposure Time             62.60%
  Equity Final              117010.57$
  Equity Peak               126762.73$
  Avg Drawdown              -1.84%
  Max Drawdown Duration     286 days 00:00:00
  Max Trade Duration        127 days 00:00:00
  Avg Trade Duration        37 days 00:00:00
  Ann. Return               8.24%
  Ann. Volatility           13.47%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — arbitrage-matrix-luxalgo
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    average_length = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.sma_fast = self.I(pta.sma, close, length=10)
        self.sma_slow = self.I(pta.sma, close, length=20)
        self.rsi = self.I(pta.rsi, close, length=14)
        self.atr = self.I(pta.atr, high, low, close, length=14)

    def next(self):
        if len(self.data) < 2:
            return
        
        if not self.position:
            if crossover(self.sma_fast, self.sma_slow) and self.rsi[-1] < 70:
                self.buy()
        else:
            if crossover(self.sma_slow, self.sma_fast) or self.rsi[-1] > 80:
                self.position.close()


if __name__ == '__main__':
    df = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()