"""
OpenClaw Backtest Results: arbitrage-detector-luxalgo
============================================================

--- SPY ---
  Return                    -65.75%
  Buy & Hold Return         41.94%
  Max Drawdown              -66.21%
  Sharpe Ratio              -4.43
  Sortino Ratio             -3.27
  Calmar Ratio              -0.63
  Profit Factor             0.47
  Expectancy                -0.30%
  SQN                       -4.70
  # Trades                  353
  Win Rate                  33.71%
  Best Trade                10.07%
  Worst Trade               -6.89%
  Avg Trade                 -0.30%
  Exposure Time             98.20%
  Equity Final              34252.76$
  Equity Peak               101378.17$
  Avg Drawdown              -22.39%
  Max Drawdown Duration     706 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -41.72%
  Ann. Volatility           9.41%

--- BTC ---
  Return                    -44.18%
  Buy & Hold Return         46.22%
  Max Drawdown              -44.18%
  Sharpe Ratio              -1.60
  Sortino Ratio             -1.53
  Calmar Ratio              -0.57
  Profit Factor             0.59
  Expectancy                -0.71%
  SQN                       -1.88
  # Trades                  110
  Win Rate                  44.55%
  Best Trade                8.14%
  Worst Trade               -14.85%
  Avg Trade                 -0.78%
  Exposure Time             20.11%
  Equity Final              55821.66$
  Equity Peak               100000.00$
  Avg Drawdown              -44.18%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        3 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -25.26%
  Ann. Volatility           15.79%

--- QQQ ---
  Return                    -66.89%
  Buy & Hold Return         42.67%
  Max Drawdown              -67.86%
  Sharpe Ratio              -3.58
  Sortino Ratio             -2.70
  Calmar Ratio              -0.63
  Profit Factor             0.57
  Expectancy                -0.31%
  SQN                       -3.76
  # Trades                  347
  Win Rate                  35.73%
  Best Trade                10.28%
  Worst Trade               -7.43%
  Avg Trade                 -0.32%
  Exposure Time             98.00%
  Equity Final              33108.20$
  Equity Peak               100817.58$
  Avg Drawdown              -23.27%
  Max Drawdown Duration     706 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -42.71%
  Ann. Volatility           11.92%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — arbitrage-detector-luxalgo
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    average_length = 20
    spread_length = 1000
    unusual_percentile = 98
    high_percentile = 75
    typical_percentile = 25
    smoothing_length = 9
    auto_smoothing = True

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate spreads (using high-low as a proxy for arbitrage spread)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Spread calculation: difference between high and low
        spreads = high - low
        
        # Calculate percentiles
        self.spread_series = self.I(lambda x: x, spreads.values)
        
        # EMA smoothing for the spread
        if self.auto_smoothing:
            # Adaptive moving average based on percent rank
            self.ama = self.I(self._calculate_adaptive_ma, spreads.values)
        else:
            self.ema_smooth = self.I(pta.ema, close, length=self.smoothing_length)
    
    def _calculate_adaptive_ma(self, spreads):
        """Calculate adaptive moving average based on percent rank"""
        if len(spreads) < 2:
            return spreads[-1] if len(spreads) > 0 else 0
        
        ama_val = 0
        result = []
        for i in range(len(spreads)):
            if i == 0:
                ama_val = spreads[i]
            else:
                # Simple adaptive calculation
                pct_rank = self._percentile_rank(spreads[:i+1], spreads[i])
                ama_val += (0.01 * pct_rank) * (spreads[i] - ama_val)
            result.append(ama_val)
        return np.array(result)
    
    def _percentile_rank(self, data, value):
        """Calculate percentile rank of a value in data"""
        if len(data) == 0:
            return 0
        sorted_data = np.sort(data)
        rank = np.searchsorted(sorted_data, value) / len(data) * 100
        return rank
    
    def _get_spread_percentile_rank(self, idx):
        """Get current spread percentile rank"""
        if idx < 1:
            return 0
        spreads = self.spread_series[:idx+1]
        current_spread = spreads[-1]
        rank = np.sum(spreads <= current_spread) / len(spreads) * 100
        return rank

    def next(self):
        spread_rank = self._get_spread_percentile_rank(len(self.data) - 1)
        current_spread = self.spread_series[-1]
        
        # Get smoothed average
        if self.auto_smoothing:
            avg_spread = self.ama[-1]
        else:
            avg_spread = self.ema_smooth[-1]
        
        # Trading logic based on spread levels
        # Buy when spread is low (unusual activity, potential arbitrage opportunity)
        if spread_rank < self.typical_percentile and current_spread < avg_spread:
            if not self.position:
                self.buy()
        
        # Sell when spread is high (reduced opportunity)
        elif spread_rank > self.high_percentile and current_spread > avg_spread:
            if self.position:
                self.sell()
        
        # Close position if spread normalizes
        elif self.typical_percentile <= spread_rank <= self.high_percentile:
            if self.position:
                self.sell()


if __name__ == '__main__':
    bt = Backtest(pd.read_csv('data.csv', index_col=0, parse_dates=True),
                  TvStrategy,
                  cash=10000,
                  commission=.002)
    results = bt.run()
    print(results)
    bt.plot()