"""
OpenClaw Backtest Results: breakouts-pullbacks-trendoscope
============================================================

--- SPY ---
  Return                    -46.95%
  Buy & Hold Return         41.94%
  Max Drawdown              -51.72%
  Sharpe Ratio              -2.56
  Sortino Ratio             -2.48
  Calmar Ratio              -0.53
  Profit Factor             0.45
  Expectancy                -0.29%
  SQN                       -3.49
  # Trades                  211
  Win Rate                  30.33%
  Best Trade                4.96%
  Worst Trade               -6.03%
  Avg Trade                 -0.29%
  Exposure Time             80.60%
  Equity Final              53045.35$
  Equity Peak               109623.34$
  Avg Drawdown              -8.52%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        73 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -27.35%
  Ann. Volatility           10.70%

--- BTC ---
  Return                    -8.80%
  Buy & Hold Return         46.22%
  Max Drawdown              -12.94%
  Sharpe Ratio              -0.60
  Sortino Ratio             -0.65
  Calmar Ratio              -0.35
  Profit Factor             0.53
  Expectancy                -1.01%
  SQN                       -0.75
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                6.19%
  Worst Trade               -10.44%
  Avg Trade                 -1.11%
  Exposure Time             1.92%
  Equity Final              91201.93$
  Equity Peak               104761.46$
  Avg Drawdown              -12.94%
  Max Drawdown Duration     457 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -4.49%
  Ann. Volatility           7.43%

--- QQQ ---
  Return                    -48.58%
  Buy & Hold Return         42.67%
  Max Drawdown              -53.95%
  Sharpe Ratio              -2.23
  Sortino Ratio             -2.19
  Calmar Ratio              -0.53
  Profit Factor             0.50
  Expectancy                -0.32%
  SQN                       -3.06
  # Trades                  210
  Win Rate                  32.38%
  Best Trade                5.32%
  Worst Trade               -6.97%
  Avg Trade                 -0.33%
  Exposure Time             85.20%
  Equity Final              51424.82$
  Equity Peak               108472.73$
  Avg Drawdown              -9.47%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        165 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -28.48%
  Ann. Volatility           12.80%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — breakouts-pullbacks-trendoscope
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy


class TvStrategy(Strategy):
    minimum_gap = 30
    
    def init(self):
        self.ath_price = self.data.High[0]
        self.ath_index = 0
        self.local_low_price = self.data.Low[0]
        self.local_low_index = 0
        self.last_ath_break_index = -1
        self.breakouts = []
        self.last_breakout = None
        self.breakout_detected = False
        
    def next(self):
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_index = len(self.data) - 1
        
        gap = current_index - self.ath_index if current_high > self.ath_price else 0
        
        if current_high > self.ath_price:
            self.ath_price = current_high
            self.ath_index = current_index
        
        if current_low <= self.local_low_price:
            self.local_low_price = current_low
            self.local_low_index = current_index
        
        if gap >= self.minimum_gap:
            self.last_ath_break_index = self.ath_index
            self.last_breakout = {
                'ath_price': self.ath_price,
                'ath_index': self.ath_index,
                'low_price': self.local_low_price,
                'low_index': self.local_low_index,
                'breakout_index': current_index
            }
            self.breakouts.append(self.last_breakout)
            self.breakout_detected = True
        
        if gap > 0:
            self.local_low_price = current_low
            self.local_low_index = current_index
        
        if self.last_breakout is not None:
            pullback_price = self.last_breakout['ath_price'] - self.local_low_price
            pullback_percent = (pullback_price * 100) / self.last_breakout['ath_price']
            pullback_bars = self.local_low_index - self.last_breakout['ath_index']
            
            runup_percent = 0.0
            runup_bars = 0
            
            if current_high >= self.last_breakout['ath_price']:
                runup_price = current_high - self.last_breakout['ath_price']
                runup_percent = (runup_price * 100) / self.last_breakout['ath_price']
                runup_bars = current_index - self.last_breakout['ath_index']
            
            total_runup_price = current_high - self.local_low_price
            total_runup_percent = (total_runup_price * 100) / self.local_low_price if self.local_low_price > 0 else 0
            total_runup_bars = current_index - self.local_low_index
            
            if self.breakout_detected and pullback_percent > 0:
                if not self.position:
                    self.buy()
                    self.breakout_detected = False
            
            if self.position:
                if runup_percent > 5:
                    self.sell()