"""
OpenClaw Backtest Results: hyperfork-matrix
============================================================

--- SPY ---
  Return                    -56.82%
  Buy & Hold Return         41.94%
  Max Drawdown              -57.01%
  Sharpe Ratio              -3.11
  Sortino Ratio             -2.63
  Calmar Ratio              -0.61
  Profit Factor             0.49
  Expectancy                -0.38%
  SQN                       -3.13
  # Trades                  210
  Win Rate                  37.14%
  Best Trade                6.39%
  Worst Trade               -7.47%
  Avg Trade                 -0.39%
  Exposure Time             99.20%
  Equity Final              43182.58$
  Equity Peak               100444.26$
  Avg Drawdown              -57.01%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        15 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -34.51%
  Ann. Volatility           11.10%

--- BTC ---
  Return                    -33.18%
  Buy & Hold Return         46.22%
  Max Drawdown              -35.27%
  Sharpe Ratio              -0.88
  Sortino Ratio             -0.97
  Calmar Ratio              -0.52
  Profit Factor             0.69
  Expectancy                -0.52%
  SQN                       -1.19
  # Trades                  122
  Win Rate                  55.74%
  Best Trade                8.14%
  Worst Trade               -20.78%
  Avg Trade                 -0.61%
  Exposure Time             34.47%
  Equity Final              66816.08$
  Equity Peak               103227.08$
  Avg Drawdown              -35.27%
  Max Drawdown Duration     729 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -18.24%
  Ann. Volatility           20.65%

--- QQQ ---
  Return                    -58.97%
  Buy & Hold Return         42.67%
  Max Drawdown              -59.79%
  Sharpe Ratio              -2.61
  Sortino Ratio             -2.22
  Calmar Ratio              -0.61
  Profit Factor             0.57
  Expectancy                -0.39%
  SQN                       -2.77
  # Trades                  210
  Win Rate                  39.05%
  Best Trade                6.54%
  Worst Trade               -9.28%
  Avg Trade                 -0.41%
  Exposure Time             99.20%
  Equity Final              41025.85$
  Equity Peak               100035.81$
  Avg Drawdown              -59.79%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -36.18%
  Ann. Volatility           13.84%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hyperfork-matrix
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        close = self.data.Close[-1]
        prev_close = self.data.Close[-2]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if not self.position:
            if close > prev_close and high > low:
                self.buy()
        else:
            if close < prev_close:
                self.sell()


def run_backtest():
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()


if __name__ == "__main__":
    run_backtest()