"""
OpenClaw Backtest Results: match-finder-theultimator5
============================================================

--- SPY ---
  Return                    -52.32%
  Buy & Hold Return         41.94%
  Max Drawdown              -53.81%
  Sharpe Ratio              -3.20
  Sortino Ratio             -2.93
  Calmar Ratio              -0.58
  Profit Factor             0.30
  Expectancy                -0.33%
  SQN                       -5.51
  # Trades                  227
  Win Rate                  26.43%
  Best Trade                7.33%
  Worst Trade               -2.91%
  Avg Trade                 -0.33%
  Exposure Time             90.40%
  Equity Final              47679.06$
  Equity Peak               103221.02$
  Avg Drawdown              -14.54%
  Max Drawdown Duration     640 days 00:00:00
  Max Trade Duration        73 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -31.15%
  Ann. Volatility           9.74%

--- BTC ---
  Return                    -25.59%
  Buy & Hold Return         46.22%
  Max Drawdown              -43.77%
  Sharpe Ratio              -0.62
  Sortino Ratio             -0.71
  Calmar Ratio              -0.31
  Profit Factor             0.73
  Expectancy                -0.36%
  SQN                       -0.79
  # Trades                  65
  Win Rate                  38.46%
  Best Trade                11.25%
  Worst Trade               -10.44%
  Avg Trade                 -0.42%
  Exposure Time             36.66%
  Equity Final              74408.34$
  Equity Peak               119606.61$
  Avg Drawdown              -9.49%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        53 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -13.72%
  Ann. Volatility           22.27%

--- QQQ ---
  Return                    -53.18%
  Buy & Hold Return         42.67%
  Max Drawdown              -57.24%
  Sharpe Ratio              -2.59
  Sortino Ratio             -2.42
  Calmar Ratio              -0.56
  Profit Factor             0.35
  Expectancy                -0.38%
  SQN                       -4.82
  # Trades                  202
  Win Rate                  30.69%
  Best Trade                9.66%
  Worst Trade               -3.63%
  Avg Trade                 -0.39%
  Exposure Time             91.40%
  Equity Final              46821.75$
  Equity Peak               106708.59$
  Avg Drawdown              -14.66%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        73 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -31.78%
  Ann. Volatility           12.29%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — match-finder-theultimator5
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    correlation_window = 30
    
    def init(self):
        pass
    
    def next(self):
        if len(self.data) < self.correlation_window:
            return
        
        close_series = pd.Series(self.data.Close[-self.correlation_window:]).reset_index(drop=True)
        
        current_mean = close_series.mean()
        current_std = close_series.std()
        
        if current_std > 0:
            momentum = (self.data.Close[-1] - current_mean) / current_std
            
            if momentum < -1.0 and not self.position:
                self.buy()
            elif momentum > 1.0 and self.position:
                self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("SPY", start="2020-01-01", end="2023-12-31", progress=False)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)