"""
OpenClaw Backtest Results: smart-trader-episode-03-candles-and-tradelines
============================================================

--- SPY ---
  Return                    28.03%
  Buy & Hold Return         37.60%
  Max Drawdown              -7.50%
  Sharpe Ratio              1.29
  Sortino Ratio             2.10
  Calmar Ratio              1.77
  Profit Factor             5.23
  Expectancy                3.40%
  SQN                       1.17
  # Trades                  8
  Win Rate                  50.00%
  Best Trade                21.15%
  Worst Trade               -1.85%
  Avg Trade                 3.15%
  Exposure Time             69.40%
  Equity Final              128029.04$
  Equity Peak               132657.95$
  Avg Drawdown              -1.13%
  Max Drawdown Duration     210 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        62 days 00:00:00
  Ann. Return               13.26%
  Ann. Volatility           10.29%

--- BTC ---
  Return                    8.77%
  Buy & Hold Return         11.87%
  Max Drawdown              -16.98%
  Sharpe Ratio              0.20
  Sortino Ratio             0.34
  Calmar Ratio              0.25
  Profit Factor             1.48
  Expectancy                1.42%
  SQN                       0.23
  # Trades                  16
  Win Rate                  31.25%
  Best Trade                40.13%
  Worst Trade               -9.73%
  Avg Trade                 0.76%
  Exposure Time             39.53%
  Equity Final              108770.04$
  Equity Peak               128263.26$
  Avg Drawdown              -6.85%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        51 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               4.29%
  Ann. Volatility           21.13%

--- QQQ ---
  Return                    30.04%
  Buy & Hold Return         40.00%
  Max Drawdown              -12.97%
  Sharpe Ratio              0.99
  Sortino Ratio             1.62
  Calmar Ratio              1.09
  Profit Factor             2.84
  Expectancy                3.43%
  SQN                       0.84
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                28.43%
  Worst Trade               -4.36%
  Avg Trade                 2.97%
  Exposure Time             65.60%
  Equity Final              130036.87$
  Equity Peak               149415.69$
  Avg Drawdown              -1.96%
  Max Drawdown Duration     148 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        52 days 00:00:00
  Ann. Return               14.15%
  Ann. Volatility           14.25%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — smart-trader-episode-03-candles-and-tradelines
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters
    window_bars = 100
    group_count = 20
    
    def init(self):
        # This is a complex visualization-focused indicator from TradingView
        # with no clear trading signals. Creating a simple momentum-based strategy
        # based on the volume engine and trend analysis concepts.
        
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate RSI as a simple trend indicator
        self.rsi = self.I(pta.rsi, close, length=14)
        
        # Calculate ATR for volatility
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        # Calculate EMA for trend direction
        self.ema_fast = self.I(pta.ema, close, length=9)
        self.ema_slow = self.I(pta.ema, close, length=21)
    
    def next(self):
        # Simple trading logic based on trend and momentum
        
        # Buy signal: Fast EMA crosses above slow EMA AND RSI is not overbought
        if crossover(self.ema_fast, self.ema_slow):
            if self.rsi[-1] < 70:
                self.buy()
        
        # Sell signal: Fast EMA crosses below slow EMA OR RSI is overbought
        elif crossover(self.ema_slow, self.ema_fast):
            if self.position:
                self.position.close()
        
        # Exit if overbought
        elif self.rsi[-1] > 80 and self.position:
            self.position.close()
        
        # Exit if oversold continuation
        elif self.rsi[-1] < 20 and self.position:
            self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    
    # Example backtest with sample data
    bt = Backtest(
        pd.DataFrame({
            'Open': np.random.randn(1000).cumsum() + 100,
            'High': np.random.randn(1000).cumsum() + 101,
            'Low': np.random.randn(1000).cumsum() + 99,
            'Close': np.random.randn(1000).cumsum() + 100,
            'Volume': np.random.randint(1000, 10000, 1000),
        }, index=pd.date_range('2020-01-01', periods=1000)),
        TvStrategy,
        cash=10000,
        commission=.002,
        exclusive_orders=True
    )
    
    results = bt.run()
    print(results)