"""
OpenClaw Backtest Results: smooth-theil-sen
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — smooth-theil-sen
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 25
    offset = 0
    multiplier = 2.0

    def init(self):
        self.theil_sen_values = []
        self.deviation_top_values = []
        self.deviation_bottom_values = []
        
    def next(self):
        close = pd.Series(self.data.Close)
        
        if len(close) < self.length + self.offset:
            return
        
        window_start = len(close) - self.length - self.offset
        window_end = len(close) - self.offset
        window = close.iloc[window_start:window_end].values
        
        if len(window) < 2:
            return
        
        pairwise_slopes = []
        for i in range(len(window)):
            for j in range(i + 1, len(window)):
                slope = (window[j] - window[i]) / (j - i)
                pairwise_slopes.append(slope)
        
        if len(pairwise_slopes) == 0:
            return
        
        beta_1 = np.median(pairwise_slopes)
        
        residuals = []
        for i, val in enumerate(window):
            residual = val - beta_1 * i
            residuals.append(residual)
        
        beta_0 = np.median(residuals)
        predicted = beta_0 + beta_1 * (-self.offset)
        
        errors = []
        for i, val in enumerate(window):
            predicted_val = beta_0 + beta_1 * i
            error = abs(val - predicted_val)
            errors.append(error)
        
        mad = np.median(errors) * self.multiplier
        
        theil_sen_out = predicted
        deviation_top_out = predicted + mad
        deviation_bottom_out = predicted - mad
        
        self.theil_sen_values.append(theil_sen_out)
        self.deviation_top_values.append(deviation_top_out)
        self.deviation_bottom_values.append(deviation_bottom_out)
        
        if len(self.theil_sen_values) < 2:
            return
        
        current_price = self.data.Close[-1]
        prev_theil_sen = self.theil_sen_values[-2]
        curr_theil_sen = self.theil_sen_values[-1]
        curr_dev_top = self.deviation_top_values[-1]
        curr_dev_bot = self.deviation_bottom_values[-1]
        
        if not self.position:
            if crossover(curr_theil_sen, curr_dev_bot) and current_price < curr_theil_sen:
                self.buy()
        else:
            if crossover(curr_dev_top, curr_theil_sen) and current_price > curr_theil_sen:
                self.sell()
            elif crossover(curr_theil_sen, curr_dev_top):
                self.sell()


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.002,
        exclusive_orders=True
    )
    
    stats = bt.run()
    print(stats)
    bt.plot()