"""
OpenClaw Backtest Results: vdubus-divergence-wave-pattern-generator-v1
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vdubus-divergence-wave-pattern-generator-v1
Generated by OpenClaw TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Fast Structure Parameters
    fastDepth = 9
    # Slow Structure Parameters
    slowDepth = 24
    # Momentum Physics Parameters
    fastLen = 21
    slowLen = 34
    sigLen = 5
    lookback = 3
    # Pattern Filters
    showStandard = True
    showClimax = True
    showRounded = True
    showPred = True
    # Harmonic Shape Selectors
    showGartley = False
    showBat = False
    showButterfly = False
    showCrab = False
    showDeep = False
    showHS = True
    err_tol = 0.15

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # MACD calculation
        macd_result = self.I(pta.macd, close, fast=self.fastLen, slow=self.slowLen, signal=self.sigLen)
        self.macd_line = macd_result[:, 0] if macd_result.ndim > 1 else macd_result
        self.signal_line = macd_result[:, 1] if macd_result.ndim > 1 else macd_result
        self.hist_line = macd_result[:, 2] if macd_result.ndim > 1 else macd_result
        
        # Store price data for pivot detection
        self.high_series = high
        self.low_series = low
        self.close_series = close
        
        # Trading state
        self.last_pivot_high = None
        self.last_pivot_low = None
        self.pattern_detected = False
        self.pattern_direction = None  # 'bearish' or 'bullish'

    def detect_pivot_high(self, bar_idx):
        """Detect pivot high at bar_idx"""
        if bar_idx < self.lookback or bar_idx >= len(self.data) - self.lookback:
            return None
        
        lookback_idx = bar_idx - self.lookback
        lookahead_idx = bar_idx + self.lookback
        
        if lookahead_idx >= len(self.data):
            return None
            
        pivot_high = self.data.High[bar_idx]
        
        is_pivot = True
        for i in range(lookback_idx, bar_idx):
            if self.data.High[i] > pivot_high:
                is_pivot = False
                break
        
        if is_pivot:
            for i in range(bar_idx + 1, lookahead_idx + 1):
                if self.data.High[i] >= pivot_high:
                    is_pivot = False
                    break
        
        return pivot_high if is_pivot else None

    def detect_pivot_low(self, bar_idx):
        """Detect pivot low at bar_idx"""
        if bar_idx < self.lookback or bar_idx >= len(self.data) - self.lookback:
            return None
        
        lookback_idx = bar_idx - self.lookback
        lookahead_idx = bar_idx + self.lookback
        
        if lookahead_idx >= len(self.data):
            return None
            
        pivot_low = self.data.Low[bar_idx]
        
        is_pivot = True
        for i in range(lookback_idx, bar_idx):
            if self.data.Low[i] < pivot_low:
                is_pivot = False
                break
        
        if is_pivot:
            for i in range(bar_idx + 1, lookahead_idx + 1):
                if self.data.Low[i] <= pivot_low:
                    is_pivot = False
                    break
        
        return pivot_low if is_pivot else None

    def check_standard_bearish_momentum(self):
        """Check if MACD histogram shows standard bearish pattern"""
        if len(self.hist_line) < 3:
            return False
        
        h1 = self.hist_line[-3]
        h2 = self.hist_line[-2]
        h3 = self.hist_line[-1]
        
        if pd.isna(h1) or pd.isna(h2) or pd.isna(h3):
            return False
        
        return h2 < h1 and h3 <= h2

    def check_standard_bullish_momentum(self):
        """Check if MACD histogram shows standard bullish pattern"""
        if len(self.hist_line) < 3:
            return False
        
        h1 = self.hist_line[-3]
        h2 = self.hist_line[-2]
        h3 = self.hist_line[-1]
        
        if pd.isna(h1) or pd.isna(h2) or pd.isna(h3):
            return False
        
        return h2 > h1 and h3 >= h2

    def check_climax_bearish_momentum(self):
        """Check if MACD histogram shows climax bearish pattern"""
        if len(self.hist_line) < 3:
            return False
        
        h1 = self.hist_line[-3]
        h2 = self.hist_line[-2]
        h3 = self.hist_line[-1]
        
        if pd.isna(h1) or pd.isna(h2) or pd.isna(h3):
            return False
        
        return h2 >= h1 and h3 < h2

    def check_climax_bullish_momentum(self):
        """Check if MACD histogram shows climax bullish pattern"""
        if len(self.hist_line) < 3:
            return False
        
        h1 = self.hist_line[-3]
        h2 = self.hist_line[-2]
        h3 = self.hist_line[-1]
        
        if pd.isna(h1) or pd.isna(h2) or pd.isna(h3):
            return False
        
        return h2 <= h1 and h3 > h2

    def next(self):
        """Main trading logic"""
        current_idx = len(self.data) - 1
        
        # Check for pivot highs (bearish signal)
        if current_idx >= self.lookback:
            pivot_h = self.detect_pivot_high(current_idx - self.lookback)
            if pivot_h is not None:
                # Standard bearish
                if self.showStandard and self.check_standard_bearish_momentum():
                    if not self.position:
                        self.sell()
                
                # Climax bearish
                elif self.showClimax and self.check_climax_bearish_momentum():
                    if not self.position:
                        self.sell()
        
        # Check for pivot lows (bullish signal)
        if current_idx >= self.lookback:
            pivot_l = self.detect_pivot_low(current_idx - self.lookback)
            if pivot_l is not None:
                # Standard bullish
                if self.showStandard and self.check_standard_bullish_momentum():
                    if self.position:
                        self.position.close()
                    else:
                        self.buy()
                
                # Climax bullish
                elif self.showClimax and self.check_climax_bullish_momentum():
                    if self.position:
                        self.position.close()
                    else:
                        self.buy()
        
        # Exit logic using MACD crossover
        if self.position:
            if crossover(self.signal_line, self.macd_line):
                self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()