// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TradingView

//@version=6
indicator("Commitment of Traders: Legacy Metrics", "COT Legacy", format = format.volume)

// "Commitment of Traders: Legacy Metrics"
// v5, 2025.12.20

// This code's style is based on the recommendations from the Pine Script User Manual's Style guide:
//    https://www.tradingview.com/pine-script-docs/writing/style-guide/



// +-----------------------------------+------------------------+
// |  Legacy (COT) Metric Names        |       Directions       |
// +-----------------------------------+------------------------+
// | Open Interest                     | No direction           |
// | Noncommercial Positions           | Long, Short, Spreading |
// | Commercial Positions              | Long, Short            |
// | Total Reportable Positions        | Long, Short            |
// | Nonreportable Positions           | Long, Short            |
// | Traders Total                     | No direction           |
// | Traders Noncommercial             | Long, Short, Spreading |
// | Traders Commercial                | Long, Short            |
// | Traders Total Reportable          | Long, Short            |
// | Concentration Gross LT 4 TDR      | Long, Short            |
// | Concentration Gross LT 8 TDR      | Long, Short            |
// | Concentration Net LT 4 TDR        | Long, Short            |
// | Concentration Net LT 8 TDR        | Long, Short            |
// +-----------------------------------+------------------------+



import TradingView/LibraryCOT/5 as cot



//#region ———————————————————— Constants and inputs


// Allowed directions
string ND  = " [ND]"
string LS  = " [L|Sh]"
string LSS = " [L|Sh|Sp]"

// Metric information types
string IO01 = "Futures"
string IO02 = "Options"
string IO03 = "Futures + Options"

// Metric names
string MB01 = "Open Interest"
string MB02 = "Noncommercial Positions"
string MB03 = "Commercial Positions"
string MB04 = "Total Reportable Positions"
string MB05 = "Nonreportable Positions"
string MB06 = "Traders Total"
string MB07 = "Traders Noncommercial"
string MB08 = "Traders Commercial"
string MB09 = "Traders Total Reportable"
string MB10 = "Concentration Gross LT 4 TDR"
string MB11 = "Concentration Gross LT 8 TDR"
string MB12 = "Concentration Net LT 4 TDR"
string MB13 = "Concentration Net LT 8 TDR"

// "Metric" input options
string M01 = MB01 + ND
string M02 = MB02 + LSS
string M03 = MB03 + LS
string M04 = MB04 + LS
string M05 = MB05 + LS
string M06 = MB06 + ND
string M07 = MB07 + LSS
string M08 = MB08 + LS
string M09 = MB09 + LS
string M10 = MB10 + LS
string M11 = MB11 + LS
string M12 = MB12 + LS
string M13 = MB13 + LS

// Tooltips
string TT_METRIC = (
    "Specifies the metric to request, and indicates the available directions in square brackets:\n"
    + " [ND] 🠆 No direction\n [L] 🠆 Long\n [Sh] 🠆 Short\n [Sp] 🠆 Spreading"
)
string TT_DIR = (
    "Specifies the direction for the metric. "
    + "The items in the dropdown menu above show which direction options apply to each metric."
)
string TT_TYPE = (
    "Specifies the metric's type. "
    + "See the 'Old and Other Futures' section of the CFTC's Explanatory Notes for details on types."
)
string TT_OPTIONS = "Determines whether the data includes information for futures, options, or both."
string TT_SYMBOL = (
    "Specifies the futures instrument for which to request COT data. "
    + "If not empty, the indicator retrieves the CFTC code for the instrument referenced by the specified symbol. "
    + "Otherwise, it retrieves the code for the instrument referenced by the chart's symbol."
)

// Inputs
string metricNameInput      = input.string(M01,            "Metric",          options = [M01, M02, M03, M04, M05, M06, M07, M08, M09, M10, M11, M12, M13], tooltip = TT_METRIC)
string metricDirectionInput = input.string("No direction", "Direction",       options = ["No direction", "Long", "Short", "Spreading"], tooltip = TT_DIR)
string metricTypeInput      = input.string("All",          "Type",            options = ["All", "Old", "Other"], tooltip = TT_TYPE)
string includeOptionsInput  = input.string(IO01,           "Futures/Options", options = [IO01, IO02, IO03], tooltip = TT_OPTIONS)
string userCFTCSymInput    = input.symbol("",              "Symbol",          tooltip = TT_SYMBOL)
//#endregion



//#region ———————————————————— Calculations


// @variable A string containing the CFTC code for the instrument referenced by the chart's symbol or a specified symbol.
var string cftcCode = cot.getCFTCCode(userCFTCSymInput)

// @variable A string containing the metric name.
var string metricName = str.substring(metricNameInput, 0, str.pos(metricNameInput, "[") - 1)

// @variable The COT ticker ID that specifies futures-only information.
var string futuresOnlyTickerID = cot.COTTickerid(
    "Legacy", cftcCode, false, metricName, metricDirectionInput, metricTypeInput
)
// @variable The COT ticker ID that specifies futures and options information.
var string futuresWithOptionsTickerID = cot.COTTickerid(
    "Legacy", cftcCode, true, metricName, metricDirectionInput, metricTypeInput
)

// @variable The requested Legacy metric for futures data.
float futuresOnly = cot.requestCommitmentOfTraders(
    "Legacy", cftcCode, false, metricName, metricDirectionInput, metricTypeInput
)
// @variable The requested Legacy metric for futures and options data.
float futuresWithOptions = cot.requestCommitmentOfTraders(
    "Legacy", cftcCode, true, metricName, metricDirectionInput, metricTypeInput
)

// @variable COT series for futures, options, or futures and options data, depending on `includeOptionsInput`.
float COTSeries = switch includeOptionsInput
    IO01 => futuresOnly
    IO02 => futuresWithOptions - futuresOnly
    IO03 => futuresWithOptions
    => na
//#endregion



//#region ———————————————————— Display


// Plot `COTSeries` as a step line with diamonds.
plot(COTSeries, "COT", style = plot.style_stepline_diamond)

// @variable References a `table` instance that displays symbol and COT ticker ID information in the bottom-right corner.
var table symbolDisplay = table.new(position.bottom_right, 1, 1)
// Populate the `symbolDisplay` table on the first bar.
if barstate.isfirst
    color TEXT_COLOR = color.white
    color BG_COLOR   = color.new(color.blue, 50)
    int    pos       = str.pos(userCFTCSymInput, ":")
    string ticker    = str.substring(userCFTCSymInput, pos + 1)
    string symbol    = userCFTCSymInput != "" ? ticker : syminfo.ticker
    string tickerID  = switch includeOptionsInput
        IO01 => futuresOnlyTickerID
        IO02 => futuresWithOptionsTickerID + "-" + futuresOnlyTickerID
        IO03 => futuresWithOptionsTickerID
    string txt = str.format("COT data for {0} {1}\nCOT ticker ID: {2}", symbol, includeOptionsInput, tickerID)
    table.cell(symbolDisplay, 0, 0, txt, text_halign = text.align_left, text_color = TEXT_COLOR, bgcolor = BG_COLOR)
//#endregion
