//@version=6

//
// Pine Script v4
// @author BigBitsIO
// Script Library: https://www.tradingview.com/u/BigBitsIO/#published-scripts
//

indicator(title = 'Fancy Triple Moving Averages [BigBitsIO]', shorttitle = 'Fancy Triple Moving Averages [BigBitsIO]', overlay = true)
import TradingView/ta/10

MAPeriod = input.int(50, title = 'MA1 Period', minval = 1, step = 1)
MAType = input.string(title = 'MA1 Type', defval = 'SMA', options = ['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA', 'KAMA', 'ALMA'])
MASource = input(title = 'MA1 Source', defval = close)
MAResolution = input.string(title = 'MA1 Resolution', defval = '00 Current', options = ['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'])
MACandleType = input.string(title = 'MA1 Candle Type', defval = '00 Current', options = ['00 Current', '01 Heikin Ashi', '02 Renko', '03 Line Break', '04 Kagi', '05 Point & Figure'])
MAVisible = input(title = 'MA1 Visible', defval = true) // Will automatically hide crossBovers containing this MA

MA2Period = input.int(100, title = 'MA2 Period', minval = 1, step = 1)
MA2Type = input.string(title = 'MA2 Type', defval = 'SMA', options = ['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA', 'KAMA', 'ALMA'])
MA2Source = input(title = 'MA2 Source', defval = close)
MA2Resolution = input.string(title = 'MA2 Resolution', defval = '00 Current', options = ['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'])
MA2CandleType = input.string(title = 'MA2 Candle Type', defval = '00 Current', options = ['00 Current', '01 Heikin Ashi', '02 Renko', '03 Line Break', '04 Kagi', '05 Point & Figure'])
MA2Visible = input(title = 'MA2 Visible', defval = true) // Will automatically hide crossBovers containing this MA

MA3Period = input.int(200, title = 'MA3 Period', minval = 1, step = 1)
MA3Type = input.string(title = 'MA3 Type', defval = 'SMA', options = ['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA', 'KAMA', 'ALMA'])
MA3Source = input(title = 'MA3 Source', defval = close)
MA3Resolution = input.string(title = 'MA3 Resolution', defval = '00 Current', options = ['00 Current', '01 1m', '02 3m', '03 5m', '04 15m', '05 30m', '06 45m', '07 1h', '08 2h', '09 3h', '10 4h', '11 1D', '12 1W', '13 1M'])
MA3CandleType = input.string(title = 'MA3 Candle Type', defval = '00 Current', options = ['00 Current', '01 Heikin Ashi', '02 Renko', '03 Line Break', '04 Kagi', '05 Point & Figure'])
MA3Visible = input(title = 'MA3 Visible', defval = true) // Will automatically hide crossBovers containing this MA

HighlightInclusion = input(title = 'Highlight Inclusion', defval = true)
ShowGhostTrail = input(title = 'Show Inclusion Ghost Trail', defval = true)

STVisible = input(title = 'SuperTrend Visible', defval = false)

ForecastBias = input.string(title = 'Forecast Bias', defval = 'Neutral', options = ['Neutral', 'Bullish', 'Bearish'])
ForecastBiasPeriod = input(14, title = 'Forecast Bias Period')
ForecastBiasMagnitude = input.float(1, title = 'Forecast Bias Magnitude', minval = 0.25, maxval = 20, step = 0.25)
ShowForecast = input(title = 'Show Forecasts', defval = true)

// MA# is a variable used to store the actual moving average value.
// if statements - https://www.tradingview.com/pine-script-reference/#op_if
// MA functions - https://www.tradingview.com/pine-script-reference/ (must search for appropriate MA)
// custom functions in  pine - https://www.tradingview.com/wiki/Declaring_Functions
ma(MAType, MASource, MAPeriod) =>
    if MAPeriod > 0
        if MAType == 'SMA'
            ta.sma(MASource, MAPeriod)
        else if MAType == 'EMA'
            ta.ema(MASource, MAPeriod)
        else if MAType == 'WMA'
            ta.wma(MASource, MAPeriod)
        else if MAType == 'RMA'
            ta.rma(MASource, MAPeriod)
        else if MAType == 'HMA'
            ta.hma(MASource, MAPeriod)
        else if MAType == 'DEMA'
            e = ta.ema(MASource, MAPeriod)
            2 * e - ta.ema(e, MAPeriod)
        else if MAType == 'TEMA'
            e = ta.ema(MASource, MAPeriod)
            3 * (e - ta.ema(e, MAPeriod)) + ta.ema(ta.ema(e, MAPeriod), MAPeriod)
        else if MAType == 'VWMA'
            ta.vwma(MASource, MAPeriod)
        else if MAType == 'ALMA'
            ta.alma(MASource, MAPeriod, 6, .85)

res(MAResolution) =>
    if MAResolution == '00 Current'
        timeframe.period
    else if MAResolution == '01 1m'
        '1'
    else if MAResolution == '02 3m'
        '3'
    else if MAResolution == '03 5m'
        '5'
    else if MAResolution == '04 15m'
        '15'
    else if MAResolution == '05 30m'
        '30'
    else if MAResolution == '06 45m'
        '45'
    else if MAResolution == '07 1h'
        '60'
    else if MAResolution == '08 2h'
        '120'
    else if MAResolution == '09 3h'
        '180'
    else if MAResolution == '10 4h'
        '240'
    else if MAResolution == '11 1D'
        '1D'
    else if MAResolution == '12 1W'
        '1W'
    else if MAResolution == '13 1M'
        '1M'

gettickerid(MACandleType) =>
    if MACandleType == '00 Current'
        syminfo.tickerid
    else if MACandleType == '01 Heikin Ashi'
        ticker.heikinashi(syminfo.tickerid)
    else if MACandleType == '02 Renko'
        ticker.renko(syminfo.tickerid, 'ATR', 10)
    else if MACandleType == '03 Line Break'
        ticker.linebreak(syminfo.tickerid, 3)
    else if MACandleType == '04 Kagi'
        ticker.kagi(syminfo.tickerid, 3)
    else if MACandleType == '05 Point & Figure'
        ticker.pointfigure(syminfo.tickerid, 'hl', 'Traditional', 1, 3)

// https://www.tradingview.com/pine-script-reference/#fun_security
MA = request.security(gettickerid(MACandleType), res(MAResolution), ma(MAType, MASource, MAPeriod))

plot(MAVisible ? MA : na, color = color.new(color.lime, 0), linewidth = 2, title = 'MA1', show_last = HighlightInclusion == false ? 0 : MAResolution == '00 Current' ? MAPeriod : 0)
plot(MAVisible and MAResolution == '00 Current' and HighlightInclusion and ShowGhostTrail ? MA[MAPeriod - 1] : na, color = color.new(color.lime, 80), linewidth = 2, title = 'MA1 Trail', offset = (MAPeriod - 1) * -1)

MA2 = request.security(gettickerid(MA2CandleType), res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period))

plot(MA2Visible ? MA2 : na, color = color.new(color.yellow, 0), linewidth = 2, title = 'MA2', show_last = HighlightInclusion == false ? 0 : MA2Resolution == '00 Current' ? MA2Period : 0)
plot(MA2Visible and MA2Resolution == '00 Current' and HighlightInclusion and ShowGhostTrail ? MA2[MA2Period - 1] : na, color = color.new(color.yellow, 80), linewidth = 2, title = 'MA2 Trail', offset = (MA2Period - 1) * -1)

MA3 = request.security(gettickerid(MA3CandleType), res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period))

plot(MA3Visible ? MA3 : na, color = color.new(color.red, 0), linewidth = 2, title = 'MA3', show_last = HighlightInclusion == false ? 0 : MA3Resolution == '00 Current' ? MA3Period : 0)
plot(MA3Visible and MA3Resolution == '00 Current' and HighlightInclusion and ShowGhostTrail ? MA3[MA3Period - 1] : na, color = color.new(color.red, 80), linewidth = 2, title = 'MA3 Trail', offset = (MA3Period - 1) * -1)

[ST, STDir] = ta.supertrend(3,10)

plot(STVisible ? ST : na, color= STDir < 0 ? color.new(color.green, 0) : color.new(color.red, 0), linewidth = 1, style = plot.style_circles)

// Forecasting - forcasted prices are calculated using our MAType and MASource for the MAPeriod - the last X candles.
//              it essentially replaces the oldest X candles, with the selected source * X candles
// Bias - We'll add an "adjustment" for each additional candle being forecasted based on ATR of the previous X candles
// custom functions in  pine - https://www.tradingview.com/wiki/Declaring_Functions
bias(Bias, BiasPeriod) =>
    if Bias == 'Neutral'
        0
    else
        if Bias == 'Bullish'
            ta.atr(BiasPeriod) * ForecastBiasMagnitude
        else
            if Bias == 'Bearish'
                ta.atr(BiasPeriod) * ForecastBiasMagnitude * -1 // multiplying by -1 to make it a negative, bearish bias

// Note - Can not show forecasts on different resolutions at the moment, x-axis is an issue
Bias = bias(ForecastBias, ForecastBiasPeriod) // 14 is default atr period

MAForecast1 = MAPeriod > 1 ? (request.security(syminfo.tickerid, res(MAResolution), ma(MAType, MASource, MAPeriod - 1)) * (MAPeriod - 1) + MASource * 1 + Bias * 1) / MAPeriod : na
MAForecast2 = MAPeriod > 2 ? (request.security(syminfo.tickerid, res(MAResolution), ma(MAType, MASource, MAPeriod - 2)) * (MAPeriod - 2) + MASource * 2 + Bias * 2) / MAPeriod : na
MAForecast3 = MAPeriod > 3 ? (request.security(syminfo.tickerid, res(MAResolution), ma(MAType, MASource, MAPeriod - 3)) * (MAPeriod - 3) + MASource * 3 + Bias * 3) / MAPeriod : na
MAForecast4 = MAPeriod > 4 ? (request.security(syminfo.tickerid, res(MAResolution), ma(MAType, MASource, MAPeriod - 4)) * (MAPeriod - 4) + MASource * 4 + Bias * 4) / MAPeriod : na
MAForecast5 = MAPeriod > 5 ? (request.security(syminfo.tickerid, res(MAResolution), ma(MAType, MASource, MAPeriod - 5)) * (MAPeriod - 5) + MASource * 5 + Bias * 5) / MAPeriod : na

plot(MAResolution == '00 Current' and ShowForecast and MAVisible ? MAForecast1 : na, color = color.new(color.lime, 0), linewidth = 1, style = plot.style_circles, title = 'MA Forecast 1', offset = 1, show_last = 1)
plot(MAResolution == '00 Current' and ShowForecast and MAVisible ? MAForecast2 : na, color = color.new(color.lime, 0), linewidth = 1, style = plot.style_circles, title = 'MA Forecast 2', offset = 2, show_last = 1)
plot(MAResolution == '00 Current' and ShowForecast and MAVisible ? MAForecast3 : na, color = color.new(color.lime, 0), linewidth = 1, style = plot.style_circles, title = 'MA Forecast 3', offset = 3, show_last = 1)
plot(MAResolution == '00 Current' and ShowForecast and MAVisible ? MAForecast4 : na, color = color.new(color.lime, 0), linewidth = 1, style = plot.style_circles, title = 'MA Forecast 4', offset = 4, show_last = 1)
plot(MAResolution == '00 Current' and ShowForecast and MAVisible ? MAForecast5 : na, color = color.new(color.lime, 0), linewidth = 1, style = plot.style_circles, title = 'MA Forecast 5', offset = 5, show_last = 1)

MA2Forecast1 = MA2Period > 1 ? (request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period - 1)) * (MA2Period - 1) + MA2Source * 1 + Bias * 1) / MA2Period : na
MA2Forecast2 = MA2Period > 2 ? (request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period - 2)) * (MA2Period - 2) + MA2Source * 2 + Bias * 2) / MA2Period : na
MA2Forecast3 = MA2Period > 3 ? (request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period - 3)) * (MA2Period - 3) + MA2Source * 3 + Bias * 3) / MA2Period : na
MA2Forecast4 = MA2Period > 4 ? (request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period - 4)) * (MA2Period - 4) + MA2Source * 4 + Bias * 4) / MA2Period : na
MA2Forecast5 = MA2Period > 5 ? (request.security(syminfo.tickerid, res(MA2Resolution), ma(MA2Type, MA2Source, MA2Period - 5)) * (MA2Period - 5) + MA2Source * 5 + Bias * 5) / MA2Period : na

plot(MA2Resolution == '00 Current' and ShowForecast and MA2Visible ? MA2Forecast1 : na, color = color.new(color.yellow, 0), linewidth = 1, style = plot.style_circles, title = 'MA2 Forecast 1', offset = 1, show_last = 1)
plot(MA2Resolution == '00 Current' and ShowForecast and MA2Visible ? MA2Forecast2 : na, color = color.new(color.yellow, 0), linewidth = 1, style = plot.style_circles, title = 'MA2 Forecast 2', offset = 2, show_last = 1)
plot(MA2Resolution == '00 Current' and ShowForecast and MA2Visible ? MA2Forecast3 : na, color = color.new(color.yellow, 0), linewidth = 1, style = plot.style_circles, title = 'MA2 Forecast 3', offset = 3, show_last = 1)
plot(MA2Resolution == '00 Current' and ShowForecast and MA2Visible ? MA2Forecast4 : na, color = color.new(color.yellow, 0), linewidth = 1, style = plot.style_circles, title = 'MA2 Forecast 4', offset = 4, show_last = 1)
plot(MA2Resolution == '00 Current' and ShowForecast and MA2Visible ? MA2Forecast5 : na, color = color.new(color.yellow, 0), linewidth = 1, style = plot.style_circles, title = 'MA2 Forecast 5', offset = 5, show_last = 1)

MA3Forecast1 = MA3Period > 1 ? (request.security(syminfo.tickerid, res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period - 1)) * (MA3Period - 1) + MA3Source * 1 + Bias * 1) / MA3Period : na
MA3Forecast2 = MA3Period > 2 ? (request.security(syminfo.tickerid, res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period - 2)) * (MA3Period - 2) + MA3Source * 2 + Bias * 2) / MA3Period : na
MA3Forecast3 = MA3Period > 3 ? (request.security(syminfo.tickerid, res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period - 3)) * (MA3Period - 3) + MA3Source * 3 + Bias * 3) / MA3Period : na
MA3Forecast4 = MA3Period > 4 ? (request.security(syminfo.tickerid, res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period - 4)) * (MA3Period - 4) + MA3Source * 4 + Bias * 4) / MA3Period : na
MA3Forecast5 = MA3Period > 5 ? (request.security(syminfo.tickerid, res(MA3Resolution), ma(MA3Type, MA3Source, MA3Period - 5)) * (MA3Period - 5) + MA3Source * 5 + Bias * 5) / MA3Period : na

plot(MA3Resolution == '00 Current' and ShowForecast and MA3Visible ? MA3Forecast1 : na, color = color.new(color.red, 0), linewidth = 1, style = plot.style_circles, title = 'MA3 Forecast 1', offset = 1, show_last = 1)
plot(MA3Resolution == '00 Current' and ShowForecast and MA3Visible ? MA3Forecast2 : na, color = color.new(color.red, 0), linewidth = 1, style = plot.style_circles, title = 'MA3 Forecast 2', offset = 2, show_last = 1)
plot(MA3Resolution == '00 Current' and ShowForecast and MA3Visible ? MA3Forecast3 : na, color = color.new(color.red, 0), linewidth = 1, style = plot.style_circles, title = 'MA3 Forecast 3', offset = 3, show_last = 1)
plot(MA3Resolution == '00 Current' and ShowForecast and MA3Visible ? MA3Forecast4 : na, color = color.new(color.red, 0), linewidth = 1, style = plot.style_circles, title = 'MA3 Forecast 4', offset = 4, show_last = 1)
plot(MA3Resolution == '00 Current' and ShowForecast and MA3Visible ? MA3Forecast5 : na, color = color.new(color.red, 0), linewidth = 1, style = plot.style_circles, title = 'MA3 Forecast 5', offset = 5, show_last = 1)


alertcondition(ta.crossover(MA, MA2), title = '1 - MA crossover MA2', message = 'MA crossed over MA2')
alertcondition(ta.crossunder(MA, MA2), title = '2 - MA crossunder MA2', message = 'MA crossed under MA2')

alertcondition(ta.crossover(MA, MA3), title = '3 - MA crossover MA3', message = 'MA crossed over MA3')
alertcondition(ta.crossunder(MA, MA3), title = '4 - MA crossunder MA3', message = 'MA crossed under MA3')

alertcondition(ta.crossover(MA2, MA3), title = '5 - MA2 crossover MA3', message = 'MA2 crossed over MA3')
alertcondition(ta.crossunder(MA2, MA3), title = '6 - MA2 crossunder MA3', message = 'MA2 crossed under MA3')

alertcondition(ta.crossover(close, MA), title = '7 - Close crossover MA', message = 'Close crossed over MA')
alertcondition(ta.crossunder(close, MA), title = '8 - Close crossunder MA', message = 'Close crossed under MA')

alertcondition(ta.crossover(close, MA2), title = '9 - Close crossover MA2', message = 'Close crossed over MA2')
alertcondition(ta.crossunder(close, MA2), title = '10 - Close crossunder MA2', message = 'Close crossed under MA2')

alertcondition(ta.crossover(close, MA3), title = '11 - Close crossover MA3', message = 'Close crossed over MA3')
alertcondition(ta.crossunder(close, MA3), title = '12 - Close crossunder MA3', message = 'Close crossed under MA3')
