// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd
//                                       ░▒             
//                                  ▒▒▒   ▒▒      
//                              ▒▒▒▒▒     ▒▒      
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒          
//                  ▒▒▒▒▒▒           ▒     ▒▒          
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒  
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒         
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░        
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒         
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒                       
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒                            
//                 ▒▒▒▒▒▒▒▒▒                           
//                ▒▒▒▒▒ ▒▒▒▒▒                          
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗ 
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝  
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒                        
//@version=6
indicator('Supertrend - Ladder ATR - 1909Capital [Trendoscope®]', "SLA [Trendoscope®]", overlay = true)
import HeWhoMustNotBeNamed/arrayutils/10 as pa

matype = input.string('hma', title = 'Moving Average  ', group = 'Supertrend', options = ['sma', 'ema', 'rma', 'wma', 'hma'], inline = 'ma')
malength = input.int(7, title = '', group = 'Supertrend', inline = 'ma')

multiplier = input.int(4, 'ATR Multiplier', step = 1, group = 'Supertrend')
waitForClose = input.bool(false, 'Wait For Close', group = 'Supertrend')
delayed = input.bool(false, 'Delayed/Sticky', group = 'Supertrend')

supertrend_atr(float positiveAtr, float negativeAtr, simple float multiplier, simple bool waitForClose = false, simple bool delayed = false) =>
    var dir = 1
    lowSource = low
    highSource = high
    source = close
    buyStopDiff = negativeAtr * multiplier
    sellStopDiff = positiveAtr * multiplier
    buyStopDiff := dir == 1 ? math.min(buyStopDiff, nz(buyStopDiff[1], buyStopDiff)) : buyStopDiff
    sellStopDiff := dir == -1 ? math.min(sellStopDiff, nz(sellStopDiff[1], sellStopDiff)) : sellStopDiff
    var buyStop = lowSource - buyStopDiff
    var sellStop = highSource + sellStopDiff

    buyStopCurrent = lowSource - buyStopDiff
    sellStopCurrent = highSource + sellStopDiff

    buyStopInverse = lowSource - buyStopDiff / 2
    sellStopInverse = highSource + sellStopDiff / 2

    highConfirmation = waitForClose ? source : highSource
    lowConfirmation = waitForClose ? source : lowSource
    dir := dir == 1 and lowConfirmation[1] < buyStop[1] ? -1 : dir == -1 and highConfirmation[1] > sellStop[1] ? 1 : dir
    targetReached = dir == 1 and nz(highConfirmation[1]) >= nz(sellStop[1]) or dir == -1 and nz(lowConfirmation[1]) <= nz(buyStop[1]) or not delayed
    buyStop := dir == 1 ? targetReached ? math.max(nz(buyStop, buyStopCurrent), buyStopCurrent) : buyStop : targetReached ? buyStopCurrent : math.max(nz(buyStop, buyStopInverse), buyStopInverse)
    sellStop := dir == -1 ? targetReached ? math.min(nz(sellStop, sellStopCurrent), sellStopCurrent) : sellStop : targetReached ? sellStopCurrent : math.min(nz(sellStop, sellStopInverse), sellStopInverse)
    [dir, dir > 0 ? buyStop : sellStop]

var positiveTrArray = array.new_float()
var negativeTrArray = array.new_float()

if open < close
    pa.push(positiveTrArray, ta.tr, malength)
else
    pa.push(negativeTrArray, ta.tr, malength)

positiveAtr = pa.ma(positiveTrArray, matype, malength)
negativeAtr = pa.ma(negativeTrArray, matype, malength)

[dir, supertrend] = supertrend_atr(positiveAtr, negativeAtr, multiplier, waitForClose, delayed)
alertcondition(ta.change(dir) > 0, 'Supertrend Bullish Alert')
alertcondition(ta.change(dir) < 0, 'Supertrend Bearish Alert')

directionChange = ta.change(dir)
alertMessage = directionChange > 0 ? 'Supertrend Bullish' : directionChange < 0 ? 'Supertrend Bearish' : 'na'
if directionChange != 0
    alert(alertMessage, alert.freq_once_per_bar_close)

plot(supertrend, color = dir > 0 ? color.rgb(83, 195, 189) : color.fuchsia, title = 'Supertrend Stop')
plot(dir, 'Direction', display=display.data_window)
