"""
DS-TV Backtest Results: amt-institutional-model-v2
============================================================

--- SPY ---
  Return                    -0.37%
  Buy & Hold Return         40.20%
  Max Drawdown              -2.18%
  Sharpe Ratio              -0.13
  Sortino Ratio             -0.17
  Calmar Ratio              -0.08
  Profit Factor             0.00
  Expectancy                -0.37%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -0.37%
  Worst Trade               -0.37%
  Avg Trade                 -0.37%
  Exposure Time             1.20%
  Equity Final              99634.77$
  Equity Peak               101666.35$
  Avg Drawdown              -2.18%
  Max Drawdown Duration     410 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -0.18%
  Ann. Volatility           1.42%

--- BTC ---
  Return                    18.22%
  Buy & Hold Return         0.29%
  Max Drawdown              -10.61%
  Sharpe Ratio              0.61
  Sortino Ratio             1.12
  Calmar Ratio              0.82
  Profit Factor             191.81
  Expectancy                12.07%
  SQN                       0.99
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                24.26%
  Worst Trade               -0.13%
  Avg Trade                 11.40%
  Exposure Time             13.13%
  Equity Final              118222.70$
  Equity Peak               130427.88$
  Avg Drawdown              -3.52%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        51 days 00:00:00
  Avg Trade Duration        47 days 00:00:00
  Ann. Return               8.72%
  Ann. Volatility           14.22%

--- QQQ ---
  Return                    -3.72%
  Buy & Hold Return         45.93%
  Max Drawdown              -5.51%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.78
  Calmar Ratio              -0.34
  Profit Factor             0.00
  Expectancy                -3.73%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -3.73%
  Worst Trade               -3.73%
  Avg Trade                 -3.73%
  Exposure Time             2.60%
  Equity Final              96280.31$
  Equity Peak               101899.24$
  Avg Drawdown              -5.51%
  Max Drawdown Duration     412 days 00:00:00
  Max Trade Duration        21 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -1.89%
  Ann. Volatility           2.93%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — amt-institutional-model-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.atr14 = self.I(pta.atr, high, low, close, length=14)
        self.sma20 = self.I(pta.sma, close, length=20)
        self.sma50 = self.I(pta.sma, close, length=50)
        
        atr_short_len = 3
        self.atr_short = self.I(pta.atr, high, low, close, length=atr_short_len)
        self.atr_long = self.I(pta.atr, high, low, close, length=20)
        
        self.vol_avg = self.I(pta.sma, volume, length=20)
        
    def next(self):
        if len(self.data) < 50:
            return
        
        atr14_val = self.atr14[-1] if not np.isnan(self.atr14[-1]) else 0.01
        vol_avg_val = self.vol_avg[-1] if not np.isnan(self.vol_avg[-1]) else 1.0
        atr_short_val = self.atr_short[-1] if not np.isnan(self.atr_short[-1]) else 0.01
        atr_long_val = self.atr_long[-1] if not np.isnan(self.atr_long[-1]) else 0.01
        
        balance_ratio = atr_short_val / atr_long_val if atr_long_val > 0 else 0.5
        is_imbalanced = balance_ratio >= 0.6
        
        vol_threshold = vol_avg_val * 2.0
        vol_spike = self.data.Volume[-1] > vol_threshold and vol_avg_val > 0
        
        candle_range = self.data.High[-1] - self.data.Low[-1]
        body_ratio = abs(self.data.Close[-1] - self.data.Open[-1]) / candle_range if candle_range > 0 else 0.0
        meaningful_body = body_ratio > 0.30
        
        buy_aggression = vol_spike and self.data.Close[-1] > self.data.Open[-1] and meaningful_body
        sell_aggression = vol_spike and self.data.Close[-1] < self.data.Open[-1] and meaningful_body
        
        dup_threshold = atr14_val * 0.30
        support_price = None
        resistance_price = None
        
        if len(self.data) > 10:
            highest_h = max(self.data.High[-10:])
            lowest_l = min(self.data.Low[-10:])
            support_price = lowest_l
            resistance_price = highest_h
        
        near_support = False
        near_resistance = False
        
        if support_price and abs(self.data.Close[-1] - support_price) < atr14_val * 0.50:
            near_support = True
        if resistance_price and abs(self.data.Close[-1] - resistance_price) < atr14_val * 0.50:
            near_resistance = True
        
        bull_confluence = is_imbalanced and near_support and buy_aggression
        bear_confluence = is_imbalanced and near_resistance and sell_aggression
        
        price_above_sma20 = self.data.Close[-1] > self.sma20[-1]
        price_above_sma50 = self.data.Close[-1] > self.sma50[-1]
        price_below_sma20 = self.data.Close[-1] < self.sma20[-1]
        price_below_sma50 = self.data.Close[-1] < self.sma50[-1]
        
        if bull_confluence or (is_imbalanced and price_above_sma50 and buy_aggression and not self.position):
            self.buy()
        elif bear_confluence or (is_imbalanced and price_below_sma50 and sell_aggression and self.position):
            self.position.close()
        
        if self.position and len(self.data) > 1:
            if self.position.is_long:
                if price_below_sma50 or self.data.Close[-1] < support_price - atr14_val * 0.5 if support_price else False:
                    self.position.close()
            elif self.position.is_short:
                if price_above_sma50 or self.data.Close[-1] > resistance_price + atr14_val * 0.5 if resistance_price else False:
                    self.position.close()


if __name__ == '__main__':
    import yfinance as yf
    
    data = yf.download('QQQ', start='2023-01-01', end='2024-01-01', interval='5m')
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()