"""
DS-TV Backtest Results: colidation-breakout-structureha-cbs
============================================================

--- SPY ---
  Return                    -0.86%
  Buy & Hold Return         41.94%
  Max Drawdown              -14.41%
  Sharpe Ratio              -0.04
  Sortino Ratio             -0.06
  Calmar Ratio              -0.03
  Profit Factor             0.97
  Expectancy                -0.13%
  SQN                       -0.05
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                7.43%
  Worst Trade               -7.69%
  Avg Trade                 -0.42%
  Exposure Time             24.60%
  Equity Final              99143.15$
  Equity Peak               108174.20$
  Avg Drawdown              -2.55%
  Max Drawdown Duration     430 days 00:00:00
  Max Trade Duration        155 days 00:00:00
  Avg Trade Duration        86 days 00:00:00
  Ann. Return               -0.43%
  Ann. Volatility           11.69%

--- BTC ---
  Return                    0.84%
  Buy & Hold Return         46.22%
  Max Drawdown              -10.53%
  Sharpe Ratio              0.05
  Sortino Ratio             0.08
  Calmar Ratio              0.04
  Profit Factor             nan
  Expectancy                1.25%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                1.25%
  Worst Trade               1.25%
  Avg Trade                 1.25%
  Exposure Time             1.92%
  Equity Final              100838.64$
  Equity Peak               106078.47$
  Avg Drawdown              -5.57%
  Max Drawdown Duration     699 days 00:00:00
  Max Trade Duration        13 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               0.42%
  Ann. Volatility           7.73%

--- QQQ ---
  Return                    2.21%
  Buy & Hold Return         42.67%
  Max Drawdown              -19.91%
  Sharpe Ratio              0.08
  Sortino Ratio             0.12
  Calmar Ratio              0.06
  Profit Factor             1.32
  Expectancy                0.65%
  SQN                       0.13
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                12.06%
  Worst Trade               -7.89%
  Avg Trade                 0.44%
  Exposure Time             28.40%
  Equity Final              102212.89$
  Equity Peak               116140.90$
  Avg Drawdown              -3.54%
  Max Drawdown Duration     468 days 00:00:00
  Max Trade Duration        80 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               1.11%
  Ann. Volatility           13.92%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — colidation-breakout-structureha-cbs
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    consolidation_length = 4
    fvg_period_length = 4
    candle_margin_rate = 0.015

    def init(self):
        self.consolidation_signal = 0
        self.fvg_signal = 0
        self.last_consolidation_signal = 0
        self.consolidation_boxes = []
        self.fvg_boxes = []
        
    def next(self):
        if len(self.data) < max(self.consolidation_length, self.fvg_period_length) + 5:
            return
        
        close = self.data.Close
        high = self.data.High
        low = self.data.Low
        
        current_high = high[-1]
        current_low = low[-1]
        current_close = close[-1]
        
        ha_open = (self.data.Open[-2] + self.data.Close[-2]) / 2 if len(self.data) > 1 else self.data.Open[-1]
        ha_close = (self.data.Open[-1] + self.data.High[-1] + self.data.Low[-1] + self.data.Close[-1]) / 4
        ha_high = max(self.data.High[-1], ha_open, ha_close)
        ha_low = min(self.data.Low[-1], ha_open, ha_close)
        
        ha_oc_max = max(ha_open, ha_close)
        ha_oc_min = min(ha_open, ha_close)
        ha_margin = (ha_high - ha_low) * self.candle_margin_rate
        
        consolidation_signal = 0
        is_consolidation = True
        
        if len(self.data) >= self.consolidation_length:
            for i in range(self.consolidation_length - 1):
                lookback_idx = len(self.data) - 1 - i
                if lookback_idx < 0:
                    continue
                h_prev = high[lookback_idx]
                l_prev = low[lookback_idx]
                
                prev_ha_open = (self.data.Open[lookback_idx - 1] + self.data.Close[lookback_idx - 1]) / 2 if lookback_idx > 0 else self.data.Open[lookback_idx]
                prev_ha_close = (self.data.Open[lookback_idx] + self.data.High[lookback_idx] + self.data.Low[lookback_idx] + self.data.Close[lookback_idx]) / 4
                prev_ha_oc_max = max(prev_ha_open, prev_ha_close)
                prev_ha_oc_min = min(prev_ha_open, prev_ha_close)
                prev_ha_margin = (self.data.High[lookback_idx] - self.data.Low[lookback_idx]) * self.candle_margin_rate
                
                if ha_oc_max + ha_margin < prev_ha_oc_max or ha_oc_min - ha_margin > prev_ha_oc_min:
                    is_consolidation = False
                    break
        
        if is_consolidation and len(self.data) >= self.consolidation_length:
            consolidation_signal = 0
        
        fvg_signal = 0
        if len(self.data) >= self.fvg_period_length + 2:
            idx_left = len(self.data) - 1 - self.fvg_period_length
            idx_right = len(self.data) - 1
            
            if idx_left >= 0 and idx_right >= 0:
                h_left = high[idx_left]
                l_left = low[idx_left]
                h_right = high[idx_right]
                l_right = low[idx_right]
                
                close_left = close[idx_left]
                close_right = close[idx_right]
                
                oc_min_left = min(self.data.Open[idx_left], close_left)
                oc_max_left = max(self.data.Open[idx_left], close_left)
                oc_min_right = min(self.data.Open[idx_right], close_right)
                oc_max_right = max(self.data.Open[idx_right], close_right)
                
                if h_left < l_right:
                    fvg_signal = 2
                    if idx_left > 0 and high[idx_left - 1] < close[len(self.data) - 1]:
                        fvg_signal = 2
                elif l_left > h_right:
                    fvg_signal = -2
                    if idx_left > 0 and low[idx_left - 1] > close[len(self.data) - 1]:
                        fvg_signal = -2
        
        if is_consolidation and fvg_signal > 0 and ha_oc_max > ha_oc_min:
            consolidation_signal = 1
        elif is_consolidation and fvg_signal < 0 and ha_oc_min < ha_oc_max:
            consolidation_signal = -1
        
        self.fvg_signal = fvg_signal
        self.consolidation_signal = consolidation_signal
        
        if consolidation_signal == 1 and self.last_consolidation_signal != 1:
            if not self.position:
                self.buy()
            self.last_consolidation_signal = 1
        elif consolidation_signal == -1 and self.last_consolidation_signal != -1:
            if self.position:
                self.position.close()
            self.last_consolidation_signal = -1
        
        if self.position:
            if consolidation_signal == -1:
                self.position.close()
            elif current_high >= ha_oc_max * 1.05:
                self.position.close()