"""
DS-TV Backtest Results: decycler-momentum-regime-filter-charonquant
============================================================

--- SPY ---
  Return                    8.71%
  Buy & Hold Return         38.09%
  Max Drawdown              -19.56%
  Sharpe Ratio              0.28
  Sortino Ratio             0.40
  Calmar Ratio              0.22
  Profit Factor             1.45
  Expectancy                1.06%
  SQN                       0.32
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                16.08%
  Worst Trade               -7.90%
  Avg Trade                 0.81%
  Exposure Time             84.40%
  Equity Final              108708.41$
  Equity Peak               114990.98$
  Avg Drawdown              -2.86%
  Max Drawdown Duration     422 days 00:00:00
  Max Trade Duration        196 days 00:00:00
  Avg Trade Duration        76 days 00:00:00
  Ann. Return               4.30%
  Ann. Volatility           15.43%

--- BTC ---
  Return                    -8.07%
  Buy & Hold Return         10.58%
  Max Drawdown              -40.17%
  Sharpe Ratio              -0.12
  Sortino Ratio             -0.18
  Calmar Ratio              -0.10
  Profit Factor             0.68
  Expectancy                -2.07%
  SQN                       -0.47
  # Trades                  11
  Win Rate                  18.18%
  Best Trade                46.38%
  Worst Trade               -19.39%
  Avg Trade                 -3.16%
  Exposure Time             55.95%
  Equity Final              91930.49$
  Equity Peak               108492.35$
  Avg Drawdown              -17.20%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        37 days 00:00:00
  Ann. Return               -4.11%
  Ann. Volatility           33.52%

--- QQQ ---
  Return                    7.71%
  Buy & Hold Return         41.44%
  Max Drawdown              -21.32%
  Sharpe Ratio              0.20
  Sortino Ratio             0.29
  Calmar Ratio              0.18
  Profit Factor             1.42
  Expectancy                1.19%
  SQN                       0.29
  # Trades                  11
  Win Rate                  36.36%
  Best Trade                27.60%
  Worst Trade               -5.68%
  Avg Trade                 0.79%
  Exposure Time             92.80%
  Equity Final              107706.32$
  Equity Peak               125283.87$
  Avg Drawdown              -3.90%
  Max Drawdown Duration     428 days 00:00:00
  Max Trade Duration        198 days 00:00:00
  Avg Trade Duration        60 days 00:00:00
  Ann. Return               3.81%
  Ann. Volatility           19.14%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — decycler-momentum-regime-filter-charonquant
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    highpass_length = 8
    first_length = 23
    second_length = 17
    signal_length = 10

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Ehlers Highpass Filter (Decycler Core)
        def calc_decycler():
            PI = 2 * np.arcsin(1)
            alpha_arg = 2 * PI / (self.highpass_length * np.sqrt(2))
            
            alpha = np.zeros(len(close))
            alpha[0] = (np.cos(alpha_arg) + np.sin(alpha_arg) - 1) / np.cos(alpha_arg) if np.cos(alpha_arg) != 0 else 0
            
            hp = np.zeros(len(close))
            decycler_vals = np.zeros(len(close))
            
            for i in range(2, len(close)):
                if np.cos(alpha_arg) != 0:
                    alpha[i] = (np.cos(alpha_arg) + np.sin(alpha_arg) - 1) / np.cos(alpha_arg)
                else:
                    alpha[i] = alpha[i-1]
                
                hp[i] = (np.power(1 - (alpha[i] / 2), 2) * (close.iloc[i] - 2 * close.iloc[i-1] + close.iloc[i-2]) +
                        2 * (1 - alpha[i]) * hp[i-1] -
                        np.power(1 - alpha[i], 2) * hp[i-2])
                
                decycler_vals[i] = close.iloc[i] - hp[i]
            
            return pd.Series(decycler_vals, index=close.index)
        
        self.decycler = self.I(calc_decycler)
        
        # ROC calculation
        def calc_roc():
            roc_vals = np.zeros(len(close))
            for i in range(1, len(close)):
                roc_vals[i] = close.iloc[i] - close.iloc[i-1]
            return pd.Series(roc_vals, index=close.index)
        
        roc1 = self.I(calc_roc)
        
        # PMO Calculation
        def calc_pmo():
            roc1_vals = pd.Series(self.data.Close)
            for i in range(1, len(roc1_vals)):
                roc1_vals.iloc[i] = self.data.Close[i] - self.data.Close[i-1]
            
            ema1 = pta.ema(10 * roc1_vals, length=self.first_length)
            if ema1 is None:
                ema1 = pd.Series(0, index=close.index)
            pmo_vals = pta.ema(ema1, length=self.second_length)
            if pmo_vals is None:
                pmo_vals = pd.Series(0, index=close.index)
            return pmo_vals
        
        self.pmo = self.I(calc_pmo)
        
        # Signal line
        def calc_signal():
            pmo_vals = self.pmo
            sig = pta.ema(pmo_vals, length=self.signal_length)
            if sig is None:
                sig = pd.Series(0, index=close.index)
            return sig
        
        self.signal = self.I(calc_signal)
        
        # Decycler momentum for tracking previous values
        self.decycler_prev = None

    def next(self):
        if len(self.data) < 2:
            return
        
        # Current values
        current_decycler = self.decycler[-1]
        prev_decycler = self.decycler[-2] if len(self.decycler) > 1 else current_decycler
        
        current_pmo = self.pmo[-1]
        current_signal = self.signal[-1]
        
        # Decycler signals
        decycler_up = current_decycler > prev_decycler
        decycler_down = current_decycler < prev_decycler
        
        # PMO signals
        pmo_bull = (current_pmo > current_signal) and (current_pmo > 0)
        pmo_bear = (current_pmo < current_signal) and (current_pmo < 0)
        
        # Combined signals
        long_signal = decycler_up and pmo_bull
        short_signal = decycler_down and pmo_bear
        
        # Trading logic
        if long_signal:
            if self.position.is_short:
                self.position.close()
            if not self.position:
                self.buy()
        elif short_signal:
            if self.position.is_long:
                self.position.close()
            if not self.position:
                self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("AAPL", start="2023-01-01", end="2024-01-01", progress=False)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()