"""
DS-TV Backtest Results: delta-strike-order-flow-absorption-momentum-confirmation
============================================================

--- SPY ---
  ERROR: Indicator "λ(1)" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ(1)" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ(1)" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — delta-strike-order-flow-absorption-momentum-confirmation
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param1 = 50
    param2 = 86
    param3 = 15
    param4 = 20
    param5 = 60
    param6 = 180
    param7 = 1.5
    param8 = 3.0
    param9 = 5.0
    param10 = 14
    param11 = 60
    param12 = 40
    param13 = 12
    param14 = True
    param15 = 5.0
    param16 = True
    param17 = 14
    param18 = 3.0
    param19 = True

    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        self.avg_vol_short = self.I(pta.sma, volume, length=self.param4)
        self.vol_ratio_short = volume / self.avg_vol_short
        self.avg_vol_middle = self.I(pta.sma, volume, length=self.param5)
        self.vol_ratio_middle = volume / self.avg_vol_middle
        self.avg_vol_long = self.I(pta.sma, volume, length=self.param6)
        self.vol_ratio_long = volume / self.avg_vol_long
        self.rsi_val = self.I(pta.rsi, close, length=self.param10)
        self.current_delta_pct = self.I(lambda: (volume == 0) * 0 or (np.abs(self.I(lambda: self.data.FootprintDelta) / volume) * 100), length=1)
        self.st_value, self.st_dir = self.I(pta.supertrend, close, length=self.param17, multiplier=self.param18)

    def next(self):
        is_vol_spike = (self.vol_ratio_short[-1] >= self.param7) or (self.vol_ratio_middle[-1] >= self.param7) or (self.vol_ratio_long[-1] >= self.param7)
        base_setup_bottom = is_vol_spike and (self.current_delta_pct[-1] < 0) and (self.data.Close[-1] > self.data.Low[-1] + (self.data.High[-1] - self.data.Low[-1]) * 0.2) and (self.rsi_val[-1] <= self.param12)
        base_setup_top = is_vol_spike and (self.current_delta_pct[-1] > 0) and (self.data.Close[-1] < self.data.High[-1] - (self.data.High[-1] - self.data.Low[-1]) * 0.2) and (self.rsi_val[-1] >= self.param11)
        self.confirm_bottom = False
        self.confirm_top = False
        if base_setup_bottom:
            self.confirm_bottom = True
        if base_setup_top:
            self.confirm_top = True
        if self.confirm_bottom:
            self.buy()
        elif self.confirm_top:
            self.sell()