"""
DS-TV Backtest Results: double-relative-strength-index-drsi
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — double-relative-strength-index-drsi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length_RSI = 14
    LT_DRSI = 57
    ST_DRSI = 56

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate RSI
        rsi = self.I(pta.rsi, close, length=self.Length_RSI)
        
        # Calculate D_RSI (Double RSI)
        # D_RSI = 2 * RSI - RSI(RSI)
        def calc_drsi(close_data):
            rsi_vals = pta.rsi(close_data, length=self.Length_RSI)
            if rsi_vals is None or len(rsi_vals) == 0:
                return pd.Series(50, index=close_data.index)
            rsi_of_rsi = pta.rsi(rsi_vals, length=self.Length_RSI)
            if rsi_of_rsi is None or len(rsi_of_rsi) == 0:
                return pd.Series(50, index=close_data.index)
            drsi = 2 * rsi_vals - rsi_of_rsi
            return drsi
        
        self.drsi = self.I(calc_drsi, close)
        
        # State variable T: tracks trend
        # T = 1 if D_RSI > LT_DRSI, -1 if D_RSI < ST_DRSI, else previous value
        self.T = np.zeros(len(self.data))
        for i in range(len(self.data)):
            if i == 0:
                self.T[i] = 0
            elif self.drsi[i] > self.LT_DRSI:
                self.T[i] = 1
            elif self.drsi[i] < self.ST_DRSI:
                self.T[i] = -1
            else:
                self.T[i] = self.T[i - 1]

    def next(self):
        # Bull signal: T crosses above 0 (from -1 or 0 to 1)
        if len(self) > 1:
            if self.T[-2] <= 0 and self.T[-1] > 0:
                self.buy()
            # Bear signal: T crosses below 0 (from 1 or 0 to -1)
            elif self.T[-2] >= 0 and self.T[-1] < 0:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()