"""
DS-TV Backtest Results: dynamic-extreme-channels-reversals-luxalgo
============================================================

--- SPY ---
  Return                    25.76%
  Buy & Hold Return         41.94%
  Max Drawdown              -18.75%
  Sharpe Ratio              0.67
  Sortino Ratio             1.13
  Calmar Ratio              0.65
  Profit Factor             nan
  Expectancy                33.03%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                33.03%
  Worst Trade               33.03%
  Avg Trade                 33.03%
  Exposure Time             75.00%
  Equity Final              125761.83$
  Equity Peak               135621.31$
  Avg Drawdown              -1.74%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        545 days 00:00:00
  Avg Trade Duration        545 days 00:00:00
  Ann. Return               12.25%
  Ann. Volatility           18.21%

--- BTC ---
  Return                    -4.65%
  Buy & Hold Return         46.22%
  Max Drawdown              -32.85%
  Sharpe Ratio              -0.07
  Sortino Ratio             -0.10
  Calmar Ratio              -0.07
  Profit Factor             1.15
  Expectancy                1.46%
  SQN                       -0.10
  # Trades                  5
  Win Rate                  40.00%
  Best Trade                38.91%
  Worst Trade               -24.83%
  Avg Trade                 -1.15%
  Exposure Time             77.56%
  Equity Final              95352.89$
  Equity Peak               126253.88$
  Avg Drawdown              -9.71%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        207 days 00:00:00
  Avg Trade Duration        113 days 00:00:00
  Ann. Return               -2.35%
  Ann. Volatility           33.89%

--- QQQ ---
  Return                    4.59%
  Buy & Hold Return         42.67%
  Max Drawdown              -5.71%
  Sharpe Ratio              0.45
  Sortino Ratio             0.66
  Calmar Ratio              0.40
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              104593.27$
  Equity Peak               107806.27$
  Avg Drawdown              -2.28%
  Max Drawdown Duration     33 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               2.29%
  Ann. Volatility           5.11%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — dynamic-extreme-channels-reversals-luxalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lengthInput = 20
    alphaInput = 0.5
    trailingModeInput = False

    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return

        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        if not hasattr(self, 'upperLevel'):
            self.upperLevel = high.iloc[0]
            self.lowerLevel = low.iloc[0]
            self.upperCounter = 0
            self.lowerCounter = 0
            self.trend = 0

        current_high = high.iloc[-1]
        current_low = low.iloc[-1]
        current_close = close.iloc[-1]

        isHH = current_high >= self.upperLevel
        isLL = current_low <= self.lowerLevel

        if current_high >= self.upperLevel:
            self.upperLevel = current_high
            self.upperCounter = 0
            self.trend = 1
        else:
            self.upperCounter += 1
            if self.upperCounter >= self.lengthInput:
                self.upperLevel = self.upperLevel * (1 - self.alphaInput) + current_high * self.alphaInput
                self.upperCounter = 0

        if current_low <= self.lowerLevel:
            self.lowerLevel = current_low
            self.lowerCounter = 0
            self.trend = -1
        else:
            self.lowerCounter += 1
            if self.lowerCounter >= self.lengthInput:
                self.lowerLevel = self.lowerLevel * (1 - self.alphaInput) + current_low * self.alphaInput
                self.lowerCounter = 0

        midline = (self.upperLevel + self.lowerLevel) / 2

        bearishSignal = isHH and current_low < midline
        bullishSignal = isLL and current_high > midline

        if bullishSignal and not self.position:
            self.buy()
        elif bearishSignal and self.position:
            self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()