"""
DS-TV Backtest Results: fatih-pivot-box-v2-stable
============================================================

--- SPY ---
  Return                    2.65%
  Buy & Hold Return         35.59%
  Max Drawdown              -19.17%
  Sharpe Ratio              0.09
  Sortino Ratio             0.13
  Calmar Ratio              0.07
  Profit Factor             1.19
  Expectancy                0.30%
  SQN                       0.15
  # Trades                  18
  Win Rate                  27.78%
  Best Trade                18.38%
  Worst Trade               -3.44%
  Avg Trade                 0.18%
  Exposure Time             91.63%
  Equity Final              102652.24$
  Equity Peak               114966.51$
  Avg Drawdown              -3.80%
  Max Drawdown Duration     402 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        38 days 00:00:00
  Ann. Return               1.32%
  Ann. Volatility           14.84%

--- BTC ---
  Return                    20.87%
  Buy & Hold Return         -6.53%
  Max Drawdown              -28.20%
  Sharpe Ratio              0.32
  Sortino Ratio             0.54
  Calmar Ratio              0.35
  Profit Factor             1.17
  Expectancy                0.61%
  SQN                       -0.02
  # Trades                  20
  Win Rate                  30.00%
  Best Trade                51.20%
  Worst Trade               -9.73%
  Avg Trade                 -0.14%
  Exposure Time             60.52%
  Equity Final              120865.29$
  Equity Peak               127521.86$
  Avg Drawdown              -7.34%
  Max Drawdown Duration     430 days 00:00:00
  Max Trade Duration        75 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               9.91%
  Ann. Volatility           31.22%

--- QQQ ---
  Return                    18.24%
  Buy & Hold Return         38.94%
  Max Drawdown              -19.22%
  Sharpe Ratio              0.43
  Sortino Ratio             0.66
  Calmar Ratio              0.46
  Profit Factor             1.74
  Expectancy                1.39%
  SQN                       0.56
  # Trades                  16
  Win Rate                  37.50%
  Best Trade                28.43%
  Worst Trade               -4.36%
  Avg Trade                 1.09%
  Exposure Time             90.44%
  Equity Final              118239.92$
  Equity Peak               139320.18$
  Avg Drawdown              -2.73%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               8.77%
  Ann. Volatility           20.64%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fatih-pivot-box-v2-stable
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param1 = 10
    param2 = 21

    def init(self):
        close = pd.Series(self.data.Close)
        self.ema1 = self.I(pta.ema, close, length=self.param1)
        self.ema2 = self.I(pta.ema, close, length=self.param2)

    def next(self):
        if crossover(self.ema1, self.ema2):
            self.buy()
        elif crossover(self.ema2, self.ema1):
            self.sell()