"""
DS-TV Backtest Results: htf-candle-dynamics-luxalgo
============================================================

--- SPY ---
  Return                    -14.33%
  Buy & Hold Return         41.07%
  Max Drawdown              -24.09%
  Sharpe Ratio              -0.50
  Sortino Ratio             -0.70
  Calmar Ratio              -0.31
  Profit Factor             0.70
  Expectancy                -0.52%
  SQN                       -0.63
  # Trades                  21
  Win Rate                  19.05%
  Best Trade                16.89%
  Worst Trade               -9.30%
  Avg Trade                 -0.63%
  Exposure Time             80.08%
  Equity Final              85665.78$
  Equity Peak               101601.57$
  Avg Drawdown              -13.79%
  Max Drawdown Duration     671 days 00:00:00
  Max Trade Duration        141 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               -7.47%
  Ann. Volatility           15.09%

--- BTC ---
  Return                    -18.65%
  Buy & Hold Return         30.05%
  Max Drawdown              -29.84%
  Sharpe Ratio              -0.47
  Sortino Ratio             -0.59
  Calmar Ratio              -0.33
  Profit Factor             0.69
  Expectancy                -2.04%
  SQN                       -0.58
  # Trades                  10
  Win Rate                  30.00%
  Best Trade                19.98%
  Worst Trade               -28.92%
  Avg Trade                 -2.99%
  Exposure Time             38.52%
  Equity Final              81354.81$
  Equity Peak               112439.79$
  Avg Drawdown              -11.65%
  Max Drawdown Duration     488 days 00:00:00
  Max Trade Duration        103 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               -9.78%
  Ann. Volatility           20.79%

--- QQQ ---
  Return                    -15.85%
  Buy & Hold Return         43.36%
  Max Drawdown              -23.99%
  Sharpe Ratio              -0.44
  Sortino Ratio             -0.63
  Calmar Ratio              -0.35
  Profit Factor             0.64
  Expectancy                -0.99%
  SQN                       -0.85
  # Trades                  19
  Win Rate                  31.58%
  Best Trade                13.04%
  Worst Trade               -7.62%
  Avg Trade                 -1.15%
  Exposure Time             84.66%
  Equity Final              84149.11$
  Equity Peak               105691.76$
  Avg Drawdown              -5.93%
  Max Drawdown Duration     561 days 00:00:00
  Max Trade Duration        151 days 00:00:00
  Avg Trade Duration        33 days 00:00:00
  Ann. Return               -8.30%
  Ann. Volatility           18.85%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — htf-candle-dynamics-luxalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    # Default parameters from Pine Script
    param1 = 14  # example

    def init(self):
        close = pd.Series(self.data.Close)
        # Calculate indicators using self.I() wrapper
        self.indicator = self.I(pta.rsi, close, length=self.param1)

    def next(self):
        # Trading logic
        if crossover(self.indicator, 30):
            self.buy()
        elif crossover(70, self.indicator):
            self.sell()