"""
DS-TV Backtest Results: internal-vs-external-liquidity-zones-alpha-extract
============================================================

--- SPY ---
  Return                    34.69%
  Buy & Hold Return         43.17%
  Max Drawdown              -16.97%
  Sharpe Ratio              0.91
  Sortino Ratio             1.58
  Calmar Ratio              0.95
  Profit Factor             4.32
  Expectancy                7.22%
  SQN                       0.95
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                26.02%
  Worst Trade               -5.74%
  Avg Trade                 6.48%
  Exposure Time             72.60%
  Equity Final              134693.19$
  Equity Peak               134991.94$
  Avg Drawdown              -1.68%
  Max Drawdown Duration     107 days 00:00:00
  Max Trade Duration        270 days 00:00:00
  Avg Trade Duration        130 days 00:00:00
  Ann. Return               16.20%
  Ann. Volatility           17.89%

--- BTC ---
  Return                    26.19%
  Buy & Hold Return         2.85%
  Max Drawdown              -22.90%
  Sharpe Ratio              0.38
  Sortino Ratio             0.66
  Calmar Ratio              0.54
  Profit Factor             2.50
  Expectancy                5.34%
  SQN                       0.59
  # Trades                  10
  Win Rate                  20.00%
  Best Trade                56.19%
  Worst Trade               -10.88%
  Avg Trade                 3.67%
  Exposure Time             85.64%
  Equity Final              126190.18$
  Equity Peak               156924.52$
  Avg Drawdown              -6.04%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        235 days 00:00:00
  Avg Trade Duration        62 days 00:00:00
  Ann. Return               12.32%
  Ann. Volatility           32.24%

--- QQQ ---
  Return                    49.26%
  Buy & Hold Return         39.12%
  Max Drawdown              -20.94%
  Sharpe Ratio              0.92
  Sortino Ratio             1.68
  Calmar Ratio              1.07
  Profit Factor             5.90
  Expectancy                8.91%
  SQN                       1.11
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                34.15%
  Worst Trade               -7.57%
  Avg Trade                 7.88%
  Exposure Time             88.80%
  Equity Final              149256.29$
  Equity Peak               156947.96$
  Avg Drawdown              -2.45%
  Max Drawdown Duration     119 days 00:00:00
  Max Trade Duration        316 days 00:00:00
  Avg Trade Duration        128 days 00:00:00
  Ann. Return               22.37%
  Ann. Volatility           24.36%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — internal-vs-external-liquidity-zones-alpha-extract
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Structure parameters
    intLen = 3
    extLen = 10
    eqTolAtr = 0.25
    
    # Structure Labels parameters
    structureLookbackExternal = 36
    structureLookbackInternal = 2
    
    # Zones parameters
    atrLen = 14
    zoneAtrExt = 0.40
    zoneAtrInt = 0.40
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # Calculate pivot points for external structure (high)
        def pivot_high_ext():
            result = pd.Series(index=close.index, dtype=float)
            for i in range(self.extLen, len(close)):
                if i < self.extLen:
                    result.iloc[i] = np.nan
                else:
                    window_high = high.iloc[i - self.extLen:i + self.extLen + 1]
                    pivot = high.iloc[i]
                    is_pivot = all(pivot >= window_high.iloc[j] for j in range(len(window_high)) if j != self.extLen)
                    result.iloc[i] = pivot if is_pivot else np.nan
            return result
        
        # Calculate pivot points for external structure (low)
        def pivot_low_ext():
            result = pd.Series(index=close.index, dtype=float)
            for i in range(self.extLen, len(close)):
                if i < self.extLen:
                    result.iloc[i] = np.nan
                else:
                    window_low = low.iloc[i - self.extLen:i + self.extLen + 1]
                    pivot = low.iloc[i]
                    is_pivot = all(pivot <= window_low.iloc[j] for j in range(len(window_low)) if j != self.extLen)
                    result.iloc[i] = pivot if is_pivot else np.nan
            return result
        
        # Calculate pivot points for internal structure (high)
        def pivot_high_int():
            result = pd.Series(index=close.index, dtype=float)
            for i in range(self.intLen, len(close)):
                if i < self.intLen:
                    result.iloc[i] = np.nan
                else:
                    window_high = high.iloc[i - self.intLen:i + self.intLen + 1]
                    pivot = high.iloc[i]
                    is_pivot = all(pivot >= window_high.iloc[j] for j in range(len(window_high)) if j != self.intLen)
                    result.iloc[i] = pivot if is_pivot else np.nan
            return result
        
        # Calculate pivot points for internal structure (low)
        def pivot_low_int():
            result = pd.Series(index=close.index, dtype=float)
            for i in range(self.intLen, len(close)):
                if i < self.intLen:
                    result.iloc[i] = np.nan
                else:
                    window_low = low.iloc[i - self.intLen:i + self.intLen + 1]
                    pivot = low.iloc[i]
                    is_pivot = all(pivot <= window_low.iloc[j] for j in range(len(window_low)) if j != self.intLen)
                    result.iloc[i] = pivot if is_pivot else np.nan
            return result
        
        self.pivot_high_ext = self.I(pivot_high_ext)
        self.pivot_low_ext = self.I(pivot_low_ext)
        self.pivot_high_int = self.I(pivot_high_int)
        self.pivot_low_int = self.I(pivot_low_int)
        
        # Track external and internal pivot levels
        self.ext_high_level = None
        self.ext_low_level = None
        self.int_high_levels = []
        self.int_low_levels = []
        self.liquidity_zones = []
        
    def next(self):
        # Update external pivot levels
        if not np.isnan(self.pivot_high_ext[-1]):
            self.ext_high_level = self.pivot_high_ext[-1]
        
        if not np.isnan(self.pivot_low_ext[-1]):
            self.ext_low_level = self.pivot_low_ext[-1]
        
        # Update internal pivot levels
        if not np.isnan(self.pivot_high_int[-1]):
            self.int_high_levels.append(self.pivot_high_int[-1])
            if len(self.int_high_levels) > 5:
                self.int_high_levels.pop(0)
        
        if not np.isnan(self.pivot_low_int[-1]):
            self.int_low_levels.append(self.pivot_low_int[-1])
            if len(self.int_low_levels) > 5:
                self.int_low_levels.pop(0)
        
        # Basic trading logic based on liquidity zones and structure
        # Buy when price breaks above external low with internal confirmation
        if (self.ext_low_level is not None and 
            self.data.Close[-1] > self.ext_low_level and 
            len(self.int_low_levels) > 0):
            
            zone_height = self.atr[-1] * self.zoneAtrInt if self.atr[-1] else 0
            
            # Buy signal: price breaks above external low near internal low
            if not self.position:
                self.buy()
        
        # Sell when price breaks below external high with internal confirmation
        elif (self.ext_high_level is not None and 
              self.data.Close[-1] < self.ext_high_level and 
              len(self.int_high_levels) > 0):
            
            # Sell signal: price breaks below external high near internal high
            if self.position:
                self.position.close()
        
        # Exit long if price breaks below recent internal low
        if self.position and len(self.int_low_levels) > 0:
            recent_int_low = min(self.int_low_levels)
            if self.data.Close[-1] < recent_int_low:
                self.position.close()
        
        # Exit short if price breaks above recent internal high
        if not self.position and len(self.int_high_levels) > 0:
            recent_int_high = max(self.int_high_levels)
            if self.data.Close[-1] > recent_int_high:
                if self.position:
                    self.position.close()