"""
DS-TV Backtest Results: malaysian-snr-kaidon
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — malaysian-snr-kaidon
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    depth = 3
    sma_len = 21

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.sma21 = self.I(pta.sma, close, length=self.sma_len)
        
        self.pivot_low = self.I(self._calculate_pivot_low, low, self.depth)
        self.pivot_high = self.I(self._calculate_pivot_high, high, self.depth)
        
        self.support_levels = []
        self.resistance_levels = []
        self.last_support_idx = -1
        self.last_resistance_idx = -1

    def _calculate_pivot_low(self, low, depth):
        result = np.full(len(low), np.nan)
        for i in range(depth, len(low) - depth):
            if low.iloc[i] == low.iloc[i-depth:i+depth+1].min():
                result[i] = low.iloc[i]
        return pd.Series(result, index=low.index)

    def _calculate_pivot_high(self, high, depth):
        result = np.full(len(high), np.nan)
        for i in range(depth, len(high) - depth):
            if high.iloc[i] == high.iloc[i-depth:i+depth+1].max():
                result[i] = high.iloc[i]
        return pd.Series(result, index=high.index)

    def next(self):
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_sma = self.sma21[-1]
        
        if np.isnan(current_sma):
            return
        
        current_pivot_low = self.pivot_low[-1]
        current_pivot_high = self.pivot_high[-1]
        
        if not np.isnan(current_pivot_low) and current_pivot_low < current_sma:
            if len(self.support_levels) == 0 or self.support_levels[-1] != current_pivot_low:
                self.support_levels.append(current_pivot_low)
                if len(self.support_levels) > 5:
                    self.support_levels.pop(0)
        
        if not np.isnan(current_pivot_high) and current_pivot_high > current_sma:
            if len(self.resistance_levels) == 0 or self.resistance_levels[-1] != current_pivot_high:
                self.resistance_levels.append(current_pivot_high)
                if len(self.resistance_levels) > 5:
                    self.resistance_levels.pop(0)
        
        if len(self.support_levels) > 0:
            nearest_support = self.support_levels[-1]
            
            if self.last_support_idx != len(self) and current_close > nearest_support:
                if not self.position:
                    self.buy()
                self.last_support_idx = len(self.data)
        
        if len(self.resistance_levels) > 0:
            nearest_resistance = self.resistance_levels[-1]
            
            if self.last_resistance_idx != len(self) and current_close < nearest_resistance:
                if self.position:
                    self.position.close()
                self.last_resistance_idx = len(self.data)
        
        if self.position and len(self.support_levels) > 0:
            nearest_support = self.support_levels[-1]
            if current_close < nearest_support:
                self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    import yfinance as yf
    
    data = yf.download('EURUSD=X', start='2022-01-01', end='2024-01-01', interval='1h')
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.0002)
    results = bt.run()
    print(results)
    bt.plot()