"""
DS-TV Backtest Results: mtf-fractal-model
============================================================

--- SPY ---
  Return                    -58.48%
  Buy & Hold Return         41.94%
  Max Drawdown              -58.66%
  Sharpe Ratio              -3.31
  Sortino Ratio             -2.73
  Calmar Ratio              -0.61
  Profit Factor             0.48
  Expectancy                -0.36%
  SQN                       -3.77
  # Trades                  236
  Win Rate                  38.56%
  Best Trade                6.39%
  Worst Trade               -6.20%
  Avg Trade                 -0.37%
  Exposure Time             99.20%
  Equity Final              41518.99$
  Equity Peak               100444.26$
  Avg Drawdown              -58.66%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        12 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -35.79%
  Ann. Volatility           10.83%

--- BTC ---
  Return                    -33.18%
  Buy & Hold Return         46.22%
  Max Drawdown              -35.27%
  Sharpe Ratio              -0.88
  Sortino Ratio             -0.97
  Calmar Ratio              -0.52
  Profit Factor             0.69
  Expectancy                -0.52%
  SQN                       -1.19
  # Trades                  122
  Win Rate                  55.74%
  Best Trade                8.14%
  Worst Trade               -20.78%
  Avg Trade                 -0.61%
  Exposure Time             34.47%
  Equity Final              66816.08$
  Equity Peak               103227.08$
  Avg Drawdown              -35.27%
  Max Drawdown Duration     729 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -18.24%
  Ann. Volatility           20.65%

--- QQQ ---
  Return                    -60.32%
  Buy & Hold Return         42.67%
  Max Drawdown              -61.23%
  Sharpe Ratio              -2.75
  Sortino Ratio             -2.29
  Calmar Ratio              -0.61
  Profit Factor             0.57
  Expectancy                -0.37%
  SQN                       -3.03
  # Trades                  234
  Win Rate                  40.17%
  Best Trade                6.54%
  Worst Trade               -7.20%
  Avg Trade                 -0.39%
  Exposure Time             99.40%
  Equity Final              39678.60$
  Equity Peak               100652.38$
  Avg Drawdown              -61.23%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -37.24%
  Ann. Volatility           13.53%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — mtf-fractal-model
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        close = self.data.Close[-1]
        open_price = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if not self.position:
            if close > open_price:
                self.buy()
        else:
            if close < open_price:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)