"""
DS-TV Backtest Results: swing-highlow-wick-zones-support-resistance-indicator
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — swing-highlow-wick-zones-support-resistance-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swing_length = 5
    box_extension = 10
    line_extension = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Detect swing highs and lows using pivot logic
        self.swing_high = self.I(self._detect_swing_high, high, self.swing_length)
        self.swing_low = self.I(self._detect_swing_low, low, self.swing_length)

    def _detect_swing_high(self, high, length):
        """Detect swing highs: high that is higher than length bars to left and right"""
        result = pd.Series(np.nan, index=high.index)
        for i in range(length, len(high) - length):
            if high.iloc[i] == high.iloc[i-length:i+length+1].max():
                if high.iloc[i] > high.iloc[i-length:i].max() and high.iloc[i] > high.iloc[i+1:i+length+1].max():
                    result.iloc[i] = high.iloc[i]
        return result

    def _detect_swing_low(self, low, length):
        """Detect swing lows: low that is lower than length bars to left and right"""
        result = pd.Series(np.nan, index=low.index)
        for i in range(length, len(low) - length):
            if low.iloc[i] == low.iloc[i-length:i+length+1].min():
                if low.iloc[i] < low.iloc[i-length:i].min() and low.iloc[i] < low.iloc[i+1:i+length+1].min():
                    result.iloc[i] = low.iloc[i]
        return result

    def next(self):
        # Buy signal: when price breaks above swing high
        if not np.isnan(self.swing_high[-1]):
            swing_high_price = self.swing_high[-1]
            if len(self) > 1 and self.data.Close[-2] <= swing_high_price and self.data.Close[-1] > swing_high_price:
                if not self.position:
                    self.buy()
        
        # Sell signal: when price breaks below swing low
        if not np.isnan(self.swing_low[-1]):
            swing_low_price = self.swing_low[-1]
            if len(self) > 1 and self.data.Close[-2] >= swing_low_price and self.data.Close[-1] < swing_low_price:
                if self.position:
                    self.sell()
        
        # Exit long on swing low break
        if self.position and not np.isnan(self.swing_low[-1]):
            swing_low_price = self.swing_low[-1]
            if self.data.Low[-1] < swing_low_price:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()