"""
DS-TV Backtest Results: time-orb-algorich
============================================================

--- SPY ---
  ERROR: 'TvStrategy' object has no attribute 'param1'

--- BTC ---
  ERROR: 'TvStrategy' object has no attribute 'param1'

--- QQQ ---
  ERROR: 'TvStrategy' object has no attribute 'param1'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — time-orb-algorich
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    param_utc_offset = -3  # example
    param_tipo_calculo = "Mechas"  # example
    param_hora_inicio_rango = 20  # example
    param_min_inicio_rango = 0  # example
    param_hora_fin_rango = 4  # example
    param_min_fin_rango = 0  # example
    param_permitir_segunda_entrada = True  # example
    param_hora_fin_extension = 12  # example
    param_min_fin_extension = 0  # example
    param_color_buy = "#00ff80"  # example
    param_color_sell = "#ff003a"  # example
    param_color_equil = "#ffbf00"  # example
    param_texto_color_buy = "#000000"  # example
    param_texto_color_sell = "white"  # example
    param_param1 = 14  # example

    def init(self):
        close = pd.Series(self.data.Close)
        self.indicator = self.I(pta.rsi, close, length=self.param1)
        self.maximo = np.nan
        self.minimo = np.nan
        self.niveles_disponibles = False
        self.primera_confirmada = False
        self.segunda_confirmada = False
        self.direccion_primera = 0
        self.rango_high = np.nan
        self.rango_low = np.nan
        self.t_high = np.nan
        self.t_low = np.nan
        self.fuente_high = self.param_tipo_calculo == "Mechas" if self.param_tipo_calculo == "Mechas" else np.maximum(self.data.Open, self.data.Close)
        self.fuente_low = self.param_tipo_calculo == "Mechas" if self.param_tipo_calculo == "Mechas" else np.minimum(self.data.Open, self.data.Close)

    def next(self):
        minutos_actuales = self.data.Time.hour * 60 + self.data.Time.minute
        minutos_inicio_val = self.param_hora_inicio_rango * 60 + self.param_min_inicio_rango
        minutos_fin_val = self.param_hora_fin_rango * 60 + self.param_min_fin_rango
        minutos_fin_ext_val = self.param_hora_fin_extension * 60 + self.param_min_fin_extension

        en_rango = minutos_inicio_val < minutos_fin_val and (minutos_actuales >= minutos_inicio_val and minutos_actuales < minutos_fin_val) or (minutos_actuales >= minutos_inicio_val or minutos_actuales < minutos_fin_val)
        en_extension = minutos_fin_val < minutos_fin_ext_val and (minutos_actuales >= minutos_fin_val and minutos_actuales < minutos_fin_ext_val) or (minutos_actuales >= minutos_fin_val or minutos_actuales < minutos_fin_ext_val)

        if en_rango:
            if self.fuente_high > self.rango_high:
                self.rango_high = self.fuente_high
                self.t_high = self.data.Time[0]
            if self.fuente_low < self.rango_low:
                self.rango_low = self.fuente_low
                self.t_low = self.data.Time[0]

        if not en_rango and self.niveles_disponibles:
            self.maximo = self.rango_high
            self.minimo = self.rango_low
            self.niveles_disponibles = True
            if self.t_high != np.nan:
                line.new(self.t_high, self.maximo, self.data.Time[0], self.maximo, xloc=xloc.bar_time, color=self.param_color_buy, width=2)
            if self.t_low != np.nan:
                line.new(self.t_low, self.minimo, self.data.Time[0], self.minimo, xloc=xloc.bar_time, color=self.param_color_sell, width=2)

        equilibrium = (self.maximo + self.minimo) / 2

        condiciones_basicas = self.niveles_disponibles and not en_rango and en_extension
        senal_buy = condiciones_basicas and not self.primera_confirmada and self.data.Close[-1] > self.maximo and self.data.Close[-2] <= self.maximo
        senal_sell = condiciones_basicas and not self.primera_confirmada and self.data.Close[-1] < self.minimo and self.data.Close[-2] >= self.minimo

        if senal_buy:
            self.primera_confirmada = True
            self.direccion_primera = 1
            label.new(self.data.index[-1], self.data.Low[-1], "Buy", style=label.style_label_up, yloc=yloc.belowbar, color=self.param_color_buy, textcolor=self.param_texto_color_buy, size=size.small)
        if senal_sell:
            self.primera_confirmada = True
            self.direccion_primera = -1
            label.new(self.data.index[-1], self.data.High[-1], "Sell", style=label.style_label_down, yloc=yloc.abovebar, color=self.param_color_sell, textcolor=self.param_texto_color_sell, size=size.small)

        segunda_buy = self.param_permitir_segunda_entrada and self.primera_confirmada and not self.segunda_confirmada and self.direccion_primera == -1 and self.data.Close[-1] > self.maximo and self.data.Close[-2] <= self.maximo and en_extension
        segunda_sell = self.param_permitir_segunda_entrada and self.primera_confirmada and not self.segunda_confirmada and self.direccion_primera == 1 and self.data.Close[-1] < self.minimo and self.data.Close[-2] >= self.minimo and en_extension

        if segunda_buy:
            self.segunda_confirmada = True
            label.new(self.data.index[-1], self.data.Low[-1], "Buy", style=label.style_label_up, yloc=yloc.belowbar, color=self.param_color_buy, textcolor=self.param_texto_color_buy, size=size.small)
        if segunda_sell:
            self.segunda_confirmada = True
            label.new(self.data.index[-1], self.data.High[-1], "Sell", style=label.style_label_down, yloc=yloc.abovebar, color=self.param_color_sell, textcolor=self.param_texto_color_sell, size=size.small)

        plot_visible = self.niveles_disponibles and not en_rango and en_extension
        plot(plot_visible and not np.isnan(self.maximo) if plot_visible else np.nan, "Máximo", color=self.param_color_buy, style=plot.style_linebr, linewidth=2)
        plot(plot_visible and not np.isnan(self.minimo) if plot_visible else np.nan, "Mínimo", color=self.param_color_sell, style=plot.style_linebr, linewidth=2)
        plot(plot_visible and not np.isnan(equilibrium) if plot_visible else np.nan, "Equil", color=self.param_color_equil, style=plot.style_linebr, linewidth=1)

        barcolor((senal_buy or segunda_buy) if senal_buy or segunda_buy else (senal_sell or segunda_sell) if senal_sell or segunda_sell else np.nan)