"""
DS-TV Backtest Results: top-score-scalping-3-signal-dashboard-v2
============================================================

--- SPY ---
  Return                    22.60%
  Buy & Hold Return         18.15%
  Max Drawdown              -4.94%
  Sharpe Ratio              1.38
  Sortino Ratio             2.39
  Calmar Ratio              2.19
  Profit Factor             nan
  Expectancy                10.90%
  SQN                       1.08
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                21.15%
  Worst Trade               0.66%
  Avg Trade                 10.43%
  Exposure Time             38.20%
  Equity Final              122597.13$
  Equity Peak               126124.21$
  Avg Drawdown              -1.08%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        138 days 00:00:00
  Ann. Return               10.81%
  Ann. Volatility           7.81%

--- BTC ---
  Return                    1.52%
  Buy & Hold Return         4.23%
  Max Drawdown              -18.56%
  Sharpe Ratio              0.05
  Sortino Ratio             0.07
  Calmar Ratio              0.04
  Profit Factor             1.20
  Expectancy                0.60%
  SQN                       0.07
  # Trades                  6
  Win Rate                  33.33%
  Best Trade                20.66%
  Worst Trade               -8.88%
  Avg Trade                 0.19%
  Exposure Time             13.41%
  Equity Final              101517.53$
  Equity Peak               114173.44$
  Avg Drawdown              -5.69%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        50 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               0.75%
  Ann. Volatility           15.08%

--- QQQ ---
  Return                    20.65%
  Buy & Hold Return         20.28%
  Max Drawdown              -11.40%
  Sharpe Ratio              1.00
  Sortino Ratio             1.65
  Calmar Ratio              0.87
  Profit Factor             4.66
  Expectancy                5.58%
  SQN                       0.67
  # Trades                  4
  Win Rate                  25.00%
  Best Trade                28.43%
  Worst Trade               -3.35%
  Avg Trade                 4.82%
  Exposure Time             37.40%
  Equity Final              120651.97$
  Equity Peak               136170.40$
  Avg Drawdown              -1.72%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        67 days 00:00:00
  Ann. Return               9.92%
  Ann. Volatility           9.96%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — top-score-scalping-3-signal-dashboard-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # EMA Settings
    emaFastL = 9
    emaSlowL = 21
    
    # RSI Settings
    rsiLen = 14
    rsiBuyLv = 50
    rsiSellLv = 50
    
    # VFI Settings
    vfiLen = 130
    vfiCoef = 0.2
    vfiSmooth = 3
    
    # Weight Settings
    wEMA = 40
    wRSI = 35
    wVFI = 25
    
    # Dashboard Settings
    minProb = 60

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # EMA
        self.emaFast = self.I(pta.ema, close, length=self.emaFastL)
        self.emaSlow = self.I(pta.ema, close, length=self.emaSlowL)
        
        # RSI
        self.rsiVal = self.I(pta.rsi, close, length=self.rsiLen)
        
        # VFI (Volume Flow Indicator)
        self.vfiVal = self.I(self._calculate_vfi, close, high, low, volume)
    
    def _calculate_vfi(self, close, high, low, volume):
        """Calculate Volume Flow Indicator"""
        typ = (high + low + close) / 3
        
        inter = np.log(typ) - np.log(typ.shift(1))
        vInter = inter.rolling(window=30).std()
        cutOff = self.vfiCoef * vInter * close
        
        vave = volume.rolling(window=self.vfiLen).mean().shift(1)
        vMax = vave * 2.5
        vc = np.minimum(volume, vMax)
        
        mf = typ - typ.shift(1)
        vcp = pd.Series(0.0, index=close.index)
        vcp[mf > cutOff] = vc[mf > cutOff]
        vcp[mf < -cutOff] = -vc[mf < -cutOff]
        
        rawVFI = vcp.rolling(window=self.vfiLen).sum() / vave
        vfiVal = pta.ema(rawVFI, length=self.vfiSmooth)
        
        return vfiVal if vfiVal is not None else pd.Series(0.0, index=close.index)
    
    def next(self):
        # Check for sufficient data
        if len(self.data) < max(self.emaSlowL, self.rsiLen, self.vfiLen) + 5:
            return
        
        # EMA signals
        emaBullish = self.emaFast[-1] > self.emaSlow[-1]
        emaBearish = self.emaFast[-1] < self.emaSlow[-1]
        
        # RSI signals
        rsiBullish = self.rsiVal[-1] > self.rsiBuyLv
        rsiBearish = self.rsiVal[-1] < self.rsiSellLv
        
        # VFI signals
        vfiBullish = self.vfiVal[-1] > 0
        vfiBearish = self.vfiVal[-1] < 0
        
        # Calculate normalized weights
        totalW = self.wEMA + self.wRSI + self.wVFI
        if totalW > 0:
            normEMA = (self.wEMA / totalW) * 100
            normRSI = (self.wRSI / totalW) * 100
            normVFI = (self.wVFI / totalW) * 100
        else:
            normEMA = normRSI = normVFI = 33.33
        
        # Calculate buy and sell scores
        buyScore = 0
        if emaBullish:
            buyScore += normEMA
        if rsiBullish:
            buyScore += normRSI
        if vfiBullish:
            buyScore += normVFI
        
        sellScore = 0
        if emaBearish:
            sellScore += normEMA
        if rsiBearish:
            sellScore += normRSI
        if vfiBearish:
            sellScore += normVFI
        
        # Generate signals
        buySignal = buyScore >= self.minProb and buyScore > sellScore
        sellSignal = sellScore >= self.minProb and sellScore > buyScore
        
        # Check for transitions
        buyTrigger = False
        sellTrigger = False
        
        if len(self.data) > 1:
            prev_buyScore = 0
            prev_emaBullish = self.emaFast[-2] > self.emaSlow[-2]
            prev_rsiBullish = self.rsiVal[-2] > self.rsiBuyLv
            prev_vfiBullish = self.vfiVal[-2] > 0
            
            if prev_emaBullish:
                prev_buyScore += normEMA
            if prev_rsiBullish:
                prev_buyScore += normRSI
            if prev_vfiBullish:
                prev_buyScore += normVFI
            
            prev_buySignal = prev_buyScore >= self.minProb and prev_buyScore > (100 - prev_buyScore)
            
            prev_sellScore = 0
            prev_emaBearish = self.emaFast[-2] < self.emaSlow[-2]
            prev_rsiBearish = self.rsiVal[-2] < self.rsiSellLv
            prev_vfiBearish = self.vfiVal[-2] < 0
            
            if prev_emaBearish:
                prev_sellScore += normEMA
            if prev_rsiBearish:
                prev_sellScore += normRSI
            if prev_vfiBearish:
                prev_sellScore += normVFI
            
            prev_sellSignal = prev_sellScore >= self.minProb and prev_sellScore > (100 - prev_sellScore)
            
            buyTrigger = buySignal and not prev_buySignal
            sellTrigger = sellSignal and not prev_sellSignal
        
        # Trading logic
        if buyTrigger and not self.position:
            self.buy()
        elif sellTrigger and self.position:
            self.position.close()