"""
DS-TV Backtest Results: visual-trading-zones
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — visual-trading-zones
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    step_value = 10
    step_unit = "Ticks"
    sub_levels = 0
    range_bars = 2000
    max_zones = 120

    def init(self):
        self.levels = []
        self.last_bar_index = -1

    def next(self):
        current_bar_index = len(self.data) - 1
        
        if current_bar_index != self.last_bar_index:
            self.last_bar_index = current_bar_index
            
            if current_bar_index >= self.range_bars:
                start_idx = max(0, current_bar_index - self.range_bars + 1)
                end_idx = current_bar_index + 1
                
                range_low = self.data.Low[start_idx:end_idx].min()
                range_high = self.data.High[start_idx:end_idx].max()
                
                tick = 0.0001
                if range_low > 0:
                    tick = self._get_tick(range_low)
                
                unit = tick
                if self.step_unit == "Pips (FX)":
                    pip = tick * 10.0 if tick in [0.00001, 0.001] else tick
                    unit = pip
                
                step = self.step_value * unit
                
                if step > 0:
                    low_base = self._norm(np.floor(range_low / step) * step, tick)
                    high_base = self._norm(np.ceil(range_high / step) * step, tick)
                    
                    self.levels = []
                    cur = low_base
                    zones = 0
                    
                    while cur <= high_base and zones < self.max_zones:
                        self.levels.append(self._norm(cur, tick))
                        self.levels.append(self._norm(cur + step, tick))
                        
                        if self.sub_levels > 0:
                            sub_step = step / (self.sub_levels + 1)
                            for i in range(1, self.sub_levels + 1):
                                self.levels.append(self._norm(cur + sub_step * i, tick))
                            for i in range(1, self.sub_levels + 1):
                                self.levels.append(self._norm(cur + step + sub_step * i, tick))
                        
                        cur += step * 2
                        zones += 1
        
        close_price = self.data.Close[-1]
        
        if len(self.levels) > 0:
            sorted_levels = sorted(set(self.levels))
            
            closest_level_below = None
            closest_level_above = None
            
            for level in sorted_levels:
                if level < close_price:
                    closest_level_below = level
                elif level > close_price and closest_level_above is None:
                    closest_level_above = level
            
            if closest_level_below is not None and closest_level_above is not None:
                distance_to_below = close_price - closest_level_below
                distance_to_above = closest_level_above - close_price
                
                distance_threshold = (closest_level_above - closest_level_below) * 0.1
                
                if distance_to_below < distance_threshold and len(self) > 1:
                    if self.data.Close[-2] < close_price:
                        if not self.position:
                            self.buy()
                
                if distance_to_above < distance_threshold and len(self) > 1:
                    if self.data.Close[-2] > close_price:
                        if self.position:
                            self.sell()

    def _get_tick(self, price):
        if price < 0.01:
            return 0.00001
        elif price < 1:
            return 0.001
        elif price < 100:
            return 0.01
        else:
            return 0.1

    def _norm(self, price, tick):
        if tick == 0:
            return price
        return np.round(price / tick) * tick


if __name__ == "__main__":
    from datetime import datetime
    import yfinance as yf
    
    data = yf.download("AAPL", start="2022-01-01", end="2023-01-01", progress=False)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()