"""
DS-TV Backtest Results: amt-institutional-model-v2
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    9.13%
  Buy & Hold Return         14.14%
  Max Drawdown              -6.66%
  Sharpe Ratio              0.50
  Sortino Ratio             0.82
  Calmar Ratio              0.67
  Profit Factor             nan
  Expectancy                5.10%
  SQN                       1.14
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                9.67%
  Worst Trade               0.53%
  Avg Trade                 5.00%
  Exposure Time             5.75%
  Equity Final              109125.44$
  Equity Peak               116907.99$
  Avg Drawdown              -3.18%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        22 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               4.46%
  Ann. Volatility           8.98%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — amt-institutional-model-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Module A: 30-Min Trend
    trendLookback = 5
    
    # Module B: 30-Min S/R
    srLeftBars = 3
    srRightBars = 3
    
    # Module C: Aggression
    futuresMultiplier = 2.0
    etfMultiplier = 2.5
    aggrVolPeriod = 20
    isFutures = True
    
    # Module E: Balance/Imbalance
    balancePeriod = 20
    balanceThreshold = 0.6
    
    # Module F: Volume Profile
    vpLookback = 200
    vpRows = 24
    vaPercent = 70.0
    
    # Settings
    sensitivity = "Medium"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # ATR for various uses
        self.atr14 = self.I(pta.atr, high, low, close, length=14)
        
        # Balance detection ATRs
        atr_short_len = max(1, self.balancePeriod // 2)
        self.atr_short = self.I(pta.atr, high, low, close, length=atr_short_len)
        self.atr_long = self.I(pta.atr, high, low, close, length=self.balancePeriod)
        
        # Volume average
        self.vol_avg = self.I(pta.sma, volume, length=self.aggrVolPeriod)
        
        # Sensitivity mappings
        if self.sensitivity == "Low":
            self.body_ratio = 0.45
            self.sens_vol_boost = 0.5
        elif self.sensitivity == "High":
            self.body_ratio = 0.20
            self.sens_vol_boost = -0.3
        else:  # Medium
            self.body_ratio = 0.30
            self.sens_vol_boost = 0.0
        
        # Effective volume multipliers
        self.vol_threshold_mult = (self.futuresMultiplier if self.isFutures else self.etfMultiplier) + self.sens_vol_boost

    def next(self):
        if len(self.data) < self.vpLookback:
            return
        
        # Current bar values
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        atr14 = self.atr14[-1]
        atr_short = self.atr_short[-1]
        atr_long = self.atr_long[-1]
        vol_avg = self.vol_avg[-1]
        
        if np.isnan(atr14) or np.isnan(vol_avg) or vol_avg <= 0:
            return
        
        # Balance/Imbalance detection
        balance_ratio = atr_short / atr_long if atr_long > 0 else 0.5
        is_in_balance = balance_ratio < self.balanceThreshold
        is_imbalanced = not is_in_balance
        
        # Volume spike detection
        vol_threshold = vol_avg * self.vol_threshold_mult
        vol_spike = volume > vol_threshold
        
        # Candle structure
        candle_range = high - low
        body_ratio = abs(close - open_) / candle_range if candle_range > 0 else 0.0
        meaningful_body = body_ratio > self.body_ratio
        
        # Aggression detection
        buy_aggression = vol_spike and close > open_ and meaningful_body
        sell_aggression = vol_spike and close < open_ and meaningful_body
        
        vol_ratio = volume / vol_avg if vol_avg > 0 else 0.0
        is_medium_spike = 2.0 <= vol_ratio < 3.5
        is_large_spike = 3.5 <= vol_ratio < 5.0
        is_huge_spike = vol_ratio >= 5.0
        
        # Simple trend detection (higher highs/lows vs lower highs/lows over lookback)
        if len(self.data.High) > self.trendLookback * 2:
            highest_recent = self.data.High[-self.trendLookback:].max()
            lowest_recent = self.data.Low[-self.trendLookback:].min()
            highest_prev = self.data.High[-(self.trendLookback * 2):-self.trendLookback].max()
            lowest_prev = self.data.Low[-(self.trendLookback * 2):-self.trendLookback].min()
            
            higher_high = highest_recent > highest_prev
            higher_low = lowest_recent > lowest_prev
            lower_low = lowest_recent < lowest_prev
            lower_high = highest_recent < highest_prev
            
            if higher_high and higher_low:
                trend_state = 1  # Bullish
            elif lower_low and lower_high:
                trend_state = -1  # Bearish
            else:
                trend_state = 0  # Neutral
        else:
            trend_state = 0
        
        # Entry logic: Use confluence of imbalance, aggression, and trend
        # Buy signal: Imbalanced bullish trend + buy aggression
        if trend_state == 1 and is_imbalanced and buy_aggression and not self.position:
            self.buy()
        
        # Sell signal: Imbalanced bearish trend + sell aggression
        elif trend_state == -1 and is_imbalanced and sell_aggression and self.position:
            self.position.close()
        
        # Exit long on bearish reversal or if in balance
        if self.position and (trend_state == -1 or is_in_balance):
            self.position.close()
        
        # Failed auction exit: If previous bar had aggression but current bar reverses
        if len(self.data) > 1:
            prev_close = self.data.Close[-2]
            prev_open = self.data.Open[-2]
            prev_high = self.data.High[-2]
            prev_low = self.data.Low[-2]
            
            prev_candle_range = prev_high - prev_low
            prev_body_ratio = abs(prev_close - prev_open) / prev_candle_range if prev_candle_range > 0 else 0.0
            
            prev_vol = self.data.Volume[-2]
            prev_vol_spike = prev_vol > vol_threshold
            
            if self.position and prev_vol_spike and prev_body_ratio > self.body_ratio:
                if prev_close > prev_open and close < prev_low:
                    self.position.close()
                elif prev_close < prev_open and close > prev_high:
                    self.buy()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("NQ=F", start="2023-01-01", end="2023-12-31", interval="5m")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.0002)
    stats = bt.run()
    print(stats)
    bt.plot()