"""
DS-TV Backtest Results: average-true-range-v2
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         43.02%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         33.91%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         45.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — average-true-range-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 14
    smoothing = "RMA"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate True Range
        tr = pta.atr(high, low, close, length=1)
        
        # Calculate ATR with selected smoothing
        if self.smoothing == "RMA":
            self.atr = self.I(pta.rma, tr, length=self.length)
        elif self.smoothing == "SMA":
            self.atr = self.I(pta.sma, tr, length=self.length)
        elif self.smoothing == "EMA":
            self.atr = self.I(pta.ema, tr, length=self.length)
        else:  # WMA
            self.atr = self.I(pta.wma, tr, length=self.length)
        
        # Calculate 3-day and 7-day extremes
        self.low3 = self.I(lambda: pd.Series(self.data.Close).rolling(3).min())
        self.high3 = self.I(lambda: pd.Series(self.data.Close).rolling(3).max())
        self.low7 = self.I(lambda: pd.Series(self.data.Close).rolling(7).min())
        self.high7 = self.I(lambda: pd.Series(self.data.Close).rolling(7).max())

    def next(self):
        # Simple trading logic based on ATR
        if len(self.data) < self.length + 1:
            return
        
        current_atr = self.atr[-1]
        prev_atr = self.atr[-2] if len(self.atr) > 1 else current_atr
        
        # Buy when ATR crosses above its moving average (increased volatility)
        if prev_atr is not None and current_atr is not None:
            if prev_atr <= 0 and current_atr > 0:
                if not self.position:
                    self.buy()
            # Sell when ATR crosses below zero or decreases significantly
            elif current_atr <= 0 or (prev_atr > current_atr and self.position):
                if self.position:
                    self.position.close()