"""
DS-TV Backtest Results: beautiful-trend-lines-for-xauusd-zeeshan
============================================================

--- SPY ---
  ERROR: Can't instantiate abstract class TvStrategy without an implementation for abstract method 'next'

--- BTC ---
  ERROR: Can't instantiate abstract class TvStrategy without an implementation for abstract method 'next'

--- QQQ ---
  ERROR: Can't instantiate abstract class TvStrategy without an implementation for abstract method 'next'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — beautiful-trend-lines-for-xauusd-zeeshan
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

class TvStrategy(Strategy):
    # Default parameters from Pine Script
    _fast = 34
    _slow = 89
    _swingLen = 20
    _atrLen = 14
    _volLen = 20
    _rangeFactor = 0.45
    _confirmBars = 0
    _breakoutPct = 0.001
    _allowPossibleStart = True
    _fadeBars = 600

    def init(self):
        close = pd.Series(self.data.Close)
        atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        atr_ma = self.I(pta.sma, src=atr, length=self._atrLen)
        vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.fast_ema = self.I(pta.ema, src=close, length=self._fast)
        self.slow_ema = self.I(pta.ema, src=close, length=self._slow)
        self.slope_abs = np.abs(self.fast_ema.diff())
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.ema_bull = self.fast_ema > self.slow_ema
        self.ema_bear = self.fast_ema < self.slow_ema
        self.slope_bull = self.fast_ema > self.fast_ema.shift(1)
        self.slope_bear = self.fast_ema < self.fast_ema.shift(1)
        self.flat_slope = np.abs(self.slope_abs) < atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.atr_compression = atr < atr_ma * self._rangeFactor
        self.is_ranging = self.atr_compression and self.flat_slope and self.no_struct
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.is_ranging = self.atr_compression and self.flat_slope and self.no_struct
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr_exp = self.atr > self.atr_ma
        self.vol_exp = self.data.Volume > self.vol_ma
        self.relaxed_vol_atr = self.vol_exp or self.atr_exp
        self.relaxed_htf = True
        self.relaxed_confirm = self.relaxed_vol_atr and self.relaxed_htf
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.is_ranging = self.atr_compression and self.flat_slope and self.no_struct
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor
        self.flat_slope = np.abs(self.slope_abs) < self.atr * 0.1
        self.no_struct = not (self.recent_low < self.data.Close) and not (self.recent_high > self.data.Close)
        self.recent_high = self.I(pta.highest, src=self.data.High, length=self._swingLen)
        self.recent_low = self.I(pta.lowest, src=self.data.Low, length=self._swingLen)
        self.atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self._atrLen)
        self.atr_ma = self.I(pta.sma, src=self.atr, length=self._atrLen)
        self.vol_ma = self.I(pta.sma, src=self.data.Volume, length=self._volLen)
        self.atr_compression = self.atr < self.atr_ma * self._rangeFactor