"""
DS-TV Backtest Results: btc-vs-m2-global-indexmit
============================================================

--- SPY ---
  Return                    27.70%
  Buy & Hold Return         30.74%
  Max Drawdown              -5.07%
  Sharpe Ratio              1.57
  Sortino Ratio             2.82
  Calmar Ratio              2.59
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              127703.88$
  Equity Peak               127987.24$
  Avg Drawdown              -1.22%
  Max Drawdown Duration     42 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               13.12%
  Ann. Volatility           8.37%

--- BTC ---
  Return                    -28.58%
  Buy & Hold Return         -27.69%
  Max Drawdown              -51.66%
  Sharpe Ratio              -0.54
  Sortino Ratio             -0.69
  Calmar Ratio              -0.30
  Profit Factor             0.00
  Expectancy                -18.66%
  SQN                       -1.28
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -3.91%
  Worst Trade               -33.41%
  Avg Trade                 -20.01%
  Exposure Time             29.00%
  Equity Final              71416.07$
  Equity Peak               100000.00$
  Avg Drawdown              -51.66%
  Max Drawdown Duration     309 days 00:00:00
  Max Trade Duration        210 days 00:00:00
  Avg Trade Duration        106 days 00:00:00
  Ann. Return               -15.47%
  Ann. Volatility           28.64%

--- QQQ ---
  Return                    26.58%
  Buy & Hold Return         35.63%
  Max Drawdown              -7.88%
  Sharpe Ratio              1.17
  Sortino Ratio             1.99
  Calmar Ratio              1.60
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              126579.84$
  Equity Peak               130830.03$
  Avg Drawdown              -1.55%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               12.61%
  Ann. Volatility           10.79%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — btc-vs-m2-global-indexmit
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    offsetValue = 108
    normLength = 200
    
    def init(self):
        close = pd.Series(self.data.Close)
        
        # Since we can't fetch external economic data in backtesting,
        # we'll use a simplified proxy: use BTC normalized against itself
        # and create a synthetic M2 proxy using a slower moving average
        
        btc_sma_fast = self.I(pta.sma, close, length=self.normLength)
        btc_sma_slow = self.I(pta.sma, close, length=int(self.normLength * 1.5))
        
        # Normalized BTC (price / SMA)
        self.norm_btc = self.I(lambda: close / btc_sma_fast)
        
        # Synthetic M2 proxy (slower moving average normalized)
        self.norm_m2 = self.I(lambda: btc_sma_slow / btc_sma_fast)
        
        # Deviation: M2 proxy - BTC normalized
        self.deviation = self.I(lambda: self.norm_m2 - self.norm_btc)
    
    def next(self):
        # Trading logic based on deviation
        # Buy when deviation crosses below 0 (BTC undervalued vs M2)
        # Sell when deviation crosses above 0 (BTC overvalued vs M2)
        
        if len(self.data) < 2:
            return
        
        if crossover(0, self.deviation):
            # Deviation crossing below 0: BTC becoming undervalued
            if not self.position:
                self.buy()
        elif crossover(self.deviation, 0):
            # Deviation crossing above 0: BTC becoming overvalued
            if self.position:
                self.sell()