"""
DS-TV Backtest Results: codapro-supertrend-confirmed-flags-trade-management
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "atr(H,L,14)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (732,); indicator "atr(H,L,14)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "atr(H,L,14)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — codapro-supertrend-confirmed-flags-trade-management
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 14
    mult = 3.0
    confirmBars = 2
    tpPct = 0.15
    slPct = 0.10
    maxBarsInput = 80
    cooldownLen = 10
    eodHour = 16
    eodMinute = 40
    stopLineWidth = 2
    flagSizeOpt = "Small"
    tpColor = (0, 226, 118, 30)
    slColor = (255, 23, 68, 30)

    def init(self):
        close = pd.Series(self.data.Close)
        atr = self.I(pta.atr, high=self.data.High, low=self.data.Low, close=close, length=self.atrLen)
        self.upperBasic = close + self.mult * atr
        self.lowerBasic = close - self.mult * atr
        self.upperFinal = self.I(lambda: self.upperBasic if self.upperBasic < self.upperFinal[-1] or close[-1] > self.upperFinal[-1] else self.upperFinal[-1])
        self.lowerFinal = self.I(lambda: self.lowerBasic if self.lowerBasic > self.lowerFinal[-1] or close[-1] < self.lowerFinal[-1] else self.lowerFinal[-1])
        self.dir = self.I(lambda: 1 if self.dir[-1] is na or (self.dir[-1] == 1 and close[-1] < self.lowerFinal[-1]) or (self.dir[-1] == -1 and close[-1] > self.upperFinal[-1]) else self.dir[-1])
        self.supertrend = self.I(lambda: self.lowerFinal if self.dir == 1 else self.upperFinal)
        self.isBull = self.dir == 1
        self.isBear = self.dir == -1
        self.flipToBear = self.I(lambda: self.isBear and self.isBull[-1])
        self.flipToBull = self.I(lambda: self.isBull and self.isBear[-1])
        self.bearConfirmed = self.I(lambda: self.flipToBear[-1 + self.confirmBars])
        self.bullConfirmed = self.I(lambda: self.flipToBull[-1 + self.confirmBars])
        self.tradeDir = 0
        self.entryPrice = na
        self.tpLevel = na
        self.slLevel = na
        self.entryBar = 0
        self.exitBar = -999
        self.tpLine = na
        self.slLine = na
        self.exitLabel = na

    def next(self):
        isEOD = self.eodHour and self.eodMinute and (self.data.Time.hour == self.eodHour and self.data.Time.minute >= self.eodMinute or self.data.Time.hour > self.eodHour)
        isFlat = self.tradeDir == 0
        cooldownOK = (self.bar_index - self.exitBar) >= self.cooldownLen

        buySignal = self.bullConfirmed and isFlat and cooldownOK and not isEOD and self.barstate.isconfirmed and self.enableTM
        sellSignal = self.bearConfirmed and isFlat and cooldownOK and not isEOD and self.barstate.isconfirmed and self.enableTM

        if buySignal:
            self.tradeDir = 1
            self.entryPrice = self.data.Close
            self.tpLevel = self.data.Close * (1 + self.tpPct / 100)
            self.slLevel = self.data.Close * (1 - self.slPct / 100)
            self.entryBar = self.bar_index
            if not na(self.tpLine):
                self.line.delete(self.tpLine)
            if not na(self.slLine):
                self.line.delete(self.slLine)
            self.tpLine = self.line.new(self.bar_index, self.tpLevel, self.bar_index + self.maxBarsInput, self.tpLevel, color=self.tpColor, style=self.line.style_dashed, width=1)
            self.slLine = self.line.new(self.bar_index, self.slLevel, self.bar_index + self.maxBarsInput, self.slLevel, color=self.slColor, style=self.line.style_dashed, width=1)

        if sellSignal:
            self.tradeDir = -1
            self.entryPrice = self.data.Close
            self.tpLevel = self.data.Close * (1 - self.tpPct / 100)
            self.slLevel = self.data.Close * (1 + self.slPct / 100)
            self.entryBar = self.bar_index
            if not na(self.tpLine):
                self.line.delete(self.tpLine)
            if not na(self.slLine):
                self.line.delete(self.slLine)
            self.tpLine = self.line.new(self.bar_index, self.tpLevel, self.bar_index + self.maxBarsInput, self.tpLevel, color=self.tpColor, style=self.line.style_dashed, width=1)
            self.slLine = self.line.new(self.bar_index, self.slLevel, self.bar_index + self.maxBarsInput, self.slLevel, color=self.slColor, style=self.line.style_dashed, width=1)

        exitReason = ""

        if self.tradeDir == 1 and not na(self.tpLevel) and self.barstate.isconfirmed:
            if self.data.High >= self.tpLevel:
                exitReason = "TP HIT"
            elif self.data.Low <= self.slLevel:
                exitReason = "SL HIT"
            elif (self.bar_index - self.entryBar) >= self.maxBarsInput:
                exitReason = "MAX BARS"
            elif isEOD:
                exitReason = "EOD EXIT"

        if self.tradeDir == -1 and not na(self.tpLevel) and self.barstate.isconfirmed:
            if self.data.Low <= self.tpLevel:
                exitReason = "TP HIT"
            elif self.data.High >= self.slLevel:
                exitReason = "SL HIT"
            elif (self.bar_index - self.entryBar) >= self.maxBarsInput:
                exitReason = "MAX BARS"
            elif isEOD:
                exitReason = "EOD EXIT"

        if exitReason != "":
            self.exitBar = self.bar_index
            if not na(self.tpLine):
                self.line.delete(self.tpLine)
                self.tpLine = na
            if not na(self.slLine):
                self.line.delete(self.slLine)
                self.slLine = na
            isTP = "TP" in exitReason
            self.exitLabel = self.label.new(self.bar_index, self.tradeDir == 1 and self.data.Low or self.tradeDir == -1 and self.data.High,
                                           exitReason,
                                           style=self.tradeDir == 1 and self.label.style_label_up or self.tradeDir == -1 and self.label.style_label_down,
                                           color=isTP and self.color.new(0, 188, 212, 0) or self.color.new(85, 85, 85, 40),
                                           textcolor=isTP and self.color.white or self.color.new(255, 255, 255, 30),
                                           size=size.normal)
            self.tradeDir = 0
            self.entryPrice = na
            self.tpLevel = na
            self.slLevel = na

        plot(self.supertrend if self.showStopLine else na, "Supertrend Stop", color=self.showStopLine and self.color.new(0, 0, 0, 0) or self.color.new(0, 0, 0, 0), linewidth=self.stopLineWidth, style=plot.style_line)

        showBear = self.enableTM and self.sellSignal or (self.showFlags and self.bearConfirmed)
        showBull = self.enableTM and self.buySignal or (self.showFlags and self.bullConfirmed)

        bearTiny = showBear and self.flagSizeOpt == "Tiny"
        bearSmall = showBear and self.flagSizeOpt == "Small"
        bearNormal = showBear and self.flagSizeOpt == "Normal"
        bearLarge = showBear and self.flagSizeOpt == "Large"

        bullTiny = showBull and self.flagSizeOpt == "Tiny"
        bullSmall = showBull and self.flagSizeOpt == "Small"
        bullNormal = showBull and self.flagSizeOpt == "Normal"
        bullLarge = showBull and self.flagSizeOpt == "Large"

        plotshape(bearTiny, title="Short Flag (Tiny)", style=shape.flag, location=location.abovebar, color=self.color.red, text="short", textcolor=self.color.white, size=size.tiny)
        plotshape(bearSmall, title="Short Flag (Small)", style=shape.flag, location=location.abovebar, color=self.color.red, text="short", textcolor=self.color.white, size=size.small)
        plotshape(bearNormal, title="Short Flag (Normal)", style=shape.flag, location=location.abovebar, color=self.color.red, text="short", textcolor=self.color.white, size=size.normal)
        plotshape(bearLarge, title="Short Flag (Large)", style=shape.flag, location=location.abovebar, color=self.color.red, text="short", textcolor=self.color.white, size=size.large)

        plotshape(bullTiny, title="Buy Flag (Tiny)", style=shape.flag, location=location.belowbar, color=self.color.lime, text="buy", textcolor=self.color.white, size=size.tiny)
        plotshape(bullSmall, title="Buy Flag (Small)", style=shape.flag, location=location.belowbar, color=self.color.lime, text="buy", textcolor=self.color.white, size=size.small)
        plotshape(bullNormal, title="Buy Flag (Normal)", style=shape.flag, location=location.belowbar, color=self.color.lime, text="buy", textcolor=self.color.white, size=size.normal)
        plotshape(bullLarge, title="Buy Flag (Large)", style=shape.flag, location=location.belowbar, color=self.color.lime, text="buy", textcolor=self.color.white, size=size.large)

        alertcondition(self.buySignal or self.buyRaw, "Confirmed Buy", "Supertrend confirmed bullish flip")
        alertcondition(self.sellSignal or self.sellRaw, "Confirmed Sell", "Supertrend confirmed bearish flip")