"""
DS-TV Backtest Results: dual-super-trend-indicator
============================================================

--- SPY ---
  Return                    40.46%
  Buy & Hold Return         41.94%
  Max Drawdown              -18.71%
  Sharpe Ratio              0.96
  Sortino Ratio             1.70
  Calmar Ratio              1.00
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              140464.20$
  Equity Peak               140775.28$
  Avg Drawdown              -1.75%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.68%
  Ann. Volatility           19.42%

--- BTC ---
  Return                    17.52%
  Buy & Hold Return         46.22%
  Max Drawdown              -35.99%
  Sharpe Ratio              0.25
  Sortino Ratio             0.40
  Calmar Ratio              0.23
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              117524.25$
  Equity Peak               172426.72$
  Avg Drawdown              -6.06%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               8.40%
  Ann. Volatility           33.87%

--- QQQ ---
  Return                    42.32%
  Buy & Hold Return         42.67%
  Max Drawdown              -22.69%
  Sharpe Ratio              0.78
  Sortino Ratio             1.36
  Calmar Ratio              0.86
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              142322.86$
  Equity Peak               147088.84$
  Avg Drawdown              -2.86%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               19.47%
  Ann. Volatility           25.06%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — dual-super-trend-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen1 = 10
    factor1 = 3.0
    atrLen2 = 10
    factor2 = 3.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate Supertrend for both timeframes
        # Since we can't use request.security, we'll use the current timeframe data
        # and apply supertrend indicators
        self.st1 = self.I(self._calculate_supertrend, high, low, close, self.atrLen1, self.factor1)
        self.st2 = self.I(self._calculate_supertrend, high, low, close, self.atrLen2, self.factor2)
        
        self.trend_state = 0

    def _calculate_supertrend(self, high, low, close, length, multiplier):
        """Calculate supertrend direction: -1 for bullish, 1 for bearish"""
        hl2 = (high + low) / 2
        atr = pta.atr(high, low, close, length=length)
        
        if atr is None:
            return pd.Series(0, index=close.index)
        
        basic_ub = hl2 + multiplier * atr
        basic_lb = hl2 - multiplier * atr
        
        final_ub = pd.Series(index=close.index, dtype=float)
        final_lb = pd.Series(index=close.index, dtype=float)
        
        final_ub.iloc[0] = basic_ub.iloc[0]
        final_lb.iloc[0] = basic_lb.iloc[0]
        
        for i in range(1, len(close)):
            final_ub.iloc[i] = basic_ub.iloc[i] if basic_ub.iloc[i] < final_ub.iloc[i-1] or close.iloc[i-1] > final_ub.iloc[i-1] else final_ub.iloc[i-1]
            final_lb.iloc[i] = basic_lb.iloc[i] if basic_lb.iloc[i] > final_lb.iloc[i-1] or close.iloc[i-1] < final_lb.iloc[i-1] else final_lb.iloc[i-1]
        
        supertrend_dir = pd.Series(0, index=close.index, dtype=int)
        for i in range(1, len(close)):
            if close.iloc[i] <= final_ub.iloc[i]:
                supertrend_dir.iloc[i] = 1
            else:
                supertrend_dir.iloc[i] = -1
        
        return supertrend_dir

    def next(self):
        if len(self.data) < max(self.atrLen1, self.atrLen2) + 1:
            return
        
        dir1 = self.st1[-1]
        dir2 = self.st2[-1]
        
        # Determine current trend
        if dir1 == -1 and dir2 == -1:
            curr_trend = 1
        elif dir1 == 1 and dir2 == 1:
            curr_trend = -1
        else:
            curr_trend = 0
        
        # Generate signals on true flip
        long_signal = curr_trend == 1 and self.trend_state != 1
        short_signal = curr_trend == -1 and self.trend_state != -1
        
        # Execute trades
        if long_signal:
            if self.position.is_short:
                self.position.close()
            self.buy()
        
        if short_signal:
            if self.position.is_long:
                self.position.close()
            self.sell()
        
        # Update state
        if curr_trend != 0:
            self.trend_state = curr_trend