"""
DS-TV Backtest Results: eurusd-m15-sniper-arrows
============================================================

--- SPY ---
  Return                    15.43%
  Buy & Hold Return         17.90%
  Max Drawdown              -9.51%
  Sharpe Ratio              0.76
  Sortino Ratio             1.16
  Calmar Ratio              0.79
  Profit Factor             0.00
  Expectancy                -7.11%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -7.11%
  Worst Trade               -7.11%
  Avg Trade                 -7.11%
  Exposure Time             13.40%
  Equity Final              115431.16$
  Equity Peak               115686.80$
  Avg Drawdown              -1.64%
  Max Drawdown Duration     131 days 00:00:00
  Max Trade Duration        99 days 00:00:00
  Avg Trade Duration        99 days 00:00:00
  Ann. Return               7.50%
  Ann. Volatility           9.81%

--- BTC ---
  Return                    28.95%
  Buy & Hold Return         17.39%
  Max Drawdown              -15.48%
  Sharpe Ratio              0.57
  Sortino Ratio             1.00
  Calmar Ratio              0.87
  Profit Factor             nan
  Expectancy                20.93%
  SQN                       2.22
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                33.35%
  Worst Trade               8.52%
  Avg Trade                 20.29%
  Exposure Time             48.97%
  Equity Final              128945.06$
  Equity Peak               152219.93$
  Avg Drawdown              -4.20%
  Max Drawdown Duration     170 days 00:00:00
  Max Trade Duration        196 days 00:00:00
  Avg Trade Duration        178 days 00:00:00
  Ann. Return               13.53%
  Ann. Volatility           23.60%

--- QQQ ---
  Return                    15.25%
  Buy & Hold Return         22.08%
  Max Drawdown              -13.18%
  Sharpe Ratio              0.56
  Sortino Ratio             0.83
  Calmar Ratio              0.56
  Profit Factor             0.00
  Expectancy                -9.26%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -9.26%
  Worst Trade               -9.26%
  Avg Trade                 -9.26%
  Exposure Time             13.00%
  Equity Final              115249.05$
  Equity Peak               119107.22$
  Avg Drawdown              -2.30%
  Max Drawdown Duration     134 days 00:00:00
  Max Trade Duration        97 days 00:00:00
  Avg Trade Duration        97 days 00:00:00
  Ann. Return               7.42%
  Ann. Volatility           13.19%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — eurusd-m15-sniper-arrows
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy


class TvStrategy(Strategy):
    emaLength = 200
    breakLength = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema200 = self.I(pta.ema, close, length=self.emaLength)
        
        self.highestHigh = self.I(lambda: high.rolling(window=self.breakLength).max())
        self.lowestLow = self.I(lambda: low.rolling(window=self.breakLength).min())

    def next(self):
        if len(self.data) < self.breakLength + 1:
            return
        
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        ema_val = self.ema200[-1]
        
        highest_prev = self.highestHigh[-2]
        lowest_prev = self.lowestLow[-2]
        
        longCondition = (current_close > ema_val and 
                         current_close > highest_prev)
        
        shortCondition = (current_close < ema_val and 
                          current_close < lowest_prev)
        
        if longCondition:
            if not self.position:
                self.buy()
        elif shortCondition:
            if self.position:
                self.position.close()