"""
DS-TV Backtest Results: gamma-hedging-pressure
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gamma-hedging-pressure
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lenATR = 14
    lenVol = 20
    gammaThresh = 0.5
    useSessionReset = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # ATR for volatility
        self.atr = self.I(pta.atr, high, low, close, length=self.lenATR)
        
        # Range normalization
        self.rangeNorm = self.I(lambda: (high - low) / (self.atr + 1e-10))
        
        # Price acceleration
        self.priceDelta = self.I(lambda: close.diff())
        self.acceleration = self.I(lambda: self.priceDelta.diff())
        
        # Volume participation
        self.volMA = self.I(pta.sma, volume, length=self.lenVol)
        self.volNorm = self.I(lambda: volume / (self.volMA + 1e-10))
        
        # Raw pressure
        self.rawPressure = self.I(lambda: self.rangeNorm * self.acceleration * self.volNorm)
        
        # Gamma pressure (EMA smoothed)
        self.gammaPressure = self.I(pta.ema, self.rawPressure, length=5)
        
        # Gamma state
        self.gammaState = self.I(self._compute_gamma_state)
    
    def _compute_gamma_state(self):
        state = pd.Series(0, index=self.gammaPressure.index)
        state[self.gammaPressure > self.gammaThresh] = -1
        state[self.gammaPressure < -self.gammaThresh] = 1
        return state
    
    def next(self):
        if len(self.data) < 2:
            return
        
        current_gamma = self.gammaPressure[-1]
        current_state = self.gammaState[-1]
        prev_state = self.gammaState[-2]
        
        # Buy signal: transition to positive gamma (mean reversion regime)
        if prev_state != 1 and current_state == 1:
            if not self.position:
                self.buy()
        
        # Sell signal: transition to negative gamma (trend/breakout regime)
        elif prev_state != -1 and current_state == -1:
            if self.position:
                self.position.close()
        
        # Exit on neutral transition
        elif current_state == 0 and prev_state != 0:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from datetime import datetime
    import yfinance as yf
    
    # Download sample data
    data = yf.download("SPY", start="2022-01-01", end="2023-12-31", interval="1d")
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()