"""
DS-TV Backtest Results: impulse-candles
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.28%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         18.33%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         21.43%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — impulse-candles
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    reversalsOnly = True
    candleSizeRatio = 5.0
    atrLength = 200
    maxBarAlpha = 10

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate True Range and ATR
        def calc_tr():
            tr = np.maximum(high - low, np.maximum(np.abs(high - close.shift(1)), np.abs(low - close.shift(1))))
            return pd.Series(tr, index=close.index)
        
        tr = self.I(calc_tr)
        
        # Calculate ATR as SMA of True Range
        def calc_atr():
            tr_series = np.maximum(high - low, np.maximum(np.abs(high - close.shift(1)), np.abs(low - close.shift(1))))
            atr_result = pd.Series(tr_series, index=close.index).rolling(self.atrLength).mean()
            return atr_result
        
        self.atr_value = self.I(calc_atr)
        
        # Store close and open for impulse logic
        self.close_series = close
        self.open_series = open_

    def next(self):
        if len(self.data) < 3:
            return
        
        idx = len(self.data) - 1
        
        # Current and previous candles
        close_curr = self.data.Close[-1]
        open_curr = self.data.Open[-1]
        close_prev1 = self.data.Close[-2]
        open_prev1 = self.data.Open[-2]
        close_prev2 = self.data.Close[-3]
        open_prev2 = self.data.Open[-3]
        
        atr = self.atr_value[-1]
        
        # Skip if ATR is not valid
        if atr is None or np.isnan(atr):
            return
        
        # Reversal conditions
        bear_candles = close_prev1 < open_prev1 and close_prev2 < open_prev2
        bull_candles = close_prev1 > open_prev1 and close_prev2 > open_prev2
        
        # Impulse conditions
        bull_impulse_raw = close_curr > open_curr and (close_curr - open_curr) > self.candleSizeRatio * atr
        bear_impulse_raw = close_curr < open_curr and (open_curr - close_curr) > self.candleSizeRatio * atr
        
        # Apply reversal filter
        if self.reversalsOnly:
            bull_impulse = bear_candles and bull_impulse_raw
            bear_impulse = bull_candles and bear_impulse_raw
        else:
            bull_impulse = bull_impulse_raw
            bear_impulse = bear_impulse_raw
        
        # Trading logic
        if bull_impulse:
            if self.position.is_short:
                self.position.close()
            if not self.position:
                self.buy()
        elif bear_impulse:
            if self.position.is_long:
                self.position.close()
            if not self.position:
                self.sell()


if __name__ == "__main__":
    # Load data
    data = pd.read_csv("data.csv", parse_dates=True, index_col=0)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()