"""
DS-TV Backtest Results: inside-bar-strategy-with-sltp
============================================================

--- SPY ---
  Return                    -2.67%
  Buy & Hold Return         41.94%
  Max Drawdown              -7.96%
  Sharpe Ratio              -0.26
  Sortino Ratio             -0.35
  Calmar Ratio              -0.17
  Profit Factor             0.89
  Expectancy                -0.05%
  SQN                       -0.36
  # Trades                  51
  Win Rate                  29.41%
  Best Trade                3.64%
  Worst Trade               -2.21%
  Avg Trade                 -0.05%
  Exposure Time             20.20%
  Equity Final              97328.76$
  Equity Peak               103024.62$
  Avg Drawdown              -3.51%
  Max Drawdown Duration     535 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -1.36%
  Ann. Volatility           5.17%

--- BTC ---
  Return                    -15.14%
  Buy & Hold Return         46.22%
  Max Drawdown              -25.15%
  Sharpe Ratio              -0.62
  Sortino Ratio             -0.86
  Calmar Ratio              -0.31
  Profit Factor             0.90
  Expectancy                -0.12%
  SQN                       -0.73
  # Trades                  92
  Win Rate                  26.09%
  Best Trade                10.21%
  Worst Trade               -6.17%
  Avg Trade                 -0.16%
  Exposure Time             20.25%
  Equity Final              84856.17$
  Equity Peak               113364.76$
  Avg Drawdown              -9.18%
  Max Drawdown Duration     453 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -7.87%
  Ann. Volatility           12.76%

--- QQQ ---
  Return                    -10.77%
  Buy & Hold Return         42.67%
  Max Drawdown              -16.76%
  Sharpe Ratio              -0.70
  Sortino Ratio             -0.81
  Calmar Ratio              -0.33
  Profit Factor             0.72
  Expectancy                -0.18%
  SQN                       -0.86
  # Trades                  60
  Win Rate                  26.67%
  Best Trade                5.60%
  Worst Trade               -6.84%
  Avg Trade                 -0.19%
  Exposure Time             22.60%
  Equity Final              89229.96$
  Equity Peak               107200.57$
  Avg Drawdown              -3.34%
  Max Drawdown Duration     483 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -5.58%
  Ann. Volatility           7.95%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — inside-bar-strategy-with-sltp
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        # Current bar values
        high_current = self.data.High[-1]
        low_current = self.data.Low[-1]
        open_current = self.data.Open[-1]
        close_current = self.data.Close[-1]
        
        # Previous bar values
        high_prev = self.data.High[-2]
        low_prev = self.data.Low[-2]
        
        # Inside Bar condition
        is_inside_bar = high_current < high_prev and low_current > low_prev
        
        # Calculate candle range and middle
        candle_range = high_current - low_current
        candle_middle = (high_current + low_current) / 2
        
        # LONG ENTRY
        if is_inside_bar and close_current > open_current:
            long_stop_loss = low_current
            long_take_profit = high_current + (candle_range * 2)
            
            self.buy(sl=long_stop_loss, tp=long_take_profit)
        
        # SHORT ENTRY
        elif is_inside_bar and close_current < open_current:
            short_stop_loss = high_current
            short_take_profit = low_current - (candle_range * 2)
            
            self.sell(sl=short_stop_loss, tp=short_take_profit)


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()