"""
DS-TV Backtest Results: orion-hybrid-volatility-breakout-strategy
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — orion-hybrid-volatility-breakout-strategy
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookback = 15
    atr_mult = 2.5
    slope_thresh = 0.2
    cooldown_bars = 5
    max_box_life = 45
    use_ema = True
    ema_len = 150
    risk_per_trade = 0.8
    reward_ratio = 1.9
    use_gold = True
    std_len = 20
    squeeze_th = 0.6

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema_val = self.I(pta.ema, close, length=self.ema_len)
        self.atr_val = self.I(pta.atr, high, low, close, length=14)
        self.std_dev = self.I(pta.stdev, close, length=self.std_len)
        
        self.highest_high = self.I(lambda: high.rolling(window=self.lookback).max())
        self.lowest_low = self.I(lambda: low.rolling(window=self.lookback).min())
        
        self.in_trade = False
        self.trade_entry = None
        self.trade_dir = 0
        self.trade_sl = None
        self.trade_tp = None
        self.trade_qty = 0
        self.last_exit_bar = -999
        self.box_ready = False
        self.box_start_bar = 0
        self.z_high = None
        self.z_low = None

    def next(self):
        if len(self) < max(self.lookback, self.ema_len, self.std_len):
            return
        
        close_val = self.data.Close[-1]
        high_val = self.data.High[-1]
        low_val = self.data.Low[-1]
        bar_idx = len(self) - 1
        
        ema_val = self.ema_val[-1]
        atr_val = self.atr_val[-1]
        std_dev = self.std_dev[-1]
        highest = self.highest_high[-1]
        lowest = self.lowest_low[-1]
        
        if pd.isna(ema_val) or pd.isna(atr_val) or pd.isna(std_dev) or pd.isna(highest) or pd.isna(lowest):
            return
        
        trend_long = close_val > ema_val if self.use_ema else True
        trend_short = close_val < ema_val if self.use_ema else True
        
        box_h = highest - lowest
        is_squeeze = std_dev < (atr_val * self.squeeze_th)
        is_tight = box_h < (atr_val * self.atr_mult)
        
        if len(self.data.Close) >= self.lookback:
            close_series = pd.Series(self.data.Close[-self.lookback:])
            linreg_curr = np.polyfit(np.arange(len(close_series)), close_series.values, 1)[0]
            if len(self.data.Close) >= self.lookback + 1:
                close_series_prev = pd.Series(self.data.Close[-self.lookback-1:-1])
                linreg_prev = np.polyfit(np.arange(len(close_series_prev)), close_series_prev.values, 1)[0]
                slope = abs((linreg_curr - linreg_prev) / close_val) * 1000
            else:
                slope = 0
        else:
            slope = 0
        
        is_flat = slope < self.slope_thresh
        is_resting = (bar_idx - self.last_exit_bar) < self.cooldown_bars
        
        if self.in_trade:
            sl_hit = False
            tp_hit = False
            
            if self.trade_dir == 1:
                tp_hit = high_val >= self.trade_tp
                sl_hit = low_val <= self.trade_sl
            elif self.trade_dir == -1:
                tp_hit = low_val <= self.trade_tp
                sl_hit = high_val >= self.trade_sl
            
            if tp_hit or sl_hit:
                self.in_trade = False
                self.last_exit_bar = bar_idx
                if self.trade_dir == 1:
                    self.sell()
                else:
                    self.buy()
        
        if not self.in_trade:
            if self.box_ready:
                box_age = bar_idx - self.box_start_bar
                
                if box_age > self.max_box_life:
                    self.box_ready = False
                else:
                    still_in_range = close_val <= self.z_high and close_val >= self.z_low
                    
                    if still_in_range:
                        pass
                    else:
                        break_up = close_val > self.z_high
                        break_down = close_val < self.z_low
                        
                        if break_up and not trend_long:
                            break_up = False
                        if break_down and not trend_short:
                            break_down = False
                        
                        if break_up or break_down:
                            self.box_ready = False
                            self.last_exit_bar = bar_idx
                            self.in_trade = True
                            
                            self.trade_entry = close_val
                            
                            if break_up:
                                self.trade_dir = 1
                                self.trade_sl = self.z_low
                                risk = abs(self.trade_entry - self.trade_sl)
                                self.trade_tp = self.trade_entry + (risk * self.reward_ratio)
                                self.trade_qty = (self.equity * self.risk_per_trade / 100) / risk if risk > 0 else 1
                                self.buy()
                            
                            elif break_down:
                                self.trade_dir = -1
                                self.trade_sl = self.z_high
                                risk = abs(self.trade_sl - self.trade_entry)
                                self.trade_tp = self.trade_entry - (risk * self.reward_ratio)
                                self.trade_qty = (self.equity * self.risk_per_trade / 100) / risk if risk > 0 else 1
                                self.sell()
                        else:
                            self.box_ready = False
            
            elif is_tight and is_flat and not is_resting:
                self.box_ready = True
                self.box_start_bar = bar_idx
                self.z_high = highest
                self.z_low = lowest