"""
DS-TV Backtest Results: paradigm-shift-delivery-state
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — paradigm-shift-delivery-state
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        # Calculate bond volatility (using close price as proxy)
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Bond volatility standard deviation over 20 periods
        self.bond_vol = self.I(lambda: close.rolling(window=20).std())
        
        # Percent rank of bond volatility over 252 periods
        self.move_proxy = self.I(lambda: close.rolling(window=252).apply(
            lambda x: (x[-1] > x).sum() / len(x) * 100 if len(x) > 0 else 50
        ))
        
        # FVG tracking
        self.last_fvg_high = np.nan
        self.last_fvg_low = np.nan
        self.was_fvg_filled = False
        
        # Market state
        self.market_state = "SYMMETRICAL"

    def next(self):
        # Detect Bullish FVG: low[1] > high[3]
        if len(self.data) >= 4:
            if self.data.Low[-2] > self.data.High[-4]:
                self.last_fvg_high = self.data.High[-4]
                self.last_fvg_low = self.data.Low[-2]
        
        # Check if FVG was filled
        if not np.isnan(self.last_fvg_low):
            if self.data.Low[-1] <= self.last_fvg_low:
                self.was_fvg_filled = True
        
        # Determine market state
        move_proxy_val = self.move_proxy[-1] if len(self.move_proxy) > 0 else 50
        
        if move_proxy_val > 90 and self.data.Close[-1] > self.data.Open[-1]:
            self.market_state = "OPAQUE (PARADIGM SHIFT)"
            if not self.position:
                self.buy()
        elif move_proxy_val > 70 or not self.was_fvg_filled:
            self.market_state = "SATURATED"
            if self.position:
                self.sell()
        else:
            self.market_state = "SYMMETRICAL"
            if self.position and move_proxy_val < 30:
                self.sell()