"""
DS-TV Backtest Results: pro-grid-dual-asset-momentum-visualizer
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — pro-grid-dual-asset-momentum-visualizer
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsi_len = 14
    vol_len = 14
    lookback = 200
    use_stoch = False
    stoch_k = 14
    stoch_d = 3
    velocity_len = 5
    div_lookback = 5
    corr_len = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        if self.use_stoch:
            stoch_result = pta.stoch(high, low, close, k=self.stoch_k, d=self.stoch_d)
            self.momentum = self.I(lambda: stoch_result['STOCHk_%d_%d_%d' % (self.stoch_k, self.stoch_d, self.stoch_d)] if stoch_result is not None else pd.Series(50, index=close.index))
        else:
            rsi_result = pta.rsi(close, length=self.rsi_len)
            self.momentum = self.I(lambda: rsi_result if rsi_result is not None else pd.Series(50, index=close.index))

        atr_result = pta.atr(high, low, close, length=self.vol_len)
        self.atr = self.I(lambda: atr_result if atr_result is not None else pd.Series(0.01, index=close.index))

        highest_atr = self.I(lambda: self.atr.rolling(self.lookback).max())
        lowest_atr = self.I(lambda: self.atr.rolling(self.lookback).min())

        self.norm_vol = self.I(lambda: self._normalize_vol(self.atr, highest_atr, lowest_atr))

    def _normalize_vol(self, atr, highest, lowest):
        result = pd.Series(index=atr.index, dtype=float)
        for i in range(len(atr)):
            if i < len(atr) and i < len(highest) and i < len(lowest):
                if highest.iloc[i] - lowest.iloc[i] != 0:
                    result.iloc[i] = (atr.iloc[i] - lowest.iloc[i]) / (highest.iloc[i] - lowest.iloc[i]) * 100
                else:
                    result.iloc[i] = 0
        return result

    def _get_zone(self, momentum_val, vol_val):
        if momentum_val >= 50 and vol_val >= 50:
            return "Strong Bull"
        elif momentum_val < 50 and vol_val >= 50:
            return "Vol Spike"
        elif momentum_val < 50 and vol_val < 50:
            return "Weak Bear"
        else:
            return "Low Vol"

    def next(self):
        if len(self) < self.rsi_len + 5:
            return

        momentum_current = self.momentum[-1]
        vol_current = self.norm_vol[-1]
        momentum_prev = self.momentum[-2] if len(self) > 1 else momentum_current

        zone = self._get_zone(momentum_current, vol_current)

        if momentum_current < 30 and momentum_prev <= momentum_current:
            if not self.position:
                self.buy()
        elif momentum_current > 70 and momentum_prev >= momentum_current:
            if self.position:
                self.sell()
        elif zone == "Weak Bear" and vol_current < 40:
            if self.position:
                self.sell()
        elif zone == "Strong Bull" and vol_current > 60:
            if not self.position:
                self.buy()