"""
DS-TV Backtest Results: radiant-mean-reversion-channels-pineify
============================================================

--- SPY ---
  Return                    -38.43%
  Buy & Hold Return         39.05%
  Max Drawdown              -38.57%
  Sharpe Ratio              -1.74
  Sortino Ratio             -1.88
  Calmar Ratio              -0.56
  Profit Factor             0.23
  Expectancy                -3.09%
  SQN                       -1.69
  # Trades                  14
  Win Rate                  28.57%
  Best Trade                6.78%
  Worst Trade               -22.42%
  Avg Trade                 -3.34%
  Exposure Time             87.00%
  Equity Final              61569.40$
  Equity Peak               100000.00$
  Avg Drawdown              -38.57%
  Max Drawdown Duration     675 days 00:00:00
  Max Trade Duration        123 days 00:00:00
  Avg Trade Duration        46 days 00:00:00
  Ann. Return               -21.69%
  Ann. Volatility           12.46%

--- BTC ---
  Return                    -23.09%
  Buy & Hold Return         2.22%
  Max Drawdown              -40.21%
  Sharpe Ratio              -0.62
  Sortino Ratio             -0.71
  Calmar Ratio              -0.31
  Profit Factor             0.39
  Expectancy                -3.76%
  SQN                       -0.80
  # Trades                  7
  Win Rate                  57.14%
  Best Trade                7.70%
  Worst Trade               -24.53%
  Avg Trade                 -4.45%
  Exposure Time             32.83%
  Equity Final              76907.70$
  Equity Peak               116667.74$
  Avg Drawdown              -8.41%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        113 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               -12.29%
  Ann. Volatility           19.85%

--- QQQ ---
  Return                    -42.64%
  Buy & Hold Return         43.14%
  Max Drawdown              -44.88%
  Sharpe Ratio              -1.61
  Sortino Ratio             -1.70
  Calmar Ratio              -0.54
  Profit Factor             0.30
  Expectancy                -3.27%
  SQN                       -1.44
  # Trades                  15
  Win Rate                  46.67%
  Best Trade                7.11%
  Worst Trade               -29.69%
  Avg Trade                 -3.71%
  Exposure Time             84.40%
  Equity Final              57364.27$
  Equity Peak               100959.31$
  Avg Drawdown              -22.93%
  Max Drawdown Duration     651 days 00:00:00
  Max Trade Duration        119 days 00:00:00
  Avg Trade Duration        41 days 00:00:00
  Ann. Return               -24.43%
  Ann. Volatility           15.14%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — radiant-mean-reversion-channels-pineify
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 21
    mult = 2.0
    smooth = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # HMA for the mean
        self.mean = self.I(pta.hma, close, length=self.len)
        
        # ATR for volatility
        self.volatility = self.I(pta.atr, high, low, close, length=self.len)
        
        # Calculate bands
        def calc_upper_band():
            if self.mean[-1] is None or self.volatility[-1] is None:
                return 0
            return self.mean[-1] + self.volatility[-1] * self.mult
        
        def calc_lower_band():
            if self.mean[-1] is None or self.volatility[-1] is None:
                return 0
            return self.mean[-1] - self.volatility[-1] * self.mult
        
        # Calculate raw oscillator
        def calc_raw_osc():
            if len(self.data) < self.len:
                return 50
            mean_val = self.mean[-1]
            vol_val = self.volatility[-1]
            src_val = close.iloc[-1]
            
            if mean_val is None or vol_val is None:
                return 50
            
            upper = mean_val + vol_val * self.mult
            lower = mean_val - vol_val * self.mult
            
            if upper == lower:
                return 50
            
            raw = (src_val - lower) / (upper - lower) * 100
            return np.clip(raw, 0, 100)
        
        # Use a manual oscillator calculation
        def calc_osc_series():
            osc_values = []
            for i in range(len(close)):
                if i < self.len:
                    osc_values.append(50)
                    continue
                
                mean_val = self.mean[i] if i < len(self.mean) else None
                vol_val = self.volatility[i] if i < len(self.volatility) else None
                src_val = close.iloc[i]
                
                if mean_val is None or vol_val is None or pd.isna(mean_val) or pd.isna(vol_val):
                    osc_values.append(50)
                    continue
                
                upper = mean_val + vol_val * self.mult
                lower = mean_val - vol_val * self.mult
                
                if upper == lower:
                    osc_values.append(50)
                else:
                    raw = (src_val - lower) / (upper - lower) * 100
                    osc_values.append(np.clip(raw, 0, 100))
            
            return pd.Series(osc_values, index=close.index)
        
        # Calculate raw oscillator series
        raw_osc_series = calc_osc_series()
        
        # Apply WMA smoothing to the oscillator
        self.osc = self.I(pta.wma, raw_osc_series, length=self.smooth)

    def next(self):
        if self.osc[-1] is None or pd.isna(self.osc[-1]):
            return
        
        # Buy signal: crossover above 20 (leaving oversold)
        if len(self.osc) > 1:
            if self.osc[-2] <= 20 and self.osc[-1] > 20:
                if not self.position:
                    self.buy()
        
        # Sell signal: crossunder below 80 (leaving overbought)
        if len(self.osc) > 1:
            if self.osc[-2] >= 80 and self.osc[-1] < 80:
                if self.position:
                    self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()