"""
DS-TV Backtest Results: rsi-divergence-v6
============================================================

--- SPY ---
  Return                    -19.47%
  Buy & Hold Return         43.93%
  Max Drawdown              -33.63%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.84
  Calmar Ratio              -0.31
  Profit Factor             13.83
  Expectancy                5.03%
  SQN                       0.86
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                10.84%
  Worst Trade               -0.78%
  Avg Trade                 4.87%
  Exposure Time             19.20%
  Equity Final              80534.77$
  Equity Peak               120886.04$
  Avg Drawdown              -4.51%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        135 days 00:00:00
  Avg Trade Duration        69 days 00:00:00
  Ann. Return               -10.34%
  Ann. Volatility           15.90%

--- BTC ---
  Return                    -36.41%
  Buy & Hold Return         44.64%
  Max Drawdown              -39.92%
  Sharpe Ratio              -0.96
  Sortino Ratio             -1.00
  Calmar Ratio              -0.51
  Profit Factor             0.00
  Expectancy                -19.74%
  SQN                       -5.15
  # Trades                  3
  Win Rate                  0.00%
  Best Trade                -12.30%
  Worst Trade               -24.58%
  Avg Trade                 -19.91%
  Exposure Time             36.53%
  Equity Final              63590.64$
  Equity Peak               100500.67$
  Avg Drawdown              -39.92%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        247 days 00:00:00
  Avg Trade Duration        89 days 00:00:00
  Ann. Return               -20.23%
  Ann. Volatility           21.00%

--- QQQ ---
  Return                    -20.44%
  Buy & Hold Return         44.93%
  Max Drawdown              -39.14%
  Sharpe Ratio              -0.54
  Sortino Ratio             -0.71
  Calmar Ratio              -0.28
  Profit Factor             3.73
  Expectancy                2.48%
  SQN                       0.66
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                9.32%
  Worst Trade               -2.72%
  Avg Trade                 2.35%
  Exposure Time             18.80%
  Equity Final              79560.27$
  Equity Peak               123303.80$
  Avg Drawdown              -5.49%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        112 days 00:00:00
  Avg Trade Duration        45 days 00:00:00
  Ann. Return               -10.88%
  Ann. Volatility           20.26%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-divergence-v6
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsiLen = 14
    lvlLow = 20
    lvlMid = 50
    lvlHigh = 80

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate RSI for close, high, and low
        self.rsiClose = self.I(pta.rsi, close, length=self.rsiLen)
        self.rsiHigh = self.I(pta.rsi, high, length=self.rsiLen)
        self.rsiLow = self.I(pta.rsi, low, length=self.rsiLen)
        
        # Band that always contains RSI Close
        self.rsiUpper = self.I(
            lambda: pd.Series(
                np.maximum(self.rsiHigh, np.maximum(self.rsiLow, self.rsiClose)),
                index=close.index
            )
        )
        self.rsiLower = self.I(
            lambda: pd.Series(
                np.minimum(self.rsiHigh, np.minimum(self.rsiLow, self.rsiClose)),
                index=close.index
            )
        )

    def next(self):
        # Buy when RSI Close crosses above the low level (oversold condition)
        if crossover(self.rsiClose, self.lvlLow):
            self.buy()
        
        # Sell when RSI Close crosses below the high level (overbought condition)
        elif crossover(self.lvlHigh, self.rsiClose):
            self.sell()