"""
DS-TV Backtest Results: stock-expansion-pullback-screener-v6
============================================================

--- SPY ---
  ERROR: Indicator "vwap" error. See traceback above.

--- BTC ---
  ERROR: Indicator "vwap" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "vwap" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — stock-expansion-pullback-screener-v6
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 14
    atrMult = 1.3
    rsiLen = 14
    emaFast = 20
    emaSlow = 50
    maxBars = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        self.ema20 = self.I(pta.ema, close, length=self.emaFast)
        self.ema50 = self.I(pta.ema, close, length=self.emaSlow)
        self.vwap = self.I(pta.vwap, close, volume=volume)
        
        self.candleRange = self.I(lambda: high - low)
        self.candleBody = self.I(lambda: np.abs(open_ - close))
        
        self.bullExpIndex = -np.inf
        self.bearExpIndex = -np.inf
        
    def next(self):
        if len(self.data) < max(self.atrLen, self.rsiLen, self.emaFast, self.emaSlow) + 1:
            return
        
        atr_val = self.atr[-1]
        rsi_val = self.rsi[-1]
        ema20_val = self.ema20[-1]
        ema50_val = self.ema50[-1]
        vwap_val = self.vwap[-1]
        close_val = self.data.Close[-1]
        high_val = self.data.High[-1]
        low_val = self.data.Low[-1]
        
        if np.isnan(atr_val) or np.isnan(rsi_val) or np.isnan(ema20_val) or np.isnan(ema50_val) or np.isnan(vwap_val):
            return
        
        candleRange_val = self.candleRange[-1]
        candleBody_val = self.candleBody[-1]
        
        isExpansion = (
            candleRange_val > atr_val * self.atrMult and
            candleBody_val > candleRange_val * 0.6
        )
        
        bullMomentum = rsi_val > 55
        bearMomentum = rsi_val < 45
        
        if isExpansion and bullMomentum:
            self.bullExpIndex = len(self.data) - 1
        
        if isExpansion and bearMomentum:
            self.bearExpIndex = len(self.data) - 1
        
        bullActive = (len(self.data) - 1 - self.bullExpIndex) <= self.maxBars
        bearActive = (len(self.data) - 1 - self.bearExpIndex) <= self.maxBars
        
        pullbackBull = (
            (close_val <= ema20_val and close_val >= ema50_val) or
            (abs(close_val - vwap_val) / close_val < 0.003)
        )
        pullbackBear = (
            (close_val >= ema20_val and close_val <= ema50_val) or
            (abs(close_val - vwap_val) / close_val < 0.003)
        )
        
        bullSignal = bullActive and bullMomentum and pullbackBull
        bearSignal = bearActive and bearMomentum and pullbackBear
        
        if bullSignal:
            if not self.position:
                self.buy()
        elif bearSignal:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()