// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © HandlesHandled

//@version=5
indicator("270min Cycles"
  , overlay          = true
  , max_bars_back    = 500
  , max_lines_count  = 500
  , max_boxes_count  = 500
  , max_labels_count = 500)
//------------------------------------------------------------------------------
//Settings
//-----------------------------------------------------------------------------{

///Session 270
show_ses270 = input(false, '', inline='ses270', group='Session 270')
ses270_txt = input('extra', '', inline='ses270', group='Session 270')
ses270_ses = input.session('1600-1630', '', inline='ses270', group='Session 270')
ses270_css = input.color(#0340f8, '', inline='ses270', group='Session 270')
ses270_range = input(true, 'Range', inline='ses270_overlays', group='Session 270')

///Session 271
show_ses271 = input(true, '', inline='ses271', group='Session 271')
ses271_txt = input('OG', '', inline='ses271', group='Session 271')
ses271_ses = input.session('1600-1700', '', inline='ses271', group='Session 271')
ses271_css = input.color(#ffffff, '', inline='ses271', group='Session 271')
ses271_range = input(true, 'Range', inline='ses271_overlays', group='Session 271')

///Session 272
show_ses272 = input(true, '', inline='ses272', group='Session 272')
ses272_txt = input('Asia', '', inline='ses272', group='Session 272')
ses272_ses = input.session('1800-0230', '', inline='ses272', group='Session 272')
ses272_css = input.color(#808080, '', inline='ses272', group='Session 272')
ses272_range = input(true, 'Range', inline='ses272_overlays', group='Session 272')

///Session 273
show_ses273 = input(true, '', inline='ses273', group='Session 273')
ses273_txt = input('270 A', '', inline='ses273', group='Session 273')
ses273_ses = input.session('0230-0700', '', inline='ses273', group='Session 273')
ses273_css = input.color(#5b9cf6, '', inline='ses273', group='Session 273')
ses273_range = input(true, 'Range', inline='ses273_overlays', group='Session 273')

///Session 274
show_ses274 = input(true, '', inline='ses274', group='Session 274')
ses274_txt = input('270 M', '', inline='ses274', group='Session 274')
ses274_ses = input.session('0700-1130', '', inline='ses274', group='Session 274')
ses274_css = input.color(#f23645, '', inline='ses274', group='Session 274')
ses274_range = input(true, 'Range', inline='ses274_overlays', group='Session 274')

///Session 275
show_ses275 = input(true, '', inline='ses275', group='Session 275')
ses275_txt = input('270 D', '', inline='ses275', group='Session 275')
ses275_ses = input.session('1130-1600', '', inline='ses275', group='Session 275')
ses275_css = input.color(#4caf50, '', inline='ses275', group='Session 275')
ses275_range = input(true, 'Range', inline='ses275_overlays', group='Session 275')


//Timezones
tz_incr = input.int(-5, 'UTC (+/-)'
  , group = 'Timezone')

use_exchange = input(false, 'Use Exchange Timezone'
  , group = 'Timezone')

//Ranges Options
bg_transp = input.float(100, 'Range Area Transparency'
  , group = 'Ranges Settings')

show_outline = input(true, 'Range Outline'
  , group = 'Ranges Settings')

show_txt = input(true, 'Range Label'
  , group = 'Ranges Settings')


//-----------------------------------------------------------------------------}
//Functions
//-----------------------------------------------------------------------------{
n = bar_index

//Set session range
get_range(session, session_name, session_css)=>
    var t = 0 
    var max = high
    var min = low
    var box bx = na
    var label lbl = na 
    
    if session > session[1]
        t := time
        max := high
        min := low

        bx := box.new(n, max, n, min
          , bgcolor = color.new(session_css, bg_transp)
          , border_color = show_outline ? session_css : na
          , border_style = line.style_dashed)

        if show_txt
            lbl := label.new(t, max, session_name
              , xloc = xloc.bar_time
              , textcolor = session_css
              , style = label.style_label_down
              , color = color.new(color.white, 100)
              , size = size.small)

    if session and session == session[1]
        max := math.max(high, max)
        min := math.min(low, min)

        box.set_top(bx, max)
        box.set_rightbottom(bx, n + 1, min)

        if show_txt
            label.set_xy(lbl, int(math.avg(t, time)), max)

//-----------------------------------------------------------------------------}
//Sessions
//-----------------------------------------------------------------------------{
tf = timeframe.period

var tz = use_exchange ? syminfo.timezone :
  str.format('UTC{0}{1}', tz_incr >= 0 ? '+' : '-', math.abs(tz_incr))

is_ses270 = math.sign(nz(time(tf, ses270_ses, tz)))
is_ses271 = math.sign(nz(time(tf, ses271_ses, tz)))
is_ses272 = math.sign(nz(time(tf, ses272_ses, tz)))
is_ses273 = math.sign(nz(time(tf, ses273_ses, tz)))
is_ses274 = math.sign(nz(time(tf, ses274_ses, tz)))
is_ses275 = math.sign(nz(time(tf, ses275_ses, tz)))

//-----------------------------------------------------------------------------}
//Overlays
//-----------------------------------------------------------------------------{
//Ranges
if show_ses270 and ses270_range
    get_range(is_ses270, ses270_txt, ses270_css)
    
if show_ses271 and ses271_range
    get_range(is_ses271, ses271_txt, ses271_css)

if show_ses272 and ses272_range
    get_range(is_ses272, ses272_txt, ses272_css)

if show_ses273 and ses273_range
    get_range(is_ses273, ses273_txt, ses273_css)

if show_ses274 and ses274_range
    get_range(is_ses274, ses274_txt, ses274_css)

if show_ses275 and ses275_range
    get_range(is_ses275, ses275_txt, ses275_css)
