// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © traderharikrishna

//@version=6
indicator("Hybrid Volume Spread Analysis", "HVSA")

v = volume / volume[1]
//plot(v)

lenth = input.int(10, 'MA Length')
malenth = input.int(20, 'EMA Length')

mac = ta.ema(close, lenth)
vmac = mac * v

mao = ta.ema(open, lenth)
vmao = mao * v

vd = vmac - vmao

plot(vd, color = vd < 0 ? color.red : color.green, style = plot.style_columns)

vdma = ta.ema(vd, malenth)

// Semi-transparent black area (background)
plot(vdma, color = color.new(color.rgb(0, 0, 0), 52), linewidth = 2, style = plot.style_area)

// Conditional semi-transparent green/red area (overlay)
plot(vdma, color = vdma > 0 ? color.new(color.rgb(23, 235, 4), 81) : color.new(color.rgb(133, 4, 4), 75), linewidth = 2, style = plot.style_area)

hline(0)

dn = ta.crossunder(vd, 0)
up = ta.crossover(vd, 0)
uptrend = ta.crossover(vdma, 0)
dntrend = ta.crossunder(vdma, 0)

alertcondition(up, 'Up Signal')
alertcondition(dn, 'Down Signal')
alertcondition(up or dn, 'Up/Down Signal')
alertcondition(uptrend, 'Up Trend')
alertcondition(dntrend, 'Down Trend')
alertcondition(uptrend or dntrend, 'Trend Changed')
