// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stanislavbenov04
//Last Updated: 22/02/2026 <-- Irish Date Format
//@version=5
strategy("Multi-Supertrend Moving Average", shorttitle = "MSMA" ,overlay=true, initial_capital = 10000, default_qty_value = 100, default_qty_type = strategy.percent_of_equity, commission_value = 0.025)

// Moving Averages
fastVWMA = ta.vwma(close, 35)
fastALMA = ta.alma(close, 140, 0.6, 6)
atrPeriod = input.int(14, "ATR Period")
factor = input.float(3.0, "Factor")
[supertrend, direction] = ta.supertrend(factor, atrPeriod)

// Long and Exit conditions
goLongCondition = (direction < 0) and ta.crossover(fastVWMA, fastALMA)
exitCondition = (direction > 0) and ta.crossunder(fastVWMA, fastALMA)

// Bullish Bearish MA's
maBullish = fastVWMA > fastALMA
maBearish = fastVWMA < fastALMA

// Trend color
trendColor = (direction < 0 and maBullish) ? color.green :
     (direction < 0) ? color.new(color.green, 70) :
     (direction > 0 and maBearish) ? color.red :
     (direction > 0) ? color.new(color.red, 70) : color.gray

// InTrade Not InTrade
inTrade = strategy.position_size > 0
NotInTrade = strategy.position_size <= 0

// If Conditions 
var float stoploss = na

if (goLongCondition and NotInTrade)
    strategy.entry("Long", strategy.long)

strategy.exit("SL", "Long", stop = stoploss)

if (inTrade and exitCondition)
    strategy.close("Long", comment = "Exit Signal")

// Visuals
plot(supertrend, "Muilti-Conditional Supertrend", color = trendColor, linewidth = 3)
bgcolor(inTrade ? color.new(color.green, 85) : color.new(color.red, 85))
