"""
DS-TV Backtest Results: 7m-multi-factor-momentum-scoreboard
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 7m-multi-factor-momentum-scoreboard
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # 7M System Parameters
    chg_min = 1.0
    flt_max = 25000.0
    v5_min = 1000000
    rvat_m = 1.2
    rd_m = 1.1
    m7_pass_thr = 7

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate indicators
        self.vwap = self.I(lambda: pta.vwap(high, low, close) or pd.Series(0, index=close.index))
        self.vwma = self.I(lambda: pta.vwma(close, volume, length=20) or pd.Series(0, index=close.index))
        
        # MACD
        macd_result = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9))
        if isinstance(macd_result, pd.DataFrame):
            self.macd_line = macd_result.iloc[:, 0]
            self.macd_signal = macd_result.iloc[:, 1]
        else:
            self.macd_line = self.I(lambda: pd.Series(0, index=close.index))
            self.macd_signal = self.I(lambda: pd.Series(0, index=close.index))
        
        self.rsi = self.I(lambda: pta.rsi(close, length=14) or pd.Series(50, index=close.index))
        
        # Calculate price change from session open
        self.session_open = self.I(lambda: pd.Series([self.data.Open[0]] * len(close)))
        
        # ADX for trend confirmation
        self.adx = self.I(lambda: pta.adx(high, low, close, length=14) or pd.Series(0, index=close.index))

    def next(self):
        # Get current values
        close_price = self.data.Close[-1]
        session_open = self.data.Open[0]
        
        # Calculate percentage change from session open
        if session_open != 0:
            pct_change = ((close_price - session_open) / session_open) * 100
        else:
            pct_change = 0
        
        rsi_val = self.rsi[-1]
        vwap_val = self.vwap[-1]
        vwma_val = self.vwma[-1]
        macd_line = self.macd_line[-1]
        macd_signal = self.macd_signal[-1]
        adx_val = self.adx[-1] if not np.isnan(self.adx[-1]) else 0
        
        # Build 7M Score
        m7_score = 0
        
        # 1. Price change >= min threshold
        if pct_change >= self.chg_min:
            m7_score += 1
        
        # 2. Float check (simplified - assume passes if we have data)
        m7_score += 1
        
        # 3. 5m Volume check (simplified - assume passes)
        m7_score += 1
        
        # 4. Relative Volume at Time (simplified - assume passes)
        m7_score += 1
        
        # 5. Daily Relative Volume (simplified - assume passes)
        m7_score += 1
        
        # 6. MACD bullish (line > signal)
        if macd_line > macd_signal:
            m7_score += 1
        
        # 7. Price above VWAP
        if close_price > vwap_val:
            m7_score += 1
        
        # 8. RSI in neutral zone (30-70)
        if 30 <= rsi_val <= 70:
            m7_score += 1
        
        # 9. Price above VWMA (trend support)
        if close_price > vwma_val:
            m7_score += 1
        
        # Trading logic: Buy when 7M passes threshold with bullish setup
        if m7_score >= self.m7_pass_thr:
            # Bullish confirmation: price above VWAP, MACD bullish, RSI not overbought
            if (close_price > vwap_val and 
                macd_line > macd_signal and 
                rsi_val < 70):
                if not self.position:
                    self.buy()
        
        # Sell on bearish reversal or 7M score drop
        if self.position:
            # Exit if price breaks below VWAP with MACD bearish cross
            if (close_price < vwma_val and 
                macd_line < macd_signal) or rsi_val > 80:
                self.position.close()
            # Exit if 7M score drops significantly
            elif m7_score < self.m7_pass_thr - 2:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()