"""
DS-TV Backtest Results: accumulation-ftd-bullsish-swingtrading
============================================================

--- SPY ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- BTC ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- QQQ ---
  ERROR: '_Indicator' object has no attribute 'iloc'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — accumulation-ftd-bullsish-swingtrading
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    useCase1 = True
    lenSma1 = 5
    useCase2 = True
    lenSma2 = 10
    minPct = 1.24
    volLen = 50

    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)

        self.sma1 = self.I(pta.sma, close, length=self.lenSma1)
        self.sma2 = self.I(pta.sma, close, length=self.lenSma2)
        self.volSma = self.I(pta.sma, volume, length=self.volLen)

        self.close = close
        self.volume = volume
        self.high = high
        self.low = low
        self.open = open_

        self.triggered = False

    def check_conditions(self, n, sma_series):
        if len(self.data) < n + 2:
            return False

        idx = len(self.data) - 1
        idx_n = idx - n
        idx_n_plus_1 = idx_n + 1

        if idx_n < 0 or idx_n_plus_1 >= len(self.data):
            return False

        close_current = self.close.iloc[idx]
        close_prev = self.close.iloc[idx - 1]
        price_change = (close_current - close_prev) / close_prev * 100 >= self.minPct

        vol_current = self.volume.iloc[idx]
        vol_prev = self.volume.iloc[idx - 1]
        volume_increased = vol_current > vol_prev

        vol_sma_current = self.volSma.iloc[idx]
        volume_above_sma = vol_current > vol_sma_current

        close_n = self.close.iloc[idx_n]
        sma_n = sma_series[idx_n]
        closed_below_sma_n = close_n < sma_n

        open_n = self.open.iloc[idx_n]
        low_n = self.low.iloc[idx_n]
        low_current = self.low.iloc[idx]
        bullish_day_n = close_n > open_n and low_n < low_current

        close_n_plus_1 = self.close.iloc[idx_n_plus_1]
        open_n_plus_1 = self.open.iloc[idx_n_plus_1]
        bearish_next_day = close_n_plus_1 < open_n_plus_1

        higher_lows_between = True
        if n == 3:
            higher_lows_between = self.low.iloc[idx - 2] > self.low.iloc[idx_n] and self.low.iloc[idx - 1] > self.low.iloc[idx_n]
        elif n == 4:
            higher_lows_between = (self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 5:
            higher_lows_between = (self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 6:
            higher_lows_between = (self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 7:
            higher_lows_between = (self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 8:
            higher_lows_between = (self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 9:
            higher_lows_between = (self.low.iloc[idx - 8] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 10:
            higher_lows_between = (self.low.iloc[idx - 9] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 8] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 11:
            higher_lows_between = (self.low.iloc[idx - 10] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 9] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 8] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 12:
            higher_lows_between = (self.low.iloc[idx - 11] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 10] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 9] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 8] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])
        elif n == 13:
            higher_lows_between = (self.low.iloc[idx - 12] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 11] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 10] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 9] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 8] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 7] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 6] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 5] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 4] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 3] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 2] > self.low.iloc[idx_n] and 
                                    self.low.iloc[idx - 1] > self.low.iloc[idx_n])

        return (price_change and volume_increased and volume_above_sma and 
                closed_below_sma_n and bullish_day_n and higher_lows_between and bearish_next_day)

    def cond(self, n):
        return ((self.useCase1 and self.check_conditions(n, self.sma1)) or 
                (self.useCase2 and self.check_conditions(n, self.sma2)))

    def next(self):
        if self.triggered:
            return

        for n in range(3, 14):
            if self.cond(n):
                self.buy()
                self.triggered = True
                break


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)