"""
DS-TV Backtest Results: aivance-opening-range-vol-factor
============================================================

--- SPY ---
  Return                    -19.62%
  Buy & Hold Return         41.94%
  Max Drawdown              -25.34%
  Sharpe Ratio              -1.14
  Sortino Ratio             -1.20
  Calmar Ratio              -0.41
  Profit Factor             0.69
  Expectancy                -0.17%
  SQN                       -1.49
  # Trades                  129
  Win Rate                  42.64%
  Best Trade                2.93%
  Worst Trade               -6.25%
  Avg Trade                 -0.17%
  Exposure Time             77.80%
  Equity Final              80381.51$
  Equity Peak               103366.80$
  Avg Drawdown              -5.29%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -10.42%
  Ann. Volatility           9.13%

--- BTC ---
  Return                    -20.30%
  Buy & Hold Return         46.22%
  Max Drawdown              -27.11%
  Sharpe Ratio              -0.56
  Sortino Ratio             -0.72
  Calmar Ratio              -0.40
  Profit Factor             0.69
  Expectancy                -0.48%
  SQN                       -1.05
  # Trades                  73
  Win Rate                  30.14%
  Best Trade                8.56%
  Worst Trade               -12.38%
  Avg Trade                 -0.54%
  Exposure Time             28.45%
  Equity Final              79702.72$
  Equity Peak               100000.00$
  Avg Drawdown              -27.11%
  Max Drawdown Duration     728 days 00:00:00
  Max Trade Duration        6 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -10.71%
  Ann. Volatility           19.26%

--- QQQ ---
  Return                    -22.55%
  Buy & Hold Return         42.67%
  Max Drawdown              -28.86%
  Sharpe Ratio              -1.01
  Sortino Ratio             -1.07
  Calmar Ratio              -0.42
  Profit Factor             0.73
  Expectancy                -0.19%
  SQN                       -1.33
  # Trades                  128
  Win Rate                  45.31%
  Best Trade                4.68%
  Worst Trade               -6.43%
  Avg Trade                 -0.21%
  Exposure Time             78.20%
  Equity Final              77446.73$
  Equity Peak               105686.61$
  Avg Drawdown              -7.22%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -12.09%
  Ann. Volatility           11.98%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — aivance-opening-range-vol-factor
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        close = self.data.Close[-1]
        open_price = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if len(self.data) < 2:
            return
        
        prev_close = self.data.Close[-2]
        prev_open = self.data.Open[-2]
        
        current_is_long = close >= open_price
        prev_is_long = prev_close >= prev_open
        
        if len(self.data) == 2:
            if current_is_long and not prev_is_long:
                self.buy()
            elif not current_is_long and prev_is_long:
                self.sell()
        else:
            if current_is_long and not prev_is_long and self.position:
                self.position.close()
            elif not current_is_long and prev_is_long and self.position:
                self.position.close()
            
            if not self.position:
                if current_is_long and not prev_is_long:
                    self.buy()
                elif not current_is_long and prev_is_long:
                    self.sell()