"""
DS-TV Backtest Results: btc-bar-volume-color
============================================================

--- SPY ---
  Return                    -33.54%
  Buy & Hold Return         43.93%
  Max Drawdown              -40.67%
  Sharpe Ratio              -1.57
  Sortino Ratio             -1.68
  Calmar Ratio              -0.46
  Profit Factor             0.55
  Expectancy                -0.35%
  SQN                       -1.69
  # Trades                  113
  Win Rate                  35.40%
  Best Trade                7.21%
  Worst Trade               -6.89%
  Avg Trade                 -0.36%
  Exposure Time             55.00%
  Equity Final              66456.81$
  Equity Peak               111787.06$
  Avg Drawdown              -10.45%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        24 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -18.61%
  Ann. Volatility           11.82%

--- BTC ---
  Return                    -22.90%
  Buy & Hold Return         44.64%
  Max Drawdown              -23.85%
  Sharpe Ratio              -1.50
  Sortino Ratio             -1.34
  Calmar Ratio              -0.51
  Profit Factor             0.00
  Expectancy                -7.87%
  SQN                       -2.46
  # Trades                  4
  Win Rate                  0.00%
  Best Trade                -0.83%
  Worst Trade               -14.74%
  Avg Trade                 -8.03%
  Exposure Time             2.46%
  Equity Final              77098.86$
  Equity Peak               100000.00$
  Avg Drawdown              -23.85%
  Max Drawdown Duration     469 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -12.18%
  Ann. Volatility           8.10%

--- QQQ ---
  Return                    -51.56%
  Buy & Hold Return         44.93%
  Max Drawdown              -52.97%
  Sharpe Ratio              -2.26
  Sortino Ratio             -2.08
  Calmar Ratio              -0.58
  Profit Factor             0.54
  Expectancy                -0.38%
  SQN                       -2.67
  # Trades                  178
  Win Rate                  34.83%
  Best Trade                10.81%
  Worst Trade               -7.20%
  Avg Trade                 -0.39%
  Exposure Time             75.40%
  Equity Final              48438.80$
  Equity Peak               100794.71$
  Avg Drawdown              -27.84%
  Max Drawdown Duration     546 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -30.60%
  Ann. Volatility           13.54%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — btc-bar-volume-color
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 100
    z_min = -1.65
    z_max = 3.0

    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        
        # Since we only have single instrument data in backtest, we simulate aggregated volume
        # using the available volume as a proxy for total spot + perp volume
        spot = volume
        perp = volume * 0.5
        
        # Calculate z-scores for spot and perp
        def calc_z_spot():
            spot_series = spot
            sma_spot = pta.sma(spot_series, length=self.length)
            stdev_spot = spot_series.rolling(window=self.length).std()
            z_spot = (spot_series - sma_spot) / stdev_spot
            return z_spot.fillna(0)
        
        def calc_z_perp():
            perp_series = perp
            sma_perp = pta.sma(perp_series, length=self.length)
            stdev_perp = perp_series.rolling(window=self.length).std()
            z_perp = (perp_series - sma_perp) / stdev_perp
            return z_perp.fillna(0)
        
        def calc_z_vol():
            z_spot = calc_z_spot()
            z_perp = calc_z_perp()
            return (z_spot + z_perp) / 2
        
        def calc_z_scaled():
            z_vol = calc_z_vol()
            z_raw = (z_vol - self.z_min) / (self.z_max - self.z_min)
            z_scaled = np.maximum(0.0, np.minimum(z_raw, 1.0))
            return z_scaled
        
        self.z_scaled = self.I(calc_z_scaled)
        
        # Store previous close for direction detection
        self.prev_close = self.I(lambda: close.shift(1))

    def next(self):
        # Get current z-scaled value
        z_current = self.z_scaled[-1]
        
        # Trading logic based on volume z-score
        # Buy when volume is exceptionally high (z_scaled > 0.7) and price is up
        # Sell when volume is exceptionally high (z_scaled > 0.7) and price is down
        
        if len(self.data) < 2:
            return
        
        current_close = self.data.Close[-1]
        prev_close = self.data.Close[-2]
        
        # High volume signal with upward price movement - buy
        if z_current > 0.7 and current_close > prev_close:
            if not self.position:
                self.buy()
        
        # High volume signal with downward price movement - sell
        elif z_current > 0.7 and current_close < prev_close:
            if self.position:
                self.sell()
        
        # Exit on normal volume conditions
        elif z_current < 0.3:
            if self.position:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()