"""
DS-TV Backtest Results: bullbear-volume-diagram
============================================================

--- SPY ---
  Return                    -23.95%
  Buy & Hold Return         41.94%
  Max Drawdown              -28.40%
  Sharpe Ratio              -1.12
  Sortino Ratio             -1.36
  Calmar Ratio              -0.45
  Profit Factor             0.17
  Expectancy                -2.31%
  SQN                       -2.37
  # Trades                  10
  Win Rate                  10.00%
  Best Trade                4.61%
  Worst Trade               -7.31%
  Avg Trade                 -2.35%
  Exposure Time             57.00%
  Equity Final              76050.95$
  Equity Peak               105969.78$
  Avg Drawdown              -14.38%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        105 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -12.89%
  Ann. Volatility           11.54%

--- BTC ---
  Return                    -25.54%
  Buy & Hold Return         46.22%
  Max Drawdown              -43.43%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.77
  Calmar Ratio              -0.32
  Profit Factor             0.58
  Expectancy                -3.37%
  SQN                       -0.69
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                23.23%
  Worst Trade               -42.76%
  Avg Trade                 -5.08%
  Exposure Time             41.86%
  Equity Final              74463.58$
  Equity Peak               121085.70$
  Avg Drawdown              -10.01%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        126 days 00:00:00
  Avg Trade Duration        31 days 00:00:00
  Ann. Return               -13.69%
  Ann. Volatility           21.12%

--- QQQ ---
  Return                    -34.35%
  Buy & Hold Return         42.67%
  Max Drawdown              -41.07%
  Sharpe Ratio              -1.09
  Sortino Ratio             -1.29
  Calmar Ratio              -0.47
  Profit Factor             0.25
  Expectancy                -3.83%
  SQN                       -1.25
  # Trades                  9
  Win Rate                  55.56%
  Best Trade                4.25%
  Worst Trade               -19.93%
  Avg Trade                 -4.26%
  Exposure Time             87.40%
  Equity Final              65647.90$
  Equity Peak               107775.81$
  Avg Drawdown              -7.98%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        293 days 00:00:00
  Avg Trade Duration        71 days 00:00:00
  Ann. Return               -19.11%
  Ann. Volatility           17.57%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bullbear-volume-diagram
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    numOfCandles = 20

    def init(self):
        self.bullish_volumes = []
        self.bearish_volumes = []
        self.bullish_ma_values = []
        self.bearish_ma_values = []

    def next(self):
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        volume = self.data.Volume[-1]

        is_up = close > open_

        if is_up:
            self.bullish_volumes.append(volume)
            if len(self.bullish_volumes) > self.numOfCandles:
                self.bullish_volumes.pop(0)
        else:
            self.bearish_volumes.append(volume)
            if len(self.bearish_volumes) > self.numOfCandles:
                self.bearish_volumes.pop(0)

        bullish_ma = (sum(self.bullish_volumes) / len(self.bullish_volumes)) if len(self.bullish_volumes) > 0 else 0
        bearish_ma = (sum(self.bearish_volumes) / len(self.bearish_volumes)) if len(self.bearish_volumes) > 0 else 0

        self.bullish_ma_values.append(bullish_ma)
        self.bearish_ma_values.append(bearish_ma)

        if len(self.bullish_ma_values) < 2 or len(self.bearish_ma_values) < 2:
            return

        prev_bullish_ma = self.bullish_ma_values[-2]
        prev_bearish_ma = self.bearish_ma_values[-2]

        if (self.bullish_ma_values[-1] > self.bearish_ma_values[-1] and
            prev_bullish_ma <= prev_bearish_ma and
            not self.position):
            self.buy()

        elif (self.bullish_ma_values[-1] <= self.bearish_ma_values[-1] and
              prev_bullish_ma > prev_bearish_ma and
              self.position):
            self.sell()