"""
DS-TV Backtest Results: dollar-normalized-volume-v2
============================================================

--- SPY ---
  Return                    -57.02%
  Buy & Hold Return         41.94%
  Max Drawdown              -57.24%
  Sharpe Ratio              -3.17
  Sortino Ratio             -2.67
  Calmar Ratio              -0.61
  Profit Factor             0.48
  Expectancy                -0.36%
  SQN                       -3.69
  # Trades                  224
  Win Rate                  33.93%
  Best Trade                10.91%
  Worst Trade               -6.20%
  Avg Trade                 -0.38%
  Exposure Time             99.60%
  Equity Final              42976.95$
  Equity Peak               100499.19$
  Avg Drawdown              -28.92%
  Max Drawdown Duration     720 days 00:00:00
  Max Trade Duration        8 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -34.66%
  Ann. Volatility           10.93%

--- BTC ---
  Return                    -27.24%
  Buy & Hold Return         46.22%
  Max Drawdown              -38.74%
  Sharpe Ratio              -0.61
  Sortino Ratio             -0.72
  Calmar Ratio              -0.38
  Profit Factor             0.77
  Expectancy                -0.38%
  SQN                       -0.83
  # Trades                  113
  Win Rate                  44.25%
  Best Trade                10.43%
  Worst Trade               -18.84%
  Avg Trade                 -0.47%
  Exposure Time             35.98%
  Equity Final              72757.64$
  Equity Peak               109457.05$
  Avg Drawdown              -13.56%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        6 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -14.68%
  Ann. Volatility           24.10%

--- QQQ ---
  Return                    -57.63%
  Buy & Hold Return         42.67%
  Max Drawdown              -59.40%
  Sharpe Ratio              -2.55
  Sortino Ratio             -2.20
  Calmar Ratio              -0.59
  Profit Factor             0.57
  Expectancy                -0.38%
  SQN                       -2.94
  # Trades                  215
  Win Rate                  34.42%
  Best Trade                10.66%
  Worst Trade               -7.20%
  Avg Trade                 -0.40%
  Exposure Time             99.60%
  Equity Final              42371.01$
  Equity Peak               102021.30$
  Avg Drawdown              -29.79%
  Max Drawdown Duration     719 days 00:00:00
  Max Trade Duration        11 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -35.13%
  Ann. Volatility           13.80%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — dollar-normalized-volume-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        
        # Dollar Normalized Volume = close * volume
        self.dnv = self.I(lambda: close * volume)
    
    def next(self):
        # Trading logic based on Dollar Normalized Volume
        # Buy when DNV is increasing (current > previous)
        # Sell when DNV is decreasing (current < previous)
        
        if len(self.dnv) < 2:
            return
        
        current_dnv = self.dnv[-1]
        previous_dnv = self.dnv[-2]
        
        if previous_dnv > 0:
            dnv_change = (current_dnv - previous_dnv) / previous_dnv
            
            # Buy signal: DNV increasing significantly
            if dnv_change > 0.05 and not self.position:
                self.buy()
            # Sell signal: DNV decreasing significantly
            elif dnv_change < -0.05 and self.position:
                self.sell()