"""
DS-TV Backtest Results: eduvest-ifa-vp-context-v30-neon-edition
============================================================

--- SPY ---
  Return                    -28.44%
  Buy & Hold Return         17.90%
  Max Drawdown              -32.53%
  Sharpe Ratio              -1.34
  Sortino Ratio             -1.53
  Calmar Ratio              -0.48
  Profit Factor             0.41
  Expectancy                -1.44%
  SQN                       -0.95
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                6.57%
  Worst Trade               -7.74%
  Avg Trade                 -1.53%
  Exposure Time             13.80%
  Equity Final              71558.33$
  Equity Peak               105715.41$
  Avg Drawdown              -10.64%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        38 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               -15.52%
  Ann. Volatility           11.62%

--- BTC ---
  Return                    -23.37%
  Buy & Hold Return         17.39%
  Max Drawdown              -54.42%
  Sharpe Ratio              -0.43
  Sortino Ratio             -0.56
  Calmar Ratio              -0.23
  Profit Factor             0.46
  Expectancy                -2.38%
  SQN                       -0.81
  # Trades                  11
  Win Rate                  45.45%
  Best Trade                13.10%
  Worst Trade               -29.88%
  Avg Trade                 -2.98%
  Exposure Time             49.38%
  Equity Final              76631.22$
  Equity Peak               136166.31$
  Avg Drawdown              -9.18%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        189 days 00:00:00
  Avg Trade Duration        33 days 00:00:00
  Ann. Return               -12.44%
  Ann. Volatility           28.65%

--- QQQ ---
  Return                    -36.96%
  Buy & Hold Return         22.08%
  Max Drawdown              -44.82%
  Sharpe Ratio              -1.21
  Sortino Ratio             -1.36
  Calmar Ratio              -0.46
  Profit Factor             0.80
  Expectancy                -0.30%
  SQN                       -0.27
  # Trades                  8
  Win Rate                  62.50%
  Best Trade                5.54%
  Worst Trade               -7.02%
  Avg Trade                 -0.36%
  Exposure Time             13.40%
  Equity Final              63043.97$
  Equity Peak               106290.24$
  Avg Drawdown              -11.99%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        49 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               -20.75%
  Ann. Volatility           17.12%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — eduvest-ifa-vp-context-v30-neon-edition
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # SMA parameters
    sma20_len = 20
    sma50_len = 50
    sma200_len = 200
    
    # Volume Profile parameters
    vp_lookback = 100
    vp_rows = 24
    va_percent = 70
    
    # ATR parameter
    atr_len = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate SMAs
        self.sma20 = self.I(pta.sma, close, length=self.sma20_len)
        self.sma50 = self.I(pta.sma, close, length=self.sma50_len)
        self.sma200 = self.I(pta.sma, close, length=self.sma200_len)
        
        # Calculate ATR
        self.atr14 = self.I(pta.atr, high, low, close, length=self.atr_len)
        
        # Volume Profile: highest and lowest over lookback
        self.vp_high = self.I(lambda: high.rolling(self.vp_lookback).max())
        self.vp_low = self.I(lambda: low.rolling(self.vp_lookback).min())
        
        # Track position state
        self.in_poc_zone = False
        self.prev_in_poc_zone = False
        self.poc_price = None
        self.vah_price = None
        self.val_price = None

    def next(self):
        if len(self.data) < self.sma200_len:
            return
        
        # Get current values
        sma20 = self.sma20[-1]
        sma50 = self.sma50[-1]
        sma200 = self.sma200[-1]
        atr = self.atr14[-1]
        close = self.data.Close[-1]
        
        if pd.isna(sma20) or pd.isna(sma50) or pd.isna(sma200) or pd.isna(atr):
            return
        
        # Calculate Volume Profile on current bar
        if len(self.data) >= self.vp_lookback:
            vp_high = self.vp_high[-1]
            vp_low = self.vp_low[-1]
            
            if pd.notna(vp_high) and pd.notna(vp_low) and vp_high > vp_low:
                # Calculate POC, VAH, VAL
                price_range = vp_high - vp_low
                row_size = price_range / self.vp_rows
                
                # Build volume by price
                volume_by_price = [0.0] * self.vp_rows
                
                for i in range(self.vp_lookback):
                    idx = len(self.data) - self.vp_lookback + i
                    if idx >= 0 and idx < len(self.data):
                        p = self.data.Close[idx]
                        v = self.data.Volume[idx]
                        row = int((p - vp_low) / row_size) if row_size > 0 else 0
                        row = max(0, min(self.vp_rows - 1, row))
                        volume_by_price[row] += v
                
                # Find POC (max volume row)
                max_vol = max(volume_by_price)
                if max_vol > 0:
                    poc_row = volume_by_price.index(max_vol)
                    self.poc_price = vp_low + (poc_row + 0.5) * row_size
                    
                    # Calculate Value Area
                    total_vol = sum(volume_by_price)
                    target_vol = total_vol * self.va_percent / 100
                    
                    vah_row = poc_row
                    val_row = poc_row
                    acc_vol = volume_by_price[poc_row]
                    
                    while acc_vol < target_vol and (vah_row < self.vp_rows - 1 or val_row > 0):
                        upper_v = volume_by_price[vah_row + 1] if vah_row < self.vp_rows - 1 else 0.0
                        lower_v = volume_by_price[val_row - 1] if val_row > 0 else 0.0
                        
                        if upper_v > lower_v and vah_row < self.vp_rows - 1:
                            vah_row += 1
                            acc_vol += upper_v
                        elif val_row > 0:
                            val_row -= 1
                            acc_vol += lower_v
                        else:
                            break
                    
                    self.vah_price = vp_low + (vah_row + 1) * row_size
                    self.val_price = vp_low + val_row * row_size
        
        # Determine price zone
        price_zone = 'unknown'
        if self.vah_price and self.val_price:
            if close > self.vah_price:
                price_zone = 'above_vah'
            elif close < self.val_price:
                price_zone = 'below_val'
            elif self.poc_price and abs(close - self.poc_price) < atr * 0.15:
                price_zone = 'at_poc'
            else:
                price_zone = 'in_va'
        
        # POC zone detection
        self.prev_in_poc_zone = self.in_poc_zone
        if self.poc_price and abs(close - self.poc_price) < atr * 0.15:
            self.in_poc_zone = True
        else:
            self.in_poc_zone = False
        
        poc_enter = self.in_poc_zone and not self.prev_in_poc_zone
        poc_exit = not self.in_poc_zone and self.prev_in_poc_zone
        
        # SMA alignment (trend structure)
        sma_bull_aligned = sma20 > sma50 and sma50 > sma200
        sma_bear_aligned = sma20 < sma50 and sma50 < sma200
        
        # SMA crosses
        golden_cross_20x50 = crossover(self.sma20, self.sma50)
        dead_cross_20x50 = crossover(self.sma50, self.sma20)
        golden_cross_50x200 = crossover(self.sma50, self.sma200)
        dead_cross_50x200 = crossover(self.sma200, self.sma50)
        
        # Context scoring
        bull_score = 0
        bear_score = 0
        
        if sma_bull_aligned:
            bull_score += 40
        if sma_bear_aligned:
            bear_score += 40
        
        if price_zone == 'above_vah':
            bull_score += 30
        elif price_zone == 'below_val':
            bear_score += 30
        elif price_zone == 'at_poc':
            bull_score += 20
            bear_score += 20
        elif price_zone == 'in_va':
            bull_score += 10
            bear_score += 10
        
        bull_score = min(100, bull_score)
        bear_score = min(100, bear_score)
        
        context_score = max(bull_score, bear_score)
        
        # Determine if conditions are favorable
        is_long_favorable = (context_score >= 70 and sma_bull_aligned and 
                            (price_zone == 'above_vah' or price_zone == 'at_poc'))
        is_short_favorable = (context_score >= 70 and sma_bear_aligned and 
                             (price_zone == 'below_val' or price_zone == 'at_poc'))
        
        # Trading logic
        # Buy signals
        if not self.position:
            if golden_cross_20x50 or golden_cross_50x200:
                if is_long_favorable or bull_score > bear_score:
                    self.buy()
            elif poc_enter and sma_bull_aligned:
                if bull_score >= 50:
                    self.buy()
        
        # Sell signals
        if self.position:
            if dead_cross_20x50 or dead_cross_50x200:
                if is_short_favorable or bear_score > bull_score:
                    self.sell()
            elif poc_exit and sma_bear_aligned:
                if bear_score >= 50:
                    self.sell()
            elif is_short_favorable and bull_score < bear_score:
                self.sell()


if __name__ == '__main__':
    import yfinance as yf
    
    # Download sample data
    data = yf.download('AAPL', start='2023-01-01', end='2024-01-01', progress=False)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()