"""
DS-TV Backtest Results: replay-footprint
============================================================

--- SPY ---
  Return                    22.54%
  Buy & Hold Return         40.20%
  Max Drawdown              -9.27%
  Sharpe Ratio              0.93
  Sortino Ratio             1.43
  Calmar Ratio              1.16
  Profit Factor             1.55
  Expectancy                1.05%
  SQN                       0.22
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                7.78%
  Worst Trade               -5.70%
  Avg Trade                 0.90%
  Exposure Time             34.40%
  Equity Final              122541.36$
  Equity Peak               122812.40$
  Avg Drawdown              -1.81%
  Max Drawdown Duration     231 days 00:00:00
  Max Trade Duration        133 days 00:00:00
  Avg Trade Duration        83 days 00:00:00
  Ann. Return               10.79%
  Ann. Volatility           11.57%

--- BTC ---
  Return                    10.44%
  Buy & Hold Return         0.29%
  Max Drawdown              -23.28%
  Sharpe Ratio              0.20
  Sortino Ratio             0.33
  Calmar Ratio              0.22
  Profit Factor             1.48
  Expectancy                2.90%
  SQN                       0.23
  # Trades                  8
  Win Rate                  50.00%
  Best Trade                55.46%
  Worst Trade               -14.14%
  Avg Trade                 0.95%
  Exposure Time             47.74%
  Equity Final              110443.58$
  Equity Peak               137739.32$
  Avg Drawdown              -6.24%
  Max Drawdown Duration     205 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        43 days 00:00:00
  Ann. Return               5.09%
  Ann. Volatility           25.48%

--- QQQ ---
  Return                    21.87%
  Buy & Hold Return         45.93%
  Max Drawdown              -13.43%
  Sharpe Ratio              0.67
  Sortino Ratio             1.01
  Calmar Ratio              0.78
  Profit Factor             10.82
  Expectancy                7.01%
  SQN                       1.00
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                20.78%
  Worst Trade               -2.14%
  Avg Trade                 6.56%
  Exposure Time             63.40%
  Equity Final              121871.57$
  Equity Peak               125613.76$
  Avg Drawdown              -3.24%
  Max Drawdown Duration     170 days 00:00:00
  Max Trade Duration        210 days 00:00:00
  Avg Trade Duration        153 days 00:00:00
  Ann. Return               10.48%
  Ann. Volatility           15.57%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — replay-footprint
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.sma_20 = self.I(pta.sma, close, length=20)
        self.sma_50 = self.I(pta.sma, close, length=50)

    def next(self):
        if crossover(self.sma_20, self.sma_50):
            if not self.position:
                self.buy()
        elif crossover(self.sma_50, self.sma_20):
            if self.position:
                self.position.close()