"""
DS-TV Backtest Results: session-dominance-profile-pointalgo
============================================================

--- SPY ---
  Return                    27.87%
  Buy & Hold Return         30.74%
  Max Drawdown              -5.06%
  Sharpe Ratio              1.58
  Sortino Ratio             2.84
  Calmar Ratio              2.61
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              127871.87$
  Equity Peak               128155.23$
  Avg Drawdown              -1.22%
  Max Drawdown Duration     42 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               13.19%
  Ann. Volatility           8.34%

--- BTC ---
  Return                    -27.69%
  Buy & Hold Return         -27.69%
  Max Drawdown              -48.78%
  Sharpe Ratio              -0.50
  Sortino Ratio             -0.61
  Calmar Ratio              -0.31
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              72311.38$
  Equity Peak               127213.86$
  Avg Drawdown              -10.11%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               -14.95%
  Ann. Volatility           29.71%

--- QQQ ---
  Return                    31.79%
  Buy & Hold Return         35.63%
  Max Drawdown              -7.86%
  Sharpe Ratio              1.34
  Sortino Ratio             2.36
  Calmar Ratio              1.90
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              131789.31$
  Equity Peak               136204.55$
  Avg Drawdown              -1.40%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               14.93%
  Ann. Volatility           11.13%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — session-dominance-profile-pointalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    i_len = 300
    i_bins = 60
    i_fixed_wid = 200
    i_offset = 150
    i_direction = "Right to Left"
    i_asia_start = 0
    i_asia_end = 8
    i_lon_start = 8
    i_lon_end = 13

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.highest_p = self.I(lambda: high.rolling(self.i_len).max())
        self.lowest_p = self.I(lambda: low.rolling(self.i_len).min())
        
    def next(self):
        if len(self.data) < self.i_len + 1:
            return
        
        highest = self.highest_p[-1]
        lowest = self.lowest_p[-1]
        
        if highest == lowest or np.isnan(highest) or np.isnan(lowest):
            return
        
        range_p = highest - lowest
        step = range_p / self.i_bins
        
        asia_bins = np.zeros(self.i_bins)
        lon_bins = np.zeros(self.i_bins)
        ny_bins = np.zeros(self.i_bins)
        total_bins = np.zeros(self.i_bins)
        
        lookback_start = max(0, len(self.data) - self.i_len)
        
        for i in range(lookback_start, len(self.data)):
            bar_idx = i
            p = self.data.Close[bar_idx]
            v = self.data.Volume[bar_idx]
            
            bar_time = self.data.index[bar_idx]
            h = bar_time.hour
            
            if np.isnan(p) or np.isnan(v):
                continue
            
            bin_idx = int(np.floor((p - lowest) / step))
            bin_idx = max(0, min(self.i_bins - 1, bin_idx))
            
            total_bins[bin_idx] += v
            
            if h >= self.i_asia_start and h < self.i_asia_end:
                asia_bins[bin_idx] += v
            elif h >= self.i_lon_start and h < self.i_lon_end:
                lon_bins[bin_idx] += v
            else:
                ny_bins[bin_idx] += v
        
        max_total = np.max(total_bins) if np.max(total_bins) > 0 else 1
        
        dominant_session = None
        dominant_strength = 0
        
        for b in range(self.i_bins):
            tot = total_bins[b]
            a = asia_bins[b]
            l = lon_bins[b]
            n = ny_bins[b]
            
            if tot > 0:
                session_strength = max(a, l, n) / tot
                if session_strength > dominant_strength:
                    dominant_strength = session_strength
                    if a > l and a > n:
                        dominant_session = "Asia"
                    elif l > a and l > n:
                        dominant_session = "London"
                    else:
                        dominant_session = "NY"
        
        if dominant_session == "Asia" and dominant_strength > 0.5:
            if not self.position:
                self.buy()
        elif dominant_session == "London" and dominant_strength > 0.5:
            if self.position:
                self.sell()
        elif dominant_session == "NY" and dominant_strength > 0.5:
            if self.position:
                self.sell()
            else:
                pass


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("EURUSD=X", start="2023-01-01", end="2024-01-01", interval="1h")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.0002)
    results = bt.run()
    print(results)
    bt.plot()