"""
DS-TV Backtest Results: session-volume-averages
============================================================

--- SPY ---
  Return                    -27.74%
  Buy & Hold Return         41.94%
  Max Drawdown              -33.17%
  Sharpe Ratio              -1.07
  Sortino Ratio             -1.24
  Calmar Ratio              -0.46
  Profit Factor             0.51
  Expectancy                -1.07%
  SQN                       -1.20
  # Trades                  26
  Win Rate                  50.00%
  Best Trade                6.39%
  Worst Trade               -11.54%
  Avg Trade                 -1.16%
  Exposure Time             82.00%
  Equity Final              72260.25$
  Equity Peak               107870.79$
  Avg Drawdown              -7.96%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        71 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               -15.10%
  Ann. Volatility           14.18%

--- BTC ---
  Return                    -32.15%
  Buy & Hold Return         46.22%
  Max Drawdown              -34.92%
  Sharpe Ratio              -0.93
  Sortino Ratio             -0.98
  Calmar Ratio              -0.50
  Profit Factor             0.50
  Expectancy                -1.96%
  SQN                       -1.14
  # Trades                  27
  Win Rate                  51.85%
  Best Trade                10.32%
  Worst Trade               -28.85%
  Avg Trade                 -2.34%
  Exposure Time             34.75%
  Equity Final              67849.69$
  Equity Peak               103202.74$
  Avg Drawdown              -15.24%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        38 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -17.61%
  Ann. Volatility           18.97%

--- QQQ ---
  Return                    -17.34%
  Buy & Hold Return         42.67%
  Max Drawdown              -38.23%
  Sharpe Ratio              -0.51
  Sortino Ratio             -0.64
  Calmar Ratio              -0.24
  Profit Factor             0.79
  Expectancy                -0.49%
  SQN                       -0.53
  # Trades                  27
  Win Rate                  40.74%
  Best Trade                13.87%
  Worst Trade               -9.12%
  Avg Trade                 -0.61%
  Exposure Time             75.60%
  Equity Final              82661.41$
  Equity Peak               130534.26$
  Avg Drawdown              -5.96%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        104 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -9.15%
  Ann. Volatility           18.08%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — session-volume-averages
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        
        if len(self.data) < 2:
            return
        
        current_vol = volume.iloc[-1]
        prev_vol = volume.iloc[-2]
        current_close = close.iloc[-1]
        current_open = pd.Series(self.data.Open).iloc[-1]
        
        vol_ma_20 = volume.rolling(window=20).mean().iloc[-1]
        
        if np.isnan(vol_ma_20):
            vol_ma_20 = current_vol
        
        if current_vol > vol_ma_20 * 1.5:
            if current_close > current_open:
                if not self.position:
                    self.buy()
            else:
                if self.position:
                    self.sell()
        elif current_vol < vol_ma_20 * 0.5:
            if self.position:
                self.sell()
        
        if self.position and len(self.data) > 50:
            recent_high = close.iloc[-50:].max()
            recent_low = close.iloc[-50:].min()
            
            if current_close > recent_high * 1.02:
                self.sell()
            elif current_close < recent_low * 0.98:
                self.sell()


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.002,
    )
    stats = bt.run()
    print(stats)
    bt.plot()