"""
DS-TV Backtest Results: time-segmented-rvol
============================================================

--- SPY ---
  Return                    -59.94%
  Buy & Hold Return         41.94%
  Max Drawdown              -60.94%
  Sharpe Ratio              -3.54
  Sortino Ratio             -2.86
  Calmar Ratio              -0.61
  Profit Factor             0.42
  Expectancy                -0.32%
  SQN                       -3.92
  # Trades                  280
  Win Rate                  30.71%
  Best Trade                10.91%
  Worst Trade               -10.47%
  Avg Trade                 -0.33%
  Exposure Time             94.60%
  Equity Final              40061.98$
  Equity Peak               102554.85$
  Avg Drawdown              -21.20%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        24 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -36.94%
  Ann. Volatility           10.42%

--- BTC ---
  Return                    -23.59%
  Buy & Hold Return         46.22%
  Max Drawdown              -37.44%
  Sharpe Ratio              -0.55
  Sortino Ratio             -0.69
  Calmar Ratio              -0.34
  Profit Factor             0.77
  Expectancy                -0.36%
  SQN                       -0.84
  # Trades                  136
  Win Rate                  46.32%
  Best Trade                11.60%
  Worst Trade               -20.13%
  Avg Trade                 -0.44%
  Exposure Time             36.80%
  Equity Final              76408.23$
  Equity Peak               104840.05$
  Avg Drawdown              -13.30%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -12.57%
  Ann. Volatility           22.74%

--- QQQ ---
  Return                    -62.36%
  Buy & Hold Return         42.67%
  Max Drawdown              -64.30%
  Sharpe Ratio              -3.06
  Sortino Ratio             -2.47
  Calmar Ratio              -0.60
  Profit Factor             0.50
  Expectancy                -0.34%
  SQN                       -3.39
  # Trades                  281
  Win Rate                  33.45%
  Best Trade                10.73%
  Worst Trade               -11.98%
  Avg Trade                 -0.36%
  Exposure Time             95.40%
  Equity Final              37639.49$
  Equity Peak               102566.64$
  Avg Drawdown              -23.50%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        24 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -38.89%
  Ann. Volatility           12.70%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — time-segmented-rvol
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookbackDays = 20
    midThreshold = 1.5
    highThreshold = 3.0
    superThreshold = 5.0

    def init(self):
        self.volHistory = {}
        self.rvol_values = []
        
    def next(self):
        current_time = pd.Timestamp(self.data.index[-1])
        current_volume = self.data.Volume[-1]
        minute_idx = current_time.hour * 60 + current_time.minute
        
        sum_vol = 0.0
        count = 0
        
        for i in range(self.lookbackDays):
            key = (minute_idx, i)
            if key in self.volHistory:
                hist_val = self.volHistory[key]
                if hist_val > 0:
                    sum_vol += hist_val
                    count += 1
        
        historical_avg = sum_vol / count if count > 0 else 0.0
        rvol = current_volume / historical_avg if historical_avg > 0 else 1.0
        
        storage_offset_idx = len(self.data) % self.lookbackDays
        key = (minute_idx, storage_offset_idx)
        self.volHistory[key] = current_volume
        
        self.rvol_values.append(rvol)
        
        if len(self.rvol_values) < 2:
            return
        
        prev_rvol = self.rvol_values[-2]
        curr_rvol = self.rvol_values[-1]
        
        if not self.position:
            if prev_rvol < self.midThreshold and curr_rvol >= self.midThreshold:
                self.buy()
            elif curr_rvol >= self.superThreshold:
                self.buy()
        else:
            if curr_rvol >= self.superThreshold:
                pass
            elif curr_rvol < 1.0:
                self.sell()
            elif prev_rvol >= self.highThreshold and curr_rvol < self.highThreshold:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()