"""
DS-TV Backtest Results: trading-bite-supply-demand-marker-v21
============================================================

--- SPY ---
  Return                    -7.74%
  Buy & Hold Return         41.94%
  Max Drawdown              -22.55%
  Sharpe Ratio              -0.40
  Sortino Ratio             -0.47
  Calmar Ratio              -0.18
  Profit Factor             0.82
  Expectancy                -0.15%
  SQN                       -0.46
  # Trades                  46
  Win Rate                  47.83%
  Best Trade                4.86%
  Worst Trade               -12.25%
  Avg Trade                 -0.18%
  Exposure Time             62.80%
  Equity Final              92256.91$
  Equity Peak               114970.75$
  Avg Drawdown              -1.80%
  Max Drawdown Duration     430 days 00:00:00
  Max Trade Duration        32 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -3.98%
  Ann. Volatility           9.93%

--- BTC ---
  Return                    -5.53%
  Buy & Hold Return         46.22%
  Max Drawdown              -28.25%
  Sharpe Ratio              -0.13
  Sortino Ratio             -0.19
  Calmar Ratio              -0.10
  Profit Factor             1.11
  Expectancy                0.18%
  SQN                       -0.18
  # Trades                  69
  Win Rate                  33.33%
  Best Trade                20.08%
  Worst Trade               -9.54%
  Avg Trade                 0.06%
  Exposure Time             53.08%
  Equity Final              94467.11$
  Equity Peak               127819.90$
  Avg Drawdown              -5.52%
  Max Drawdown Duration     400 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -2.80%
  Ann. Volatility           21.62%

--- QQQ ---
  Return                    -3.17%
  Buy & Hold Return         42.67%
  Max Drawdown              -21.75%
  Sharpe Ratio              -0.12
  Sortino Ratio             -0.15
  Calmar Ratio              -0.07
  Profit Factor             1.03
  Expectancy                0.03%
  SQN                       -0.04
  # Trades                  45
  Win Rate                  46.67%
  Best Trade                8.32%
  Worst Trade               -12.40%
  Avg Trade                 -0.02%
  Exposure Time             66.40%
  Equity Final              96830.98$
  Equity Peak               110035.27$
  Avg Drawdown              -5.43%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -1.61%
  Ann. Volatility           13.68%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trading-bite-supply-demand-marker-v21
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        # Calculate volume-based signals
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # Volume from current and previous bars
        vol = volume
        vol1 = volume.shift(1)
        vol2 = volume.shift(2)
        
        # Determine bull/bear candles
        self.is_bull = self.I(lambda: close > open_)
        self.is_bear = self.I(lambda: close < open_)
        
        # Volume lower than previous 2 bars
        self.vol_lower_than_prev2 = self.I(lambda: (vol < vol1) & (vol < vol2))
        
        # Supply (S) and Demand (D) signals
        self.show_s = self.I(lambda: self.is_bull & self.vol_lower_than_prev2)
        self.show_d = self.I(lambda: self.is_bear & self.vol_lower_than_prev2)
        
        # Track previous signal state for entry/exit detection
        self.prev_show_s = False
        self.prev_show_d = False

    def next(self):
        # Get current signal values
        current_show_s = self.show_s[-1] if len(self.show_s) > 0 else False
        current_show_d = self.show_d[-1] if len(self.show_d) > 0 else False
        
        # Buy on Supply signal (bullish volume pattern)
        if current_show_s and not self.prev_show_s:
            if not self.position:
                self.buy()
        
        # Sell on Demand signal (bearish volume pattern)
        if current_show_d and not self.prev_show_d:
            if self.position:
                self.position.close()
        
        # Exit long if demand signal appears
        if current_show_d and self.position:
            self.position.close()
        
        # Update previous signal state
        self.prev_show_s = current_show_s
        self.prev_show_d = current_show_d


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()