"""
DS-TV Backtest Results: trading-value-auto-unit-kmb-with-price-labels
============================================================

--- SPY ---
  Return                    -40.01%
  Buy & Hold Return         41.94%
  Max Drawdown              -41.30%
  Sharpe Ratio              -1.88
  Sortino Ratio             -2.00
  Calmar Ratio              -0.55
  Profit Factor             0.42
  Expectancy                -0.63%
  SQN                       -2.62
  # Trades                  78
  Win Rate                  39.74%
  Best Trade                7.54%
  Worst Trade               -9.08%
  Avg Trade                 -0.65%
  Exposure Time             93.80%
  Equity Final              59994.58$
  Equity Peak               101978.57$
  Avg Drawdown              -14.92%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        50 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -22.70%
  Ann. Volatility           12.09%

--- BTC ---
  Return                    -33.42%
  Buy & Hold Return         46.22%
  Max Drawdown              -40.58%
  Sharpe Ratio              -0.95
  Sortino Ratio             -0.96
  Calmar Ratio              -0.45
  Profit Factor             0.66
  Expectancy                -1.07%
  SQN                       -1.08
  # Trades                  43
  Win Rate                  44.19%
  Best Trade                10.92%
  Worst Trade               -18.17%
  Avg Trade                 -1.31%
  Exposure Time             35.29%
  Equity Final              66583.43$
  Equity Peak               111352.38$
  Avg Drawdown              -10.38%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        16 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -18.38%
  Ann. Volatility           19.40%

--- QQQ ---
  Return                    -43.73%
  Buy & Hold Return         42.67%
  Max Drawdown              -47.39%
  Sharpe Ratio              -1.67
  Sortino Ratio             -1.75
  Calmar Ratio              -0.53
  Profit Factor             0.46
  Expectancy                -0.70%
  SQN                       -2.29
  # Trades                  81
  Win Rate                  32.10%
  Best Trade                9.03%
  Worst Trade               -12.94%
  Avg Trade                 -0.74%
  Exposure Time             94.60%
  Equity Final              56265.07$
  Equity Peak               103998.54$
  Avg Drawdown              -12.78%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        50 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -25.16%
  Ann. Volatility           15.10%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trading-value-auto-unit-kmb-with-price-labels
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        
        # Calculate trading value (Price * Volume)
        self.trading_value = self.I(lambda: close * volume)

    def next(self):
        # Entry signal: when trading value crosses above its 20-period moving average
        if len(self.data) < 20:
            return
        
        trading_value_sma = pd.Series(self.trading_value).rolling(window=20).mean()
        
        if crossover(self.trading_value, trading_value_sma):
            if not self.position:
                self.buy()
        
        # Exit signal: when trading value crosses below its 20-period moving average
        elif crossover(trading_value_sma, self.trading_value):
            if self.position:
                self.sell()