"""
DS-TV Backtest Results: volume-conviction-index-v10
============================================================

--- SPY ---
  Return                    -44.87%
  Buy & Hold Return         40.26%
  Max Drawdown              -45.16%
  Sharpe Ratio              -2.30
  Sortino Ratio             -2.31
  Calmar Ratio              -0.57
  Profit Factor             0.44
  Expectancy                -0.44%
  SQN                       -3.35
  # Trades                  130
  Win Rate                  33.08%
  Best Trade                5.18%
  Worst Trade               -5.30%
  Avg Trade                 -0.45%
  Exposure Time             88.40%
  Equity Final              55126.93$
  Equity Peak               100519.66$
  Avg Drawdown              -45.16%
  Max Drawdown Duration     643 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -25.93%
  Ann. Volatility           11.27%

--- BTC ---
  Return                    -29.01%
  Buy & Hold Return         -2.08%
  Max Drawdown              -39.48%
  Sharpe Ratio              -0.84
  Sortino Ratio             -0.94
  Calmar Ratio              -0.40
  Profit Factor             0.70
  Expectancy                -0.51%
  SQN                       -1.09
  # Trades                  86
  Win Rate                  40.70%
  Best Trade                10.28%
  Worst Trade               -18.17%
  Avg Trade                 -0.60%
  Exposure Time             30.92%
  Equity Final              70994.93$
  Equity Peak               107014.89$
  Avg Drawdown              -10.31%
  Max Drawdown Duration     650 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -15.72%
  Ann. Volatility           18.70%

--- QQQ ---
  Return                    -48.19%
  Buy & Hold Return         45.43%
  Max Drawdown              -49.92%
  Sharpe Ratio              -2.02
  Sortino Ratio             -2.01
  Calmar Ratio              -0.57
  Profit Factor             0.50
  Expectancy                -0.48%
  SQN                       -2.74
  # Trades                  135
  Win Rate                  31.11%
  Best Trade                8.31%
  Worst Trade               -6.76%
  Avg Trade                 -0.50%
  Exposure Time             87.60%
  Equity Final              51810.47$
  Equity Peak               100619.89$
  Avg Drawdown              -24.97%
  Max Drawdown Duration     642 days 00:00:00
  Max Trade Duration        22 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -28.21%
  Ann. Volatility           13.97%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volume-conviction-index-v10
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    vol_len = 50
    z_thresh = 1.5
    weight_recent = 0.7
    median_len = 7

    def init(self):
        close = pd.Series(self.data.Close)
        volume = pd.Series(self.data.Volume)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        def calculate_vci():
            vci_values = []
            med_vol_arr = []
            mad_vol_arr = []
            filtered_z_arr = []
            vol_change_pct_arr = []
            rvol_pct_arr = []
            weighted_conv_arr = []
            vpi_raw_arr = []
            
            for i in range(len(volume)):
                if i < self.vol_len:
                    vci_values.append(np.nan)
                    continue
                
                vol_window = volume.iloc[i-self.vol_len+1:i+1].values
                med_vol = np.median(vol_window)
                med_vol_arr.append(med_vol)
                
                devs = np.abs(vol_window - med_vol)
                mad_vol = np.median(devs)
                mad_vol_arr.append(mad_vol)
                
                current_vol = volume.iloc[i]
                
                if mad_vol == 0:
                    robust_z_vol = np.nan
                else:
                    robust_z_vol = 0.6745 * (current_vol - med_vol) / mad_vol
                
                if np.isnan(robust_z_vol):
                    filtered_z = np.nan
                else:
                    if np.abs(robust_z_vol) > self.z_thresh:
                        filtered_z = np.sign(robust_z_vol) * self.z_thresh
                    else:
                        filtered_z = robust_z_vol
                
                filtered_z_arr.append(filtered_z)
                
                if i == 0 or volume.iloc[i-1] <= 0 or current_vol <= 0:
                    vol_change_pct = 0
                else:
                    vol_change_pct = (current_vol / volume.iloc[i-1] - 1) * 100
                
                vol_change_pct_arr.append(vol_change_pct)
                
                if med_vol > 0:
                    rvol_pct = (current_vol / med_vol - 1) * 100
                else:
                    rvol_pct = 0
                
                rvol_pct_arr.append(rvol_pct)
                
                weighted_conv = self.weight_recent * vol_change_pct + (1 - self.weight_recent) * rvol_pct
                weighted_conv_arr.append(weighted_conv)
                
                if np.isnan(filtered_z):
                    vpi_raw = np.nan
                else:
                    vpi_raw = 0.6 * filtered_z + 0.4 * (weighted_conv / 10)
                
                vpi_raw_arr.append(vpi_raw)
                vci_values.append(vpi_raw)
            
            return pd.Series(vci_values)
        
        self.vci_raw = self.I(calculate_vci)
        
        def calculate_vci_median():
            vci_raw_values = calculate_vci()
            vci_median_values = []
            
            for i in range(len(vci_raw_values)):
                if i < self.median_len - 1:
                    vci_median_values.append(np.nan)
                else:
                    window = vci_raw_values.iloc[i-self.median_len+1:i+1].values
                    vci_median_values.append(np.nanmedian(window))
            
            return pd.Series(vci_median_values)
        
        self.vci_median = self.I(calculate_vci_median)

    def next(self):
        if len(self.data) < self.median_len + self.vol_len:
            return
        
        current_vci = self.vci_raw[-1]
        current_median = self.vci_median[-1]
        
        if np.isnan(current_vci) or np.isnan(current_median):
            return
        
        prev_vci = self.vci_raw[-2] if len(self.vci_raw) > 1 else np.nan
        
        if self.position:
            if current_vci < -1.5 or (current_vci < 0 and prev_vci > 0):
                self.sell()
        else:
            if current_vci > 1.5 or (current_vci > 0 and prev_vci <= 0):
                self.buy()