"""
DS-TV Backtest Results: volume-rsi-elite
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "ema(V,20)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (732,); indicator "ema(V,20)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (502,); indicator "ema(V,20)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volume-rsi-elite
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    param1 = 20  # Volume EMA Length
    param2 = 14  # RSI Length
    param3 = 70  # RSI Overbought
    param4 = 55  # RSI Gold Zone
    param5 = 30  # RSI Oversold

    def init(self):
        close = pd.Series(self.data.Close)
        self.vol_avg = self.I(pta.ema, self.data.Volume, length=self.param1)
        self.vol_ratio = self.data.Volume / self.vol_avg
        self.rsi_val = self.I(pta.rsi, close, length=self.param2)

    def next(self):
        if crossover(self.rsi_val, self.param3):
            self.sell()
        elif crossover(self.param5, self.rsi_val):
            self.buy()