"""
DS-TV Backtest Results: volume-profile-visible-range-vpvr-with-poc-price
============================================================

--- SPY ---
  Return                    -27.74%
  Buy & Hold Return         41.94%
  Max Drawdown              -33.17%
  Sharpe Ratio              -1.07
  Sortino Ratio             -1.24
  Calmar Ratio              -0.46
  Profit Factor             0.51
  Expectancy                -1.07%
  SQN                       -1.20
  # Trades                  26
  Win Rate                  50.00%
  Best Trade                6.39%
  Worst Trade               -11.54%
  Avg Trade                 -1.16%
  Exposure Time             82.00%
  Equity Final              72260.25$
  Equity Peak               107870.79$
  Avg Drawdown              -7.96%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        71 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               -15.10%
  Ann. Volatility           14.18%

--- BTC ---
  Return                    -32.15%
  Buy & Hold Return         46.22%
  Max Drawdown              -34.92%
  Sharpe Ratio              -0.93
  Sortino Ratio             -0.98
  Calmar Ratio              -0.50
  Profit Factor             0.50
  Expectancy                -1.96%
  SQN                       -1.14
  # Trades                  27
  Win Rate                  51.85%
  Best Trade                10.32%
  Worst Trade               -28.85%
  Avg Trade                 -2.34%
  Exposure Time             34.75%
  Equity Final              67849.69$
  Equity Peak               103202.74$
  Avg Drawdown              -15.24%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        38 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -17.61%
  Ann. Volatility           18.97%

--- QQQ ---
  Return                    -17.34%
  Buy & Hold Return         42.67%
  Max Drawdown              -38.23%
  Sharpe Ratio              -0.51
  Sortino Ratio             -0.64
  Calmar Ratio              -0.24
  Profit Factor             0.79
  Expectancy                -0.49%
  SQN                       -0.53
  # Trades                  27
  Win Rate                  40.74%
  Best Trade                13.87%
  Worst Trade               -9.12%
  Avg Trade                 -0.61%
  Exposure Time             75.60%
  Equity Final              82661.41$
  Equity Peak               130534.26$
  Avg Drawdown              -5.96%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        104 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -9.15%
  Ann. Volatility           18.08%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volume-profile-visible-range-vpvr-with-poc-price
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rows = 100
    vp_width = 40
    val_area_pct = 70
    placement = "Left"

    def init(self):
        pass

    def next(self):
        # This is a volume profile indicator without trading signals
        # Create a simple trading rule based on volume analysis
        
        if len(self.data) < 20:
            return
        
        # Calculate average volume
        recent_volume = pd.Series(self.data.Volume[-20:])
        avg_volume = recent_volume.mean()
        current_volume = self.data.Volume[-1]
        
        # Simple trading rules based on volume
        if current_volume > avg_volume * 1.5:
            if self.data.Close[-1] > self.data.Open[-1]:
                if not self.position:
                    self.buy()
            elif self.data.Close[-1] < self.data.Open[-1]:
                if self.position:
                    self.sell()
        
        # Exit logic
        if self.position:
            if current_volume < avg_volume * 0.5:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()