"""
DS-TV Backtest Results: vwap-trader-nxi
============================================================

--- SPY ---
  Return                    -36.40%
  Buy & Hold Return         41.94%
  Max Drawdown              -36.94%
  Sharpe Ratio              -2.90
  Sortino Ratio             -2.56
  Calmar Ratio              -0.55
  Profit Factor             0.42
  Expectancy                -0.28%
  SQN                       -3.28
  # Trades                  161
  Win Rate                  40.37%
  Best Trade                1.86%
  Worst Trade               -6.78%
  Avg Trade                 -0.29%
  Exposure Time             64.40%
  Equity Final              63600.30$
  Equity Peak               100302.34$
  Avg Drawdown              -36.94%
  Max Drawdown Duration     724 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -20.39%
  Ann. Volatility           7.04%

--- BTC ---
  Return                    -24.95%
  Buy & Hold Return         46.22%
  Max Drawdown              -40.52%
  Sharpe Ratio              -0.76
  Sortino Ratio             -0.92
  Calmar Ratio              -0.33
  Profit Factor             0.96
  Expectancy                -0.04%
  SQN                       -0.82
  # Trades                  220
  Win Rate                  47.27%
  Best Trade                11.96%
  Worst Trade               -8.52%
  Avg Trade                 -0.07%
  Exposure Time             60.19%
  Equity Final              75052.94$
  Equity Peak               126191.88$
  Avg Drawdown              -4.07%
  Max Drawdown Duration     422 days 00:00:00
  Max Trade Duration        1 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -13.35%
  Ann. Volatility           17.58%

--- QQQ ---
  Return                    -34.88%
  Buy & Hold Return         42.67%
  Max Drawdown              -35.99%
  Sharpe Ratio              -2.07
  Sortino Ratio             -1.94
  Calmar Ratio              -0.54
  Profit Factor             0.57
  Expectancy                -0.27%
  SQN                       -2.41
  # Trades                  160
  Win Rate                  48.75%
  Best Trade                2.83%
  Worst Trade               -6.92%
  Avg Trade                 -0.27%
  Exposure Time             64.00%
  Equity Final              65124.75$
  Equity Peak               100724.97$
  Avg Drawdown              -18.73%
  Max Drawdown Duration     710 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -19.44%
  Ann. Volatility           9.40%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vwap-trader-nxi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    dev1_mult = 2.0
    dev2_mult = 3.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        hlc3 = (high + low + close) / 3
        
        self.vwap_values = []
        self.dev_values = []
        self.upper1_values = []
        self.lower1_values = []
        self.upper2_values = []
        self.lower2_values = []
        
        vwap_sum = 0.0
        volume_sum = 0.0
        v2_sum = 0.0
        prev_date = None
        
        for i in range(len(hlc3)):
            current_date = pd.Timestamp(self.data.index[i]).date()
            
            if prev_date is None or current_date != prev_date:
                vwap_sum = hlc3.iloc[i] * volume.iloc[i]
                volume_sum = volume.iloc[i]
                v2_sum = volume.iloc[i] * (hlc3.iloc[i] ** 2)
            else:
                vwap_sum += hlc3.iloc[i] * volume.iloc[i]
                volume_sum += volume.iloc[i]
                v2_sum += volume.iloc[i] * (hlc3.iloc[i] ** 2)
            
            prev_date = current_date
            
            if volume_sum > 0:
                my_vwap = vwap_sum / volume_sum
                dev = np.sqrt(max(v2_sum / volume_sum - (my_vwap ** 2), 0))
            else:
                my_vwap = hlc3.iloc[i]
                dev = 0
            
            self.vwap_values.append(my_vwap)
            self.dev_values.append(dev)
            self.upper1_values.append(my_vwap + self.dev1_mult * dev)
            self.lower1_values.append(my_vwap - self.dev1_mult * dev)
            self.upper2_values.append(my_vwap + self.dev2_mult * dev)
            self.lower2_values.append(my_vwap - self.dev2_mult * dev)
        
        self.vwap = self.I(lambda: pd.Series(self.vwap_values, index=self.data.index))
        self.upper1 = self.I(lambda: pd.Series(self.upper1_values, index=self.data.index))
        self.lower1 = self.I(lambda: pd.Series(self.lower1_values, index=self.data.index))
        self.upper2 = self.I(lambda: pd.Series(self.upper2_values, index=self.data.index))
        self.lower2 = self.I(lambda: pd.Series(self.lower2_values, index=self.data.index))

    def next(self):
        close = self.data.Close[-1]
        upper1 = self.upper1[-1]
        lower1 = self.lower1[-1]
        upper2 = self.upper2[-1]
        lower2 = self.lower2[-1]
        
        re_entry_stdev1 = (close < upper1 and len(self.data) > 1 and self.data.Close[-2] >= self.upper1[-2]) or \
                          (close > lower1 and len(self.data) > 1 and self.data.Close[-2] <= self.lower1[-2])
        
        re_entry_stdev2 = (close < upper2 and len(self.data) > 1 and self.data.Close[-2] >= self.upper2[-2]) or \
                          (close > lower2 and len(self.data) > 1 and self.data.Close[-2] <= self.lower2[-2])
        
        if re_entry_stdev2:
            if not self.position:
                self.buy()
        elif re_entry_stdev1:
            if self.position:
                self.position.close()
            else:
                self.buy()
        
        if close > upper1:
            if self.position:
                self.position.close()
        
        if close < lower1:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()