// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MisinkoMaster

//@version=6
indicator("Adaptive For Loop", "AFL | MisinkoMaster", overlay = false, behind_chart = false)
///////////////////////////////////////////////////////////////////////////////////////////
//Import Libraries
import TradingView/ta/12
///////////////////////////////////////////////////////////////////////////////////////////
//Get User Defined Inputs
start = input.int(0, "From", step = 1, minval = 0,
     tooltip = "Changes the start of the calculation",
     group = "Adaptive For Loop | MisinkoMaster", inline = "FL")
end = input.int(45, "To", step = 1, minval = 1,
     tooltip = "Changes the end of the calculation",
     group = "Adaptive For Loop | MisinkoMaster", inline = "FL")

ut = input.int(39, "Upper", step = 1,
     tooltip = "Treshhold that triggers an uptrend",
     group = "Treshholds", inline = "T")

lt = input.int(-12, "Lower", step = 1,
     tooltip = "Treshhold that triggers a downtrend",
     group = "Treshholds", inline = "T")
///////////////////////////////////////////////////////////////////////////////////////////
//Calculations
o = open
h = high
l = low
c = close

score = 0
score_o = 0
score_h = 0
score_l = 0
score_c = 0

for i = start to end
    if o > o[i]
        score_o += 1
    if o < o[i]
        score_o += -1

for i = start to end
    if h > h[i]
        score_h += 1
    if h < h[i]
        score_h += -1

for i = start to end
    if l > l[i]
        score_l += 1
    if l < l[i]
        score_l += -1

for i = start to end
    if c > c[i]
        score_c += 1
    if c < c[i]
        score_c += -1

abs_o = math.abs(score_o)
abs_h = math.abs(score_h)
abs_l = math.abs(score_l)
abs_c = math.abs(score_c)
max = math.max(abs_o, abs_h, abs_l, abs_c)

if abs_o == max
    score := score_o
if abs_h == max
    score := score_h
if abs_l == max
    score := score_l
if abs_c == max
    score := score_c
///////////////////////////////////////////////////////////////////////////////////////////
//Trend Logic
var trend = 0

L = score > ut
S = score < lt

if L and not S
    trend := 1
if S
    trend := -1
///////////////////////////////////////////////////////////////////////////////////////////
//Plotting
var col = color.rgb(0, 0, 0, 100)
if L
    col := color.rgb(0, 255, 187)
if S
    col := color.rgb(255, 0, 157)

UF = score > ut
DF = score < lt
mid = (lt+ut)/2

utp = plot(ut, "Upper", color = color.rgb(0, 255, 187), linewidth = 2, display = display.pane)
ltp = plot(lt, "Lower", color = color.rgb(255, 0, 157), linewidth = 2, display = display.pane)


fill(utp, ltp, color = color.rgb(72, 72, 72, 70))

plot(mid, "Middle",display = display.pane, color = color.rgb(44, 43, 43, 20), linestyle = plot.linestyle_dashed, 
    linewidth = 3)

s = plot(score, "For Loop", color = col, linewidth = 3)

fill(s, utp, UF ? color.rgb(0, 255, 187, 70) : color.rgb(0, 0, 0, 100), fillgaps = true)
fill(s, ltp, DF ? color.rgb(255, 0, 157, 70) : color.rgb(0, 0, 0, 100), fillgaps = true)

plotcandle(open, high, low, close, color = col, wickcolor = col, bordercolor = col, force_overlay = true)
