// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Zaimop

//@version=6
indicator("RSI and bollinger bands" )

// User inputs  
rsi_length       = input.int(20,"RSI length", group = "RSI")
g_bb             = "Bollinger bands"
MA_smoothing     = input.int(30, "Bollinger bands length", group = g_bb)
upper_dev        = input.float(0.5, "Upper standard deviation", step = 0.05, group = g_bb)
lower_dev        = input.float(0.5, "Lower standard deviation", step = 0.05, group = g_bb)

G_SMOOTHING = "Trend confirmation"
rsi_confirmation = input.bool (defval = true , title = "Trend confirmation", group = G_SMOOTHING, tooltip = "When checked indicator makes sure trend excisted a bar ago")
rsi_confirmation1 = input.bool(defval = false , title = "Trend confirmation2", group = G_SMOOTHING, tooltip = "When checked indicator makes sure trend excisted two bars ago")
rsi_confirmation2 = input.bool(defval = false , title = "Trend confirmation3", group = G_SMOOTHING, tooltip = "When checked indicator makes sure trend excisted three bars ago")

//Main body 
rsi = ta.rsi(close, rsi_length)

[bbignore1, bbhigh, bbignore2] = ta.bb(rsi, MA_smoothing, upper_dev )
[bbmid, bbignore3, bblow] = ta.bb(rsi, MA_smoothing, lower_dev )

plot(rsi, color = color.purple, linewidth = 3)
plot(bbhigh)
plot(bbmid)
plot(bblow)

// Confirmation (mitu bari peab olema, enne, kui muutub)

confirmation  = rsi_confirmation ? rsi[1] < bblow[1] : rsi < bblow
confirmation4 = rsi_confirmation ? rsi[1] > bblow[1] : rsi > bblow
confirmation2 = rsi_confirmation1 ? rsi[2] < bblow[2] : rsi < bblow
confirmation5 = rsi_confirmation1 ? rsi[2] > bblow[2] : rsi > bblow
confirmation3 = rsi_confirmation2 ? rsi[3] < bblow[3] : rsi < bblow
confirmation6 = rsi_confirmation2 ? rsi[3] > bblow[3] : rsi > bblow

// BG

buy = rsi < bblow  and  confirmation and confirmation2 and confirmation3 
sell = rsi > bbhigh and  confirmation4 and confirmation5 and confirmation6

_color = sell ? color.lime : buy ? color.red : color.gray


bgcolor(_color)
barcolor(_color)
