//@version=5
indicator("Bästa Bob Multi-RSI 😎👊", overlay = false)

// Inputs
len1 = input.int(7,  "RSI 1 length")
len2 = input.int(14, "RSI 2 length")
len3 = input.int(21, "RSI 3 length")

src  = input.source(close, "Source")

// RSI-beräkningar
rsi1 = ta.rsi(src, len1)
rsi2 = ta.rsi(src, len2)
rsi3 = ta.rsi(src, len3)

// Plot
plot(rsi1, title = "RSI 1")
plot(rsi2, title = "RSI 2")
plot(rsi3, title = "RSI 3")

// Nivålinjer
hline(70)
hline(30)
hline(50)
