// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

//@version=6
indicator("Global Macro Index", timeframe = "W")


/////////////////////////////////////////////////////////////////////////////////////////////
//imports
import Unicorpus/NormalizedIndicators/1 as L



/////////////////////////////////////////////////////////////////////////////////////////////
//getting data

float amount = 1 / 23
ltpi = array.from(
             //US
             L.btc_4d_cal(request.security("USBCOI", "W", close)) * amount,
             L.btc_4d_cal(request.security("USCLI", "W", close)) * amount,
             L.btc_4d_cal(request.security("USCCI", "W", close)) * amount,
             L.btc_4d_cal(request.security("USTOT", "W", close)) * amount,
             L.btc_4d_cal(request.security("ECONOMICS:USBCOI+ECONOMICS:USMPR+ECONOMICS:USMNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("ECONOMICS:USBCOI+ECONOMICS:USMPR+ECONOMICS:USMNO+ECONOMICS:USMEMP+ECONOMICS:USNMPR+ECONOMICS:USNMNO+ECONOMICS:USNMEMP+ECONOMICS:USNMBA+ECONOMICS:USNYCBCI", "W", close)) * amount,
             L.btc_4d_cal(request.security("USBI", "W", close)) * amount,
             

             //EU
             L.btc_4d_cal(request.security("EUSS", "W", close)) * amount,
             L.btc_4d_cal(request.security("EUBCOI", "W", close)) * amount,
             L.btc_4d_cal(request.security("EUESI", "W", close)) * amount,
             L.btc_4d_cal(request.security("EUMPRYY", "W", close)) * amount,
             L.btc_4d_cal(request.security("DENO", "W", close)) * amount,
             L.btc_4d_cal(request.security("FRNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("NLNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("ESNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("DECLI", "W", close)) * amount,
             L.btc_4d_cal(request.security("FRCLI", "W", close)) * amount,
             L.btc_4d_cal(request.security("FRBCLI", "W", close)) * amount,


             

             //Asia
             L.btc_4d_cal(request.security("CNNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("JPNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("TWNO", "W", close)) * amount,
             L.btc_4d_cal(request.security("CNCLI", "W", close)) * amount,
             L.btc_4d_cal(request.security("JPCLI", "W", close)) * amount
             )
             
      


/////////////////////////////////////////////////////////////////////////////////////////////
//plot
ltpi_ = ta.sma(ltpi.sum(), 1)
plot(ltpi_, "MT TPI", color.red, 2)

//helplines
hline(0, "midline", #a3a3a350)
hline(-0.6, "lower", #f90000)
hline(0.6, "upper", #90ff00)

Zscore(src) =>
    
    meanValue = ta.sma(src, 120)
    zScoreValue = (src - meanValue) / ta.stdev(src, 65)

    ta.hma(zScoreValue, 35)

plot_zscore = Zscore(ltpi_ *-1)
show_signal = input.bool(true, "Show Zscore Signals")
overlay_signal = input.bool(true, "Overlay Zscore Signals")
bgcolor(
       show_signal ? plot_zscore >= 2 ? #5eff0015 : plot_zscore <= -2 ? #ff000015 : na : na
       )
bgcolor(
       overlay_signal ? show_signal ? plot_zscore >= 2 ? #5eff0015 : plot_zscore <= -2 ? #ff000015 : na : na : na, force_overlay = true
       )
