// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MisinkoMaster

//@version=6
indicator("Momentum RSI", "MRSI | MisinkoMaster", false)
////////////////////////////////////////////////////////////////////////////////////////////////////
//Import Library
import TradingView/ta/12
////////////////////////////////////////////////////////////////////////////////////////////////////
//Get User Defined Inputs
len = input.int(20, "RSI Length", step = 1, minval = 2,
     tooltip = "Changes the length of the RSI",
     group = "Momentum RSI | MisinkoMaster", inline = "RSI")
src = input.source(close, "Source",
     tooltip = "Changes the source of the RSI",
     group = "Momentum RSI | MisinkoMaster", inline = "RSI")

smooth = input.int(12, "Smoothing Length", step = 1, minval = 2,
     tooltip = "Changes the smoothing length of the RSI.",
     group = "Momentum RSI | MisinkoMaster")
matype = input.string("RMA", "MA Type",
     options = ["RMA", "SMA", "EMA", "WMA", "DEMA", "TEMA", "HMA", "ALMA"],
     tooltip = "Changes the MA used in the entire indicator. Can be sensitive.",
     group = "Momentum RSI | MisinkoMaster")

offset = input.float(0.85, "Offset", step = 0.05, minval = 0,
     group = "| ALMA Only |", inline = "ALMA")
sigma = input.float(6, "Sigma", step = 0.5, minval = 0,
     group = "| ALMA Only |", inline = "ALMA")

ut = input.int(55, "Upper Treshhold", step = 1,
     tooltip = "Changes the Upper Treshhold for RSI long",
     group = "Treshholds", inline = "T")
lt = input.int(45, "Lower Treshhold", step = 1,
     tooltip = "Changes the Lower Treshhold for RSI short",
     group = "Treshholds", inline = "T")

obt = input.int(85, "Overbought Treshhold", step = 1, minval = 55,
     tooltip = "Changes the Overbought Treshhold for catching low value zones",
     group = "Treshholds", inline = "O")
ost = input.int(15, "Oversold Treshhold", step = 1, maxval = 45,
     tooltip = "Changes the Oversold Treshhold for catching high value zones",
     group = "Treshholds", inline = "O")
////////////////////////////////////////////////////////////////////////////////////////////////////
//Calculations
change = src-src[1]

gain = math.max(change, 0)
loss = math.abs(math.min(change, 0))

[avg_gain, avg_loss] = switch matype
    "RMA" => [ta.rma(gain, len), ta.rma(loss, len)]
    "SMA" => [ta.sma(gain, len), ta.sma(loss, len)]
    "EMA" => [ta.ema(gain, len), ta.ema(loss, len)]
    "WMA" => [ta.wma(gain, len), ta.wma(loss, len)]
    "DEMA" => [ta.dema(gain, len), ta.dema(loss, len)]
    "TEMA" => [ta.tema(gain, len), ta.tema(loss, len)]
    "HMA" => [ta.hma(gain, len), ta.hma(loss, len)]
    "ALMA" => [ta.alma(gain, len, offset, sigma), ta.alma(loss, len, offset, sigma)]

rs = avg_gain/avg_loss
rsi = 100 - 100/(rs+1)

change2 = src-src[1]

gain2 = math.max(change, 0)
loss2 = math.abs(math.min(change, 0))

[avg_gain2, avg_loss2] = switch matype
    "RMA" => [ta.rma(gain, len+smooth), ta.rma(loss, len+smooth)]
    "SMA" => [ta.sma(gain, len+smooth), ta.sma(loss, len+smooth)]
    "EMA" => [ta.ema(gain, len+smooth), ta.ema(loss, len+smooth)]
    "WMA" => [ta.wma(gain, len+smooth), ta.wma(loss, len+smooth)]
    "DEMA" => [ta.dema(gain, len+smooth), ta.dema(loss, len+smooth)]
    "TEMA" => [ta.tema(gain, len+smooth), ta.tema(loss, len+smooth)]
    "HMA" => [ta.hma(gain, len+smooth), ta.hma(loss, len+smooth)]
    "ALMA" => [ta.alma(gain, len+smooth, offset, sigma), ta.alma(loss, len+smooth, offset, sigma)]

rs2 = avg_gain2/avg_loss2
rsi2 = 100 - 100/(rs2+1)

ma = switch matype
    "RMA" => ta.rma(rsi, smooth)
    "SMA" => ta.sma(rsi, smooth)
    "EMA" => ta.ema(rsi, smooth)
    "WMA" => ta.wma(rsi, smooth)
    "DEMA" => ta.dema(rsi, smooth)
    "TEMA" => ta.tema(rsi, smooth)
    "HMA" => ta.hma(rsi, smooth)
    "ALMA" => ta.alma(rsi, smooth, offset, sigma)

ma2 = switch matype
    "RMA" => ta.rma(rsi2, smooth)
    "SMA" => ta.sma(rsi2, smooth)
    "EMA" => ta.ema(rsi2, smooth)
    "WMA" => ta.wma(rsi2, smooth)
    "DEMA" => ta.dema(rsi2, smooth)
    "TEMA" => ta.tema(rsi2, smooth)
    "HMA" => ta.hma(rsi2, smooth)
    "ALMA" => ta.alma(rsi2, smooth, offset, sigma)

momentum = ma-ma2


mrsi = rsi[1]+momentum+(rsi-rsi2) > 100 ? 100 : rsi[1]+momentum+(rsi-rsi2) < 0 ? 0 : rsi[1]+momentum+(rsi-rsi2)
////////////////////////////////////////////////////////////////////////////////////////////////////
//Trend Logic
var trend = 0

L = mrsi > ut
S = mrsi < lt

if L
    trend := 1
if S
    trend := -1
////////////////////////////////////////////////////////////////////////////////////////////////////
//Plotting
divergence = 50+momentum

var col = color.rgb(72, 72, 72)
var colT = color.rgb(72, 72, 72, 50)
if trend == 1
    col := color.rgb(0, 255, 187)
    colT := color.rgb(0, 255, 187, 50)
if trend == -1
    col := color.rgb(255, 0, 157)
    colT := color.rgb(255, 0, 157, 50)

var colD = color.rgb(0, 255, 187, 70)
if divergence > 50
    colD := color.rgb(0, 255, 187, 70)
if divergence < 50
    colD := color.rgb(255, 0, 157, 70)

bc = mrsi > obt and mrsi == ta.highest(mrsi, smooth)
sc = mrsi < ost and mrsi == ta.lowest(mrsi, smooth) 

plotshape(sc ? mrsi : na, style = shape.diamond, location = location.absolute, size = size.normal, color = color.rgb(0, 255, 187, 50), display = display.pane)
plotshape(bc ? mrsi : na, style = shape.diamond,location = location.absolute, size = size.normal,color = color.rgb(255, 0, 157, 50), display = display.pane)
plotshape(sc ? mrsi : na, style = shape.diamond, location = location.absolute, size = size.small, color = color.rgb(0, 255, 187, 25), display = display.pane)
plotshape(bc ? mrsi : na, style = shape.diamond,location = location.absolute, size = size.small,color = color.rgb(255, 0, 157, 25), display = display.pane)
plotshape(sc ? mrsi : na, style = shape.diamond, location = location.absolute, size = size.tiny, color = color.rgb(0, 255, 187), display = display.pane)
plotshape(bc ? mrsi : na, style = shape.diamond,location = location.absolute, size = size.tiny,color = color.rgb(255, 0, 157), display = display.pane)

bgcolor(mrsi > obt ? color.rgb(255, 0, 157, 70) : color.rgb(0, 0, 0, 100), force_overlay = true)
bgcolor(mrsi > obt ? color.rgb(255, 0, 157, 70) : color.rgb(0, 0, 0, 100), force_overlay = false)

bgcolor(mrsi < ost ? color.rgb(0, 255, 187, 70) : color.rgb(0, 0, 0, 100), force_overlay = true)
bgcolor(mrsi < ost ? color.rgb(0, 255, 187, 70) : color.rgb(0, 0, 0, 100), force_overlay = false)

lp = plot(ut, title = "Long Treshhold", color = color.rgb(71, 70, 70), display = display.pane, linewidth = 3)
sp = plot(lt, title = "Short Treshhold", color = color.rgb(71, 70, 70), display = display.pane, linewidth = 3)
obp = plot(obt, title = "OB Treshhold", color = color.rgb(0, 255, 187), display = display.pane, linewidth = 3)
osp = plot(ost, title = "OS Treshhold", color = color.rgb(255, 0, 157), display = display.pane, linewidth = 3)

fill(sp, osp, color.rgb(255, 0, 157, 85))
fill(lp, obp, color.rgb(0, 255, 187, 85))
fill(lp, sp, color.rgb(71, 70, 70, 75))

plotcandle(open, high, low, close, bordercolor = col, color = col, force_overlay = true, display = display.pane)

plot(divergence, "Divergence", color = colD, style = plot.style_histogram, histbase = 50)
plot(mrsi, "ARSI | MisinkoMaster", color = col, linewidth = 2)
plot(mrsi, "ARSI | MisinkoMaster", color = colT, linewidth = 3)
