// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TFlab

//@version=6
indicator("RSI Multi Levels kiawosch [TradingFinder]  7-14-42 Consolidation", 'Multi RSI')



Show_Short  = input.bool(true, 'Short RSI', inline = 'Short', group = 'RSI Setting')
Len_Short   = input.int(7, '', inline = 'Short', group = 'RSI Setting')
Color_Short = input.color(color.red, '', inline = 'Short', group = 'RSI Setting')


Show_Mid    = input.bool(true, 'Mid  RSI'  , inline = 'Mid', group = 'RSI Setting')
Len_Mid     = input.int(14, '', inline = 'Mid', group = 'RSI Setting')
Color_Mid   = input.color(color.orange, '', inline = 'Mid', group = 'RSI Setting')


Show_Long   = input.bool(true, 'Long  RSI' , inline = 'Long', group = 'RSI Setting')
Len_Long     = input.int(42, '', inline = 'Long', group = 'RSI Setting')
Color_Long  = input.color(color.green, '', inline = 'Long', group = 'RSI Setting')


Show_LP  = input.bool(true, 'Low Potential Zone', inline = 'Lp', group = 'Zones Setting')
Color_LP = input.color(#2e10d783, '' , inline = 'Lp', group = 'Zones Setting')

Show_MP  = input.bool(true, 'Mid Potential Zone', inline = 'MP', group = 'Zones Setting')
Color_MP = input.color(#ffc13c52, '' , inline = 'MP', group = 'Zones Setting')

Show_HP  = input.bool(true, 'High Potential Zone', inline = 'HP', group = 'Zones Setting')
Color_HP = input.color(#10d7d44b, '' , inline = 'HP', group = 'Zones Setting')


Show_Lvl_1 = input.bool(true, 'Level 1', inline = 'Lvl 1', group = 'Levels Setting')
Lvl_1      = input.int(10, '', inline = 'Lvl 1', group = 'Levels Setting')

Show_Lvl_2 = input.bool(true, 'Level 2', inline = 'Lvl 2', group = 'Levels Setting')
Lvl_2      = input.int(15, '', inline = 'Lvl 2', group = 'Levels Setting')

Show_Lvl_3 = input.bool(true, 'Level 3', inline = 'Lvl 3', group = 'Levels Setting')
Lvl_3      = input.int(22, '', inline = 'Lvl 3', group = 'Levels Setting')

Show_Lvl_4 = input.bool(true, 'Level 4', inline = 'Lvl 4', group = 'Levels Setting')
Lvl_4      = input.int(30, '', inline = 'Lvl 4', group = 'Levels Setting')

Show_Lvl_5 = input.bool(true, 'Level 5', inline = 'Lvl 5', group = 'Levels Setting')
Lvl_5      = input.int(38, '', inline = 'Lvl 5', group = 'Levels Setting')

Show_Lvl_6 = input.bool(true, 'Level 6', inline = 'Lvl 6', group = 'Levels Setting')
Lvl_6      = input.int(42, '', inline = 'Lvl 6', group = 'Levels Setting')

Show_Lvl_7 = input.bool(true, 'Level 7', inline = 'Lvl 7', group = 'Levels Setting')
Lvl_7      = input.int(50, '', inline = 'Lvl 7', group = 'Levels Setting')

Show_Lvl_8 = input.bool(true, 'Level 8', inline = 'Lvl 8', group = 'Levels Setting')
Lvl_8      = input.int(58, '', inline = 'Lvl 8', group = 'Levels Setting')

Show_Lvl_9 = input.bool(true, 'Level 9', inline = 'Lvl 9', group = 'Levels Setting')
Lvl_9      = input.int(62, '', inline = 'Lvl 9', group = 'Levels Setting')

Show_Lvl_10 = input.bool(true, 'Level 10', inline = 'Lvl 10', group = 'Levels Setting')
Lvl_10      = input.int(70, '', inline = 'Lvl 10', group = 'Levels Setting')

Show_Lvl_11 = input.bool(true, 'Level 11', inline = 'Lvl 11', group = 'Levels Setting')
Lvl_11      = input.int(78, '', inline = 'Lvl 11', group = 'Levels Setting')

Show_Lvl_12 = input.bool(true, 'Level 12', inline = 'Lvl 12', group = 'Levels Setting')
Lvl_12      = input.int(85, '', inline = 'Lvl 12', group = 'Levels Setting')

Show_Lvl_13 = input.bool(true, 'Level 13', inline = 'Lvl 13', group = 'Levels Setting')
Lvl_13      = input.int(90, '', inline = 'Lvl 13', group = 'Levels Setting')


RSI_Short = ta.rsi(close, Len_Short)
RSI_Mid   = ta.rsi(close, Len_Mid)
RSI_Long  = ta.rsi(close, Len_Long)


plot(RSI_Short, 'Short RSI', color = Color_Short, linewidth = 2, display = Show_Short ? display.all : display.none)
plot(RSI_Mid  , 'Middle RSI', color = Color_Mid  , linewidth = 2, display = Show_Mid   ? display.all : display.none)
plot(RSI_Long , 'Long RSI', color = Color_Long , linewidth = 2, display = Show_Long  ? display.all : display.none)

// hline(0, linestyle = hline.style_dashed)
hline(Lvl_1, linestyle = hline.style_dashed, display = Show_Lvl_1 ? display.all : display.none)
a = hline(Lvl_2, linestyle = hline.style_dashed, display = Show_Lvl_2 ? display.all : display.none)
b = hline(Lvl_3, linestyle = hline.style_dashed, display = Show_Lvl_3 ? display.all : display.none)
c = hline(Lvl_4, linestyle = hline.style_dashed, display = Show_Lvl_4 ? display.all : display.none)
d = hline(Lvl_5, linestyle = hline.style_dashed, display = Show_Lvl_5 ? display.all : display.none)
e = hline(Lvl_6, linestyle = hline.style_dashed, display = Show_Lvl_6 ? display.all : display.none)
hline(Lvl_7, linestyle = hline.style_dashed, color = color.red, display = Show_Lvl_7 ? display.all : display.none)
f = hline(Lvl_8, linestyle = hline.style_dashed, display = Show_Lvl_8 ? display.all : display.none)
g = hline(Lvl_9, linestyle = hline.style_dashed, display = Show_Lvl_9 ? display.all : display.none)
h = hline(Lvl_10, linestyle = hline.style_dashed, display = Show_Lvl_10 ? display.all : display.none)
i = hline(Lvl_11, linestyle = hline.style_dashed, display = Show_Lvl_11 ? display.all : display.none)
j = hline(Lvl_12, linestyle = hline.style_dashed, display = Show_Lvl_12 ? display.all : display.none)
hline(Lvl_13, linestyle = hline.style_dashed, display = Show_Lvl_13 ? display.all : display.none)
// hline(100, linestyle = hline.style_dashed)


fill(d, e, Color_LP, 'Low Potential', display = Show_LP ? display.all : display.none)
fill(f, g, Color_LP, 'Low Potential', display = Show_LP ? display.all : display.none)

fill(b, c, Color_MP, 'Mid Potential', display = Show_MP ? display.all : display.none)
fill(h, i, Color_MP, 'Mid Potential', display = Show_MP ? display.all : display.none)

fill(a, b, Color_HP, 'High Potential', display =Show_HP ? display.all : display.none)
fill(i, j, Color_HP, 'High Potential', display =Show_HP ? display.all : display.none)
