// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Sivchay

//@version=5
indicator("Simple RSI")

//input
RSI_len = input(14, title="RSI Length", tooltip="Amount of candles used to calculate", display=display.data_window, group="RSI Params")
Up_thres = input(70, title="Upper Threshold", tooltip="RSI upper thresold (under bought)", display=display.data_window, group="RSI Params")
Low_thres = input(30, title="Lower Threshold", tooltip="RSI lower thresold (over bought)", display=display.data_window, group="RSI Params")


//Calculations 
RSI = ta.rsi(close, RSI_len)
under = ta.crossunder(RSI, Low_thres)
over = ta.crossover(RSI, Up_thres)

//Plotting Panel
plot(RSI)
lower_thres = hline(Low_thres, title="under bought",color=color.green, linestyle = hline.style_solid)
upper_thres = hline(Up_thres, title="over bought",color=color.red, linestyle = hline.style_solid)
fill(upper_thres, lower_thres, color.new(color.blue, 85))

//Plotting Chart
plotshape(under, title="under bought", style=shape.triangleup, location = location.belowbar, color=color.green, size=size.tiny, force_overlay=true )
plotshape(over, title="over bought",  style=shape.triangledown, location = location.abovebar, color=color.red, size=size.tiny, force_overlay=true )
