// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © FriendOfTheTrend

//@version=6
indicator("Stock Screener", overlay=true)

//Row 1 = Ticker names
//Row 2 = Volume
var volumeTrendOn = input.bool(true, title="Volume Spike & Trend On/Off", group="Volume")
var volumeTrendThreshold = input.float(120, title="Volume Trend Threshold", group="Volume")
var volumeSpikeThreshold = input.float(3.0, title="Volume Spike Threshold", group="Volume")
var volumeLength = input.int(50, title="Lookback Length For Volume Spike SMA", group="Volume")

//Row 3 = Volatility
var volatilityOn = input.bool(true, title="Volatility On/Off", group="Volatility")
var volatilityThreshold = input.int(90, title="Volatility Threshold", group="Volatility")

//Row 4 = Oscillator
var oscillatorOn = input.bool(true, title="Oscillator On/Off", group="Oscillator")
var oscillatorToUse = input.string("RSI", title="Oscillator To Use", options=["RSI", "CCI"], group="Oscillator")
rsiSource = input.source(close, title="RSI Source", group="Oscillator")
var rsiLength = input.int(14, title="RSI Length", group="Oscillator")
var rsiOverboughtThreshold = input.int(70, title="RSI Overbought Threshold", group="Oscillator")
var rsiOversoldThreshold = input.int(30, title="RSI Oversold Threshold", group="Oscillator")
cciSource = input.source(hlc3, title="CCI Source", group="Oscillator")
var cciLength = input.int(20, title="CCI Length", group="Oscillator")
var cciUpperThreshold = input.int(100, title="CCI Upper Threshold", group="Oscillator")
var cciLowerThreshold = input.int(-100, title="CCI Lower Threshold", group="Oscillator")

//Row 5 = Big Candles
var bigCandlesOn = input.bool(true, title="Big Candles On/Off", group="Big Candles")
var bigCandleThreshold = input.float(3.0, title="Big Candle Multiplier Threshold", group="Big Candles")
var bigCandleLookback = input.int(50, title="Lookback Length To Get Average Candle Size", group="Big Candles")

//Row 6 = Daily Level Touches & Trends
var dailyLevelsOn = input.bool(true, title="All Daily Level Touches & Trend On/Off", group="Daily Trend & Levels")
var dailyHighLowOn = input.bool(true, title="Previous Daily High & Low Level Touches On/Off", group="Daily Trend & Levels")
var dailyOpenOn = input.bool(true, title="Previous & Current Daily Open Level Touches On/Off", group="Daily Trend & Levels")
var dailyCloseOn = input.bool(true, title="Previous Daily Close Level Touches On/Off", group="Daily Trend & Levels")
var nyOpenOn = input.bool(true, title="Regular 930am(NY Time) Open Level Touches On/Off", group="Daily Trend & Levels")
var midnightOpenOn = input.bool(false, title="Midnight 12am(NY Time) Open Level Touches On/Off", group="Daily Trend & Levels")
var asiaOpenOn = input.bool(false, title="Asian Session 8pm(NY Time) Open Level Touches On/Off", group="Daily Trend & Levels")
var londonOpenOn = input.bool(false, title="London Session 2am(NY Time) Open Level Touches On/Off", group="Daily Trend & Levels")
var showDailyLevelsOnChart = input.bool(true, title="Show All Turned On Daily Levels On The Chart", group="Daily Trend & Levels")
var showDailyLevelLabels = input.bool(true, title="Show Labels For Each Daily Level", group="Daily Trend & Levels")
var dailyLineColor = input.color(color.gray, title="Line Color For All Daily Levels", group="Daily Trend & Levels")

//Row 7 = VWAP #1
var vwap1On = input.bool(true, title="VWAP #1 On/Off", group="VWAP #1")
var vwap1ShowOnChart = input.bool(true, title="Show VWAP #1 On The Chart", group="VWAP #1")
var vwap1TF = input.string("1D", title="VWAP #1 Timeframe", options=["60", "120", "240", "360", "720", "1D", "1W", "1M", "3M", "12M"], group="VWAP #1")
var vwap1Color = input.color(color.aqua, title="VWAP #1 Color", group="VWAP #1")
var vwap1LineWidth = input.int(1, title="VWAP #1 Line Width", group="VWAP #1")

//Row 8 = VWAP #2
var vwap2On = input.bool(true, title="VWAP #2 On/Off", group="VWAP #2")
var vwap2ShowOnChart = input.bool(true, title="Show VWAP #2 On The Chart", group="VWAP #2")
var vwap2TF = input.string("1W", title="VWAP #2 Timeframe", options=["60", "120", "240", "360", "720", "1D", "1W", "1M", "3M", "12M"], group="VWAP #2")
var vwap2Color = input.color(color.fuchsia, title="VWAP #2 Color", group="VWAP #2")
var vwap2LineWidth = input.int(2, title="VWAP #2 Line Width", group="VWAP #2")

//Allow user to choose if they want to run the scanner on a different timeframe than their chart
var scannerTimeframeChoice = input.string("Same As Chart", title="Timeframe For Scanner To Run On", options=["Same As Chart", "Timeframe Different Than My Chart"], group="Screener Timeframe")
var customScannerTimeframe = input.timeframe("", title="Custom Timeframe To Use", group="Screener Timeframe")

var scannerTimeframe = timeframe.period
if scannerTimeframeChoice == "Same As Chart"
    scannerTimeframe := timeframe.period
if scannerTimeframeChoice == "Timeframe Different Than My Chart"
    scannerTimeframe := customScannerTimeframe

//Text Size
var scannerTextSize = input.int(9, title="Text Font Size", group="Text Size")

//Table, Text, BG & Alert Colors
var textColor = input.color(color.white, title="Text Color", group="Colors")
var tickerLabelColor = input.color(color.rgb(0, 0, 0), title="Label & Ticker Background Color", group="Colors")
var neutralColor = input.color(color.rgb(52, 52, 52), title="Neutral Background Color", group="Colors")
var normalAlertColor = input.color(color.rgb(0, 130, 147), title="Alert Background Color", group="Colors")
var brightAlertColor = input.color(color.rgb(152, 43, 171), title="Important Alert Background Color", group="Colors")
var bullishColor = input.color(color.rgb(67, 149, 69), title="Bullish Trend Background Color", group="Colors")
var bearishColor = input.color(color.rgb(133, 42, 42), title="Bearish Trend Background Color", group="Colors")

//Label Offset
var labelOffset = input.int(35, title="Label Offset In Bars", group="Label Offset")

//Tickers To Scan
var ticker1On = input.bool(true, title="Ticker 1 On/Off", group="Tickers To Scan")
var ticker1 = input.symbol("COINBASE:BTCUSD", title="Ticker #1", group="Tickers To Scan")

var ticker2On = input.bool(true, title="Ticker 2 On/Off", group="Tickers To Scan")
var ticker2 = input.symbol("COINBASE:ETHUSD", title="Ticker #2", group="Tickers To Scan")

var ticker3On = input.bool(true, title="Ticker 3 On/Off", group="Tickers To Scan")
var ticker3 = input.symbol("COINBASE:SOLUSD", title="Ticker #3", group="Tickers To Scan")

var ticker4On = input.bool(true, title="Ticker 4 On/Off", group="Tickers To Scan")
var ticker4 = input.symbol("COINBASE:XRPUSD", title="Ticker #4", group="Tickers To Scan")

var ticker5On = input.bool(true, title="Ticker 5 On/Off", group="Tickers To Scan")
var ticker5 = input.symbol("COINBASE:LINKUSD", title="Ticker #5", group="Tickers To Scan")

var ticker6On = input.bool(true, title="Ticker 6 On/Off", group="Tickers To Scan")
var ticker6 = input.symbol("COINBASE:DOGEUSD", title="Ticker #6", group="Tickers To Scan")

var ticker7On = input.bool(true, title="Ticker 7 On/Off", group="Tickers To Scan")
var ticker7 = input.symbol("COINBASE:LTCUSD", title="Ticker #7", group="Tickers To Scan")

var ticker8On = input.bool(true, title="Ticker 8 On/Off", group="Tickers To Scan")
var ticker8 = input.symbol("COINBASE:UNIUSD", title="Ticker #8", group="Tickers To Scan")

var ticker9On = input.bool(true, title="Ticker 9 On/Off", group="Tickers To Scan")
var ticker9 = input.symbol("COINBASE:DOTUSD", title="Ticker #9", group="Tickers To Scan")

var ticker10On = input.bool(true, title="Ticker 10 On/Off", group="Tickers To Scan")
var ticker10 = input.symbol("COINBASE:XLMUSD", title="Ticker #10", group="Tickers To Scan")

//Table Location
var tableLocation = position.bottom_right
var tablePosition = input.string("Bottom Right", title="Table Position", options=["Top Right", "Top Left", "Top Center", "Middle Right", "Middle Left", "Middle Center", "Bottom Right", "Bottom Left", "Bottom Center"], group="Trend Score Table")

if tablePosition == "Top Right" 
    tableLocation := position.top_right
if tablePosition == "Top Left" 
    tableLocation := position.top_left
if tablePosition == "Top Center" 
    tableLocation := position.top_center
if tablePosition == "Middle Right" 
    tableLocation := position.middle_right
if tablePosition == "Middle Left" 
    tableLocation := position.middle_left
if tablePosition == "Middle Center" 
    tableLocation := position.middle_center
if tablePosition == "Bottom Right" 
    tableLocation := position.bottom_right
if tablePosition == "Bottom Left" 
    tableLocation := position.bottom_left
if tablePosition == "Bottom Center" 
    tableLocation := position.bottom_center

//Hide Screener Table From View
makeScreenerInvisible = input.bool(false, title="Do Not Show The Screener On The Chart", group="Hide Screener Table")

//New VWAP Timeframe
newVWAP1Candle = timeframe.change(vwap1TF)
newVWAP2Candle = timeframe.change(vwap2TF)
newDay = timeframe.change("D")

//Volume Functions
//Volume Trend Score
volumeTrend() =>
    float volumeTrend = na

    //Calculate volume trend score
    if volumeTrendOn
        var numberOfBarsPerDay = 1
        if newDay
            numberOfBarsPerDay := 1
        if not newDay
            numberOfBarsPerDay += 1
        var barsPerDay = 1
        if newDay
            barsPerDay := numberOfBarsPerDay[1]
        volumeShort1 = ta.sma(volume, 2)
        volumeShort2 = ta.sma(volume, 3)
        volumeShort3 = ta.sma(volume, 7)
        volumeShort4 = ta.sma(volume, 15)
        volumeLong = ta.sma(volume, barsPerDay)
        volumeTrend1 = volumeShort1 / volumeLong
        volumeTrend2 = volumeShort2 / volumeLong
        volumeTrend3 = volumeShort3 / volumeLong
        volumeTrend4 = volumeShort4 / volumeLong
        volumeTrend := (((volumeTrend1 + volumeTrend2 + volumeTrend3 + volumeTrend4) / 4) * 100)

    volumeTrend

//Volume Spike
volumeSpike() =>
    volumeSpike = false

    //Calculate volume spike
    if volumeTrendOn
        volumeMA = ta.sma(volume, volumeLength)
        if volume >= (volumeMA * volumeSpikeThreshold)
            volumeSpike := true

    volumeSpike

//Volume Color
volumeColor(volumeSpike, volumeTrend) =>
    volumeColor = neutralColor

    //Assign notification color for high volume or volume spike
    if volumeTrendOn
        if not volumeSpike
            if volumeTrend >= volumeTrendThreshold
                volumeColor := normalAlertColor
        if volumeSpike or volumeSpike[1]
            volumeColor := brightAlertColor

    volumeColor

//Volume Text
volumeText(volumeSpike, volumeTrend) =>
    volumeText = str.tostring(volumeTrend, "#")

    //Assign notification text for volume spike
    if volumeTrendOn
        if volumeSpike
            volumeText := str.tostring("Spike")

    volumeText

//Volatility Functions
//Volatility Trend Score
volatility() =>
    float volatility = na

    //Calculate volatility
    if volatilityOn
        candleSizeOC = close >= open ? close - open : open - close
        candleSizeOC5 = candleSizeOC + candleSizeOC[1] + candleSizeOC[2] + candleSizeOC[3] + candleSizeOC[4]
        benchmarkOC60 = candleSizeOC5[60]
        benchmarkOC120 = candleSizeOC5[120]
        benchmarkOC240 = candleSizeOC5[240]
        benchmarkOC480 = candleSizeOC5[480]
        benchmarkOC720 = candleSizeOC5[720]
        benchmarkOC1380 = candleSizeOC5[1380]
        benchmarkOC2000 = candleSizeOC5[2000]
        benchmarkAverage = (benchmarkOC60 + benchmarkOC120 + benchmarkOC240 + benchmarkOC480 + benchmarkOC720 + benchmarkOC1380 + benchmarkOC2000) / 7
        volatility := ((candleSizeOC5 / benchmarkAverage) * 100)

    volatility

//Volatility Color
volatilityColor(volatility) =>
    volatilityColor = neutralColor

    //Assign notification color for high volatility
    if volatilityOn
        if volatility >= volatilityThreshold
            volatilityColor := normalAlertColor

    volatilityColor

//Oscillator Functions
oscillatorValue() =>
    float oscillatorValue = na

    //Assign oscillator type and calculate values
    if oscillatorOn
        if oscillatorToUse == "RSI"
            oscillatorValue := ta.rsi(rsiSource, rsiLength)
        if oscillatorToUse == "CCI"
            oscillatorValue := ta.cci(cciSource, cciLength)

    oscillatorValue

//Oscillator Text Label
oscillatorLabel() =>
    oscillatorLabel = "-"

    //Assign oscillator label text
    if oscillatorOn
        if oscillatorToUse == "RSI"
            oscillatorLabel := "RSI"
        if oscillatorToUse == "CCI"
            oscillatorLabel := "CCI"

    oscillatorLabel

//Oscillator Color
oscillatorColor(oscillatorValue) =>
    oscillatorColor = neutralColor

    //Assign notification color for oscillator hitting upper or lower thresholds
    if oscillatorOn
        if oscillatorToUse == "RSI"
            if oscillatorValue >= rsiOverboughtThreshold or oscillatorValue <= rsiOversoldThreshold
                oscillatorColor := brightAlertColor
        if oscillatorToUse == "CCI"
            if oscillatorValue >= cciUpperThreshold or oscillatorValue <= cciLowerThreshold
                oscillatorColor := brightAlertColor

    oscillatorColor

//Big Candle Functions
//Big Candle Size Calculations To Text
bigCandle() =>
    bigCandleText = "-"

    //Identify big candles and wicks
    if bigCandlesOn
        //Calcylate candle sizes
        candleSizeOC = close > open ? close - open : open - close
        candleSizeHL = high - low
        topWickSize = close > open ? high - close : high - open
        bottomWickSize = close > open ? open - low : close - low
        //Calculate average candle sizes
        avgCandleOC = ta.sma(candleSizeOC, bigCandleLookback)
        avgCandleHL = ta.sma(candleSizeHL, bigCandleLookback)
        avgCandleTW = ta.sma(topWickSize, bigCandleLookback)
        avgCandleBW = ta.sma(bottomWickSize, bigCandleLookback)
        //Determine if candle is larger than an average and if it's size meets the threshold
        if candleSizeOC >= (avgCandleOC * bigCandleThreshold)
            bigCandleText := "OC"
        if candleSizeHL >= (avgCandleHL * bigCandleThreshold)
            bigCandleText := "HL"
        if topWickSize >= (avgCandleTW * bigCandleThreshold)
            bigCandleText := "TW"
        if bottomWickSize >= (avgCandleBW * bigCandleThreshold)
            bigCandleText := "BW"

    bigCandleText

//Big Candle Color
bigCandleColor(bigCandleText) =>
    bigCandleColor = neutralColor

    //Identify if a big candle is detected and update cell background color
    if bigCandlesOn
        if bigCandleText != "-"
            bigCandleColor := normalAlertColor

    bigCandleColor

//Daily Level Functions
//Daily Levels & Trends
dailyLevelText(dailyCloseValue) =>
    var dailyHighPrevious = 0.0
    var dailyLowPrevious = 0.0
    var dailyOpenPrevious = 0.0
    var dailyOpenToday = 0.0
    var dailyHighToday = 0.0
    var dailyLowToday = 0.0
    var openNY = 0.0
    var openAsia = 0.0
    var openLondon = 0.0
    var openMidnight = 0.0
    var dailyClose = 0.0
    dailyLevelText = "-"
    
    //NY 930 am open touches
    if nyOpenOn
        if not na(time("1", "0930-0931", "America/New_York"))
            openNY := open
        //Notify of open touches after open candle closes
        if na(time("1", "0930-0931", "America/New_York"))
            if low <= openNY and high >= openNY
                dailyLevelText := "930am"

    //NY Midnight 12am open touches
    if midnightOpenOn
        if not na(time("1", "0000-0001", "America/New_York"))
            openMidnight := open
        //Notify of open touches after open candle closes
        if na(time("1", "0000-0001", "America/New_York"))
            if low <= openMidnight and high >= openMidnight
                dailyLevelText := "12am"

    //Asia 8pm open touches
    if asiaOpenOn
        if not na(time("1", "2000-2001", "America/New_York"))
            openAsia := open
        //Notify of open touches after open candle closes
        if na(time("1", "2000-2001", "America/New_York"))
            if low <= openAsia and high >= openAsia
                dailyLevelText := "Asia"

    //London 2am open touches
    if londonOpenOn
        if not na(time("1", "0200-0201", "America/New_York"))
            openLondon := open
        //Notify of open touches after open candle closes
        if na(time("1", "0200-0201", "America/New_York"))
            if low <= openLondon and high >= openLondon
                dailyLevelText := "London"

    //Previous & current daily open touches
    if dailyOpenOn
        if newDay
            dailyOpenToday := open
            dailyOpenPrevious := dailyOpenToday[1]
        //Don't notify open touch when new day starts
        if not newDay
            if low <= dailyOpenToday and high >= dailyOpenToday
                dailyLevelText := "Open"
        //Notify of previous daily open touch any time
        if low <= dailyOpenPrevious and high >= dailyOpenPrevious
            dailyLevelText := "< Open"

    //Daily highs and lows
    if dailyHighLowOn
        //Set values at new day open
        if newDay
            dailyHighToday := high
            dailyLowToday := low
            dailyHighPrevious := dailyHighToday[1]
            dailyLowPrevious := dailyLowToday[1]
        //Update highs & lows throughout the day
        if not newDay
            if high > dailyHighToday
                dailyHighToday := high
            if low < dailyLowToday
                dailyLowToday := low
        //Notify of level touches and trends
        if low > dailyHighPrevious
            dailyLevelText := "Above"
        if high < dailyLowPrevious
            dailyLevelText := "Below"
        if low <= dailyHighPrevious and high >= dailyHighPrevious
            dailyLevelText := "High"
        if low <= dailyLowPrevious and high >= dailyLowPrevious
            dailyLevelText := "Low"

    //Daily Close
    if dailyCloseOn
        //Set values at new day open
        if newDay
            dailyClose := dailyCloseValue
        //Notify of level touches
        if low <= dailyClose and high >= dailyClose
            dailyLevelText := "Close"

    dailyLevelText

//Daily Level & Trend Colors
dailyLevelColor(dailyLevelText) =>
    dailyLevelColor = neutralColor

    //Identify trends and level touches and update cell background color
    if dailyLevelText == "Above"
        dailyLevelColor := bullishColor
    if dailyLevelText == "Below"
        dailyLevelColor := bearishColor
    if dailyLevelText == "High"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "Low"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "Close"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "Open"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "< Open"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "930am"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "Asia"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "London"
        dailyLevelColor := brightAlertColor
    if dailyLevelText == "12am"
        dailyLevelColor := brightAlertColor

    dailyLevelColor

//VWAP Functions
//VWAP Calculation Text
vwap(newVWAPCandle) =>
    vwap = ta.vwap(hlc3, newVWAPCandle)
    vwapText = "-"

    //Identify vwap trend and touches
    if close > vwap and low > vwap
        vwapText := "Above"
    if close < vwap and high < vwap
        vwapText := "Below"
    if low <= vwap and high >= vwap
        vwapText := "VWAP"

    vwapText

//VWAP Color
vwapColor(vwapText) =>
    vwapColor = neutralColor

    //Identify vwap trend and touches and update cell background color
    if vwapText == "Above"
        vwapColor := bullishColor
    if vwapText == "Below"
        vwapColor := bearishColor
    if vwapText == "VWAP"
        vwapColor := brightAlertColor

    vwapColor

//Strong Trend function
//Notify When Daily Level & VWAP Trends Align
strongTrend(dailyText, vwap1Text, vwap2Text) =>
    allSignalsAlignColor = tickerLabelColor
    
    if vwap1Text == "Above" and vwap2Text == "Above" and (dailyText == "Above" or dailyText == "High")
        allSignalsAlignColor := bullishColor
    if vwap1Text == "Below" and vwap2Text == "Below" and (dailyText == "Below" or dailyText == "Low")
        allSignalsAlignColor := bearishColor
        
    allSignalsAlignColor

//Create variables to use for getting the right daily values on historical and realtime bars
HTF = barstate.isrealtime ? 1 : 0
CTF = barstate.isrealtime ? 0 : 1

//Get close values of previous daily candle - using a seperate request.security function because values on chart don't always match actual close price due to dark pools and after hours trading
t1DailyClose = request.security(ticker1, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t2DailyClose = request.security(ticker2, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t3DailyClose = request.security(ticker3, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t4DailyClose = request.security(ticker4, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t5DailyClose = request.security(ticker5, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t6DailyClose = request.security(ticker6, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t7DailyClose = request.security(ticker7, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t8DailyClose = request.security(ticker8, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t9DailyClose = request.security(ticker9, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]
t10DailyClose = request.security(ticker10, "1D", close[HTF], ignore_invalid_symbol=true)[CTF]

//Get Function Values From Other Tickers
[t1VolumeTrend, t1VolumeSpike, t1Volatility, t1Oscillator, t1BigCandle, t1High, t1Low, t1Open, t1Close, t1DailyLevelText, t1vwap1, t1vwap2] = request.security(ticker1, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t1DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t2VolumeTrend, t2VolumeSpike, t2Volatility, t2Oscillator, t2BigCandle, t2High, t2Low, t2Open, t2Close, t2DailyLevelText, t2vwap1, t2vwap2] = request.security(ticker2, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t2DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t3VolumeTrend, t3VolumeSpike, t3Volatility, t3Oscillator, t3BigCandle, t3High, t3Low, t3Open, t3Close, t3DailyLevelText, t3vwap1, t3vwap2] = request.security(ticker3, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t3DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t4VolumeTrend, t4VolumeSpike, t4Volatility, t4Oscillator, t4BigCandle, t4High, t4Low, t4Open, t4Close, t4DailyLevelText, t4vwap1, t4vwap2] = request.security(ticker4, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t4DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t5VolumeTrend, t5VolumeSpike, t5Volatility, t5Oscillator, t5BigCandle, t5High, t5Low, t5Open, t5Close, t5DailyLevelText, t5vwap1, t5vwap2] = request.security(ticker5, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t5DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t6VolumeTrend, t6VolumeSpike, t6Volatility, t6Oscillator, t6BigCandle, t6High, t6Low, t6Open, t6Close, t6DailyLevelText, t6vwap1, t6vwap2] = request.security(ticker6, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t6DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t7VolumeTrend, t7VolumeSpike, t7Volatility, t7Oscillator, t7BigCandle, t7High, t7Low, t7Open, t7Close, t7DailyLevelText, t7vwap1, t7vwap2] = request.security(ticker7, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t7DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t8VolumeTrend, t8VolumeSpike, t8Volatility, t8Oscillator, t8BigCandle, t8High, t8Low, t8Open, t8Close, t8DailyLevelText, t8vwap1, t8vwap2] = request.security(ticker8, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t8DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t9VolumeTrend, t9VolumeSpike, t9Volatility, t9Oscillator, t9BigCandle, t9High, t9Low, t9Open, t9Close, t9DailyLevelText, t9vwap1, t9vwap2] = request.security(ticker9, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t9DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)
[t10VolumeTrend, t10VolumeSpike, t10Volatility, t10Oscillator, t10BigCandle, t10High, t10Low, t10Open, t10Close, t10DailyLevelText, t10vwap1, t10vwap2] = request.security(ticker10, scannerTimeframe, [volumeTrend(), volumeSpike(), volatility(), oscillatorValue(), bigCandle(), high, low, open, close, dailyLevelText(t10DailyClose), vwap(newVWAP1Candle), vwap(newVWAP2Candle)], ignore_invalid_symbol=true)

//Create The Scanner Table On The Last Bar And Show Values For Each Ticker
var scannerTable = table.new(tableLocation, columns=18, rows=10)
if barstate.islast and not makeScreenerInvisible
    //Ticker Name Row
    table.cell(table_id=scannerTable, column=0, row=0, text="Ticker", height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
    if ticker1On
        table.cell(table_id=scannerTable, column=1, row=0, text=str.tostring(syminfo.ticker(ticker1)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t1DailyLevelText, t1vwap1, t1vwap2))
    if ticker2On
        table.cell(table_id=scannerTable, column=2, row=0, text=str.tostring(syminfo.ticker(ticker2)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t2DailyLevelText, t2vwap1, t2vwap2))
    if ticker3On
        table.cell(table_id=scannerTable, column=3, row=0, text=str.tostring(syminfo.ticker(ticker3)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t3DailyLevelText, t3vwap1, t3vwap2))
    if ticker4On
        table.cell(table_id=scannerTable, column=4, row=0, text=str.tostring(syminfo.ticker(ticker4)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t4DailyLevelText, t4vwap1, t4vwap2))
    if ticker5On
        table.cell(table_id=scannerTable, column=5, row=0, text=str.tostring(syminfo.ticker(ticker5)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t5DailyLevelText, t5vwap1, t5vwap2))
    if ticker6On
        table.cell(table_id=scannerTable, column=6, row=0, text=str.tostring(syminfo.ticker(ticker6)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t6DailyLevelText, t6vwap1, t6vwap2))
    if ticker7On
        table.cell(table_id=scannerTable, column=7, row=0, text=str.tostring(syminfo.ticker(ticker7)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t7DailyLevelText, t7vwap1, t7vwap2))
    if ticker8On
        table.cell(table_id=scannerTable, column=8, row=0, text=str.tostring(syminfo.ticker(ticker8)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t8DailyLevelText, t8vwap1, t8vwap2))
    if ticker9On
        table.cell(table_id=scannerTable, column=9, row=0, text=str.tostring(syminfo.ticker(ticker9)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t9DailyLevelText, t9vwap1, t9vwap2))
    if ticker10On
        table.cell(table_id=scannerTable, column=10, row=0, text=str.tostring(syminfo.ticker(ticker10)), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=strongTrend(t10DailyLevelText, t10vwap1, t10vwap2))
    //Volume Trend Score Row
    if volumeTrendOn
        table.cell(table_id=scannerTable, column=0, row=1, text="Volume", height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=1, text=volumeText(t1VolumeSpike, t1VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t1VolumeSpike, t1VolumeTrend))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=1, text=volumeText(t2VolumeSpike, t2VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t2VolumeSpike, t2VolumeTrend))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=1, text=volumeText(t3VolumeSpike, t3VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t3VolumeSpike, t3VolumeTrend))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=1, text=volumeText(t4VolumeSpike, t4VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t4VolumeSpike, t4VolumeTrend))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=1, text=volumeText(t5VolumeSpike, t5VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t5VolumeSpike, t5VolumeTrend))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=1, text=volumeText(t6VolumeSpike, t6VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t6VolumeSpike, t6VolumeTrend))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=1, text=volumeText(t7VolumeSpike, t7VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t7VolumeSpike, t7VolumeTrend))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=1, text=volumeText(t8VolumeSpike, t8VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t8VolumeSpike, t8VolumeTrend))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=1, text=volumeText(t9VolumeSpike, t9VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t9VolumeSpike, t9VolumeTrend))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=1, text=volumeText(t10VolumeSpike, t10VolumeTrend), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volumeColor(t10VolumeSpike, t10VolumeTrend))
    //Volatility Trend Score Row
    if volatilityOn
        table.cell(table_id=scannerTable, column=0, row=2, text="Volatility", height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=2, text=str.tostring(t1Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t1Volatility))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=2, text=str.tostring(t2Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t2Volatility))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=2, text=str.tostring(t3Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t3Volatility))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=2, text=str.tostring(t4Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t4Volatility))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=2, text=str.tostring(t5Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t5Volatility))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=2, text=str.tostring(t6Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t6Volatility))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=2, text=str.tostring(t7Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t7Volatility))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=2, text=str.tostring(t8Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t8Volatility))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=2, text=str.tostring(t9Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t9Volatility))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=2, text=str.tostring(t10Volatility, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=volatilityColor(t10Volatility))
    //Oscillator Value Row
    if oscillatorOn
        table.cell(table_id=scannerTable, column=0, row=3, text=oscillatorLabel(), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=3, text=str.tostring(t1Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t1Oscillator))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=3, text=str.tostring(t2Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t2Oscillator))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=3, text=str.tostring(t3Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t3Oscillator))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=3, text=str.tostring(t4Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t4Oscillator))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=3, text=str.tostring(t5Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t5Oscillator))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=3, text=str.tostring(t6Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t6Oscillator))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=3, text=str.tostring(t7Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t7Oscillator))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=3, text=str.tostring(t8Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t8Oscillator))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=3, text=str.tostring(t9Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t9Oscillator))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=3, text=str.tostring(t10Oscillator, "#"), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=oscillatorColor(t10Oscillator))
    //Big Candle Row
    if bigCandlesOn
        table.cell(table_id=scannerTable, column=0, row=4, text="Big Candle", height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=4, text=t1BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t1BigCandle))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=4, text=t2BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t2BigCandle))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=4, text=t3BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t3BigCandle))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=4, text=t4BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t4BigCandle))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=4, text=t5BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t5BigCandle))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=4, text=t6BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t6BigCandle))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=4, text=t7BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t7BigCandle))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=4, text=t8BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t8BigCandle))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=4, text=t9BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t9BigCandle))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=4, text=t10BigCandle, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=bigCandleColor(t10BigCandle))
    //Daily Level Touches & Trends Row
    if dailyLevelsOn
        table.cell(table_id=scannerTable, column=0, row=5, text="1D Levels", height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=5, text=t1DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t1DailyLevelText))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=5, text=t2DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t2DailyLevelText))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=5, text=t3DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t3DailyLevelText))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=5, text=t4DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t4DailyLevelText))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=5, text=t5DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t5DailyLevelText))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=5, text=t6DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t6DailyLevelText))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=5, text=t7DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t7DailyLevelText))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=5, text=t8DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t8DailyLevelText))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=5, text=t9DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t9DailyLevelText))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=5, text=t10DailyLevelText, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=dailyLevelColor(t10DailyLevelText))
    //VWAP #1 Row
    if vwap1On
        table.cell(table_id=scannerTable, column=0, row=6, text="VWAP " + str.tostring(vwap1TF), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=6, text=t1vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t1vwap1))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=6, text=t2vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t2vwap1))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=6, text=t3vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t3vwap1))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=6, text=t4vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t4vwap1))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=6, text=t5vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t5vwap1))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=6, text=t6vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t6vwap1))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=6, text=t7vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t7vwap1))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=6, text=t8vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t8vwap1))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=6, text=t9vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t9vwap1))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=6, text=t10vwap1, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t10vwap1))
    //VWAP #2 Row
    if vwap2On
        table.cell(table_id=scannerTable, column=0, row=7, text="VWAP " + str.tostring(vwap2TF), height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=tickerLabelColor)
        if ticker1On
            table.cell(table_id=scannerTable, column=1, row=7, text=t1vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t1vwap2))
        if ticker2On
            table.cell(table_id=scannerTable, column=2, row=7, text=t2vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t2vwap2))
        if ticker3On
            table.cell(table_id=scannerTable, column=3, row=7, text=t3vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t3vwap2))
        if ticker4On
            table.cell(table_id=scannerTable, column=4, row=7, text=t4vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t4vwap2))
        if ticker5On
            table.cell(table_id=scannerTable, column=5, row=7, text=t5vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t5vwap2))
        if ticker6On
            table.cell(table_id=scannerTable, column=6, row=7, text=t6vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t6vwap2))
        if ticker7On
            table.cell(table_id=scannerTable, column=7, row=7, text=t7vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t7vwap2))
        if ticker8On
            table.cell(table_id=scannerTable, column=8, row=7, text=t8vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t8vwap2))
        if ticker9On
            table.cell(table_id=scannerTable, column=9, row=7, text=t9vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t9vwap2))
        if ticker10On
            table.cell(table_id=scannerTable, column=10, row=7, text=t10vwap2, height=0, text_color=textColor, text_halign=text.align_center, text_valign= text.align_center, text_size=scannerTextSize, bgcolor=vwapColor(t10vwap2))

//VWAP Levels For The Chart Ticker
float vwap1 = na
float vwap2 = na

//Calculate VWAPs
if vwap1ShowOnChart
    vwap1 := ta.vwap(hlc3, newVWAP1Candle)
if vwap2ShowOnChart
    vwap2 := ta.vwap(hlc3, newVWAP2Candle)

//Show VWAP Lines On The Chart
plot(vwap1, title="VWAP #1", color=vwap1Color, linewidth=vwap1LineWidth, style=plot.style_circles)
plot(vwap2, title="VWAP #2", color=vwap2Color, linewidth=vwap2LineWidth, style=plot.style_circles)

//Daily Levels For The Chart Ticker
var float dailyPrevHigh = na
var float dailyPrevLow = na
var float dailyHighStillCalculating = na
var float dailyLowStillCalculating = na
var float dailyPrevOpen = na
var float dailyCurrentOpen = na
var float daily930NYOpen = na
var float daily12amMidnightOpen = na
var float daily8pmAsiaOpen = na
var float daily2amLondonOpen = na

//Calculate Each Daily Level For The Current Chart Ticker
if showDailyLevelsOnChart
    //NY 930 am open
    if nyOpenOn
        if not na(time("1", "0930-0931", "America/New_York"))
            daily930NYOpen := open

    //NY Midnight 12am open
    if midnightOpenOn
        if not na(time("1", "0000-0001", "America/New_York"))
            daily12amMidnightOpen := open

    //Asia 8pm open
    if asiaOpenOn
        if not na(time("1", "2000-2001", "America/New_York"))
            daily8pmAsiaOpen := open

    //London 2am open
    if londonOpenOn
        if not na(time("1", "0200-0201", "America/New_York"))
            daily2amLondonOpen := open

    //Previous & current daily open
    if dailyOpenOn
        if newDay
            dailyCurrentOpen := open
            dailyPrevOpen := dailyCurrentOpen[1]

    //Daily highs and lows
    if dailyHighLowOn
        //Set values at new day open
        if newDay
            dailyHighStillCalculating := high
            dailyLowStillCalculating := low
            dailyPrevHigh := dailyHighStillCalculating[1]
            dailyPrevLow := dailyLowStillCalculating[1]
        //Update highs & lows throughout the day
        if not newDay
            if high > dailyHighStillCalculating
                dailyHighStillCalculating := high
            if low < dailyLowStillCalculating
                dailyLowStillCalculating := low

//Plot Each Daily Level
plot(dailyPrevHigh, title="Previous Daily High", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(dailyPrevLow, title="Previous Daily Low", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(dailyPrevOpen, title="Previous Daily Open", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(dailyCurrentOpen, title="Current Daily Open", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(daily930NYOpen, title="930am NY Open", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(daily12amMidnightOpen, title="12am NY Midnight Open", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(daily8pmAsiaOpen, title="8pm Asia Open", color=dailyLineColor, linewidth=1, style=plot.style_line)
plot(daily2amLondonOpen, title="2am London Open", color=dailyLineColor, linewidth=1, style=plot.style_line)

//Show Labels For Each Daily Level
if showDailyLevelLabels
    if barstate.islast
        if dailyHighLowOn
            labelDailyHigh = label.new(bar_index + labelOffset, dailyPrevHigh, text="Prev Day High", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            labelDailyLow = label.new(bar_index + labelOffset, dailyPrevLow, text="Prev Day Low", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDailyHigh)
                label.delete(labelDailyLow)
        if dailyOpenOn
            labelDailyPrevOpen = label.new(bar_index + labelOffset, dailyPrevOpen, text="Prev Day Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            labelDailyCurrentOpen = label.new(bar_index + labelOffset, dailyCurrentOpen, text="Today's Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDailyPrevOpen)
                label.delete(labelDailyCurrentOpen)
        if nyOpenOn
            labelDaily930amOpen = label.new(bar_index + labelOffset, daily930NYOpen, text="930am Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDaily930amOpen)
        if midnightOpenOn
            labelDaily12amOpen = label.new(bar_index + labelOffset, daily12amMidnightOpen, text="12am Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDaily12amOpen)
        if asiaOpenOn
            labelDaily8pmOpen = label.new(bar_index + labelOffset, daily8pmAsiaOpen, text="Asia Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDaily8pmOpen)
        if londonOpenOn
            labelDaily2amOpen = label.new(bar_index + labelOffset, daily2amLondonOpen, text="London Open", xloc=xloc.bar_index, yloc=yloc.price, color=#00000000, style=label.style_label_right, textcolor=dailyLineColor, size=size.small, textalign=text.align_left)
            if barstate.isconfirmed
                label.delete(labelDaily2amOpen)

//Alerts
bullishTrendAlert = false
bearishTrendAlert = false

//Check if all signal align to give an alert
if strongTrend(t1DailyLevelText, t1vwap1, t1vwap2) == bullishColor or
 strongTrend(t2DailyLevelText, t2vwap1, t2vwap2) == bullishColor or
  strongTrend(t3DailyLevelText, t3vwap1, t3vwap2) == bullishColor or
   strongTrend(t4DailyLevelText, t4vwap1, t4vwap2) == bullishColor or
     strongTrend(t5DailyLevelText, t5vwap1, t5vwap2) == bullishColor or
      strongTrend(t6DailyLevelText, t6vwap1, t6vwap2) == bullishColor or
       strongTrend(t7DailyLevelText, t7vwap1, t7vwap2) == bullishColor or
         strongTrend(t8DailyLevelText, t8vwap1, t8vwap2) == bullishColor or
         strongTrend(t9DailyLevelText, t9vwap1, t9vwap2) == bullishColor or
          strongTrend(t10DailyLevelText, t10vwap1, t10vwap2) == bullishColor
    bullishTrendAlert := true
if strongTrend(t1DailyLevelText, t1vwap1, t1vwap2) == bearishColor or
 strongTrend(t2DailyLevelText, t2vwap1, t2vwap2) == bearishColor or
  strongTrend(t3DailyLevelText, t3vwap1, t3vwap2) == bearishColor or
   strongTrend(t4DailyLevelText, t4vwap1, t4vwap2) == bearishColor or
     strongTrend(t5DailyLevelText, t5vwap1, t5vwap2) == bearishColor or
      strongTrend(t6DailyLevelText, t6vwap1, t6vwap2) == bearishColor or
       strongTrend(t7DailyLevelText, t7vwap1, t7vwap2) == bearishColor or
         strongTrend(t8DailyLevelText, t8vwap1, t8vwap2) == bearishColor or
         strongTrend(t9DailyLevelText, t9vwap1, t9vwap2) == bearishColor or
          strongTrend(t10DailyLevelText, t10vwap1, t10vwap2) == bearishColor
    bearishTrendAlert := true

//Fire alerts when all signals align on one ticker
alertcondition(bullishTrendAlert, title="Bullish Trend Alert - Above Daily High & Both VWAPs", message="Bullish Alert -  Above VWAPs + Above Previous Day High")
alertcondition(bearishTrendAlert, title="Bearish Trend Alert - Below Daily Low & Both VWAPs", message="Bearish Alert -  Below VWAPs + Below Previous Day Low")

//Volume Alerts
volumeAlert = false

//Check for volume above threshold or volume spike to give an alert
if volumeColor(t1VolumeSpike, t1VolumeTrend) != neutralColor or
 volumeColor(t2VolumeSpike, t2VolumeTrend) != neutralColor or
  volumeColor(t3VolumeSpike, t3VolumeTrend) != neutralColor or
   volumeColor(t4VolumeSpike, t4VolumeTrend) != neutralColor or
     volumeColor(t5VolumeSpike, t5VolumeTrend) != neutralColor or
      volumeColor(t6VolumeSpike, t6VolumeTrend) != neutralColor or
       volumeColor(t7VolumeSpike, t7VolumeTrend) != neutralColor or
         volumeColor(t8VolumeSpike, t8VolumeTrend) != neutralColor or
          volumeColor(t9VolumeSpike, t9VolumeTrend) != neutralColor or
           volumeColor(t10VolumeSpike, t10VolumeTrend) != neutralColor
    volumeAlert := true

//Fire alerts when volume is high
alertcondition(volumeAlert, title="High Volume Alert", message="Volume Is Abnormally High")

//Volatility Alerts
volatilityAlert = false

//Check for volatility above threshold to give an alert
if volatilityColor(t1Volatility) != neutralColor or
 volatilityColor(t2Volatility) != neutralColor or
  volatilityColor(t3Volatility) != neutralColor or
   volatilityColor(t4Volatility) != neutralColor or
     volatilityColor(t5Volatility) != neutralColor or
      volatilityColor(t6Volatility) != neutralColor or
       volatilityColor(t7Volatility) != neutralColor or
         volatilityColor(t8Volatility) != neutralColor or
          volatilityColor(t9Volatility) != neutralColor or
           volatilityColor(t10Volatility) != neutralColor
    volatilityAlert := true

//Fire alerts when volatility is high
alertcondition(volatilityAlert, title="High Volatility Alert", message="Volatility Is Very High")

//Oscillator Alerts
oscillatorAlert = false

//Check for extreme oscillator values to give an alert
if oscillatorColor(t1Oscillator) != neutralColor or
 oscillatorColor(t2Oscillator) != neutralColor or
  oscillatorColor(t3Oscillator) != neutralColor or
   oscillatorColor(t4Oscillator) != neutralColor or
     oscillatorColor(t5Oscillator) != neutralColor or
      oscillatorColor(t6Oscillator) != neutralColor or
       oscillatorColor(t7Oscillator) != neutralColor or
         oscillatorColor(t8Oscillator) != neutralColor or
          oscillatorColor(t9Oscillator) != neutralColor or
           oscillatorColor(t10Oscillator) != neutralColor
    oscillatorAlert := true

//Fire alerts when oscillator is at the extreme of it's range
alertcondition(oscillatorAlert, title="Oscillator Is Extended Alert", message="Oscillator Is At The Extreme Of It's Range")

//Big Candle Alerts
bigCandleAlert = false

//Check for big candles to give an alert
if bigCandleColor(t1BigCandle) != neutralColor or
 bigCandleColor(t2BigCandle) != neutralColor or
  bigCandleColor(t3BigCandle) != neutralColor or
   bigCandleColor(t4BigCandle) != neutralColor or
     bigCandleColor(t5BigCandle) != neutralColor or
      bigCandleColor(t6BigCandle) != neutralColor or
       bigCandleColor(t7BigCandle) != neutralColor or
         bigCandleColor(t8BigCandle) != neutralColor or
          bigCandleColor(t9BigCandle) != neutralColor or
           bigCandleColor(t10BigCandle) != neutralColor
    bigCandleAlert := true

//Fire alerts when big candle is detected
alertcondition(bigCandleAlert, title="Big Candle Alert", message="Big Candle Detected")

//Daily Level Alerts
dailyLevelTouchAlert = false

//Check for daily level touches to give an alert
if dailyLevelColor(t1DailyLevelText) == brightAlertColor or
 dailyLevelColor(t2DailyLevelText) == brightAlertColor or
  dailyLevelColor(t3DailyLevelText) == brightAlertColor or
   dailyLevelColor(t4DailyLevelText) == brightAlertColor or
     dailyLevelColor(t5DailyLevelText) == brightAlertColor or
      dailyLevelColor(t6DailyLevelText) == brightAlertColor or
       dailyLevelColor(t7DailyLevelText) == brightAlertColor or
         dailyLevelColor(t8DailyLevelText) == brightAlertColor or
          dailyLevelColor(t9DailyLevelText) == brightAlertColor or
           dailyLevelColor(t10DailyLevelText) == brightAlertColor
    dailyLevelTouchAlert := true

//Fire alerts when a daily level is touched
alertcondition(dailyLevelTouchAlert, title="Daily Level Touch Alert", message="Daily Level Is Being Touched")

//VWAP Touch Alerts
vwapTouchAlert = false

//Check for VWAP touches to give an alert
if vwapColor(t1vwap1) == brightAlertColor or
 vwapColor(t2vwap1) == brightAlertColor or
  vwapColor(t3vwap1) == brightAlertColor or
   vwapColor(t4vwap1) == brightAlertColor or
     vwapColor(t5vwap1) == brightAlertColor or
      vwapColor(t6vwap1) == brightAlertColor or
       vwapColor(t7vwap1) == brightAlertColor or
         vwapColor(t8vwap1) == brightAlertColor or
          vwapColor(t9vwap1) == brightAlertColor or
           vwapColor(t10vwap1) == brightAlertColor or
             vwapColor(t1vwap2) == brightAlertColor or
              vwapColor(t2vwap2) == brightAlertColor or
               vwapColor(t3vwap2) == brightAlertColor or
                 vwapColor(t4vwap2) == brightAlertColor or
                  vwapColor(t5vwap2) == brightAlertColor or
                   vwapColor(t6vwap2) == brightAlertColor or
                     vwapColor(t7vwap2) == brightAlertColor or
                      vwapColor(t8vwap2) == brightAlertColor or
                       vwapColor(t9vwap2) == brightAlertColor or
                         vwapColor(t10vwap2) == brightAlertColor
    vwapTouchAlert := true

//Fire alerts when a vwap is touched
alertcondition(vwapTouchAlert, title="VWAP Touch Alert", message="VWAP Is Being Touched")
