//@version=5
indicator("Stoch-Candles SMA", overlay=true)

// Eingaben
len1 = input.int(20, title="EMA Periode 1", minval=1)
len2 = input.int(50, title="EMA Periode 2", minval=1)
len3 = input.int(200, title="EMA Periode 3", minval=1)
src  = input.source(close, title="Datenquelle")

// EMA-Berechnung
ema1 = ta.ema(src, len1)
ema2 = ta.ema(src, len2)
ema3 = ta.ema(src, len3)

// Darstellung mit **konstanten** Titeln
plot(ema1, title="EMA 20", color=color.blue,   linewidth=1)
plot(ema2, title="EMA 50", color=color.red, linewidth=1)
plot(ema3, title="EMA 200", color=color.orange,   linewidth=1)

// Input parameters
methodOvl = input.string(title="Overlay Method", defval="50-Line", options=["Signal Cross", "50-Line", "Value Compare", "Overbought/Oversold"])
periodK = input.int(8, minval=1, title="%K Period")
periodD = input.int(3, minval=1, title="%D Period")
slowing = input.int(3, minval=1, title="Slowing")
overBought = input.float(80.0, title="Overbought Level")
overSold = input.float(20.0, title="Oversold Level")

// Stochastic calculation
k = ta.stoch(close, high, low, periodK)
k_smooth = ta.sma(k, slowing)
d = ta.sma(k_smooth, periodD)


candleColor = close > open ? color.rgb(255, 255, 255)     // bullish  (white)
                           : color.rgb(61,  61,  61)      // bearish (dark-grey)


barsLimit = input.int(150, "Fenster", minval=1)
active    = bar_index >= last_bar_index - barsLimit + 1
// Plot candles with colors (including wicks)

if methodOvl == "Signal Cross" and  active
    candleColor := k_smooth > d ? (close > open ? color.green : color.teal) : k_smooth < d ? (close > open ? color.red : color.maroon) : color.gray

else if methodOvl == "50-Line" and active
    candleColor := k_smooth > 70 ? (close > open ? color.green : color.teal) : k_smooth < 50 ? (close > open ? color.red : color.maroon) :(close > open ? color.rgb(148, 164, 255): color.rgb(180, 180, 1))

else if methodOvl == "Value Compare" and active
    candleColor := k_smooth > k_smooth[1] ? (close > open ? color.green : color.teal) : k_smooth < k_smooth[1] ? (close > open ? color.red : color.maroon) : color.gray

else if methodOvl == "Overbought/Oversold" and active
    candleColor := (k_smooth > overBought) ? (close > open ? color.green : color.teal) : (k_smooth < overSold) ? (close > open ? color.red : color.maroon) :  (close > open ? color.rgb(148, 164, 255): color.rgb(180, 180, 1))




plotcandle( open ,  high ,    low   ,  close,   color   =candleColor   ,wickcolor   = candleColor  ,bordercolor =  candleColor   )
