"""
DS-TV Backtest Results: commodity-channel-index-cci
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         1.96%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         46.09%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — commodity-channel-index-cci
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length_CCI = 55
    Length_MA = 30
    Source_MA = "EMA"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate CCI
        self.cci = self.I(pta.cci, high, low, close, length=self.Length_CCI)
        
        # Calculate MA of CCI based on Source_MA selection
        def calculate_cci_ma():
            cci_values = pta.cci(high, low, close, length=self.Length_CCI)
            if cci_values is None:
                return pd.Series(0, index=close.index)
            
            if self.Source_MA == "EMA":
                return pta.ema(cci_values, length=self.Length_MA)
            elif self.Source_MA == "SMA":
                return pta.sma(cci_values, length=self.Length_MA)
            elif self.Source_MA == "SMMA / RMA":
                return pta.rma(cci_values, length=self.Length_MA)
            elif self.Source_MA == "WMA":
                return pta.wma(cci_values, length=self.Length_MA)
            elif self.Source_MA == "VWMA":
                return pta.vwma(cci_values, self.data.Volume, length=self.Length_MA)
            elif self.Source_MA == "RMA":
                return pta.rma(cci_values, length=self.Length_MA)
            elif self.Source_MA == "HMA":
                return pta.hma(cci_values, length=self.Length_MA)
            else:
                return pta.ema(cci_values, length=self.Length_MA)
        
        self.cci_ma = self.I(calculate_cci_ma)

    def next(self):
        if len(self.data) < max(self.Length_CCI, self.Length_MA) + 5:
            return
        
        # Buy signal: CCI crosses above 50 (bullish)
        if crossover(self.cci, 50):
            if not self.position:
                self.buy()
        
        # Sell signal: CCI crosses below 50 (bearish)
        elif crossover(50, self.cci):
            if self.position:
                self.position.close()