"""
DS-TV Backtest Results: cvd-momentum-divergence
============================================================

--- SPY ---
  Return                    10.57%
  Buy & Hold Return         16.91%
  Max Drawdown              -17.19%
  Sharpe Ratio              0.39
  Sortino Ratio             0.63
  Calmar Ratio              0.30
  Profit Factor             2.97
  Expectancy                3.69%
  SQN                       0.69
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                12.84%
  Worst Trade               -5.61%
  Avg Trade                 3.41%
  Exposure Time             28.20%
  Equity Final              110570.06$
  Equity Peak               111721.48$
  Avg Drawdown              -1.75%
  Max Drawdown Duration     124 days 00:00:00
  Max Trade Duration        136 days 00:00:00
  Avg Trade Duration        67 days 00:00:00
  Ann. Return               5.19%
  Ann. Volatility           13.24%

--- BTC ---
  Return                    -13.11%
  Buy & Hold Return         18.15%
  Max Drawdown              -39.53%
  Sharpe Ratio              -0.24
  Sortino Ratio             -0.32
  Calmar Ratio              -0.17
  Profit Factor             1.34
  Expectancy                0.68%
  SQN                       0.04
  # Trades                  18
  Win Rate                  77.78%
  Best Trade                9.35%
  Worst Trade               -29.41%
  Avg Trade                 0.30%
  Exposure Time             52.26%
  Equity Final              86891.46$
  Equity Peak               131877.26$
  Avg Drawdown              -5.66%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        104 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -6.78%
  Ann. Volatility           28.22%

--- QQQ ---
  Return                    6.69%
  Buy & Hold Return         21.32%
  Max Drawdown              -21.45%
  Sharpe Ratio              0.23
  Sortino Ratio             0.36
  Calmar Ratio              0.15
  Profit Factor             1.89
  Expectancy                4.19%
  SQN                       0.26
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                17.75%
  Worst Trade               -9.37%
  Avg Trade                 3.30%
  Exposure Time             21.20%
  Equity Final              106686.38$
  Equity Peak               107311.44$
  Avg Drawdown              -3.25%
  Max Drawdown Duration     196 days 00:00:00
  Max Trade Duration        130 days 00:00:00
  Avg Trade Duration        76 days 00:00:00
  Ann. Return               3.32%
  Ann. Volatility           14.66%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — cvd-momentum-divergence
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lenPrice = 100
    lenCVD = 100
    smooth = 5
    resetDaily = True
    resetHourInput = 9
    resetMinuteInput = 0
    scaleMult = 1.0
    invertHistogram = False

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate CVD momentum divergence
        def calc_cvd_divergence():
            cvd_cum = 0.0
            price_sum = 0.0
            price_count = 0
            last_reset_day = None
            
            cvd_values = []
            price_det_sm_values = []
            cvd_det_sm_values = []
            
            for i in range(len(close)):
                # Simulate reset at specific hour/minute (simplified for backtest)
                is_reset_time = False
                
                # Calculate delta (CVD contribution)
                h_minus_l = high.iloc[i] - low.iloc[i]
                h_minus_l = max(h_minus_l, 1e-10)
                delta = volume.iloc[i] * (close.iloc[i] - open_.iloc[i]) / h_minus_l
                
                # Update CVD accumulator
                if is_reset_time:
                    cvd_cum = 0.0
                else:
                    cvd_cum += delta
                
                # Calculate price detrending with rolling sum
                if is_reset_time:
                    price_sum = 0.0
                    price_count = 0
                else:
                    price_sum += close.iloc[i]
                    price_count += 1
                    if price_count > self.lenPrice:
                        price_sum -= close.iloc[i - self.lenPrice]
                        price_count = self.lenPrice
                
                price_ma = price_sum / price_count if price_count > 0 else close.iloc[i]
                price_det = close.iloc[i] - price_ma
                
                cvd_values.append(cvd_cum)
                price_det_sm_values.append(price_det)
                cvd_det_sm_values.append(cvd_cum)
            
            cvd_series = pd.Series(cvd_values, index=close.index)
            price_det_series = pd.Series(price_det_sm_values, index=close.index)
            cvd_det_series = pd.Series(cvd_det_sm_values, index=close.index)
            
            # Apply EMA smoothing
            cvd_ema = pta.ema(cvd_series, length=5)
            if cvd_ema is None:
                cvd_ema = cvd_series
            
            price_det_sm = pta.ema(price_det_series, length=self.smooth)
            if price_det_sm is None:
                price_det_sm = price_det_series
            
            # Detrend CVD
            cvd_ma = pta.sma(cvd_ema, length=self.lenCVD)
            if cvd_ma is None:
                cvd_ma = cvd_ema
            
            cvd_det = cvd_ema - cvd_ma
            cvd_det_sm = pta.ema(cvd_det, length=self.smooth)
            if cvd_det_sm is None:
                cvd_det_sm = cvd_det
            
            # Normalization
            price_det_sm_std = pta.stdev(price_det_sm, length=self.lenPrice)
            if price_det_sm_std is None:
                price_det_sm_std = pd.Series(1.0, index=close.index)
            
            cvd_det_sm_std = pta.stdev(cvd_det_sm, length=self.lenCVD)
            if cvd_det_sm_std is None:
                cvd_det_sm_std = pd.Series(1.0, index=close.index)
            
            # Avoid division by zero
            price_norm = price_det_sm / price_det_sm_std.replace(0, 1e-10)
            cvd_norm = cvd_det_sm / cvd_det_sm_std.replace(0, 1e-10)
            
            final_price = self.scaleMult * price_norm
            final_cvd = self.scaleMult * cvd_norm
            
            # Calculate divergence
            if self.invertHistogram:
                div_cvd = final_price - final_cvd
            else:
                div_cvd = final_cvd - final_price
            
            return final_price, final_cvd, div_cvd
        
        self.final_price, self.final_cvd, self.div_cvd = self.I(calc_cvd_divergence)

    def next(self):
        # Trading logic based on CVD-Price divergence
        if len(self.data) < 2:
            return
        
        current_div = self.div_cvd[-1]
        prev_div = self.div_cvd[-2]
        
        # Buy when divergence crosses above zero (CVD bullish relative to price)
        if crossover(self.div_cvd, 0):
            if not self.position:
                self.buy()
        # Sell when divergence crosses below zero (CVD bearish relative to price)
        elif crossover(0, self.div_cvd):
            if self.position:
                self.position.close()