"""
DS-TV Backtest Results: directional-movement-index-dmi
============================================================

--- SPY ---
  Return                    3.15%
  Buy & Hold Return         38.96%
  Max Drawdown              -16.52%
  Sharpe Ratio              0.12
  Sortino Ratio             0.19
  Calmar Ratio              0.10
  Profit Factor             1.09
  Expectancy                0.07%
  SQN                       0.11
  # Trades                  29
  Win Rate                  48.28%
  Best Trade                4.66%
  Worst Trade               -6.25%
  Avg Trade                 0.05%
  Exposure Time             45.00%
  Equity Final              103145.49$
  Equity Peak               112615.18$
  Avg Drawdown              -2.40%
  Max Drawdown Duration     350 days 00:00:00
  Max Trade Duration        39 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               1.57%
  Ann. Volatility           12.89%

--- BTC ---
  Return                    -15.40%
  Buy & Hold Return         11.75%
  Max Drawdown              -38.83%
  Sharpe Ratio              -0.30
  Sortino Ratio             -0.40
  Calmar Ratio              -0.21
  Profit Factor             1.09
  Expectancy                0.15%
  SQN                       -0.03
  # Trades                  42
  Win Rate                  50.00%
  Best Trade                21.38%
  Worst Trade               -14.69%
  Avg Trade                 0.00%
  Exposure Time             45.69%
  Equity Final              84604.28$
  Equity Peak               126629.34$
  Avg Drawdown              -8.24%
  Max Drawdown Duration     243 days 00:00:00
  Max Trade Duration        30 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -8.01%
  Ann. Volatility           26.70%

--- QQQ ---
  Return                    -6.72%
  Buy & Hold Return         41.48%
  Max Drawdown              -22.13%
  Sharpe Ratio              -0.21
  Sortino Ratio             -0.29
  Calmar Ratio              -0.16
  Profit Factor             0.80
  Expectancy                -0.17%
  SQN                       -0.56
  # Trades                  36
  Win Rate                  50.00%
  Best Trade                3.96%
  Worst Trade               -5.42%
  Avg Trade                 -0.19%
  Exposure Time             48.20%
  Equity Final              93280.29$
  Equity Peak               106701.86$
  Avg Drawdown              -9.01%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        28 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -3.45%
  Ann. Volatility           16.20%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — directional-movement-index-dmi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    dmi_length = 17
    adx_smooth = 1

    def init(self):
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        close = pd.Series(self.data.Close)
        
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.dmi_length))
        
        self.diplus = self.I(lambda: pta.adx(high, low, close, length=self.dmi_length).iloc[:, 0] if pta.adx(high, low, close, length=self.dmi_length) is not None else pd.Series(25, index=close.index))
        self.diminus = self.I(lambda: pta.adx(high, low, close, length=self.dmi_length).iloc[:, 1] if pta.adx(high, low, close, length=self.dmi_length) is not None else pd.Series(25, index=close.index))
        self.adx = self.I(lambda: pta.adx(high, low, close, length=self.dmi_length).iloc[:, 2] if pta.adx(high, low, close, length=self.dmi_length) is not None else pd.Series(25, index=close.index))

    def next(self):
        if len(self.data) < self.dmi_length + 1:
            return
        
        if crossover(self.diplus, self.diminus):
            if not self.position:
                self.buy()
        elif crossover(self.diminus, self.diplus):
            if self.position:
                self.position.close()