"""
DS-TV Backtest Results: futures-nq-overnight-range-of-daily-atr
============================================================

--- SPY ---
  Return                    39.10%
  Buy & Hold Return         38.66%
  Max Drawdown              -18.71%
  Sharpe Ratio              0.94
  Sortino Ratio             1.65
  Calmar Ratio              0.97
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              139104.30$
  Equity Peak               139412.30$
  Avg Drawdown              -1.74%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.10%
  Ann. Volatility           19.29%

--- BTC ---
  Return                    18.23%
  Buy & Hold Return         37.68%
  Max Drawdown              -35.84%
  Sharpe Ratio              0.26
  Sortino Ratio             0.42
  Calmar Ratio              0.24
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              118233.27$
  Equity Peak               173135.75$
  Avg Drawdown              -6.27%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               8.72%
  Ann. Volatility           33.76%

--- QQQ ---
  Return                    40.71%
  Buy & Hold Return         39.38%
  Max Drawdown              -22.76%
  Sharpe Ratio              0.75
  Sortino Ratio             1.31
  Calmar Ratio              0.83
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              140707.19$
  Equity Peak               145431.90$
  Avg Drawdown              -2.90%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.78%
  Ann. Volatility           24.94%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — futures-nq-overnight-range-of-daily-atr
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_len = 14
    chop_thresh = 25.0
    trend_thresh = 50.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate daily ATR (using current data as proxy for daily)
        self.daily_atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        self.daily_close = close
        
        # Calculate ATR percentage
        self.atr_pct = self.I(
            lambda h, l, c: (pta.atr(h, l, c, length=self.atr_len) / c) * 100.0
            if pta.atr(h, l, c, length=self.atr_len) is not None else pd.Series(0, index=c.index),
            high, low, close
        )
        
        # Track overnight session state
        self.in_on = False
        self.on_high = None
        self.on_low = None
        self.on_range_pct = None
        self.regime = "NO DATA"
        self.last_regime = None

    def next(self):
        # Simple regime detection based on rolling ATR calculation
        if len(self.data) < self.atr_len:
            return
        
        # Get current ATR
        current_atr = self.daily_atr[-1] if not np.isnan(self.daily_atr[-1]) else None
        current_close = self.data.Close[-1]
        
        if current_atr is None or current_atr == 0:
            return
        
        # Simulate overnight range as a rolling high/low over last 13 bars
        # (approximating the overnight session)
        lookback = min(13, len(self.data))
        on_high = max(self.data.High[-lookback:])
        on_low = min(self.data.Low[-lookback:])
        
        on_range = on_high - on_low
        on_range_pct_of_atr = (on_range / current_atr) * 100.0
        
        # Determine regime
        if on_range_pct_of_atr < self.chop_thresh:
            regime = "CHOP-LEANING"
        elif on_range_pct_of_atr > self.trend_thresh:
            regime = "EXPANSION-LEANING"
        else:
            regime = "NEUTRAL"
        
        self.on_range_pct = on_range_pct_of_atr
        self.regime = regime
        
        # Trading logic based on regime
        # Buy on expansion leaning (trend beginning)
        if self.regime == "EXPANSION-LEANING" and self.last_regime != "EXPANSION-LEANING":
            if not self.position:
                self.buy()
        
        # Sell on chop leaning (consolidation)
        elif self.regime == "CHOP-LEANING" and self.last_regime != "CHOP-LEANING":
            if self.position:
                self.position.close()
        
        self.last_regime = self.regime


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()