"""
DS-TV Backtest Results: macd-rsi-ema-aggressive-atr-sltp-all-coin
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — macd-rsi-ema-aggressive-atr-sltp-all-coin
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastLen = 12
    slowLen = 26
    signalLen = 9
    rsiLen = 14
    rsiBuy = 52
    rsiSell = 48
    emaLen = 21
    atrLen = 14
    slATR = 1.0
    tpATR = 1.5
    volLen = 20
    volFactor = 1.2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # Calculate MACD
        macd_result = self.I(lambda: pta.macd(close, fast=self.fastLen, slow=self.slowLen, signal=self.signalLen))
        self.macd_line = self.I(lambda: pta.macd(close, fast=self.fastLen, slow=self.slowLen, signal=self.signalLen)['MACD_12_26_9'] if pta.macd(close, fast=self.fastLen, slow=self.slowLen, signal=self.signalLen) is not None else pd.Series(0, index=close.index))
        self.signal_line = self.I(lambda: pta.macd(close, fast=self.fastLen, slow=self.slowLen, signal=self.signalLen)['SIGNAL_12_26_9'] if pta.macd(close, fast=self.fastLen, slow=self.slowLen, signal=self.signalLen) is not None else pd.Series(0, index=close.index))

        # Calculate RSI
        self.rsi_val = self.I(lambda: pta.rsi(close, length=self.rsiLen) or pd.Series(50, index=close.index))

        # Calculate EMA
        self.ema_val = self.I(lambda: pta.ema(close, length=self.emaLen) or close)

        # Calculate ATR
        self.atr_val = self.I(lambda: pta.atr(high, low, close, length=self.atrLen) or pd.Series(0, index=close.index))

        # Calculate Volume SMA
        self.vol_sma = self.I(lambda: pta.sma(volume, length=self.volLen) or pd.Series(1, index=volume.index))

    def next(self):
        close = self.data.Close[-1]
        volume = self.data.Volume[-1]

        # Volume filter
        vol_ok = volume > self.vol_sma[-1] * self.volFactor

        # Get current indicator values
        macd_line_val = self.macd_line[-1]
        signal_line_val = self.signal_line[-1]
        rsi_val = self.rsi_val[-1]
        ema_val = self.ema_val[-1]
        atr_val = self.atr_val[-1]

        # Buy condition
        if len(self.data) > 1:
            macd_prev = self.macd_line[-2]
            signal_prev = self.signal_line[-2]
            macd_crossover = (macd_prev <= signal_prev) and (macd_line_val > signal_line_val)

            buy_cond = macd_crossover and rsi_val > self.rsiBuy and close > ema_val and vol_ok

            # Sell condition
            macd_crossunder = (macd_prev >= signal_prev) and (macd_line_val < signal_line_val)
            sell_cond = macd_crossunder and rsi_val < self.rsiSell and close < ema_val and vol_ok

            if buy_cond:
                sl = close - atr_val * self.slATR
                tp = close + atr_val * self.tpATR
                self.buy(sl=sl, tp=tp)

            elif sell_cond:
                if self.position:
                    self.position.close()