"""
DS-TV Backtest Results: predictive-moving-average-convergence-divergence-ryder
============================================================

--- SPY ---
  Return                    3.78%
  Buy & Hold Return         35.76%
  Max Drawdown              -14.92%
  Sharpe Ratio              0.21
  Sortino Ratio             0.30
  Calmar Ratio              0.13
  Profit Factor             1.18
  Expectancy                0.12%
  SQN                       0.28
  # Trades                  37
  Win Rate                  54.05%
  Best Trade                7.61%
  Worst Trade               -4.13%
  Avg Trade                 0.10%
  Exposure Time             55.60%
  Equity Final              103780.31$
  Equity Peak               113105.84$
  Avg Drawdown              -1.94%
  Max Drawdown Duration     455 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               1.89%
  Ann. Volatility           8.85%

--- BTC ---
  Return                    -4.69%
  Buy & Hold Return         -2.17%
  Max Drawdown              -31.69%
  Sharpe Ratio              -0.11
  Sortino Ratio             -0.16
  Calmar Ratio              -0.07
  Profit Factor             1.06
  Expectancy                0.16%
  SQN                       -0.15
  # Trades                  30
  Win Rate                  30.00%
  Best Trade                22.85%
  Worst Trade               -14.67%
  Avg Trade                 -0.10%
  Exposure Time             38.03%
  Equity Final              95311.12$
  Equity Peak               124175.52$
  Avg Drawdown              -5.51%
  Max Drawdown Duration     445 days 00:00:00
  Max Trade Duration        21 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -2.37%
  Ann. Volatility           21.96%

--- QQQ ---
  Return                    5.16%
  Buy & Hold Return         39.41%
  Max Drawdown              -19.65%
  Sharpe Ratio              0.21
  Sortino Ratio             0.30
  Calmar Ratio              0.13
  Profit Factor             1.22
  Expectancy                0.20%
  SQN                       0.30
  # Trades                  33
  Win Rate                  48.48%
  Best Trade                11.90%
  Worst Trade               -4.21%
  Avg Trade                 0.15%
  Exposure Time             52.80%
  Equity Final              105161.57$
  Equity Peak               116311.23$
  Avg Drawdown              -2.93%
  Max Drawdown Duration     501 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               2.57%
  Ann. Volatility           12.16%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — predictive-moving-average-convergence-divergence-ryder
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fast_length = 5
    slow_length = 34
    signal_length = 5
    percent = False

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate fast and slow EMAs
        self.fast_ma = self.I(pta.ema, close, length=self.fast_length)
        self.slow_ma = self.I(pta.ema, close, length=self.slow_length)
        
        # Calculate MACD
        def calc_macd():
            fast = pta.ema(close, length=self.fast_length)
            slow = pta.ema(close, length=self.slow_length)
            if fast is None or slow is None:
                return pd.Series(0, index=close.index)
            if self.percent:
                macd = (fast - slow) / slow.fillna(1) * 100
            else:
                macd = fast - slow
            return macd
        
        self.macd = self.I(calc_macd)
        
        # Calculate signal line
        def calc_signal():
            fast = pta.ema(close, length=self.fast_length)
            slow = pta.ema(close, length=self.slow_length)
            if fast is None or slow is None:
                return pd.Series(0, index=close.index)
            if self.percent:
                macd_vals = (fast - slow) / slow.fillna(1) * 100
            else:
                macd_vals = fast - slow
            signal = pta.ema(macd_vals, length=self.signal_length)
            if signal is None:
                return pd.Series(0, index=close.index)
            return signal
        
        self.signal = self.I(calc_signal)
        
        # Calculate histogram
        def calc_hist():
            fast = pta.ema(close, length=self.fast_length)
            slow = pta.ema(close, length=self.slow_length)
            if fast is None or slow is None:
                return pd.Series(0, index=close.index)
            if self.percent:
                macd_vals = (fast - slow) / slow.fillna(1) * 100
            else:
                macd_vals = fast - slow
            signal_vals = pta.ema(macd_vals, length=self.signal_length)
            if signal_vals is None:
                return pd.Series(0, index=close.index)
            hist = macd_vals - signal_vals
            return hist
        
        self.hist = self.I(calc_hist)

    def next(self):
        # Buy when MACD crosses above signal line
        if crossover(self.macd, self.signal):
            if not self.position:
                self.buy()
        # Sell when MACD crosses below signal line
        elif crossover(self.signal, self.macd):
            if self.position:
                self.position.close()
        
        # Alternative: Use histogram for entries/exits
        # Buy when histogram crosses above zero
        if len(self.hist) > 1 and self.hist[-2] <= 0 and self.hist[-1] > 0:
            if not self.position:
                self.buy()
        # Sell when histogram crosses below zero
        elif len(self.hist) > 1 and self.hist[-2] >= 0 and self.hist[-1] < 0:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()