"""
DS-TV Backtest Results: rhokeo-vw-rsi-histogram-for-cumulative-delta-by-zeiirman
============================================================

--- SPY ---
  Return                    -8.30%
  Buy & Hold Return         40.02%
  Max Drawdown              -16.48%
  Sharpe Ratio              -0.34
  Sortino Ratio             -0.50
  Calmar Ratio              -0.26
  Profit Factor             0.65
  Expectancy                -0.27%
  SQN                       -0.64
  # Trades                  30
  Win Rate                  26.67%
  Best Trade                9.86%
  Worst Trade               -6.71%
  Avg Trade                 -0.30%
  Exposure Time             43.00%
  Equity Final              91703.16$
  Equity Peak               109792.65$
  Avg Drawdown              -4.26%
  Max Drawdown Duration     217 days 00:00:00
  Max Trade Duration        98 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -4.27%
  Ann. Volatility           12.52%

--- BTC ---
  Return                    -21.73%
  Buy & Hold Return         34.01%
  Max Drawdown              -31.47%
  Sharpe Ratio              -0.78
  Sortino Ratio             -0.88
  Calmar Ratio              -0.37
  Profit Factor             0.37
  Expectancy                -2.88%
  SQN                       -1.15
  # Trades                  11
  Win Rate                  45.45%
  Best Trade                8.14%
  Worst Trade               -23.26%
  Avg Trade                 -3.27%
  Exposure Time             26.27%
  Equity Final              78270.93$
  Equity Peak               114219.89$
  Avg Drawdown              -7.32%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        56 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               -11.51%
  Ann. Volatility           14.71%

--- QQQ ---
  Return                    -7.30%
  Buy & Hold Return         42.20%
  Max Drawdown              -35.53%
  Sharpe Ratio              -0.23
  Sortino Ratio             -0.32
  Calmar Ratio              -0.11
  Profit Factor             0.83
  Expectancy                -0.21%
  SQN                       -0.32
  # Trades                  24
  Win Rate                  41.67%
  Best Trade                14.11%
  Worst Trade               -9.64%
  Avg Trade                 -0.28%
  Exposure Time             71.80%
  Equity Final              92695.91$
  Equity Peak               138255.33$
  Avg Drawdown              -3.49%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        125 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               -3.75%
  Ann. Volatility           16.34%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rhokeo-vw-rsi-histogram-for-cumulative-delta-by-zeiirman
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsi_length = 9
    rsi_ma_type = "EMA"
    rsi_ma_length = 14
    vwrsi_ob_level = 0.4
    vwrsi_os_level = -0.4

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate OHLC4
        ohlc4 = (self.data.Open + high + low + close) / 4
        ohlc4_series = pd.Series(ohlc4)
        
        # VW-RSI Calculation
        price_change = ohlc4_series.diff()
        vw_gain = price_change.copy()
        vw_gain[vw_gain <= 0] = 0
        vw_gain = vw_gain * volume
        
        vw_loss = -price_change.copy()
        vw_loss[vw_loss <= 0] = 0
        vw_loss = vw_loss * volume
        
        # RMA (Wilder's smoothing)
        def rma(src, length):
            result = pd.Series(np.nan, index=src.index)
            if len(src) < length:
                return result
            result.iloc[length - 1] = src.iloc[:length].mean()
            for i in range(length, len(src)):
                result.iloc[i] = (result.iloc[i - 1] * (length - 1) + src.iloc[i]) / length
            return result
        
        avg_vw_gain = rma(vw_gain, self.rsi_length)
        avg_vw_loss = rma(vw_loss, self.rsi_length)
        
        def calc_vw_rsi_normalized(gains, losses):
            rs = pd.Series(np.nan, index=gains.index)
            vw_rsi_0_100 = pd.Series(np.nan, index=gains.index)
            
            for i in range(len(gains)):
                if pd.isna(gains.iloc[i]) or pd.isna(losses.iloc[i]):
                    continue
                if losses.iloc[i] == 0:
                    rs.iloc[i] = 999999.0
                else:
                    rs.iloc[i] = gains.iloc[i] / losses.iloc[i]
                vw_rsi_0_100.iloc[i] = 100.0 - (100.0 / (1.0 + rs.iloc[i]))
            
            vw_rsi_normalized = (vw_rsi_0_100 - 50.0) / 50.0
            return vw_rsi_normalized
        
        vw_rsi_normalized = calc_vw_rsi_normalized(avg_vw_gain, avg_vw_loss)
        
        # Apply MA smoothing
        def apply_ma(src, ma_type, length):
            if ma_type == "SMA":
                return src.rolling(length).mean()
            elif ma_type == "EMA":
                return src.ewm(span=length, adjust=False).mean()
            elif ma_type == "SMMA (RMA)":
                return rma(src, length)
            elif ma_type == "WMA":
                weights = np.arange(1, length + 1)
                return src.rolling(length).apply(lambda x: np.sum(x * weights) / np.sum(weights), raw=False)
            elif ma_type == "VWMA":
                numerator = (src * volume).rolling(length).sum()
                denominator = volume.rolling(length).sum()
                return numerator / denominator
            else:
                return src.ewm(span=length, adjust=False).mean()
        
        vw_rsi_smoothed = apply_ma(vw_rsi_normalized, self.rsi_ma_type, self.rsi_ma_length)
        
        # Clamp to -1 to +1
        self.vw_rsi = self.I(lambda: vw_rsi_smoothed.clip(-1.0, 1.0))
    
    def next(self):
        # Trading logic based on VW-RSI levels
        # Buy when crossing above oversold level
        if len(self.data) > 1:
            if self.vw_rsi[-2] <= self.vwrsi_os_level and self.vw_rsi[-1] > self.vwrsi_os_level:
                if not self.position:
                    self.buy()
            # Sell when crossing below overbought level
            elif self.vw_rsi[-2] >= self.vwrsi_ob_level and self.vw_rsi[-1] < self.vwrsi_ob_level:
                if self.position:
                    self.sell()
            # Also sell when price reaches overbought
            elif self.vw_rsi[-1] >= self.vwrsi_ob_level:
                if self.position:
                    self.sell()
            # Close position on zero line cross from above
            elif self.vw_rsi[-2] > 0 and self.vw_rsi[-1] <= 0:
                if self.position:
                    self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()