"""
DS-TV Backtest Results: rsi-adaptive-structure-engine-rase
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(rsi(14),5)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "ema(rsi(14),5)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(rsi(14),5)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-adaptive-structure-engine-rase
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len_structure = 21
    len_momentum = 14
    len_fast = 5
    eff_len = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        self.rsi_structure = self.I(pta.rsi, close, length=self.len_structure)
        self.rsi_momentum = self.I(pta.rsi, close, length=self.len_momentum)
        self.rsi_fast = self.I(pta.rsi, close, length=self.len_fast)
        
        self.rsi_momentum_smooth = self.I(pta.ema, self.rsi_momentum, length=5)
        
        self.rsi_efficiency = self.I(self._calc_efficiency, close)
        
        self.base_state = 0
        self.strong_state = 0

    def _calc_efficiency(self, close):
        rsi_struct = pta.rsi(close, length=self.len_structure)
        if rsi_struct is None or len(rsi_struct) < self.eff_len + 1:
            return pd.Series(0, index=close.index)
        
        result = pd.Series(0.0, index=close.index)
        
        for idx in range(self.eff_len, len(rsi_struct)):
            rsi_change = abs(rsi_struct.iloc[idx] - rsi_struct.iloc[idx - self.eff_len])
            rsi_noise = 0.0
            for i in range(self.eff_len):
                rsi_noise += abs(rsi_struct.iloc[idx - self.eff_len + i] - rsi_struct.iloc[idx - self.eff_len + i + 1])
            
            if rsi_noise != 0:
                result.iloc[idx] = rsi_change / rsi_noise
            else:
                result.iloc[idx] = 0.0
        
        return result

    def next(self):
        if len(self.data) < 2:
            return

        rsi_struct = self.rsi_structure[-1]
        rsi_struct_prev = self.rsi_structure[-2]
        rsi_mom_smooth = self.rsi_momentum_smooth[-1]
        rsi_mom_smooth_prev = self.rsi_momentum_smooth[-2]
        rsi_fast = self.rsi_fast[-1]
        rsi_fast_prev = self.rsi_fast[-2]
        eff = self.rsi_efficiency[-1]

        structure_up = rsi_struct > 50 and rsi_struct > rsi_struct_prev
        structure_down = rsi_struct < 50 and rsi_struct < rsi_struct_prev

        momentum_up = rsi_mom_smooth > rsi_mom_smooth_prev
        momentum_down = rsi_mom_smooth < rsi_mom_smooth_prev

        eff_ok = eff > 0.4

        exec_up = rsi_fast > 40 and rsi_fast > rsi_fast_prev
        exec_down = rsi_fast < 60 and rsi_fast < rsi_fast_prev

        bull_base = structure_up and momentum_up and eff_ok and exec_up
        bear_base = structure_down and momentum_down and eff_ok and exec_down

        bull_strong = bull_base and rsi_struct > 55 and self.rsi_momentum[-1] > 55
        bear_strong = bear_base and rsi_struct < 45 and self.rsi_momentum[-1] < 45

        bull_base_sig = bull_base and self.base_state != 1
        bear_base_sig = bear_base and self.base_state != -1

        if bull_base_sig:
            self.base_state = 1
        if bear_base_sig:
            self.base_state = -1

        bull_strong_sig = bull_strong and self.strong_state != 1
        bear_strong_sig = bear_strong and self.strong_state != -1

        if bull_strong_sig:
            self.strong_state = 1
        if bear_strong_sig:
            self.strong_state = -1

        if bull_base_sig or bull_strong_sig:
            if self.position:
                self.position.close()
            self.buy()
        elif bear_base_sig or bear_strong_sig:
            if self.position:
                self.position.close()