"""
DS-TV Backtest Results: stelarax-momentum
============================================================

--- SPY ---
  Return                    9.14%
  Buy & Hold Return         40.28%
  Max Drawdown              -10.96%
  Sharpe Ratio              0.46
  Sortino Ratio             0.65
  Calmar Ratio              0.41
  Profit Factor             1.40
  Expectancy                0.27%
  SQN                       0.63
  # Trades                  33
  Win Rate                  39.39%
  Best Trade                6.39%
  Worst Trade               -4.62%
  Avg Trade                 0.25%
  Exposure Time             69.60%
  Equity Final              109136.20$
  Equity Peak               117494.82$
  Avg Drawdown              -1.89%
  Max Drawdown Duration     210 days 00:00:00
  Max Trade Duration        61 days 00:00:00
  Avg Trade Duration        14 days 00:00:00
  Ann. Return               4.50%
  Ann. Volatility           9.89%

--- BTC ---
  Return                    5.60%
  Buy & Hold Return         33.60%
  Max Drawdown              -27.40%
  Sharpe Ratio              0.11
  Sortino Ratio             0.17
  Calmar Ratio              0.10
  Profit Factor             1.28
  Expectancy                0.50%
  SQN                       0.13
  # Trades                  54
  Win Rate                  24.07%
  Best Trade                42.97%
  Worst Trade               -9.08%
  Avg Trade                 0.24%
  Exposure Time             58.00%
  Equity Final              105603.35$
  Equity Peak               137107.02$
  Avg Drawdown              -5.73%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               2.76%
  Ann. Volatility           25.13%

--- QQQ ---
  Return                    13.93%
  Buy & Hold Return         41.93%
  Max Drawdown              -14.30%
  Sharpe Ratio              0.51
  Sortino Ratio             0.74
  Calmar Ratio              0.48
  Profit Factor             1.48
  Expectancy                0.46%
  SQN                       0.59
  # Trades                  34
  Win Rate                  52.94%
  Best Trade                17.65%
  Worst Trade               -6.19%
  Avg Trade                 0.39%
  Exposure Time             67.80%
  Equity Final              113931.90$
  Equity Peak               125460.85$
  Avg Drawdown              -2.46%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        62 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               6.79%
  Ann. Volatility           13.31%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — stelarax-momentum
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 10

    def init(self):
        close = pd.Series(self.data.Close)
        self.momentum = self.I(pta.mom, close, length=self.len)

    def next(self):
        if crossover(self.momentum, 0):
            if not self.position:
                self.buy()
        elif crossover(0, self.momentum):
            if self.position:
                self.position.close()