"""
DS-TV Backtest Results: tuoppi-entries
============================================================

--- SPY ---
  Return                    -24.82%
  Buy & Hold Return         39.05%
  Max Drawdown              -28.44%
  Sharpe Ratio              -0.96
  Sortino Ratio             -1.25
  Calmar Ratio              -0.47
  Profit Factor             0.41
  Expectancy                -1.69%
  SQN                       -1.50
  # Trades                  15
  Win Rate                  20.00%
  Best Trade                11.19%
  Worst Trade               -7.31%
  Avg Trade                 -1.79%
  Exposure Time             80.60%
  Equity Final              75178.80$
  Equity Peak               104814.79$
  Avg Drawdown              -7.53%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        98 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               -13.39%
  Ann. Volatility           13.92%

--- BTC ---
  Return                    18.31%
  Buy & Hold Return         2.22%
  Max Drawdown              -26.99%
  Sharpe Ratio              0.27
  Sortino Ratio             0.45
  Calmar Ratio              0.32
  Profit Factor             1.40
  Expectancy                2.23%
  SQN                       0.46
  # Trades                  9
  Win Rate                  55.56%
  Best Trade                24.97%
  Worst Trade               -31.29%
  Avg Trade                 0.79%
  Exposure Time             54.17%
  Equity Final              118306.92$
  Equity Peak               126113.83$
  Avg Drawdown              -8.19%
  Max Drawdown Duration     460 days 00:00:00
  Max Trade Duration        117 days 00:00:00
  Avg Trade Duration        44 days 00:00:00
  Ann. Return               8.76%
  Ann. Volatility           32.06%

--- QQQ ---
  Return                    7.52%
  Buy & Hold Return         43.14%
  Max Drawdown              -21.86%
  Sharpe Ratio              0.20
  Sortino Ratio             0.31
  Calmar Ratio              0.17
  Profit Factor             1.23
  Expectancy                0.59%
  SQN                       0.14
  # Trades                  13
  Win Rate                  30.77%
  Best Trade                14.03%
  Worst Trade               -7.52%
  Avg Trade                 0.33%
  Exposure Time             76.60%
  Equity Final              107516.78$
  Equity Peak               133537.04$
  Avg Drawdown              -4.69%
  Max Drawdown Duration     262 days 00:00:00
  Max Trade Duration        152 days 00:00:00
  Avg Trade Duration        43 days 00:00:00
  Ann. Return               3.72%
  Ann. Volatility           19.07%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — tuoppi-entries
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    n1 = 10
    n2 = 21
    obLevel2 = 53
    osLevel2 = -53

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate HLC3 (typical price)
        hlc3 = (high + low + close) / 3
        
        # Wavetrend calculation
        esa = self.I(pta.ema, hlc3, length=self.n1)
        
        def calc_d():
            hlc3_series = pd.Series(self.data.High) + pd.Series(self.data.Low) + pd.Series(self.data.Close)
            hlc3_series = hlc3_series / 3
            esa_vals = pta.ema(hlc3_series, length=self.n1)
            abs_diff = np.abs(hlc3_series - esa_vals)
            return pta.ema(abs_diff, length=self.n1)
        
        self.d = self.I(calc_d)
        
        def calc_ci():
            hlc3_series = pd.Series(self.data.High) + pd.Series(self.data.Low) + pd.Series(self.data.Close)
            hlc3_series = hlc3_series / 3
            esa_vals = pta.ema(hlc3_series, length=self.n1)
            abs_diff = np.abs(hlc3_series - esa_vals)
            d_vals = pta.ema(abs_diff, length=self.n1)
            ci_vals = (hlc3_series - esa_vals) / (0.015 * d_vals)
            return ci_vals
        
        self.ci = self.I(calc_ci)
        
        def calc_wt1():
            hlc3_series = pd.Series(self.data.High) + pd.Series(self.data.Low) + pd.Series(self.data.Close)
            hlc3_series = hlc3_series / 3
            esa_vals = pta.ema(hlc3_series, length=self.n1)
            abs_diff = np.abs(hlc3_series - esa_vals)
            d_vals = pta.ema(abs_diff, length=self.n1)
            ci_vals = (hlc3_series - esa_vals) / (0.015 * d_vals)
            wt1 = pta.ema(ci_vals, length=self.n2)
            return wt1
        
        self.wt1 = self.I(calc_wt1)
        
        def calc_wt2():
            hlc3_series = pd.Series(self.data.High) + pd.Series(self.data.Low) + pd.Series(self.data.Close)
            hlc3_series = hlc3_series / 3
            esa_vals = pta.ema(hlc3_series, length=self.n1)
            abs_diff = np.abs(hlc3_series - esa_vals)
            d_vals = pta.ema(abs_diff, length=self.n1)
            ci_vals = (hlc3_series - esa_vals) / (0.015 * d_vals)
            wt1 = pta.ema(ci_vals, length=self.n2)
            wt2 = pta.sma(wt1, length=4)
            return wt2
        
        self.wt2 = self.I(calc_wt2)

    def next(self):
        if len(self.data) < 2:
            return
        
        # Check for cross between wt1 and wt2
        if crossover(self.wt1, self.wt2):
            # Bullish cross (wt1 crosses above wt2)
            if self.wt2[-1] < self.osLevel2:
                self.buy()
        elif crossover(self.wt2, self.wt1):
            # Bearish cross (wt2 crosses above wt1)
            if self.wt2[-1] > self.obLevel2:
                self.sell()